libgit2/libgit2

- include/git2/sys/openssl.h
I know that's a last resort for threading, but I still feel like this should work :smile:
The path to `common.h` didn't change when `threads.h` was renamed to `sys/openssl.h`. Now, if you include `sys/openssl.h` anywhere you'll get an error because the path to `common.h` is invalid.
> Include git2/common.h in sys/openssl.h.

- src/remote.c
That's a recent regression due to the addition of the `git_remote_download()` API: if re-using the same remote to upload then download, the internal push state is still around and calling `git_remote_update_tips()` doesn't update the tags anymore.
BTW: I think there's another issue with `git_remote_download()`: the doc says it connects if needed, but I don't think it does looking at the implementation. `git_remote_upload()` does it for sure though. IMO neither API should auto-connect since they are low-level. For `git_remote_push()` and `git_remote_fetch()` however, it certainly makes sense.
> Fixed internal push state not being cleared when calling git_remote_download()

- include/git2/merge.h
`git_merge_commits` (and thus `git_merge`) do not use the same
strategy as `git-merge-recursive` wherein they can produce an
artificial common ancestor that is the merge of all common
ancestors.  Document this accordingly.
> Better document `git_merge_commits`

- src/remote.c
- tests/network/fetchlocal.c
`git_remote_create` doesn't load the prune configuration for the repository like `git_remote_lookup` does.
So `remote->prune_refs` is false after creating the remote, even when the configuration says that it should be true.
This PR changes this behaviour to load the prune configuration when a remote is created. I've added a couple of tests to verify that this works as expected.
> Load prune configuration when a remote is created.

- examples/network/clone.c
Local transports don't have data about the size, avoid dividing by
zero in the callback.
Fixes #2812
> clone example: don't divide by zero

- CMakeLists.txt
It's good that the user is able to turn off OpenSSL support even if he/she has OpenSSL install in his/her system.
> Add option to turn off OpenSSL

- src/util.h
Avoid str length recalculation every iteration
> Remove strlen() calls from loop condition

- src/diff_patch.c
When we're called with no hunk or line callback, we don't need to
do the hunk or line computation.
> diff: only compute patches when requested

- README.md
Microsoft is sponsoring a Pro account at AppVeyor for the libgit2
and LibGit2Sharp projects.  Point to that account's badge.
> README: Point to libgit2 account's AppVeyor badge

- src/pathspec.c
pathspec_match_free() should not dereference a NULL passed to it.
I found this issue when I tried to run example log program with
nonexistent branch:
./example/log help
Such call leads to segmentation fault.
> pathspec: do not try to dereference NULL

- examples/describe.c
We need to allocate memory for sizeof(char *) * ncommits, not just for
ncommits.
Issue detected by GCC's AddressSanitizer.
It would be nice to check for (m,re)alloc return values and to move
allocation code for opts->commits to its own function..
> describe example: fix memory allocation size

- src/openssl_stream.c
This fixes the build at least on FreeBSD, where those types were not
defined indirectly:
```
src/openssl_stream.c:100:18: error: variable has incomplete type 'struct in6_addr'
struct in6_addr addr6;
^
src/openssl_stream.c:100:9: note: forward declaration of 'struct in6_addr'
struct in6_addr addr6;
^
src/openssl_stream.c:111:18: error: use of undeclared identifier 'AF_INET'
if (p_inet_pton(AF_INET, host, &addr4)) {
^
src/unix/posix.h:31:40: note: expanded from macro 'p_inet_pton'
^
src/openssl_stream.c:115:18: error: use of undeclared identifier 'AF_INET6'
if(p_inet_pton(AF_INET6, host, &addr6)) {
^
src/unix/posix.h:31:40: note: expanded from macro 'p_inet_pton'
^
```
> openssl: Add all required includes for AF_INET6 and in6_addr.

- include/git2/sys/repository.h
It was missing "common.h" and "types.h" like other system headers.
This generated compilation errors if including it directly.
> Make sure sys/repository.h includes the required headers

- src/diff_patch.c
- src/index.c
- src/pathspec.c
This fixes a few scenarios where we may be dereferencing ```NULL``` pointers.
> More coverity fixes

- src/repository.c
This is supported by the underlying set_index() implementation
and setting the repository index to NULL is recommended by the
git_repository_set_bare() documentation.
> Allow passing a NULL index to git_repository_set_index()

- CHANGELOG.md
- include/git2/config.h
- src/config.c
- tests/config/read.c
Here we use the global search path variable as-is, which would mean that we might not behave as expected if the search path is actually a list. Do we want to support that? I didn't use the sysdir functions as they search for the particular file, while the config lookup semantics don't require the file to exist at all.
> config: add parsing and getter for paths

- include/git2/diff.h
- include/git2/patch.h
Fix a few minor doc changes left around after https://github.com/libgit2/libgit2/commit/10672e3e455eba2d4ca983070ed427caeeb24a6f
Fixes #2860
> diff docs: update `git_diff_delta` description

- README.md
First of all, thanks a ton for this project. It's been a real pleasure building a wrapper around such a thoughtfully implemented API.
I was wondering if my project, a set of [Swift bindings to libgit2 called Gift](https://github.com/modocache/Gift), could be added to the list in the README?
Gift currently has several maintainers that are committed to its maintenance and feature development. We've also encountered a few issues in libgit2 we wish to fix and pull request back upstream. In addition to mentioning Gift in the README, how would the libgit2 maintainers feel about including Gift in [the libgit2 GitHub organization](https://github.com/libgit2)?
Just a thought. Thanks again! :+1:
> README.md: Add Swift bindings "Gift"

- examples/for-each-ref.c
I don't get how it was working without git_libgit2_init() call. I run it
and libgit2 throws assertion somewhere in its internals. Now it works.
> for-each-ref example: initialize libgit2 in main

- src/repository.c
- tests/checkout/nasty.c
- tests/clar_libgit2.c
- tests/clar_libgit2.h
- tests/path/win32.c
> Handle 8dot3 filenames being disabled on Win32

- src/repository.c
- tests/checkout/nasty.c
- tests/path/win32.c
Windows user can disable NTFS 8.3 option.
But libgit2 may crash.
> Fix test failures when NTFS  8.3 is disabled

- src/repository.c
This is a path so we must use the path getter so we get the tilde
expansion done.
---
@alexcrichton this should fix #2814
> repository: parse init.templatedir as a path

- appveyor.yml
AppVeyor build machines come with Python 2.7 and CMake 2.8 pre-installed and in the PATH.
> Speed up AppVeyor builds.

- include/git2/annotated_commit.h
- include/git2/cherrypick.h
- include/git2/config.h
- include/git2/describe.h
- include/git2/oid.h
- include/git2/rebase.h
- include/git2/revert.h
- include/git2/transport.h
- include/git2/types.h
Fixes to doc comments to get rid of warnings (when clang `-Wdocumentation` is enabled). These are mostly parameter name typos where the name has probably changed.
> Fix doc comment formatting

- COPYING
- src/util.c
1. Our inclusion of `git__utf8_iterate` was from git core, which was originally from utf8proc.  Pay tribute.
2. Our copyright information for [clar](https://github.com/vmg/clar) incorrectly uses outdated license information.  Clar is under the ISC license, not MIT.
> Update some third-party copyrights

- tests/perf/helper__perf__do_merge.c
- tests/perf/helper__perf__do_merge.h
- tests/perf/helper__perf__timer.c
- tests/perf/helper__perf__timer.h
- tests/perf/merge.c
A large merge test with some simple performance timing.  
This test was written to help debug the filelist iterator changes described in https://github.com/libgit2/libgit2/pull/2888 but maybe be used with or without that commit.
This test uses 2 recent branches on the containing libgit2 tree itself.  On Windows, the filelist iterator changes show a small improvement in merge performance.  We need a much larger tree to fully see the performance improvements, but I wasn't sure how/if we should include something like that in the clar tests.
> Large merge perf test.

- appveyor.yml
- src/fileops.c
- src/win32/posix_w32.c
- tests/core/stat.c
- tests/repo/init.c
It seems that initializing a repository at the root of the filesystem (eg `c:\foo`) is failing.  This appears to be a regression, something I busted in some of the insidious refactoring I did recently.
Add a unit test that exercises this, but guard it in an environment variable `GITTEST_INVASIVE_FILESYSTEM`.  It is not expected that normal people would ever set this, because - you know - it creates a directory at the root of your disk.  And then `rm -r`s it!  But this seems like something that we could safely hook up in our CI builds.
So, enable these for AppVeyor, which (I think) basically runs as administrator.  Don't enable these for Travis, though we could later add a second pass of test execution that runs as root(!).
> Ensure we can make a repo at the root of the filesystem

- src/refdb_fs.c
- tests/refs/branches/create.c
When a namespace branch such as "level_one/level_two" is deleted, the "level_two" branch files are deleted, but the containing directories are not.  A later attempt to create a "level_one" branch fails because of a collision on the stale ".git/logs/refs/heads/level_one" directory.
This fix removes an empty reflog directory before trying to create the new reflog file.
(Existing code already handles cleaning up the stale ".git/refs/heads/level_one" directory.)
This issue was originally reported by @jamill against LibGit2Sharp in 
https://github.com/libgit2/libgit2sharp/pull/859
> Remove stale reflog namespace directory before branch creation

- src/fileops.c
Bionic issue: st_mtime is not typed with time_t on Android.
> Fix build warning on Android

- include/git2/checkout.h
- src/checkout.c
- src/cherrypick.c
- src/index.c
- src/index.h
- src/merge.c
- src/rebase.c
- src/revert.c
- tests/checkout/tree.c
- tests/index/tests.c
- tests/merge/workdir/setup.c
Always lock the index when we begin the merge, before we write
any of the metdata files.  This prevents a race where another
client may run a commit after we have written the `MERGE_HEAD` but
before we have updated the index, which will produce a merge
commit that is treesame to one parent.  The merge will finish and
update the index and the resultant commit would not be a merge at
all.
> merge: lock index during the merge (not just checkout)

- src/attr.c
- src/attrcache.c
- src/checkout.c
- src/commit.c
- src/config_file.c
- src/diff_driver.c
- src/fileops.c
- src/mwindow.c
- src/odb_mempack.c
- src/offmap.h
- src/oidmap.h
- src/pack.h
- src/refdb_fs.c
- src/refs.c
- src/revwalk.h
- src/sortedcache.c
- src/strmap.h
- src/submodule.c
- src/transaction.c
- src/tree.c
- tests/core/oidmap.c
- tests/core/strmap.c
This pull request is related to the R bindings [git2r](https://github.com/ropensci/git2r) and the pedantic compiler warnings in https://github.com/ropensci/git2r/issues/101
This changes removes `;` outside of a function, which generates the following warning with gcc and pedantic:
`ISO C does not allow extra ‘;’ outside of a function`
> Remove extra semicolon outside of a function

- src/pack.c
Increment refcount of newly added cache entries just like existing
entries looked up from the cache. Otherwise the new entry can be
evicted from the cache and destroyed while it's still in use.
This is a possible fix for issue #2906.
> Fix race in git_packfile_unpack.

- src/integer.h
Fix compile problem reported in #2917 on Mac when 32 bit.
> Fix Mac 32 bit build problem described in libgit2/libgit2#2917

- src/branch.c
> git_branch_delete() should ignore errors from non-existing reflogs

- src/transports/http.c
The user may decide to return any type of credential, including ones we
did not say we support. Add a check to make sure the user returned an
object of the right type and error out if not.
---
This should handle #2940 @mattyclarkson can you give it a try?
> http: enforce the credential types

- src/hashsig.c
- tests/diff/rename.c
Don't try to compare two empty hashsig_heaps.
> diff_tform: don't compare empty hashsig_heaps

- CMakeLists.txt
- tests/clar_libgit2_timer.c
- tests/clar_libgit2_timer.h
- tests/clar_libgit2_trace.c
- tests/clar_libgit2_trace.h
- tests/main.c
- tests/trace/trace.c
This code provides a way for the CLAR test runner to optionally git_trace() before running a test.  This has proven useful when adding tracing inside libgit2 routines during development.
Currently, it always assume TRACE level.
Currently, I have just the basic printf() callback on all platforms.  Windows users can also request a "printf() + debugger console" callback.
It would be easy to extend this to have a callback to write the trace log to a file instead.
> Set up git_trace in clar test suite.

- src/win32/posix.h
- src/win32/posix_w32.c
- tests/core/ftruncate.c
A crash was observed on Windows when cloning a very large repo. In this instance, the received packfile was nearly 6Gb.
The problem was in sloppy casting of the "size" field from src/indexer.c:append_to_pack() to src/win32/posix_w32.c:p_ftruncate() to _chsize_s().
Where the file position was being truncated and then sign-extended.
Also fixed the return value from _chsize_s() which differs from _chsize().
> Fix crash in git_clone on extremely large repos

- CHANGELOG.md
- src/refdb_fs.c
- tests/refs/branches/move.c
When we rename a reference, we want the old and new ids to be the same
one (as we did not change it). The normal code path looks up the old id
from the current value of the brtanch, but by the time we look it up, it
does not exist anymore and thus we write a zero id.
Pass the old id explicitly instead.
> refdb: use the same id for old and new when renaming a reference

- CMakeLists.txt
- appveyor.yml
- script/appveyor-mingw.sh
- script/cibuild.sh
- script/install-deps-linux.sh
- script/install-deps-osx.sh
- src/win32/mingw-compat.h
- src/win32/msvc-compat.h
- src/win32/posix.h
- src/win32/posix_w32.c
As discussed here https://github.com/libgit2/libgit2/pull/2414#issuecomment-76848152
This is just a start, ~~and is only using the 32-bit mingw.org that is already installed on the AppVeyor VM's. I can keep working on this and add 32 and 64 bit MinGW-w64 distributions. Just need to pick which distribution to download.~~
It looks like there might be a build issue with mingw.org at the moment. On my fork I got
```
[ 16%] Building C object CMakeFiles/git2.dir/src/trace.c.obj
In file included from c:/projects/libgit2/src/common.h:66:0,
from c:/projects/libgit2/src/buffer.h:10,
from c:/projects/libgit2/src/trace.c:8:
c:/projects/libgit2/src/trace.c: In function 'git_trace_set':
c:/projects/libgit2/src/thread-utils.h:279:43: error: expected expression before ')' token
^ …
```
> RFC: add mingw to appveyor matrix

- src/repository.c
- tests/repo/new.c
A repository created using `git_repository_new` lacks a working directory and thus should report `true` when queried with `git_repository_is_bare`.
(This repository will no longer be bare when `set_workdir` is called, if it is called.)
> "In-memory" repos are bare by default

- src/refspec.c
Adding an invalid refspec would return a nonspecific error code and
would not include an error message or class, making it hard to debug errors with
malformed refspecs. This commit fixes this by returning the appropriate
error code and setting a specific error message.
This can reproduced via rugged with the following:
```ruby
#!/usr/bin/env ruby
require 'rugged'
require 'tmpdir'
repo = Rugged::Repository.init_at(Dir.mktmpdir)
repo.config.tap do |c|
c['remote.origin.url'] = 'git@github.com:libgit2/libgit2'
c['remote.origin.fetch'] = '/an/invalid:/refspec'
end
repo.fetch('origin')
```
```
/home/adrien/development/repro/.bundle/ruby/1.9.1/gems/rugged-0.21.4/lib/rugged/repository.rb:200:in `[]': Unknown Error (Rugged::OSError)
from /home/adrien/development/repro/.bundle/ruby/1.9.1/gems/rugged …
```
> refspec: report errors when parsing an invalid refspec

- CHANGELOG.md
- src/transports/local.c
The default behaviour for the packbuilder is to perform the work in a
single thread, which is fine for the public API, but we currently have
no way for a user to determine the number of threads to use when
creating the packfile, which makes our clone behaviour over the
filesystem quite a bit slower than what git offers.
This is a very particular scenario, in which we avoid spawning git by
being ourselves the server-side, so it's probably ok to auto-set the
threading, as the upload-pack process would do if we were talking to
git.
> local: create pack with multiple threads

- src/submodule.c
- tests/submodule/modify.c
Currently git_submodule_sync writes the submodule's URL to the
key 'branch.REMOTE_NAME.remote' while the reference
implementation of `git submodule sync` writes to
'remote.REMOTE_NAME.url', which is the intended behavior
according to git-submodule(1).
> Fix git_submodule_sync writing URL to wrong key.

- src/stream.h
- src/transports/http.c
- tests/online/clone.c
When dealing with an unencrypted stream, do not attempt to perform certificate validation.
This fixes #2904
> Don't ask for a stream's certificate unless it's encrypted

- include/git2/pack.h
- src/describe.c
- src/indexer.c
- src/pack-objects.c
- src/pack-objects.h
- src/pack.c
- src/pack.h
- src/revwalk.c
- src/revwalk.h
- src/transports/local.c
This attempts to let the caller describe what objects they'd like to have packed as a walk and make the way we insert objects into the set less wasteful.
The first place to make use of this is local fetching, as it's one of the places where it should have the most effect. The time it takes is still pretty terrible, with 35s vs 41s to perform a clone+checkout of the libgit2 repository. It is however quite a bit less wasteful, at 1_067_758 vs 23_192_189 duplicate insertions into the set and 2s vs 10s of object-insertion time. The rest of those duplicate insertions are likely blobs and thus letting them be inserted multiple times would still faster than diffing (but I still need to test this hypothesis).
> [WIP] Smarter pack-building

- CHANGELOG.md
- include/git2/annotated_commit.h
- include/git2/branch.h
- include/git2/repository.h
- include/git2/reset.h
- src/annotated_commit.c
- src/branch.c
- src/repository.c
- src/reset.c
- tests/refs/branches/create.c
- tests/repo/head.c
- tests/reset/hard.c
- tests/reset/mixed.c
- tests/reset/soft.c
This adds a way to get an annotated commit from an extended sha string in order to know what the user typed so we can put that in the reflog.
This provides for branch creation, detaching HEAD and reset.
This fixes #2949
> Add annotated versions of ref-modying functions

- src/remote.c
Otherwise, bailing out early when ls_to_vector() fails accesses
uninitialized memory.
This is also a possible candidate for v0.22.
> Initialize refs vector in git_remote_update_tips().

- src/merge.c
- src/merge.h
The MERGE code is calling merge_diff_detect_binary() for every modified file -- even if it was only modified by one branch.  This requires fetching all 2 or 3 versions of the file and scanning them.   Only the code in merge_conflict_resolve_automerge() actually cares if the files are in fact binary.
This change moves the "is binary" check into the automerge code.
I also removed the "git_merge_diff.binary" field, since it is is only needed by automerge and to prevent accidents.
> PERF: In MERGE, lazily compute is_binary

- src/common.h
- src/openssl_stream.c
Fixes issue #2850.
Might break build on Windows, I don't know! I don't have a Windows machine where to test that.
Also I put this to the maint/v0.22 branch because master branch doesn't build on mingw because of commit 3cda6be76b which includes various headers unconditionally on every platform. One or more of those headers aren't available on mingw.
> Fix build on mingw

- tests/checkout/icase.c
Since the Linux platform has a case sensitive file system, the header name should be lower case for cross 
compiling purposes. (On Linux, the mingw header is called ```windows.h```).
> Lower case the include directive of windows header

- src/path.c
- src/repository.c
- src/repository.h
- tests/repo/reservedname.c
When we look at a submodule's 8dot3-compatible "short name", we really need to look at the name of the .git file that specified the actual repository directory, not the repository directory.
Ie, given a submodule .git:
gitdir: ../.git/modules/libgit2
We shouldn't resolve the shortname of the repository `libgit2`, or else we'll end up preventing somebody from creating a file `libgit2` in their repository.  We care about the `.git` file itself.
Now, a repository can have multiple "reserved names".  By default, this contains only `.git` on non-Windows platforms.  On Windows platforms, this will contain `.git` and `git~1`, and we will look at the short name of the `.git` pointer file in a submodule, or the `.git` repository itself.
I think this is a little more clear than trying to maintain a …
> NTFS path validation: care about the short name of the submodule pointer file, not the short name of what it points to

- tests/clar.c
Update clar to 08f434d.  This could save us a little bit of time in test execution on the CI builds as it makes the `-s` flag imply the `-i` flag for tests that are disabled by default.  Our test workflow at present is to run the default tests, then run the online tests afterward (using `-s...`).  This patch should mean that we don't re-run all the tests we've already run *and* the online tests, it will *only* run the online tests.
> clar: update to 08f434d

- src/win32/git2.rc
The "Comments" field of a DLL resource is not immediately visible (in Windows Explorer, for example) but it is queryable.  Consumers may wish to put something custom here about their DLL build - for example, the version of LibGit2 that it was built from.
> win32 resource: allow custom comments field in DLL

- src/checkout.c
Oops.  (On file creation, you won't have a `new` path and this is a less than good experience.)
> checkout: report correct invalid path

- examples/.gitignore
- examples/Makefile
- examples/remote.c
This commit implements an example for the remote API. The program mimics behavior of git remote, providing the subcommands add, remove, rename, set-url and show.
> examples: add remote example.

- CHANGELOG.md
- include/git2/notes.h
- src/notes.c
- tests/notes/notes.c
- tests/notes/notesref.c
The caller has otherwise no way to know how long the string will be
allocated or ability to free it.
This fixes #2944.
---
The code is still a bit awkward, as we return an allocated string which for most uses we do not use, but at least it's safe and freeable.
> note: use a git_buf to return the default namespace

- include/git2/sys/transport.h
- src/transport.c
- src/transports/git.c
- src/transports/http.c
- src/transports/smart.c
- src/transports/ssh.c
- src/transports/winhttp.c
A custom param will enable the implementer of a smart subtransport to store payload.
> Add a custom param to git_smart_subtransport_definition

- examples/.gitignore
- examples/Makefile
- src/describe.c
- tests/describe/describe.c
Currently it is not possible to describe a revision with OID fallbacks enabled and a repository that has got no refs. This PR fixes the issue and provides a test that detects the error.
In addition to the fix I also included a second commit that enables building the describe example by default and adds the resulting executable to .gitignore. Feel free to drop that patch if it is not desired.
> Fix describe without refs and OID fallbacks

- src/config.c
- src/config_file.c
- src/diff_driver.c
- tests/config/read.c
The regcomp function returns a non-zero value if compilation of
a regular expression fails. In most places we only check for
negative values, but positive values indicate an error, as well.
Fix this tree-wide, fixing a segmentation fault when calling
git_config_iterator_glob_new with an invalid regexp.
> Fix checking of return value for regcomp.

- src/repository.c
- tests/checkout/index.c
If `work_dir` is not specified, use `repo_dir` to test if symlink is supported
This avoids temp file creation failure if current directory is readonly.
> If work_dir is not specified, use repo_dir to test if symlink is supported

- include/git2/pack.h
- src/pack-objects.c
- src/transports/local.c
- src/tree.c
- tests/clone/nonetwork.c
When we have e.g. a tag, we also need to recursively insert referenced objects, not just the top one as we do currently. This introduces a function to recursively insert objects without having to care about the particular type and then uses it in the local transport.
While getting the test wrong, I also saw that we have some misleading error messages in the tree entry lookup, so one of the commits changes the error message a bit as well.
> Make sure to pack referenced objects for non-branches

- CMakeLists.txt
- appveyor.yml
- src/util.h
- tests/main.c
These changes add memory leak reporting to the clar test suite using the MSVC CRTDBG facility.
To activate, set MSVC_CRTDBG on the CMAKE line.  Initial testing shows several leaks, but I have not yet investigated them to see if they are just leaks in the tests or in the library proper.
We might consider improving this further with the following:
* change clar exit status if there are leaks.
* use the crtdbg checkpoint facility (in conjunction with the detailed trace reporting) to indicate which specific test caused the leak.
> Add memory leak detection/reporting using MSVC CRTDBG facility.

- include/git2/revwalk.h
- src/revwalk.c
- tests/revwalk/basic.c
When a commit is first set as unintersting and then pushed, we must take care that we do not put it into the commit list as that makes us return at least that commit (but maybe more) as we've inserted it into the list because we have the assumption that we want anything in the commit list.
This fixes the aside made in #3034 though it shouldn't be the cause of the slowness.
> Handle hide-then-push in the revwalk

- src/ignore.c
- tests/status/ignore.c
Currently we are not able to correctly handle negative ignore patterns when they do not contain wildcards. This PR fixes the issue and adds a test that checks for a few different cases that have been checked to match the behavior of git.git.
I'm not really comfortable with the function name "does_negate_pattern" - if there are any ideas I'd be glad to change its name.
> ignore: fix negative ignores without wildcards.

- src/diff_tform.c
When diffs are generated, the value for the 'nfiles' field of 'git_diff_delta'
will be consistent with the value in the 'status' field. Merging diffs can
modify the 'status' field of some deltas and the 'nfiles' field needs to be
updated accordingly.
> Make sure to also update delta->nfiles when merging diffs

- CHANGELOG.md
- include/git2/rebase.h
- include/git2/reset.h
- src/rebase.c
- src/reset.c
- tests/rebase/abort.c
- tests/rebase/iterator.c
- tests/rebase/merge.c
- tests/rebase/setup.c
Introduce a few trivial fixes to rebase:
* Provide the ability to identify when a rebase has been initialized (with `rebase_init`) but the first patch has not yet been applied.  Since we track the *current patch*, beginning at index 0, this is useful.
* Correct `git_rebase_commit` to return `GIT_EUNMERGED` when there are unmerged paths (as it is documented to do)
* Calling `git_rebase_commit` when there are unstaged changes should produce an error, similar to git.git:
> You must edit all merge conflicts and then mark them as resolved using git add
And a more serious one:  we took `git_checkout_options` for `git_rebase_next` to use when it was applying the patch.  We did not take `git_checkout_options` in `git_rebase_init` (which checks out the base, "rewinding" to it) or …
> Rebase fixes

- src/global.c
- src/global.h
- src/win32/pthread.c
Here is an attempt to fix the TLS leak on Windows reported by CRTDBG. 
```
D:\lg2\src\global.c(264) : {644153} normal block at 0x0433E948, 56 bytes long.
Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
The thread TLS data contains space for storing the thread's error info.  It looks like this is only used by the thread itself during its lifetime.  Control thread waiting for the thread to finish just look at the final exit code (in the various thread_join) calls.  So it looks safe to have the thread dispose of the data as it is exiting.
I have only tested this using the CLAR suite on Windows.
> Attempt to fix Windows TLS memory leak.

- tests/network/remote/remotes.c
- tests/online/remotes.c
I wrangled moving the 2 tests that were failing over to the online subdirectory and renamed the test functions accordingly.  Thanks for marking things as "up for grabs" by the way, as it makes it much easier to help/participate.
Please let me know if you guys want anything changed here, but I think the change set seems pretty reasonable.
Commit Message:
Moved offending tests from network to online so they will get skipped
when there is a lack of network connectivity:
-test_online_remotes__single_branch
-test_online_remotes__restricted_refspecs
> Fix for Issue #3023 tests fail with no network

- src/checkout.c
- src/index.c
- tests/checkout/tree.c
- tests/index/filemodes.c
git_checkout_tree() has some fallback behaviors for file systems
which don't have full support of filemodes.  Generally works fine,
but if a given file had a change of type from a 0644 to 0755 (i.e.,
you add executable permissions), the fallback behavior incorrectly
triggers when writing hte updated index.
This would cause a git_checkout_tree() command, even with the
GIT_CHECKOUT_FORCE option set, to leave a dirty index on Windows.
Also added checks to an existing test to catch this case.
> Fix git_checkout_tree() to do index filemodes correctly on Windows.

- src/config_file.c
- tests/config/write.c
- tests/resources/config/config21
When `config_write` is called with `value = NULL`, ensure that we searche the whole config file before giving up.
This is necessary to handle the possibility of duplicate headers.
For example, given:
```
[remote "origin"]
[branch "master"]
remote = "origin"
[remote "origin"]
url = "foo"
```
Trying to delete remote.origin.url would silently fail to remove the actual entry as it would exit after passing through the first matching section.
Fixes #3043, where this bug could cause `remote_rename` to duplicate a remote (it created a new remote while silently failing to delete the old one).
> config_write -- handle duplicate section headers when deleting entries

- src/config_file.c
- tests/config/read.c
- tests/config/write.c
We were not previously validating the configuration keys and were allowing any old string before an equal sign to be considered a configuration key.
We should only allow alphanumerics and dash (`-`), like [git does](https://github.com/git/git/blob/master/config.c#L318), and which [we documented](https://github.com/libgit2/libgit2/blob/master/src/config_file.c#L1133) but were not previously enforcing.
> Validate configuration keys

- src/reflog.c
Fix wrong format string in `git_reflog_drop()` error message
> Fix wrong format string in git_reflog_drop() error message

- tests/rebase/merge.c
> Fixed unused warning in tests/rebase/merge.c

- CHANGELOG.md
- include/git2/merge.h
As part of updating the version of libgit used by LibGit2Sharp, I came across a couple of breaking changes where some more documentation would have been helpful.
The CHANGELOG.md changes are for modifications in 142e5379
> Update documentation for API changes

- src/checkout.c
- src/filter.c
- src/remote.c
In checkout.c and filter.c we were casting a sub struct
to a parent struct which breaks the strict aliasing rules
in C. However we can use .parent or .base to access the
parent struct to avoid the build warnings.
In remote.c the local variable error was not initialized
or updated in some cases. For unintialized error a build
warning will be generated. So always keep error variable
up-to-date.
> Fix some build warnings

- include/git2/push.h
- include/git2/remote.h
- include/git2/types.h
- src/push.c
- src/push.h
- src/remote.c
- tests/online/push_util.h
It can be useful for the caller to know which update commands will be
sent to the server before the packfile is pushed up. git does this via
the pre-push hook.
We don't have hooks, but as it adds introspection into what is
happening, we can add a callback which performs the same function.
---
This isn't tested yet beyond not crashing the current tests but it should provide a good platform on which to decide how we want to approach our equivalent to the pre-push hook, which is at the heart of what #3004 is trying to get to.
I wanted to make it work for both upload and download and we might still do so, but we should probably focus on the push part first.
> [WIP/RFC] push: report the update plan to the caller

- cmake/Modules/FindIconv.cmake
Since OpenSSL isn't used any more on OS X, there is no dependency
on any MacPorts library under /opt/local and there is no danger of
conflicts between MacPorts and system iconv. For this reason the
system iconv can always be used now.
> Don't search iconv in /opt/local

- src/config_file.c
- tests/config/write.c
You can have a configuration file with two sections with the same name.  For example:
[section "foo"]
name = value
[section "bar"]
barname = barvalue
[section "foo"]
name2 = value2
Our existing `config_write` makes assumptions that once it has seen a section it will never see that section again, and will simply copy the rest of the file in.  This means that with the above example, we cannot change `section.foo.name2`; we would add the new value to the first section, then copy the rest of the file, which would leave us with the second section.
Instead, we need to read the rest of the file when writing, in case we see another section with the same name.  Doing so means that we need to examine each line of the config file.
I've moved the common configuration parsing code into a function that …
> Configuration changes for handling multiple of the same sections

- CMakeLists.txt
When building on Mac OS X, the `CoreFoundation` and `Security` frameworks where missing from `Libs.private` in the generated `libgit2.pc` file.
This should fix building Rugged on OS X.
> Ensure frameworks are mentioned in libgit2.pc

- CMakeLists.txt
- README.md
The reason why Android build needed deps/regex is Android NDK 4 doesn't include those regex symbols in the libc.so. See https://groups.google.com/forum/#!topic/android-ndk/BepvBlDw4_w.
It is a bug in Android NDK 4 rather than Android 2.2 (froyo).
I cannot find an Android 2.2 (froyo) device or emulator. But the libc.so in Android NDK 10 for Android 2.2 (froyo) does contain the regex functions. (Froyo's Android API level is 8). This means the native library should be able to use these functions on Android 2.2 devices. Removing deps/regex from Android build can only break those projects that still use Android NDK 4. Should we worry about that?
android-ndk-r10c/platforms/android-8/arch-arm/usr/lib$ arm-linux-androideabi-objdump -t libc.so | grep reg
00008044 g F .text 00000014 …
> Android build doesn't need deps/regex

- src/filter.c
64K is optimal buffer size per https://technet.microsoft.com/en-us/library/cc938632.aspx. This change should benefit any x86 based system, not just Windows.
> Adjusting stream buffer size to 64KB

- AUTHORS
- CHANGELOG.md
- include/git2/checkout.h
- include/git2/stash.h
- src/checkout.c
- src/index.c
- src/index.h
- src/merge.c
- src/merge.h
- src/stash.c
- tests/core/structinit.c
- tests/index/read_index.c
- tests/merge/trees/treediff.c
- tests/stash/apply.c
A modification on #2705.  I made some notes in that PR, though actually acting on those notes was quite a bit more challenging than I had hoped.  This introduces two lower level ideas:
* `git_merge__iterators`, to allow one to merge a tree and an index and get an index out as a result.  (Interestingly `git_merge` had this broken out as a helper function at one point, and it was brought back in.  So now it's a helper function again.)  This allows us to merge the results of another merge, without having to write it out to a tree.
* `git_index_read_index`, which behaves like `git_index_read_tree` except that it reads an index into the index.  This maintains the stat cache of the existing items.
Sorry about the long delay in finishing this up.  Stash application is completely and totally …
> Stash apply

- src/blob.c
- src/common.h
- src/filebuf.c
- src/fileops.c
- src/filter.c
- src/odb.c
- src/transports/http.c
Moving all IO buffer size values into common.h for easy modification for those who actually need to restrict the size of stack allocated buffers.
Defaulting the value of buffer sizes to 64KiB.
> Centralizing all IO buffer size values

- src/odb.c
We currently first look in the loose object dir and then in the packs
for objects. When performing operations on recent history this has a
higher likelihood of hitting, but when we deal with operations which
look further back into the past, we start spending a large amount of
time getting ENOTENT from `access`.
Reversing the priorities means that long-running operations can get to
their objects faster, as we can look at the index data we have in memory
(or rather mapped) to figure out whether we have an object, which is
faster than going out to the filesystem.
The packed backend already implements an optimistic read algorithm by
first looking at the packs we know about and only going out to disk to
referesh if the object is not found which means that in the case where
we do have the …
> odb: reverse the default backend priorities

- tests/clone/nonetwork.c
We have a few tests checking each step, but we do not yet have a test
which tests the documented workflow for creating a submodule, namely
`setup_add` followed by cloning into it, followed by `add_finalize`.
Add such a test to protect against regressions in this workflow.
> submodule: add test initialising and cloning a repo

- include/git2/index.h
While we are confident about the size of an int in architectures we're
likely to care about, the index format is defined by the exact size of
the fields. Use the definitions which show the exact width of the entry
fields.
As part of that, bring back 32-bit time and size fields, which currently
are 64 bits wide and can bring a false sense of security in how much
data they really store. Document that these fields are not to be taken
as authoritative.
---
Funnily enough, this doesn't throw any warnings during compilation, which means that we're already using these sizes internally.
> index: make the entries have more accurate sizes

- include/git2/odb.h
- include/git2/odb_backend.h
- include/git2/sys/odb_backend.h
- src/blob.c
- src/odb.c
- src/odb.h
- src/odb_loose.c
Restricting files to size_t is a silly limitation. The loose backend
writes to a file directly, so there is no issue in using 63 bits for the
size.
We still assume that the header is going to fit in 64 bytes, which does
mean quite a bit smaller files due to the run-length encoding, but it's
still a much larger size than you would want Git to handle.
---
This should be enough to fix #2936 though this return an error if no backends support streaming writes in, as we currently still try to keep everything in memory. We will have to use a spill buffer at some point, but that's longer-term and would only affect users with custom backends which do not support streaming.
> odb: make the writestream's size a git_off_t

- examples/network/clone.c
- src/pack-objects.c
- src/pack-objects.h
- src/transports/local.c
Related to #1902 , start showing git-similar text during the packing process to show the client that we are doing something.
> Show progress during packing for the local transport

- src/transports/local.c
- tests/network/remote/local.c
This is what #1902 was complaining about all that time ago.
What we currently do is likely one of the worst ways of pushing. By actually using the packbuilder we also get the progress which we lack.
> Use the packbuilder in local push

- src/attr.c
- src/attr_file.c
- tests/attr/ignore.c
When a rule specifies a folder, eg:
foo/
Ensure that a file of the same name is not matched.  (In the above example, a file named `foo`).
I added a relatively minor change to attr matching to handle this case, by simply testing whether we're looking at a file with the same name as the directory.  This also involved removing some historic path mangling that is unnecessary after we always use our own `fnmatch` function that supports folders.
However I did a little bit more refactoring in 90997e4 that allows us to do a little less copying and path mangling in general, which seems like a win.
Also, I also added some regression tests in adad518 for ensuring that attrs are actually matched in the directories that specify them.  (This was fixed in c6bf03b but additional tests made seemed to make …
> Attributes: don't match files for folders

- src/push.c
- tests/network/remote/push.c
The feature was merged before the tests were ready, so let's add them now and fix the constructor.
This fixes #3126
> Add tests for and fix push negotiation notification

- src/transports/smart_protocol.c
Early EOF is used 2 more times and uses a capital E in the beginning. Let's have them the same.
> Bring Early EOF message in line with the other two

- src/fileops.c
- src/path.c
This function currently always overwrites the underlying error message with a rather useless one. Instead let's let the callback set their own error message and only set our own when they fail to do so. 
This sets a more informative error message for #2797 and fixes #2965
> Provide error messages for git_path_direach operations

- CHANGELOG.md
- src/index.c
- tests/index/addall.c
Re-adding every entry means we hash data we already have hashed, which proves quite a bit slower than it has to be. We can know whether we need to re-calculate hashes by iterating over the entries a diff gives us, rather than every entry in the index.
This should resolve #2687
> Use a diff for iteration in index_update_all and index_add_all

- CHANGELOG.md
- include/git2/errors.h
- src/openssl_stream.c
- src/transports/smart_protocol.c
- src/transports/ssh.c
Git's reporting for errors on the server is all over the place. Sometimes you'll get an error via the protocol, sometimes that same process will send the error over stderr. This PR catches those different ways of reporting errors an make it easier for tools to report such errors.
Crucially, if a repository we're trying to access over ssh is not there, the server process will send the error message over stderr rather than send an error pkt (which it does for some other errors, such as three-level repo names on GitHub). If we don't get anything over stdout, we report whatever we get from stderr as the error message.
Adding `GIT_EEOF` comes from the fact that it's a somewhat unique failure mode, and we can expect users of the library to be able to respond to it; e.g. git itself shows the …
> Improve server error reporting

- src/ignore.c
- tests/status/ignore.c
When we discover that we want to keep a negative rule, make sure to
clear the error variable, as it we otherwise return whatever was left by
the previous loop iteration.
This fixes #3143
> ignore: clear the error when matching a pattern negation

- src/index.c
- tests/index/addall.c
By default, diff will collapse a new directory that contains only untracked files into a single delta for the whole directory.  (This is akin to `git status` on the command line's behavior.)
Make `git_index_add_all` ask for the individual untracked files, so it can add each of them.
> index_add_all: include untracked files in new subdirs

- include/git2/remote.h
Use enumerator name to fix build as C++.
> Fix error when building as C++.

- src/openssl_stream.c
We use a blocking socket and set the mode to AUTO_RETRY which means that
`SSL_write` and `SSL_read` will only return once the read or write has
been completed. We therefore don't need to handle partial writes or
re-try read due to a regenotiation.
While here, consider that a zero also indicates an error condition.
> openssl: don't try to handle WANT_READ or WANT_WRITE

- src/indexer.c
- src/pack.c
When fixing a thin pack, we should not try to open an index for the packfile that we are currently writing.  (There is guaranteed to be no index.)  The second commit is really not a big win (we will probably have the base cached), but might prevent some unnecessary mucking around in the object cache.
> Thin packs: don't 

- src/ident.c
- tests/checkout/crlf.c
- tests/filter/blob.c
- tests/filter/custom.c
- tests/filter/ident.c
Git inserts a space after the SHA1 (as of 2.1.4 at least), so do the same for consistency.
This is particularly useful when diffing a filtered blob against a file checked out by Git, as without this the `$Id$` line will be different.
---
Git behavior:
```console
$ git --version 
git version 2.1.4
$ git init .
Initialized empty Git repository in .../.git/
$ echo '$Id$' > foo
$ echo 'foo ident' > .gitattributes
$ git add foo .gitattributes
$ git commit -m "init"
[master (root-commit) 3684894] init
2 files changed, 2 insertions(+)
create mode 100644 .gitattributes
create mode 100644 foo
$ rm -f foo
$ git checkout .
$ cat foo
$Id: 055c8729cdcc372500a08db659c045e16c4409fb $
```
> Fix ident replacement to match Git behavior

- CHANGELOG.md
- examples/network/fetch.c
- examples/network/ls-remote.c
- include/git2/remote.h
- src/remote.c
- tests/network/remote/local.c
- tests/network/remote/remotes.c
- tests/online/remotes.c
The `set_fetch_refspecs()` bit was something which I wasn't quite sure if we wanted to support. But changing the idea of what the base refpecs are at runtime... doesn't sit well with me, so let's just remove it. If you want to perform complex fetches, you can perform a couple or craft your per-operation refspecs to your satisfaction.
This also fixes a test which was relying on implicit side effects in clone and which this run-time setting let succeed even though the final result was not what we wanted.
Add validation to `add_fetch()` and `add_push()` and removed the fetch param from `create_anonymous()` which cannot have configured refspecs by definition.
> Tackle remote API issues from bindings

- src/branch.c
- src/refspec.c
- tests/network/refspecs.c
- tests/refs/branches/upstream.c
We currently leave all strings `NULL` when we find a matching refspec. This means that you can't treat all refspecs the same. Let's fill in these strings so a consumer/transformer doesn't have to care whether they're dealing with a matching refspec or not.
The extra test came about because of #3140 where I realised that we don't return the right error message.
This fixes #3140
> Fill the pointers for matching refspecs

- CHANGELOG.md
- include/git2/diff.h
- include/git2/index.h
- include/git2/status.h
- src/diff.c
- src/index.c
- src/iterator.c
- src/iterator.h
- src/merge.c
- src/reset.c
- src/status.c
- tests/checkout/conflict.c
- tests/checkout/index.c
- tests/checkout/tree.c
- tests/clar_libgit2.c
- tests/clar_libgit2.h
- tests/diff/diff_helpers.c
- tests/diff/diff_helpers.h
- tests/diff/index.c
- tests/diff/workdir.c
- tests/index/addall.c
- tests/index/collision.c
- tests/index/conflicts.c
- tests/merge/trees/trivial.c
- tests/merge/workdir/trivial.c
- tests/object/tree/duplicateentries.c
- tests/reset/hard.c
- tests/status/worktree.c
When diffing a tree with the index, or the index with the working directory, it is useful to know whether you have conflicts.  At present, we only look at zero-stage index entries when iterating the index, which has the effect of pretending as if conflicts don't exist at all.
This has generally been okay (even if bizarre), but by ignoring conflicts, a conflicted file might appear to be ignored (because it does not exist in the index).  This could cause a consumer to fail to add a conflict resolution when [using a mechanism that filters out ignored files during add](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Repository.cs#L1640).
Add a new diff delta type, `CONFLICTED`, to return when a conflict exists in the index.  (Do not provide any of the `old_file` or `new_file` …
> Include conflicts when diffing

- CHANGELOG.md
- include/git2/errors.h
- src/checkout.c
- src/merge.c
- src/stash.c
- tests/checkout/tree.c
- tests/stash/apply.c
We do not error on "merge conflicts"; on the contrary, merge conflicts
are a normal part of merging.  We only error on "checkout conflicts",
where a change exists in the index or the working directory that would
otherwise be overwritten by performing the checkout.
This *may* happen during merge (after the production of the new index
that we're going to checkout) but it could happen during any checkout.
> Rename GIT_EMERGECONFLICT to GIT_ECONFLICT

- CHANGELOG.md
- include/git2/remote.h
- src/remote.c
- tests/remote/insteadof.c
- tests/resources/testrepo2/.gitted/config
This PR implements intepretation of the url.*.insteadOf and url.*.pushInsteadOf configurations. They are intended to replace URL prefixes with user-chosen prefixes, e.g. url.git@foo.insteadOf = https://bar would result in the URL https://bar:repos/baz being rewritten to git@foo:repos/baz. This can be useful when a user wants to use different access methods for a certain repository or similar use cases.
I've implemented this by adding two new fields url_insteadof and pushurl_insteadof to the `git_remote` struct which can be accessed through newly added functions. It might have been nicer to fold this into existing methods, but like this backwards compatibility is intact as nothing will change for existing users.
In addition, there was a new option `apply_insteadof` added to `struct …
> Implementation of url.*.insteadOf

- appveyor.yml
equivalent of ca183d27366ba75597a9806b746e42a074df7795
If I get a moment I'll also see if I can backport some of #2946 to v0.22
> build maint branches on appveyor

- include/git2.h
- src/attr.c
- src/attr_file.c
- src/checkout.c
- src/config.c
- src/config_file.c
- src/diff_driver.c
- src/diff_tform.c
- src/ignore.c
- src/reflog.c
- src/revwalk.c
- tests/attr/ignore.c
- tests/checkout/tree.c
- tests/config/read.c
- tests/status/ignore.c
Here's a few things we can backport for v0.22.3. There's a bunch of useful fixes in master which don't quite fit into v0.22 anymore as they rely on newer code, so the list isn't as large as I wanted, but these are still good fixes if anybody can't update to v0.23 immediately.
> Maintenance updates for v0.22

- examples/describe.c
Hello.
Use the previously created function to display a message when the arguments are not valid.
https://github.com/libgit2/libgit2/issues/3095
]$ ./describe --abcde
usage: see `git help describe
> print_usage functions is defined but not used

- src/path.c
- tests/odb/foreach.c
When the callback returns an error, we should stop immediately. This
broke when trying to make sure we pass specific errors up the chain.
This broke cancelling out of the loose backend's foreach.
> path: error out if the callback returns an error

- src/global.c
Additionally, check if the locking callback is already set before
setting it, and if it's our callback before unsetting it. This way we
can play a bit nicer with other libraries that also use OpenSSL that may
also be part of the application using our library.
> global: Ensure we free our SSL context.

- src/filter.c
- src/merge.c
- src/object.c
- src/pack.c
This is what I managed to get done this morning. There's some very real issues fixed in this branch plus a bit of readability.
Unfortunately I haven't managed to figure out how to tell it to ignore memory leaks in case of OOM so it's not the nicest thing to drudge through the issues to find the real ones.
> A few more fixes from coverity

- .gitattributes
Use "text=auto" to ensure that we get LFs in the repository, but
let clients have their native line endings in their worktree.
> gitattributes: let clients use native line endings

- src/diff_tform.c
git_diff_find_similar() now ignores git_diff_delta records with a status
of GIT_DELTA_CONFLICTED, which fixes a crash due to assert() being hit.
> Fixed handling of GIT_DELTA_CONFLICTED  in git_diff_find_similar()

- src/indexer.c
We've been using `p_ftruncate()` to extend the packfile in order to mmap
it and write the new data into it. This works well in the general case,
but as truncation does not allocate space in the filesystem, it must do
so when we write data to it.
The only way the OS has to indicate a failure to allocate space is via
SIGBUS which means we tried to write outside the file. This will cause
everyone to crash as they don't expect to handle this signal.
Switch to using `p_lseek()` and `p_write()` to extend the file in a way
which tells the filesystem to allocate the space for the missing
data. We can then be sure that we have space to write into.
> indexer: use lseek to extend the packfile

- CHANGELOG.md
- include/git2/filter.h
- src/filter.c
- tests/filter/query.c
`git_filter_list_contains` can be used to query a filter list to determine if a given filter will be run.
This is useful, for example, for determining whether the repository intends to run (for instance) the `crlf` or `ident` filter for a particular file.  Note that it is *not* necessarily a substitute for running the filter or some of the deeper introspection that the filter itself may do.  For example, just because you're running the `crlf` filter doesn't mean that you're actually doing `\n` -> `\r\n` conversion.  One could have `eol=lf`, which the `crlf` filter is also resposible for.
> Introduce `git_filter_list_contains`

- include/git2/cred_helpers.h
Make both `username` & `password` in `git_cred_userpass_payload` `const`. The values are not altered anywhere, and the extra qualifier allows clients to assign `const` values there.
I've checked most of the bindings listed on homepage and none of them seem to use `git_cred_userpass_payload`. The tests pass. Also confirmed that gitg & subsurface (two random packages using libgit2) don't rely on the lack of `const`. So it should be safe to change.
> cred_helpers: Add 'const' qualifiers to git_cred_userpass_payload

- src/path.c
Memory leak in git_path_diriter on Windows.
> Fix memory leak on windows in diriter.

- src/openssl_stream.c
This is a backport of a944c6cc40273b45922fa22949fe6b12ff668889, but it didn't cherry-pick cleanly so I resolved the conflict by hand.
> Fix MinGW build against openssl on maint/v0.22

- src/path.c
- src/path.h
Arguably all uses of readdir_r are unnecessary, but in this case
especially so, as the directory handle only exists within this function,
so we don't race with anybody.
> path: remove unnecessary readdir_r usage

- src/transaction.c
Transaction.c did not include the visibility definition of its symbol
(that are in git2/transaction.h) and so was by default hidden.
> Fix visibility of transaction symbol

- src/remote.c
This is what we used to return in the settter and there's tests in
bindings which ask for this. There's no particular reason to stop doing
so.
---
This seems like the right place to put it, though I don't know if anybody has a better idea.
> remote: return EINVALIDSPEC when given an empty URL

- src/commit.c
- tests/commit/parse.c
Some tools create multiple author fields. git is rather lax when parsing
them, although fsck does complain about them. This means that they exist
in the wild.
As it's not too taxing to check for them, and there shouldn't be a
noticeable slowdown when dealing with correct commits, add logic to skip
over these extra fields when parsing the commit.
----
The size check may look a bit awkward. It's done this way because we don't have `git__prefixncmp()` and I didn't quite feel this deserved adding more util functions.
This fixes #3182
> commit: ignore multiple author fields

- src/checkout.c
- src/index.c
- src/unix/posix.h
- src/win32/posix.h
- src/win32/posix_w32.c
- src/win32/w32_util.h
- tests/checkout/checkout_helpers.c
- tests/checkout/checkout_helpers.h
- tests/checkout/crlf.c
- tests/core/posix.c
- tests/diff/racy.c
- tests/diff/workdir.c
- tests/merge/workdir/dirty.c
- tests/status/worktree.c
This is a part of racy-git which we have not implemented, and can lead to diffs between the index and the workdir that do not include files which were modified immediately after the index was written.
> Zero out racily-clean entries' file_size

- include/git2/index.h
- src/index.c
- src/index.h
- src/submodule.c
- src/submodule.h
- tests/index/tests.c
We currently use a timetamp to check whether an index file has been modified since we last read it, but this is racy. If two updates happen in the same second and we read after the first one, we won't detect the second one.
Instead read the SHA-1 checksum of the file, which are its last 20 bytes which gives us a sure-fire wa to detect whether the file has changed since we last read it.
PS: There's also `git_index__changed_relative_to()` which is used in a couple of places, which we might want to update at some point.
> Use the checksum to check whether an index has been modified

- src/checkout.c
- src/diff.c
- src/diff.h
- tests/status/worktree.c
When diff updates the index, it updates based on the *workdir* mode.  It should instead preserve the original mode to ensure that symlinks on Windows are not treated as regular files (which is their workdir mode).
> Don't propagate workdir's mode to the index during diff's update index

- src/stash.c
Same as with git_stash_save(), there's no reason not to write the index
to disk since it has been modified.
> Write modified index in git_stash_apply()

- CHANGELOG.md
- include/git2/commit.h
- src/commit.c
- tests/commit/parse.c
This allows the user to look up fields which we don't parse in libgit2,
and allows them to access gpgsig or mergetag fields if they wish to
check the signature.
--- 
This should be enough to consider #762 closed. We may perform some checking in the future, but for now it falls to the user.
> commit: allow retrieving an arbitrary header field

- include/git2/blob.h
We currently recommend using `git_buf_grow` in order to make a buffer
make an owned copy of the memory it points to. This is not behaviour we
should encourage, so remove this recommendation.
The function itself is not changed, as we need to remain compatible, but
it will be changed not to allow usage on borrowed buffers.
---
This comes from the discussion in #3187. /cc @ethomson
> blob: don't recomment using git_buf_grow

- src/repository.c
- tests/repo/open.c
It hasn't mattered that we don't check for it on open, as it has been 0 since the first release of git, way back when; but times, they're a-changing and we will soon(ish) see version 1in the wild and we must take care that we don't open those and possibly break something (or just produce uncomprehensible results).
> Check the repository version

- CHANGELOG.md
- src/diff.c
- src/index.c
- src/iterator.c
- src/iterator.h
- tests/diff/racy.c
- tests/diff/workdir.c
- tests/index/racy.c
- tests/merge/workdir/dirty.c
- tests/status/worktree.c
It turns out that the description in racy-git is deceptively simple, and the implementation for the smudging of racily-clean entries goes all the way to performing a diff check which we were not doing.
---
I'm not too thrilled with the use of `sleep()` but the alternative is changing the timestamp for both the index and file in unison, which we may actually want to do, but it's good enough for PoC.
> racy-git, the missing link

- include/git2/describe.h
This fixes a warning in `examples/describe.c` without breaking the main build.
OTOH, I'm not sure if this is an API-compatible change.
> Add `const` qualifier

- src/diff.h
- src/diff_tform.c
- src/stash.c
- tests/stash/foreach.c
- tests/stash/save.c
- tests/stash/stash_helpers.c
We do not presently stash files correctly when a file is added in the index and then modified in the working directory.  We are examining only the working directory with regard to the HEAD, and without examining the index as well (with that file staged) we treat that file as untracked and thus do not include it in the workdir tree.
Correct that by using a diff that includes the index similar to `git_diff_tree_to_workdir_with_index` but with different special cases.  (`git_diff_tree_to_workdir_with_index` is aimed at producing something like `git diff` and so collapses some cases - we differ in that we want to ensure that we still pay attention to the workdir side when the index side is deleted.)
> Stash workdir correctly when added in the index, modified in the workdir

- src/diff_patch.c
- src/diff_patch.h
- tests/diff/binary.c
Set `GIT_DIFF_PATCH_DIFFABLE` correctly for all files that differ, regardless of binary-ness.  It's up to the callbacks what to do about diffable files - either producing an actual binary delta diff, or simply saying "Binary files differ".
Binary files need some deeper inspection into this, since we have avoided loading their data if we knew we wouldn't need it (eg, `SHOW_BINARY` was not provided).  This means we look at the actual file sizes to determine difference, not the file map data size.  Note that we cannot do this for all deltas since some (like submodules) populate the file map data but do not actually have files backing them.
Ugh.
> Handle binary DIFFABLEness properly

- CHANGELOG.md
- CMakeLists.txt
- THREADING.md
- include/git2/sys/stream.h
- include/git2/types.h
- src/curl_stream.c
- src/curl_stream.h
- src/openssl_stream.c
- src/stransport_stream.c
- src/stream.h
- src/transports/http.c
cURL has a mode in which it provides TLS and proxy setup but otherwise allows us to use one of its handles very much like our own streams, so it's fairly simple to make the library use libcurl for talking to the server.
~~~Unfortunately I have not found a way to extract the certificate information without implementing it via the multiple crypto engines which curl uses, which is not something we can do.~~~
What we'll do here is use libcurl as the underlying stream and then build our own TLS streams on top of that. This allows us to keep doing what we do with certificates while letting libcurl take care of the proxy.
> Implement a cURL stream

- examples/status.c
- include/git2/diff.h
- include/git2/submodule.h
- include/git2/types.h
- src/checkout.c
- src/config.c
- src/config.h
- src/diff_file.c
- src/repository.c
- src/repository.h
- src/submodule.c
- src/submodule.h
- tests/diff/submodules.c
- tests/diff/tree.c
- tests/submodule/init.c
- tests/submodule/modify.c
- tests/submodule/nosubs.c
- tests/submodule/status.c
- tests/submodule/submodule_helpers.c
- tests/submodule/update.c
It's me again, breaking all your code. Hopefully it's for the better.
I was doing the same thing to submodules as to remotes, but found that we have even deeper problems here. We currently have a per-repo cache of submodules, which unfortunately makes code like
```C
puts(git_submodule_url(sm));
```
susceptible to crashing, as we dish out submodules from that cache, but make them mutable so a different thread might have got the same intsance and may be setting the url or simply reloading it.
The first commit gets rid of this cache and returns a new instance per lookup. It leaves some tests broken, but that gets fixed later in "bring back finding by path" and "correct detecting of existing submodules"
The rest of the commits get rid of the load-modify-save pseudo-ORM which was a bad idea to …
> Remove run-time configuration settings from submodules

- CHANGELOG.md
- include/git2/blob.h
- include/git2/errors.h
- src/buffer.c
- src/buffer.h
- src/path.c
- tests/core/buffer.c
When we don't own a buffer (asize=0) we currently allow the usage of grow to copy the memory into a buffer we do own. This muddles the meaning of grow, and lets us be a bit cavalier with ownership semantics.
Don't allow this any more. Usage of grow should be restricted to buffers which we know own their own memory. If unsure, we must not attempt to modify it.
This includes a cherry-pick of the documentation change that just went into the maintenance release. This also comes from the discussion in #3187.
> Don't allow growing borrowed buffers

- src/remote.c
- tests/fetchhead/nonetwork.c
When a refspec contains no rhs and thus won't cause an explicit update,
we skip all the logic, but that means that we don't update FETCH_HEAD
with it, which is what the implicit rhs is.
Add another bit of logic which puts those remote heads in the list of
updates so we put them into FETCH_HEAD.
This fixes #3241
> remote: insert refspecs with no rhs in FETCH_HEAD

- src/object.c
- tests/diff/blob.c
- tests/refs/revparse.c
They were previously fucked up since @carlosmn merged https://github.com/libgit2/libgit2/pull/3201
The inconspicuous fix to stop Coverity from complaining broke essentially most prefix lookups in the library where the prefix was more than 20 nibbles long. I'm glad I caught this in github/gitrpc integration testing 'cause this the kinda stuff that keeps me awake at night.
> Desenfuckenate prefix lookups

- include/git2/errors.h
- src/iterator.c
- src/iterator.h
- src/merge.c
- src/stash.c
- tests/stash/apply.c
Stash application should stage new files, even when we're not updating the index.
````
C:\Temp\stash_apply_sucks>git status
On branch master
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
new file:   bar
modified:   foo
C:\Temp\stash_apply_sucks>git stash
Saved working directory and index state WIP on master: 4a6df6d foo
HEAD is now at 4a6df6d foo
C:\Temp\stash_apply_sucks>git status
On branch master
nothing to commit, working directory clean
C:\Temp\stash_apply_sucks>git stash apply
On branch master
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
new file:   bar
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   foo
```` …
> Stash apply: stage new files even when not updating the index

- libgit2.pc.in
Because of the fact that pkg-config is pants-on-head retarded and that
the Linux linker *requires* a static library to come before all its
dynamic dependencies in the link path, calling `pkg-config --libs
--static` was generating the wrong flags for linking.
Before this patch:
-Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/local/lib -lcurl -lssh2
-lrt -lgit2 -lssl -lcrypto -ldl -lz
After this patch:
-Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/local/lib -lgit2 -lcurl
-lssh2 -lrt -lssl -lcrypto -ldl -lz
By setting the "Libs" line before all other rules, we make sure that
`-lgit2` is the first library in the link path and that it gets its
symbols resolved with the libraries coming after it.
This fix (ab)uses an implementation detail in `pkg-config` (namely, that
flags are output as they are …
> pkg-config: Sort the different sections

- src/submodule.c
- src/transports/http.c
- tests/submodule/lookup.c
Plug a leak in submodules and re-allow trainling slashes for looking up submodules.
Let the HTTP transport ask the caller again if the server rejected authentication.
> Submodule and http fixes

- src/transports/http.c
t->cred might have been allocated the previous time and needs to be
freed before asking caller for credentials again.
> http: fixed leak when asking for credentials again

- src/repository.c
Fix 8.3 filename tests failure when 8.3 is disabled
> Fix 8.3 filename tests failure when 8.3 is disabled

- src/submodule.c
- tests/submodule/lookup.c
Oh my, regex.
We were missing the pattern to match a full stop just after the submodule name, so when we wanted to look for 'Test_App' , we would create the lookup rule `submodule\.Test_App.*` which is obviously wrong. We want `submodule\.Test_App\..*` or we end up looking up the 'Test_App2' submodule as well.
This fixes #3284
> Correctly delimit the keys for submodule lookup

- tests/filter/stream.c
Don't use the filter's free callback to free the actual data structure
holding the filter, as we may not always actually initialize it (the
test may be skipped).
> filter::stream: free the filter sanely

- include/git2/filter.h
These functions are available on the public API but don't have any
documentation, so they don't appear on the API reference. Fix that.
This fixes #3283
> filter: add docs for streaming filters

- src/remote.c
- src/sysdir.c
- src/util.c
- src/util.h
- src/win32/posix_w32.c
- tests/clar_libgit2.c
- tests/clar_libgit2.h
- tests/core/env.c
- tests/core/ftruncate.c
- tests/filter/stream.c
- tests/online/clone.c
- tests/online/push.c
- tests/repo/init.c
Presently, `cl_getenv` wraps `getenv` on posixy systems and does some UTF16-UTF8 magic on Windows.  The return code must be freed on Windows and must not be on Unix boxes.  Ugh.
`p_getenv` just wraps `getenv` on all systems, which means it's ANSI code page on Windows.  (This hasn't really bitten us, yet, as we don't read potentially Unicode values in the library, only in the tests.)  But still, ugh again.
This introduces `git__getenv` which is a UTF-8 aware `getenv` everywhere.  Plus some helpery clar stuff because we can.
> git__getenv: utf-8 aware env reader

- git.git-authors
Antoine Pelisse <apelisse@gmail.com> has kindly allowed his contributions to core git to be used under the libgit2 license.
> meta: Add Antoine Pelisse to hall-of-fame list

- src/blame_git.c
- src/xdiff/xdiff.h
- src/xdiff/xdiffi.c
- src/xdiff/xdiffi.h
- src/xdiff/xemit.c
- src/xdiff/xemit.h
- src/xdiff/xhistogram.c
- src/xdiff/xmerge.c
- src/xdiff/xpatience.c
- src/xdiff/xprepare.c
- src/xdiff/xutils.c
- src/xdiff/xutils.h
- tests/merge/files.c
- tests/revert/workdir.c
Upgrade xdiff to version used in core git 2.4.5 ([0df0541](https://github.com/git/git/commit/0df0541)).
Corrects an issue where a trailing newline is added at the EOF when all the inputs lacked a trailing newline.
> Don't add unnecessary trailing newline during file merge

- CHANGELOG.md
- include/git2/sys/filter.h
- src/filter.c
- tests/filter/custom.c
- tests/filter/custom_helpers.c
- tests/filter/custom_helpers.h
- tests/filter/wildcard.c
Allow custom filters with wildcard attributes, so that clients
can support some random `filter=foo` in a .gitattributes and look
up the corresponding smudge/clean commands in the configuration file.
This is a one-liner to match `*` in an attribute value.  Otherwise, this is mostly tests.
> filters: custom filters with wildcard attributes

- CHANGELOG.md
- include/git2/transport.h
- src/curl_stream.c
- src/openssl_stream.c
- src/stransport_stream.c
- src/transports/ssh.c
- src/transports/winhttp.c
Add a proper `parent` member to the `git_cert` descendants to prevent type punning.
> git_cert: child types use proper base type

- src/openssl_stream.c
Versions prior to 0.9.8f  did not have this function, rhel/centos5 are still on a
heavily backported version of 0.9.8e and theoretically supported until March 2017
Without this ifdef, I get the following link failure:
```
CMakeFiles/libgit2_clar.dir/src/openssl_stream.c.o: In function `openssl_connect':
openssl_stream.c:(.text+0x45a): undefined reference to `SSL_set_tlsext_host_name'
collect2: error: ld returned 1 exit status
make[6]: *** [libgit2_clar] Error 1
```
> Fix undefined reference with old versions of openssl

- CMakeLists.txt
- README.md
My bad, this policy line was introduced with #2986
> Increase required version of cmake to 2.8

- examples/network/fetch.c
Under normal conditions, git_remote_fetch() should be the only function
used to perform a fetch. Don't let the example lead people astray.
> examples: modernise the fetch example

- src/submodule.c
- tests/submodule/lookup.c
This solution is probably fragile, but it'll do until the config-loading gets moved to something less callback-based.
This fixes #3293
> List a submodule only once when the path matches a submodule in the index

- src/thread-utils.c
As above, fixes build warning on Visual Studio.
> Fix macro redefinition warning

- include/git2/remote.h
`git_fetch_options` was [missing from the api docs](https://libgit2.github.com/libgit2/#HEAD/search/git_fetch) so I gave it a doc comment.
Also fixed a small typo.
> Document git_fetch_options struct and fix typo.

- CHANGELOG.md
- include/git2/sys/refdb_backend.h
- src/branch.c
- src/refdb_fs.c
- tests/refs/branches/delete.c
Removing a reflog upon ref deletion is something which only some
backends might wish to do. Backends which are database-backed may wish
to archive a reflog, log-based ones may not need to do anything.
This fixes #2939.
> refdb: delete a ref's reflog upon deletion

- include/git2/errors.h
- src/blob.c
- src/index.c
- tests/index/bypath.c
- tests/submodule/add.c
Just like git allows you to do `git add some_submodule` to update the entry in the index. ~~~This still needs some work extracting the submodule-entry code from the submodule and making sure we invalidate the tree right (wrt casing).~~~ We use a function which does the invalidation, so it's fine.
This also adds `GIT_EDIRECTORY` as an error code and provides a nicer error message when trying to add a directory.
> Allow adding a submodule through git_index_add_bypath

- src/path.c
- src/path.h
- src/submodule.c
- tests/submodule/lookup.c
Our functions expect slashes in the url, so convert backslashes before looking at it. This is a similar though distinct problem to what we have when fetching. There we act on the url/path so we can ask the filesystem for a realpath. Here we're just acting on the string, so we can't rely on that.
This fixes #2248 and possibly #2706.
> Normalize submodule urls before looking at them

- src/iterator.c
- tests/repo/iterator.c
An error here will typically mean that the directory was removed between
the time we iterated the parent and the time we wanted to visit it in
which case we should ignore it.
Other kinds of errors such as permissions (or transient errors) also
better dealt with by pretending we didn't see it.
This is an alternative to #3327 which is probably better as it should cover more cases. The test for this is still unfortunately really hard to get it to trigger and trying to get it into shape for submission makes it stop finding the error (and somehow trigger a segfault seemingly inside pthreads).
> iterator: skip over errors in diriter init

- src/transports/git.c
- src/transports/ssh.c
For such a path '/~/...' the leading '/' is stripped so the server will
get a path starting with '~' and correctly handle it.
solution for issue #3345
> Handle ssh:// and git:// urls containing a '~' character.

- src/index.c
- tests/index/bypath.c
index: stage an unregistered submodule as well
We previously added logic to `_add_bypath()` to update a submodule. Go
further and stage the submodule even if it's not registered to behave
like git.
This is an alternative to #3326 and #3336 which mimics git's behaviour while not changing the behaviour of the submodule API, so we can easily backport it.
> index: stage an unregistered submodule as well

- src/filebuf.c
- src/filebuf.h
- tests/core/filebuf.c
When we have an error renaming the lockfile, we need to make sure
that we remove it upon cleanup. For this, we need to keep track of
whether we opened the file and whether the rename succeeded.
If we did create the lockfile but the rename did not succeed, we
remove the lockfile. This won't protect against all errors, but
the most common ones (target file is open) does get handled.
This test is only active for Windows because that's where it happens. The reasons this would fail to rename on unix (no write permission on the parent) would also prevent us from removing the file (if not from creating it outright).
>  filebuf: remove lockfile upon rename errors

- include/git2/errors.h
- src/clone.c
- src/common.h
- src/errors.c
- src/global.c
- src/global.h
- src/index.c
- src/iterator.c
- tests/core/errors.c
Merges #3329 and #3323 and tightens up the sloppiness where we blindly free the detached error message (which may be the static OOM string) by providing a free function.  Move everything to the `giterr_state` namespace, lest `giterr_free` be confusing.
> Error handling: use buffers, improved OOM handling

- include/git2/errors.h
- src/errors.c
- tests/core/errors.c
I noticed a mechanism that can lead to attempts to free the statically allocated OOM error message (whilst trying to reproduce #3313).  The function `giterr_detach` assumes that any error message it detaches is dynamically allocated.  This PR fixes that, so that it becomes safe to detach an OOM error.
I have also added a test that performs the full `giterr_capture`/`giterr_restore` cycle, checking to ensure that the static pointer is not saved in the `git_error_state` structure.
Comments welcome!
> Fix attempt to free static OOM error message

- src/errors.c
- src/global.c
- src/global.h
Instead of allocating a brand new buffer for each error string we want
to store, we can use a per-thread buffer to store the error string and
re-use the underlying storage. We already use the buffer to format the
string, so this mostly makes that more direct.
Checking for cumulative allocations with valgrind, this saves about a tweet's worth of error strings and 2 mallocs when opening a repostory, and the `core` suite saves about 15kB and 204 mallocs. A `-xonline` run of the full test suite saves about 62MB and 660k mallocs (plus their corresponding frees).
These are not memory usage numbers, but memory we keep getting and returning to the system, and `malloc` and `free` calls we're saving. It's not necessarily a big deal for every use-case, but it's still a small win on each of them.
> error: store the error messages in a reusable buffer

- CHANGELOG.md
- include/git2/config.h
- include/git2/sys/config.h
- src/config.c
- src/config.h
- src/config_file.c
- src/config_file.h
- src/transaction.c
- src/transaction.h
- tests/config/write.c
You sometimes want to update more than a single entry in the configuration. This is not possible currently, which is why exposing a couple of new functions is necessary.
These allow you to lock a configuration file, locking out concurrent writers, and perform many operations without any readers seeing them (and as an implementation detail, without doing any I/O) until you commit it.
I wanted to do this via `git_transaction` but it turns out the API doesn't really fit what we do here, or we'd have to add more namespacing.
/cc @jamill who mentioned the need for something like this when users prefer clicking to opening up `.git/config` with their editor.
> Locking and transactional/atomic updates for config

- src/curl_stream.c
When curl uses a proxy, it will only use Basic unless we prompt it to
try to use the most secure on it has available.
This is something which git did recently, and it seems like a good idea.
> curl: use the most secure auth method for the proxy

- src/diff_driver.c
- tests/diff/drivers.c
When parsing user-provided regex patterns for functions, we must not
fail to provide a diff just because a pattern is not well
formed. Ignore it instead.
--
This fixes #3235
> diff: don't error out on an invalid regex

- src/transports/smart_protocol.c
The conditional checked cbs->transfer_progress then used the value in cbs->push_transfer_progress. In both cases it should be push_transfer_progress
> Fix bug in git_smart__push: push_transfer_progress cb is only called at end

- CMakeLists.txt
Starting at OS X 10.8, the Security framework offers some functions
which are unified across OS X and iOS. These are the functions that we
use.
Older versions of OS X do not have these functions and we fail to
compile. In these situations, fall back to using OpenSSL for our TLS
stream instead.
---
@alexcrichton can you give this a try? I tested it locally by reversing the logic, but I'd like to get an actual confirmation.
> CMake: fall back to OpenSSL on older OS X

- include/git2/sys/transport.h
- include/git2/transport.h
- src/transports/cred.c
- src/transports/smart.c
libgit2 implementations of smart subtransports can simply reach through
the structure, but external implementors cannot. Provide this functions
as a way for the smart subtransports to get the callbacks as set by the
user.
---
The current external implementors I know of don't need this, either because it's just for testing, or because their purpose is to bypass the libgit2 authentication bits.
But if you want to write one which behaves just like the built-in ones, we need access to these functions.
> transport: provide a way to get the callbacks

- src/transports/smart_pkt.c
Improve error messages as described in issue #2830 by including the 4 characters not recognised as hexadecimal digit.
If there are any control characters among these, we stop at the first one found to avoid garbage in error string.
> Include the 4 characters not recognised as hex-number in parse_len

- COPYING
Include the copyright notice from the deps/winhttp/ sources.  Move the
LGPL to the bottom of the file (since multiple dependencies are LGPL
licensed) and include the actual copyright notices from the regex sources.
> COPYING: include winhttp definition copyright

- include/git2/cred_helpers.h
Fixes the following warning.
```
/Users/phatblat/dev/libgit2/objective-git/External/libgit2/include/git2/cred_helpers.h:37:66: warning: unknown command tag name 'host'; did you mean 'post'? [-Wdocumentation]
* @param user_from_url The username that was embedded in a "user@host"
^~~~~~
post
```
> Escape @ in doc comment

- include/git2/diff.h
- src/checkout.c
- src/diff.c
- src/index.c
- src/iterator.c
- src/iterator.h
- src/merge.c
- src/notes.c
- src/pathspec.c
- src/refdb_fs.c
- src/stash.c
- src/submodule.c
- tests/diff/iterator.c
- tests/diff/workdir.c
- tests/merge/trees/treediff.c
- tests/repo/iterator.c
- tests/status/worktree_init.c
- tests/submodule/status.c
- tests/threads/iterator.c
I rebased #2888 onto master and was faced with mega conflicts.  In resolving these I:
1. Wanted the filelists to be part of the general iterator mechanism, instead of having a workdir iterator and a workdir+filelist iterator
2. Did not want a third diff path maching mechanism (pathspecs, non-pathspecs and slightly more literal iterator filelists).
So this moves the filelists into the general iterator mechanisms, and it expands the filelist handling to deal with directory prefixes (eg, `foo/`) instead of requiring that patches be listed explicitly.
Note that this should be generally adequate and a huge perf benefit for index and workdir iterators (like the original was), and tree iterators are working, but they expand all trees unnecessarily.  We could perform tree iteration without …
> Provide path matching in the iterators (for faster diffs)

- src/idxmap.h
- src/index.c
- src/index.h
- tests/index/filemodes.c
- tests/index/tests.c
The whole discussion[0] below is a bit of a mess, so the summary is that we can keep the hash table alongside the vector with a rather small penalty to parsing and filling times as long as we pre-allocate the size of the table (which we do in this series), so here it is.
We hash case-insensitively so we don't have to rehash when the index changes its case-sensitivity. There shouldn't be any extra collisions as long as we don't actually have paths which would collide.
During the switch from case-sensitive to case-insensitive, we do assume that we haven't now created two entries which would match the same (path, stage) key, but the vector sorting seems to assume the same thing.
[0] For lack for a better term, like "Carlos' stream of consciousness while he can't benchmark his way out of a …
> Use a hashmap for path-based lookups in the index

- CHANGELOG.md
- src/filebuf.c
- tests/core/filebuf.c
We create a lockfile to update files under GIT_DIR. Sometimes these
files are actually located elsewhere and a symlink takes their place. In
that case we should lock and update the file at its final location
rather than overwrite the symlink.
---
It's quite late, but this should take care of #620.
The code to resolve the symlink is not pretty at all, but it seems we don't have this anywhere else. It might be worth putting in a more general place if there's a need to do this elsewhere, though I don't know if we want to follow symlinks in any other situation.
> filebuf: follow symlinks when creating a lock file

- include/git2/index.h
- src/index.c
- tests/index/tests.c
git_index_directory_iterator, git_index_directory_iterator_new,
git_index_directory_iterator_next and git_index_directory_iterator_free
are added.
I know we could achieve this by going through git_tree_entry recursively for stage 0.
But I think my patch here is more efficient compared to that approach. Further this patch
also support going through a directory in other stages.
> New feature: add the ablility to iterate through a directory in index

- CHANGELOG.md
- src/index.c
- tests/index/bypath.c
- tests/index/rename.c
On case insensitive systems, when given a user-provided path in the
higher-level index addition functions (eg `git_index_add_bypath` /
`git_index_add_frombuffer`), examine the index to try to match the
given path to an existing directory.
Various mechanisms can cause the on-disk representation of a folder
to not match the representation in HEAD or the index - for example,
a case changing rename of some file `a/file.txt` to `A/file.txt`
will update the paths in the index, but not rename the folder on
disk.
If a user subsequently adds `a/other.txt`, then this should be stored
in the index as `A/other.txt`.
For example:
% git init .
% mkdir a
% echo hello > a/file.txt
% git add a
% git commit -mfoo
% git mv -f a/file.txt A/file.txt
% git status
On branch master
Changes to be committed:
(use …
> index: canonicalize directory case when adding

- tests/core/filebuf.c
- tests/core/futils.c
Tests the alternate method by which #3310 might be failing.
> filebuf: ensure we can lock a hidden file

- src/odb_mempack.c
The first time `git_mempack_reset` is called it frees the objects in `db->objects` but the pointers to those objects are left in place. So if an attempt is made to reset the mempack again, a “double free” occurs.
> Fixing dangling pointers in git_mempack_reset

- src/submodule.c
- tests/submodule/lookup.c
When searching for information about a submdoule, let's be more explicit
in what we expect to find. We currently insert a submodule into the map
and change certain parameters when the config callback gets called.
Switch to asking for the configuration we're interested in, rather than
taking it in an arbitrary order.
---
Not as many minuses as I'd hoped, but a bunch of the code is rather repetitive. This may handle #3365 as a side-effect, but there's currently no test for explicitly such a case.
> submodule: refactor to be more explicit in the search

- src/transaction.c
- tests/config/write.c
The config is not owned by the transaction, so please don’t free it.
> Don't free config in `git_transaction_commit`.

- tests/online/push.c
- tests/online/push_util.c
- tests/online/push_util.h
These are small pieces of data, so there is no advantage to allocating
them separately. Include the two ids inline in the struct we use to
check that the expected and actual ids match.
---
I just saw this earlier today an it annoyed me that we were allocating a couple of `git_oid` instead of using them in the struct.
> push: put the git_oid inline in the test structure

- src/path.c
- tests/core/dirent.c
On Windows, our `git_path_diriter` adds a '/' to combine the path being queried with a filesystem entry.  For example, when iterating a directory `c:/foo` that contains some file `bar.txt`, we create a path `c:/foo/bar.txt`.  (Yay!)
We need to not do this on the root of a volume (eg, `c:/`) since it is already, correctly, suffixed with a `/`.
Fixes #3417
> Handle `git_path_diriter` instances at the drive root on Windows

- src/checkout.c
- tests/checkout/tree.c
As reported in #3158, we do not quite handle mode changes correctly in checkout.  We will always set execute bits properly, but we fail to *unset* execute bits.
This ports the unit tests that were mentioned in #3158.  It does not take the fix that was mentioned in that issue, though, as it was heavy-handed.  Instead, we simply delete the old file and let `p_open` set the mode for us and drop any notion of trying to `chmod`.  (This is handy since we were not providing the umask properly, nor is there a sane way to query the umask in a thread safe manner across architectures.)  
Fixes #3158
> Checkout: handle mode changes

- src/checkout.c
- src/fileops.c
- src/fileops.h
- src/odb_loose.c
- src/path.c
- src/path.h
- src/refdb_fs.c
- src/repository.c
- src/win32/posix_w32.c
- tests/checkout/index.c
- tests/config/global.c
- tests/core/buffer.c
- tests/core/copy.c
- tests/core/mkdir.c
- tests/core/stat.c
- tests/index/tests.c
- tests/odb/alternates.c
- tests/refs/pack.c
- tests/repo/discover.c
- tests/repo/init.c
- tests/repo/iterator.c
- tests/repo/open.c
- tests/status/ignore.c
- tests/status/worktree.c
- tests/submodule/status.c
When attempting to create a directory recursive (eg, matching `mkdir -p` semantics), we walk *up* from the given `base` to determine what directories need to be created.  For checkout, this is right and good and true as we may stumble across a symbolic link within the working directory, and this needs to be *deleted* and re-created as a proper directory.
However, we should only do this walk up when we have a `base` to build relative paths from (eg, when operating in the repository or working directory).  Otherwise, we'll end up trying to walk all the way up from the directory root to the path that we're trying to create.  This is not correct.  For example: we shouldn't be examining `/home` to create a repository in `/home/user/foo/myrepo.git` - we may get hung up trying to stat `/home`. …
> `mkdir`: split into `mkdir` and `mkdir_relative`

- CMakeLists.txt
- libgit2.pc.in
Before:
libdir=/usr//usr/lib64
includedir=/usr//usr/include
After:
libdir=/usr/lib64
includedir=/usr/include
(note the duplication of /usr in the before case)
> pkg-config: fix directory references in libgit2.pc

- src/config_file.c
- tests/config/write.c
This tries to solve the same issue as #3368 while reducing the amount of changes that are needed by using the buffering technique described by @ethomson in that thread.
We buffer the comments until we are forced to write them by reaching a section end, a variable or the end of the file.
> Keep config comments in the same place as git

- src/win32/path_w32.c
- tests/win32/longpath.c
Reset the windows error message when we detect that a path was too long, setting the windows error to `ERROR_FILENAME_EXCED_RANGE`,
(Why the Windows team in their infinite wisdom decided to save that single character to avoid spelling `EXCEED` correctly, I'll be damned if I know.)
We only test clone, where we cannot *create* a file whose name is longer than `MAX_PATH`.  We do not have a test where we try to read a file whose name is longer, because we'd have to first *create* said file and all our internal path munging is already unable to do that.
> win32: give better error message on long paths

- src/diff_print.c
- tests/diff/binary.c
git expects an empty line after the binary data:
literal X
...binary data...
<empty_line>
The last literal block of the generated patches were not containing the required empty line. Example:
diff --git a/binary_file b/binary_file
index 3f1b3f9098131cfecea4a50ff8afab349ea66d22..86e5c1008b5ce635d3e3fffa4434c5eccd8f00b6 100644
GIT binary patch
literal 8
Pc${NM&PdElPvrst3ey5{
literal 6
Nc${NM%g@i}0ssZ|0lokL
diff --git a/binary_file2 b/binary_file2
index 31be99be19470da4af5b28b21e27896a2f2f9ee2..86e5c1008b5ce635d3e3fffa4434c5eccd8f00b6 100644
GIT binary patch
literal 8
Pc${NM&PdElPvrst3ey5{
literal 13
Sc${NMEKbZyOexL+Qd|HZV+4u-
git apply of that diff results in:
error: corrupt binary patch at line 9: diff --git a/binary_file2 b/binary_file2
fatal: patch with only garbage at line 10
The proper …
> Fix binary diffs

- tests/online/badssl.c
These provide bad X.509 certificates, which we should refuse to connect
to by default.
> net: add tests against badssl.com

- tests/win32/longpath.c
This was a leftover debugging message.
> win32::longpath: don't print path

- include/git2/sys/odb_backend.h
- include/git2/sys/refdb_backend.h
- src/odb.c
- src/refdb.c
- tests/odb/sorting.c
As refdb and odb backends can be allocated by client code, libgit2
can’t know whether an alternative memory allocator was used, and thus
should not try to call `git__free` on those objects.
Instead, odb and refdb backend implementations must always provide
their own `free` functions to ensure memory gets freed correctly.
> refdb and odb backends must provide `free` function

- examples/network/fetch.c
`transfer_progress_cb` should return a value, otherwise the transfer gets aborted sometimes.
> Examples: network/fetch.c transfer_progress_cb - should return a value

- CMakeLists.txt
There's been a few reports of users not understanding what the python
error means, so spell out the options they have.
> CMake: be more explicit with python errors

- src/odb.c
- src/odb_pack.c
- tests/odb/sorting.c
As discussed in chat -- the commit messages have all the details.
cc @carlosmn @ethomson 
cc @scottjg who spotted this
> Fix pathological performance in ODB lookups

- include/git2/index.h
- src/index.c
- tests/index/bypath.c
When we are on a filesystem where we do not trust the mode (ie, Windows), we presently preserve the modes from a given file when adding entries to the index by looking at the existing index entry for that path.
If we are resolving a conflict, we should also look at *those* entries to try to take their mode.  (If you had a file that was executable and are resolving the conflict on Windows, you would not want to lose the executableness.)
> Preserve modes from a conflict in `git_index_insert`

- src/commit_list.c
- src/commit_list.h
- tests/revwalk/basic.c
We moved the "main" parsing to use 64 bits for the timestamp, but the
quick parsing for the revwalk did not. This means that for large
timestamps we fail to parse the time and thus the walk.
Move this parser to use 64 bits as well.
> revwalk: make commit list use 64 bits for time

- src/index.c
- src/signature.c
- tests/commit/signature.c
- tests/diff/workdir.c
- tests/revwalk/basic.c
- tests/revwalk/signatureparsing.c
So, Git does this: https://github.com/github/git/blob/github/ident.c#L137-L155
And we don't. So I feel we should be doing this. As to do the same thing that Git does. Even though whatever Git does is weird. But this is causing commits to differ from my experiments. So it would make my life easier if we did the same thing that Git does.
cc @carlosmn @ethomson
> signature: Strip crud

- include/git2/config.h
- src/config.c
- src/config.h
- src/repository.c
- src/sysdir.c
- src/sysdir.h
- src/win32/findfile.c
- src/win32/findfile.h
- tests/config/global.c
This is where portable git stores the global configuration which we can
use to adhere to it even though git isn't quite installed on the system.
---
The test isn't amazing, but it gets the job done. Locally I had to add my user as allowed to touch the file, so let's see how this goes on Appveyor.
/cc @ethomson
> config: add a ProgramData level

- include/git2/errors.h
- include/git2/merge.h
- src/merge.c
- tests/merge/merge_helpers.c
- tests/merge/trees/commits.c
Provide a new merge option, GIT_MERGE_TREE_FAIL_ON_CONFLICT, which
will stop on the first conflict and fail the merge operation with
GIT_EMERGECONFLICT.
> merge: add GIT_MERGE_TREE_FAIL_ON_CONFLICT

- src/xdiff/xdiff.h
Although CMake will correctly configure include directories for us,
some people may use their own build system, and we should reference
`util.h` based on where it actually lives.
> xdiff: reference util.h in parent directory

- CMakeLists.txt
The MSVC_SPLIT_SOURCES function is helpful for other IDEs, like Xcode,
and will split the source files up into their target directories,
instead of merely placing them all in a "Sources" directory.
Rename MSVC_SPLIT_SOURCES to IDE_SPLIT_SOURCES and enable it for Xcode.
> cmake: split sources into original paths for Xcode and MSVC

- include/git2/merge.h
- src/index.c
- src/merge.c
First, we optimize the way REUC insertion works to make it hundreds of times faster (from 17s to 200ms when inserting 39k entries).
Second, we add a merge trees flag that allows us to skip the REUC generation altogether (for users that don't need to display merge results).
Lastly, we plug a small memory leak that we introduced with the `FAIL_ON_CONFLICT` flag.
cc @carlosmn @ethomson
> Better REUC generation when merging

- src/attr_file.c
- src/attrcache.c
- src/checkout.c
- src/commit_list.c
- src/diff.c
- src/diff_tform.c
- src/index.c
- src/iterator.c
- src/merge.c
- src/pack-objects.c
- src/pathspec.c
- src/pool.c
- src/pool.h
- src/refdb_fs.c
- src/repository.c
- src/revwalk.c
- src/sortedcache.c
- src/transaction.c
- tests/core/pool.c
So, here's the deal: the existing pool implementation is terribly slow. For some merge cases, you can see more than 70% of the runtime dominated by pool allocations!
Why is it so slow? Because it does a lot of very complex calculations & pointer wrangling just for the sake of keeping a "free list" and trying to squeeze some bytes out of each allocation. IMO this basically defeats the point of a memory pool/slab allocator.
I've re-implemented the pool to look more like a slab allocator. There's always an existing slab; when the existing slab has not enough space to fulfill the requested allocation, we allocate a new slab.
This implementation is hundreds of times faster than the old pool for most cases. For instance: a particular merge of the `cdnjs` repository that I discussed with …
> pool: Simplify implementation

- include/git2/sys/transport.h
We should explicitly include the declaration of git_strarray
from "include/git2/sys/transport.h"
> Fix build for custom transport users

- src/config_file.c
- src/fileops.c
- src/fileops.h
- tests/config/stress.c
Instead of using the file size and timestamp, which can lead us to ignore changes performed in the same second, use a checksum of the file contents to detect when it has changed.
> Use checksums to detect config file changes

- tests/online/badssl.c
If none of GIT_OPENSSL, GIT_WINHTTP or GIT_SECURE_TRANSPORT
is defined we should also be able to build the unit test.
> Fix build for unit test

- CHANGELOG.md
- include/git2/sys/stream.h
- src/stream.h
- src/tls_stream.c
- tests/core/stream.c
This allows the application to use their own TLS stream, regardless of
the capabilities of libgit2 itself.
---
The naming feels a bit all over the place, so suggestions there would be great.
> stream: allow registering a user-provided TLS constructor

- CHANGELOG.md
- include/git2/common.h
- src/global.c
- src/global.h
- src/settings.c
- src/transports/http.c
- src/transports/winhttp.c
- tests/core/useragent.c
It's not just us who wants fame and notoriety, some tools using the library want it to, and want their name in the User-Agent field; let's let them do that.
We do have to keep the "git/1.0" so that web servers still recognise us as wishing to talk to Git rather than a web server.
This is missing the plain/ssh support, since we don't currently send the agent over there. We should also add this capability, which might happen in this PR or not. It would be a new behaviour rather than a change, and would require us to potentially change the string given by the user, as we'd need a slug rather than a generic string.
> Support setting custom user-agent

- src/filebuf.c
- src/refdb_fs.c
- tests/core/filebuf.c
- tests/refs/create.c
- tests/refs/reflog/reflog.c
For whatever reason, we often have users who create a reference directory (eg, `refs/heads/foo/bar`) and then try to create a new reference in one of those components (eg, `refs/heads/foo`).
Our error message in that case is not very actionable - since we use a `git_filebuf`, we will successfully create the lockfile, but then we will likely fail to create the reflog (since there's a directory in its place).
As a result, the error message looks something like:
```
Could not open 'C:/Temp/testrepo.git/logs/refs/heads/new-dir' for writing: Access is denied.
```
This adds some tests to ensure that we clean up around empty directories properly.  (We do!  But I didn't see anything testing this *directly* and I wanted to make sure that this was legitimately user error and not us failing to clean …
> Improve error messages when dirs prevent ref/reflog creation

- src/pool.c
- tests/core/pool.c
Fixes https://github.com/libgit2/libgit2/issues/3504
@logancollins: Could you please verify that this works now in ARM64 & ARM32? I think we're doing alignment properly now for all architectures, but I don't have that hardware to try. :)
> pool: Never return unaligned buffers

- include/git2/common.h
- src/settings.c
- tests/clar_libgit2.c
- tests/config/global.c
Protect the windows SYSDIR when running tests, like we protect the other configuration levels, setting their paths to our sandbox path.
> Protect windows SYSDIR when running tests

- src/index.c
- tests/checkout/crlf.c
- tests/index/racy.c
At present, when we go to write a new index, we look for index entries that have racy timestamps (entry timestamps that are the same or newer than the index's timestamp) and examine them, so that we can zero their file size if they are actually not clean.  This prevents future git clients from accidentally believing that the files are up to date.
However, we do not take into account when *we're* the ones who write new files.  That means that in checkout, we load an index, write a bunch of files and update their index entries.  When we go to write the new index, we detect that every file we've written as part of checkout is newer than the index that we loaded.  Thus we inspect every file that we just checked out to see if it's up to date or not.  Yet we *know* that the files are up to …
> Racy fixes for writing new indexes

- CMakeLists.txt
- src/fileops.c
This PR fixes some issues related to the detection of ```stat```'s members. There is no real consensus between systems or even different versions of the same system when it comes to ```st_atim```/```st_atimespec``` and friends.
> Stat fixes

- src/win32/win32-compat.h
Turns out that the error code path will never be entered seeing that assigning an ```int``` of value ```-1``` to a ```uint64_t``` will give you 18446744073709551615.
> Fix <0 unsigned comparison (stat.st_size should be an off_t)

- src/checkout.c
- src/diff.c
- src/diff.h
- src/index.c
- src/index.h
When examining the working directory and determining whether it's
up-to-date, only consider the nanoseconds in the index entry when
built with `GIT_USE_NSEC`.  This prevents us from believing that
the working directory is always dirty when the index was originally
written with a git client that uinderstands nsecs (like git 2.x).
> checkout: only consider nsecs when built that way

- src/tree.c
- src/tree.h
Here's a couple of simple changes to the way we parse trees which gives us significant improvements.
The first one is just silly, really. We've already calculated how long the filename is, so we can just skip over it instead of looking for the terminator again. This gives us about half the gains.
Then, we can also very easily avoid constantly asking the system for memory by allocating the entries in a pool owned by the tree. The lifetime of the entries is tied to the tree already, so this is a great place to use a pool. Those entries for which we give ownership to the user don't need to change, as we already perform an extra allocation to give them their own lifetime.
I checked the speedup by parsing the top-level tree for `git.git` for ~41k commits. The timing is a bit rough, but the …
> Improvements to tree parsing speed

- src/tree.c
When duplicating a `struct git_tree_entry` with
`git_tree_entry_dup` the resulting structure is not allocated
inside a memory pool. As we do a 1:1 copy of the original struct,
though, we also copy the `pooled` field, which is set to `true`
for pooled entries. This results in a huge memory leak as we
never free tree entries that were duplicated from a pooled
tree entry.
Fix this by marking the newly duplicated entry as un-pooled.
> tree: mark cloned tree entries as un-pooled

- src/index.c
When adding to the index, we look to see if a portion of the given
path matches a portion of a path in the index.  If so, we will use
the existing path information.  For example, when adding `foo/bar.c`,
if there is an index entry to `FOO/other` and the filesystem is case
insensitive, then we will put `bar.c` into the existing tree instead
of creating a new one with a different case.
Use `strncmp` to do that instead of `memcmp`.  When we `bsearch`
into the index, we locate the position where the new entry would
go.  The index entry at that position does not necessarily have
a relation to the entry we're adding, so we cannot make assumptions
and use `memcmp`.  Instead, compare them as strings.
When canonicalizing paths, we look for the first index entry that
matches a given substring. …
> index: canonicalize inserted paths safely

- tests/checkout/index.c
Fix the file-mode test to expect system umask being applied to the created file as well (it is currently applied to the directory only). This fixes the test on systems where umask != 022.
> checkout test: Apply umask to file-mode test as well

- CHANGELOG.md
- src/tree.c
The trees are sorted on-disk, so we don't have to go over them
again. This cuts almost a fifth of time spent parsing trees.
> tree: mark a tree as already sorted

- include/git2/submodule.h
- src/submodule.c
This fits with the style of the rest of the project, but more importantly makes life easier for bindings authors who auto-generate code.
> Use a typedef for the submodule_foreach callback.

- src/reset.c
- tests/reset/hard.c
This keeps the state of the workdir the same as one from HEAD, removing
a source of possible confusion when calculating the work that is to be
done.
This should handle  #3541 and bring us close to what we generally should be doing when switching the current commit.
/cc @vmg
> reset: perform the checkout before moving HEAD or the index

- src/index.c
When replacing an index with a new one, we need to iterate
through all index entries in order to determine which entries are
equal. When it is not possible to re-use old entries for the new
index, we move it into a list of entries that are to be removed
and thus free'd.
When we encounter a non-zero error code, though, we skip adding
the current index entry to the remove-queue. `INSERT_MAP_EX`,
which is the function last run before adding to the remove-queue,
may return a positive non-zero code that indicates what exactly
happened while inserting the element. In this case we skip adding
the entry to the remove-queue but still continue the current
operation, leading to a leak of the current entry.
Fix this by checking for a negative return value instead of a
non-zero one when we want to add …
> index: always queue `remove_entry` for removal

- src/transports/winhttp.c
Have the winhttp transport treat a GIT_PASSTHROUGH returned from the credential handler the same as if there was no handler.  This matches the [documentation for `git_remote_callbacks.credentials`](https://libgit2.github.com/libgit2/#HEAD/type/git_remote_callbacks) and the implementations of the http and ssl transports.
> Treat GIT_PASSTHROUGH as though git_cred_acquire_cb isn't set.

- src/index.c
- src/index.h
- src/merge.c
See the commit message for details. This fixes a performance issue when merging _truly_ large trees (roughly 1.5 million entries).
cc @carlosmn @ethomson (HAH how's that for a sabbatical)
cc @piki @simonsj
> merge: Use `git_index__fill` to populate the index

- include/git2/blob.h
putting `0.` at the start of the line turns it into a numbered list.
> fix git_blob_create_fromchunks documentation

- src/idxmap.h
- src/index.c
- src/vector.c
- src/vector.h
- Adjust the namemask for the index entry (just in case!)
- Normalize the filemode (also just in case!)
- Pre-allocate the entries array (since we already know the final size!)
cc @carlosmn @ethomson
> Index fill: Small fixups

- include/git2/stash.h
- src/path.c
When cross-compiling to ARM, my compiler was complaining about these:
https://github.com/libgit2/libgit2/blob/7f2c146/include/git2/stash.h#L71
https://github.com/libgit2/libgit2/blob/7f2c146/src/stash.c#L510
https://github.com/libgit2/libgit2/blob/7f2c146/src/path.h#L550
https://github.com/libgit2/libgit2/blob/7f2c146/src/path.c#L1402
Seems it was a couple instances of mixing unsigned int with uint32_t. For consistency, just changed them to uint32_t, assuming it's desired to have a guaranteed 32-bit wide flag.
> Fix a couple function signatures

- src/repository.c
- tests/repo/init.c
Include dotfiles when copying the template directory, which handles both #3459 (that template dirs with a leading dot are not copied) and the additional issue illustrated in #3472 (that dotfiles inside the template dir are not copied).
> Handle dotfiles as the repo template dir and inside the template dir

- src/index.c
- src/index.h
We don't support using an index object from multiple threads at the same
time, so the locking doesn't have any effect when following the
rules. If not following the rules, things are going to break down
anyway.
> index: get rid of the locking

- src/transports/ssh.c
Fix the possibility of returning successfully from `ssh_stream_read()` with `*bytes_read` < 0. This would occur if stdout channel read resulted in 0, and stderr channel read failed afterwards.
> ssh_stream_read(): fix possible *bytes_read < 0 branch

- src/pack.c
- src/pack.h
packfile_unpack_compressed has already been covered in pack.h
> Make packfile_unpack_compressed a private API

- src/transports/winhttp.c
Standard Windows type systems define CLSID_InternetSecurityManager
and IID_IInternetSecurityManager, but MinGW lacks these definitions.
As a result, we must hardcode these definitions ourselves.  However,
we should not use a public struct with those names, lest another
library do the same thing and consumers cannot link to both.
Fixes #3570
> winhttp: name mangle class / iid on mingw

- CODE_OF_CONDUCT.md
The libgit2 project has - I think and I certainly hope - been pretty good about diversity.  However, we do not have a written code of conduct, and certainly we should, to ensure that we stay reasonable or - better yet - improve.  This adds the contributor covenant to the repository.  In their words:
> Open Source has always been a foundation of the Internet, and with the advent of social open source networks this is more true than ever. But free, libre, and open source projects suffer from a startling lack of diversity, with dramatically low participation by women, people of color, and other marginalized populations.
> 
> Part of this problem lies with the very structure of some projects: the use of insensitive language, thoughtless use of pronouns, assumptions of gender, and even …
> Introduce Contributor Covenant

- include/git2/merge.h
`git_merge_commits` and `git_merge` now *do* handle recursive base
building for criss-cross merges.  Remove the documentation that says
that they do not.
(Recursion is documented itself in `git_merge_options`).
This reverts commit 5e44d9bcb6d5b20922f49b1913723186f8ced8b5.
> Better document `git_merge_commits` redux

- src/commit.c
- tests/commit/parse.c
We were searching only past the first header field, which meant we were
unable to find e.g. `tree` which is the first field.
While here, make sure to set an error message in case we cannot find the
field.
---
I'm not sure wtf I was doing when I wrote the first one, but that code was stupid.
> commit: also match the first header field when searching

- src/attr_file.c
- src/checkout.c
- src/pack-objects.c
- src/pack.c
Some more small-ish fixes. I'm still unsure if it's of any benefit to fix memory leaks deep inside the internal APIs, but I guess it can't really hurt to do so.
On another note, I'd like to mark all those errors regarding GITERR_CHECK_ALLOC as false positives or intended in Coverity. Any objections to this?
> Coverity fixes

- include/git2/commit.h
- src/commit.c
- tests/commit/parse.c
This returns the GPG signature for a commit and its contents without the
signature block, allowing for the verification of the commit's
signature.
---
This code is already written to expect to be refactored into an internal function which accepts other header fields to use for the signature. I wonder if we should just make the public function accept a string directly so we don't have to worry about timing if/when git introduces new ones. And it would let fancy users have their own crypto in there.
/cc @mastahyeti
> Introduce git_commit_extract_signature

- script/coverity.sh
- script/user_nodefs.h
Two small improvements to Coverity. The first commit tries to mitigate the issue with `GITERR_CHECK_ALLOC` by providing a `user_nodefs.h` file which overrides the macro. The second is a security enhancement stopping us from sending over the Coverity authorization token in plain text.
This is a follow-up for libgit2/libgit2#3603. I was not able to verify that the `user_nodefs.h` thing suppresses the resource leak errors as I cannot get Coverity to provide the analysis results to me. It builds, but after submitting the instrumentalized archive I get no results back.
> Coverity improvements for GITERR_CHECK_ALLOC

- include/git2/rebase.h
- src/rebase.c
- tests/rebase/inmemory.c
- tests/rebase/iterator.c
- tests/rebase/merge.c
Introduce the ability to rebase in-memory or in a bare repository.
When `rebase_options.bare` is specified, the resultant `git_rebase`
session will not be persisted to disk.  Callers may still analyze
the rebase operations, resolve any conflicts against the in-memory
index and create the commits.  Neither `HEAD` nor the working
directory will be updated during this process.
I played with a few ways of tackling this - right now we have the concept of a `git_rebase_type_t` that indicates the rebase method (`apply`, `merge` or `interactive`).  I originally thought that this should be another method (`inmemory` or `bare`), but this seems to be a different axis.  Since `apply` and `merge` may yield different results, you probably want to be able to have bare forms of each (and may in fact want …
> rebase: introduce bare rebasing

- include/git2/rebase.h
- src/rebase.c
- tests/rebase/inmemory.c
- tests/rebase/iterator.c
When performing an in-memory rebase, keep a single index for the
duration, so that callers have the expected index lifecycle and
do not hold on to an index that is free'd out from under them.
> rebase: persist a single in-memory index

- include/git2/commit.h
- src/commit.c
- tests/commit/parse.c
We should be checking whether the object we're looking up is a commit,
and we should let the caller know whether the not-found return code
comes from a bad object type or just a missing signature.
---
This is messy because it comes down to error class for the same return code, but `GIT_ENOTFOUND` is consistent in both cases with what we do for each kind of error.
> commit: expose the different kinds of errors

- PROJECTS.md
`compatability` → `compatibility`
> Fix a typo

- src/index.c
- src/submodule.c
- src/transports/winhttp.c
- src/tree.c
- src/unix/posix.h
- src/win32/posix.h
- src/win32/posix_w32.c
- src/win32/w32_util.h
- src/win32/win32-compat.h
- tests/checkout/checkout_helpers.c
- tests/core/posix.c
- tests/diff/workdir.c
- tests/index/racy.c
- tests/merge/workdir/dirty.c
- tests/reset/hard.c
- tests/win32/longpath.c
Fix up some of the silly warning:  correct casts, constness, etc.  This doesn't get us to zero warnings on all platforms, but it gets us closer.
> Remove most of the silly warnings

- src/common.h
- src/fileops.c
- src/index.h
Include @Therzok 's fix from #3586 which was missed after some index timestamp refactoring.
Also increase the scope of `st_mtim` -> `st_mtimespec` so that it affects all the files.
> Handle `USE_NSECS` 

- include/git2/sys/filter.h
- src/filter.c
- src/filter.h
- src/global.c
- src/openssl_stream.c
- src/openssl_stream.h
- src/thread-utils.h
While reviewing #3564 , @carlosmn noticed that we were a bit racy in registration of merge drivers.  This registration pattern was primarily copied from filter registration, so I wanted to fix up the existing code before banging on that.
Previously we would set the global filter registry structure before adding filters to the structure, without a lock, which is quite racy. Now, register default filters during global registration and use an rwlock to read and write the filter registry (as appropriate)
> Filter registration

- include/git2/common.h
- src/settings.c
- tests/core/opts.c
For git_libgit2_opts: first, document the GIT_OPT_SET_USER_AGENT option. Second, provide some validation on invalid keys.
> git_libgit2_opts: minor documentation & usage fixes

- include/git2/errors.h
- src/unix/map.c
Update the documentation to `giterr_set_str` to reflect that it does not actually honor the `GITERR_OS` argument to include the operating system's error message.  Update internal usages of `giterr_set_str` to more accurately use `giterr_set`.
> Minor `giterr` fixups

- src/pack.c
There's a few things we can do to stop things like #3556 from happening. Here's one, also proposed for git, which checks that we're not getting sent past the end of the index for extended entries. We already check the size upon loading so the initial lookup is still safe.
We're still not checking the hashes to make sure the index corresponds to the packfile, or that the hash matches the data. We should be able to check the packfile's trailer match without too much effort. We might not want to check the hash every time as it could become a bit expensive (though it's a one-time cost (except when we miss and reload))
> Extra checks for packfile indices

- CMakeLists.txt
- src/pool.c
- src/pool.h
- tests/core/pool.c
Calls to git_pool__malloc are proxied directly to git__malloc. Allocations are tracked using a git_vector and freed when git_pool_clear is called. I am currently using ifdef/ifndef to enable and disable the debug code. I also enable/disable a couple of the pool test cases which won't work when debug is turned on.
> Add a new build flag to disable the pool allocator

- src/posix.c
These are some (hopefully correct) fixes for the p_getaddrinfo() function.
If you prefer to use GITERR_CHECK_ALLOC() in commit ea5942b I can also do it of course.
> Few p_getaddrinfo fixes

- src/xdiff/xmerge.c
Commit 3d1abc5afce fixes a memory leak in the xdiff code. In the
process of upstreaming the fix it was pointed out by Johannes
Schindelin that there is another memory leak present (see [1]).
Fix the second memory leak by applying the upstream fix to our
code base.
[1]: http://thread.gmane.org/gmane.comp.version-control.git/287034
> xdiff: fix memleak on error case

- CMakeLists.txt
- appveyor.yml
- script/cibuild.sh
- src/transports/winhttp.c
We were missing this test on Windows, which meant we didn't notice that
we never fixed the single authentication attempt it tries, nor its wrong
return code.
Enable this for the unix platforms as well over HTTP. We previously were
doing it locally but disabled it on OS X due to issues with its sshd not
accepting password authentication.
> test: make sure we retry the auth callback on all platforms

- THREADING.md
Adds a few useful bits of information that helped in resolving #3624.
For the `libssh2_init` argument, see https://github.com/libssh2/libssh2/blob/d441da3086dcc49989b7c5b9bf3043c4a6a98211/src/global.c#L74-L78 and https://www.libssh2.org/libssh2_init.html
> Expand OpenSSL and libssh2 thread safety documentation

- src/global.c
- src/transports/ssh.c
- src/transports/ssh.h
We should have been doing this, but it initializes itself upon first
use, which works as long as nobody's doing concurrent network
operations. Initialize it on our init to make sure it's not getting
initialized concurrently.
> ssh: initialize libssh2

- src/tree.c
- tests/object/tree/write.c
Submodules don't exist in the objectdb and the code is making us try to
look for a blob with its commit id, which is obviously not going to
work.
Skip the test if the user wants to insert a submodule.
> treebuilder: don't try to verify submodules exist in the odb

- examples/general.c
The existing, broken link points to v1 of the book. The new link points to the same chapter in the current version (v2) of the book.
(After finding this, I searched for other references to "Pro Git" or `progit.org`, but only found this one, so I don't think there are other URLs to update.)
> Update link to Pro Git's Git internals chapter

- CHANGELOG.md
- include/git2/commit.h
- src/commit.c
- tests/commit/write.c
Sometimes you want to create a commit but not write it out to the
objectdb immediately. For these cases, provide a new function to
retrieve the buffer instead of having to go through the db.
---
This is new, so we should wait to merge until after the release.
> commit: split creating the commit and writing it out

- deps/http-parser/http_parser.c
- src/transport.c
- src/transports/ssh.c
- tests/transport/register.c
This should add support for the `ssh+git://` and `git+ssh://` protocol schemes. The behavior is to pass directly through to the `ssh://` protocol scheme.
So, as atrocious as this is, this is a protocol that people use. From everything I can tell, they're both functionally identical to `ssh://` and are treated as such in this PR. [Here](http://git.kernel.org/cgit/git/git.git/commit/?id=c05186cc38ca4605bff1f275619d7d0faeaf2fa5) is an example of it being used in ~~the linux kernel~~ git core
> Support for ssh+git and git+ssh protocols

- include/git2/odb.h
- src/odb.c
- src/odb.h
- src/odb_loose.c
- src/odb_pack.c
- src/oid.h
- src/pack.c
- tests/odb/mixed.c
Introduce an API to take many OID prefixes and determine which (if any) are uniquely resolvable.  The full OID is returned for those that exist.
Unlike most of the ODB APIs, this *does not* reload the ODB to try to refresh the backends if a lookup fails.  That would, obviously, be a totally insane number of ODB refreshes.
> Introduce `git_odb_expand_ids`

- src/mwindow.c
The first time may be due to memory fragmentation or just bad luck on a
32-bit system. When we hit the mmap error for the first time, free up
the unused windows and try again.
> mwindow: free unused windows if we fail to mmap

- src/odb.c
- tests/odb/mixed.c
Fixes the issue with leaking the error code for the last OID in the array, and the ODB refreshes that were (still) being performed on missing objects.
> Fixes for `gid_odb_expand_ids`

- tests/rebase/abort.c
- tests/rebase/merge.c
- tests/rebase/setup.c
Test some additional exotic rebase setup behavior:  that we are
able to set up properly when already in a detached HEAD state,
that the caller specifies all of branch, upstream and onto,
and that the caller specifies branch, upstream and onto by ID.
> rebase: additional setup tests of exotic behavior

- include/git2/common.h
In ObjectiveGit have recurring problems (see https://github.com/libgit2/objective-git/issues/436#issuecomment-70563677 and https://github.com/libgit2/objective-git/issues/542) with Xcode complaining with `Include of non-modular header inside framework module 'ObjectiveGit.git2.sys.filter'` this is due to the fact that `libgit2` is including `inttypes.h` in `common.h`. There is no need to import this header on iOS and Mac platforms and thus I excluded it.
This fixes our recurring compilation issues and still works. I am happy to discuss this change as it has some implications. I also find this way of solving the problem pretty naive but after days of trying is the only solution I could come up with.
> Don't include inttypes if compiling for Mac/iOS

- include/git2/common.h
- src/global.c
- src/global.h
- src/openssl_stream.c
- src/settings.c
- tests/online/badssl.c
This ensures that when using OpenSSL a safe default set of ciphers
is selected. This is done so that the client communicates securely
and we don't accidentally enable unsafe ciphers like RC4, or even
worse some old export ciphers.
Implements the first part of https://github.com/libgit2/libgit2/issues/3682
cc @carlosmn
> Setup better defaults for OpenSSL ciphers

- script/coverity.sh
- src/config_file.c
- src/describe.c
- src/diff_tform.c
- src/index.c
- src/object.c
- src/pack-objects.c
- src/submodule.c
Another week, another round of Coverity fixes. This brings Coverity down by another ten issues. By now fixes are not that obvious anymore and require a bit more knowledge about surrounding code, so the pace is going a bit slower by now.
On top of the bug fixing commits is another fix improving interoperation between Coverity and Travis. Curl does not report any errors when receiving error status codes and thus Travis happily pretends the submission of the tarball was successful when it indeed failed. The most common case of failing (at least for me) is the rate limit hitting.
I've improved this by instructing curl to output the HTTP code and then manually parsing the whole output to not lose any information. Unfortunately curl has no easier way of accomplishing this - we want both the …
> Coverity fixes round 6

- src/blame.c
- src/blame_git.c
- src/config_cache.c
- src/config_file.c
- src/filebuf.c
- src/refdb_fs.c
Mostly fixes involving ignored return codes. Down to a defect density of 0.25 and 29 defects outstanding in my fork.
While we're at it: I've got a custom user model that fixes how Coverity models vectors (see [user_model.c](https://github.com/pks-t/libgit2/blob/f943300f1001e146445802df3ee3cbefd6bf352e/script/user_model.c)). It fixes some issues but requires us to manually upload the file into Coverity. Do we want this added?
> Coverity fixes round 7

- src/indexer.c
- src/posix.c
- src/posix.h
- src/unix/map.c
- src/win32/map.c
We've been using the allocation granularity instead for this value,
but his refers to VirtualAlloc() rather than anything we do. Using this
as a value for the pool means every pool would become at least 64kB with
foreseeable results on memory pressure.
Do use the system's page size as our value for the page size.
> win32: choose the page size as our value for the page size

- src/commit.c
- tests/commit/parse.c
The function to extract signatures suffers from a similar bug to the
header field finding one by having an unecessary line feed check as a
break condition of its loop.
Fix that and add a test for this single-line signature situation.
> commit: fix extraction of single-line signatures

- CMakeLists.txt
This is useful to force "smart" IDEs (like CLIon) to use debug
flag -g even it may have decided that "-D_DEBUG" (which is
already present) is sufficient.
> CMake: do not overwrite but only append to CMAKE_C_FLAGS_DEBUG 

- include/git2/commit.h
- src/commit.c
- tests/commit/write.c
In combination with the function which creates a commit into a buffer,
this allows us to more easily create signed commits.
---
The tests end up rather messy with all that inline text, but putting the text outside doesn't really look better.
> commit: add function to attach a signature to a commit

- CHANGELOG.md
- include/git2/merge.h
- include/git2/sys/merge.h
- src/global.c
- src/merge.c
- src/merge.h
- src/merge_driver.c
- src/merge_driver.h
- src/merge_file.c
- tests/merge/driver.c
- tests/merge/workdir/simple.c
While #3497 added support for `merge=union` in `.gitattributes`, I felt that we should have a more complete story for handling the `merge` attribute.  This PR:
1. Adds a framework for adding custom merge drivers.  This is heavily inspired by the custom filter framework, and a consumer can add one or more custom merge drivers by name (for example, you may add a new `custom` driver) or - probably more useful - can add a wildcard merge driver.  This allows a consumer to be given the option to handle all configured merge drivers that are not built-in.
For example, a consumer could register a custom merge driver for the wildcard (`*`).  If there were a `merge=custom` line in a `.gitattributes` for a file, the configured merge driver would be given the information about the file changes and the …
> Custom merge drivers and proper gitattributes `merge` handling

- src/index.c
- src/iterator.c
- src/push.c
- src/submodule.c
- src/tree.c
- src/tree.h
- tests/diff/iterator.c
- tests/object/tree/attributes.c
The memory management for the small and sometimes numerous tree-owned entries has non-trivial effects on performance. We previously tried to bundle up allocations with a pool, but this backfires quite significantly on Windows where 32-bit address spaces are common.
These patches still try to bundle up allocations, but let the system allocator do more of the work. As we've already gone though the work of allocating and inflating the tree object's buffer, and we store it in a cache so it lives in memory after we load the tree, make use of its memory to store the id and filename for the entries. The entries now simply point to them.
This makes the entries have a constant size so we can use a `git_array_t(git_tree_entry)` to allocate them in blocks and free them with a single call while …
> Reuse a tree's buffer and allocate constant-sized entries in an array

- src/indexer.c
I have seen the subtraction overflow when the pack file contains nothing with custom transport protocol (when the serving side close the connection). We have fixed it in our custom writepack implementation, but I think the right fix should be in git_indexer_commit
> Add a sanity check in git_indexer_commit to avoid subtraction overflow.

- src/array.h
- src/tree.c
- src/tree.h
- tests/core/array.c
Remove the now-unnecessary entries vector.  Add `git_array_search`
to binary search through an array to accomplish this.
> tree: drop the now-unnecessary entries vector

- CMakeLists.txt
Showing the pointer size gives a hint as to why we think this is an
unsupported architecture.
> CMakeLists: Show the pointer size for an unsupported architecture

- src/transports/smart_protocol.c
I'm experimenting with using LibGit2Sharp with [AWS CodeCommit](https://aws.amazon.com/codecommit/) over HTTPS, and one of the problems I've hit is that libgit2 is failing to parse the git-receive-pack-result.  libgit2 expects to read complete pkt-lines from each sideband packet, but CodeCommit is splitting the pkt-lines across multiple side-channel packets.  
The HTTP response looks like this (formatted as a C string literal with line breaks for clarity): 
```
"0009\x01000e"
"000f\x01unpack ok\n"
"0009\x010019"
"001a\x01ok refs/heads/master\n"
"0009\x010000"
"0006\x02\n"
"0000"
```
Core git accepts this format, and the git technical documentation describes sidebands as "streams", so I believe it's valid and libgit2 should accept it.
> Buffer sideband packet data

- src/config_file.c
- tests/config/multivar.c
This special-casing ignores that we might have a locked file, so the
hashtable does not represent the contents of the file we want to
write. This causes multivar writes to overwrite entries instead of add
to them when under lock.
There is no need for this as the normal code-path will write to the file
just fine, so simply get rid of it.
> config: don't special-case multivars that don't exist yet

- src/config_file.c
- tests/config/write.c
When we're trying to write some configuration value, we parse the existing configuration file.  When we find a section, we see if we were *previously* in the section that we wanted to write to.  If we were, then we write our value (which allows us to append it to the end of the section we were looking for.)
However, we were *not* doing this for EOF.  We assumed that if we hit the EOF that we must not have found the section that we were looking for, and write the new section and the value.  This is quite silly; we could have been in the section we were looking for and still hit the EOF.  In that case, we should just write the value.
> config: don't write duplicate section

- src/xdiff/xprepare.c
Cherry-picked two upstream fixes for memory leaks in the xdiff code from Ramsay Jones.
> xprepare memleaks

- src/indexer.c
- src/pack.c
git_mwindow_close has already been called git_packfile_unpack_header, needless to be called again from the outside.
> Remove duplicated calls to git_mwindow_close

- include/git2/common.h
Clang's documentation parser, which we use in our documentation system
does not report any comments for functions which use size_t as a type.
The root cause is buried somewhere in libclang but we can work around it
by defining the type ourselves. This typedef makes sure that libclang
sees it and that we do not change its size.
---
I'm not particularly happy with this, but I've already burnt a lot of time tracking down the root cause and a work-around would still be needed for released versions anyhow.
> Add a no-op size_t typedef for the doc parser

- src/merge_driver.c
The code initializing the merge driver registry accidentally
forgot a `goto done` in case of an error. Because of this the
next line, which registers the global shutdown callback for the
merge drivers, is only called when an error occured.
Fix this by adding the missing `goto done`. This fixes some
memory leaks when the global state is shut down.
> merge_driver: fix missing `goto done;`

- src/ignore.c
- tests/attr/ignore.c
If we're looking for a symlink, realpath will give us the resolved path,
which is not what we're after, but a canonicalized version of the path
the user asked for.
This fixes #3684
> ignore: don't use realpath to canonicalize path

- src/iterator.c
- tests/diff/submodules.c
- tests/iterator/workdir.c
In the great iterator refactor of 2016, we made clear that submodules should not have trailing slashes for the `start` and `end` paths.  This regressed some expected behavior.
Unfortunately, this does not quite jive with diff's pathspec matching, which will happily accept `foo/` if `foo` is a submodule.  This is problematic because diff will set the iterator's `start` and `end` paths to the longest common substring of the pathspecs.  (Which may be nothing, but it may be something, and if it is that would speed up the diff.)
Therefore, if you are asking about a bunch of paths, and you've foolishly added a trailing slash to a submodule, the behavior is different than if you ask about just that one path:
If you diff with `pathspecs = { "a", "b", "submod/", "z" }`, then there is no common …
> iterator/diff: allow trailing `/` on start/end paths to match submodules

- tests/core/stream.c
When passing -DUSE_OPENSSL:BOOL=OFF to cmake the testsuite will
fail with the following error:
core::stream::register_tls [/tmp/libgit2/tests/core/stream.c:40]
Function call failed: (error)
error -1 - <no message>
Fix test to assume failure for tls when built without openssl.
While at it also fix GIT_WIN32 cpp to check if it's defined
or not.
> tests: fix core/stream test when built with openssl off

- tests/refs/create.c
- tests/reset/hard.c
When we turned strict object creation validation on by default, we forgot to inform the `refs::create` tests of this.  They, in fact, believed that strict object creation was off by default.  As a result, their cleanup function went and turned strict object creation off for the remaining tests.
Also cherry-picks the `reset` fix from #3735.
> Strict object creation in `refs::create`

- src/refs.c
- tests/refs/lookup.c
If we cannot dwim the input, set the error message to be explicit about
that. Otherwise we leave the error for the last failed lookup, which
can be rather unexpected as it mentions a remote when the user thought
they were trying to look up a branch.
> refs: provide a more general error message for dwim

- tests/iterator/workdir.c
- tests/status/worktree.c
When running as root, skip the unreadable file tests, because, well,
they're probably _not_ unreadable to root unless you've got some
crazy NSA clearance-level honoring operating system shit going on.
I suspect this is the root cause of #3731
> tests: skip the unreadable file tests as root

- include/git2/remote.h
Super minor, but it was bugging me.
There was a missing closing paren in the docs.
> Add missing ')' to callbacks documentation

- src/fnmatch.c
- tests/attr/ignore.c
Add some tests and handling for a few situations where our star-star handling in gitignore patterns was behaving incorrectly.
This supersede #3721
> Improve star-star matching

- CMakeLists.txt
- appveyor.yml
- examples/network/ls-remote.c
- include/git2.h
- include/git2/proxy.h
- include/git2/remote.h
- include/git2/sys/remote.h
- include/git2/sys/stream.h
- include/git2/sys/transport.h
- script/cibuild.sh
- src/curl_stream.c
- src/netops.c
- src/openssl_stream.c
- src/proxy.c
- src/proxy.h
- src/push.c
- src/remote.c
- src/stream.h
- src/transports/http.c
- src/transports/local.c
- src/transports/smart.c
- src/transports/smart.h
- src/transports/winhttp.c
- tests/network/remote/defaultbranch.c
- tests/network/remote/local.c
- tests/network/remote/remotes.c
- tests/network/urlparse.c
- tests/online/clone.c
- tests/online/fetch.c
- tests/online/push.c
Determining the proxy from the config is but one way we can do it.
This would depend on having nicer option structures, so proper binding-in would need #3066 to go in, but we can figure out what the interface should be beforehand.
Part of the idea is to ask the caller for the proxy's pasword the same way we do for the git server's. We can re-use the credentials callbacks and structs to perform an interactive request to an end-user.
The code for WinHTTP is completely untested, but it *should* be in the right direction (according to the documentation) for grabbing the username/password from the config and using that. This was my first approach at solving #2106.
We would also need to think about what we want to do for nicer higher-level abstractions, since in e.g. pygit2[0] you can currently …
> Proxy configuration

- src/tag.c
- tests/object/tag/read.c
While no extra header fields are defined for tags, git accepts them by
ignoring them and continuing the search for the message. There are a few
tags like this in the wild which git parses just fine, so we should do
the same.
> tag: ignore extra header fields

- src/rebase.c
- tests/rebase/abort.c
- tests/rebase/merge.c
When rebasing with IDs, ensure that we can correctly abort and finish.
> Rebase improvements with IDs

- include/git2/refs.h
- src/refs.c
- tests/refs/dup.c
I'd like to make use of this in Rugged. 😄
> Allow creating copies of `git_reference` objects.

- src/annotated_commit.c
- src/annotated_commit.h
- src/branch.c
- src/repository.c
- src/reset.c
- tests/rebase/abort.c
Various mechanisms want a description of the annotated commit - most notably, they want to write the reflog to describe what we're talking about (eg, `HEAD^2` or a short commit ID).
Rebase, however, wants to actually know when an annotated commit refers to a real branch, so that we can check it back out.
Differentiate between these two things.  Otherwise if a user was trying to set their branch to something revparsed, we'll try to check it back out when we're finished.
> Annotated commits: differentiate between the ref names and the description

- src/openssl_stream.c
openssl_read should return -1 in case of error.
SSL_read returns values <= 0 in case of error.
A return value of 0 can lead to an infinite loop, so the return value
of ssl_set_error will be returned if SSL_read is not successful (analog
to openssl_write).
> Fix return value of openssl_read (infinite loop)

- include/git2/signature.h
- src/signature.c
- tests/commit/signature.c
Allow users to construct a signature from the type of signature lines that actually appear in commits.  It may be natural for users to serialize author/committer information into this type of format, a helper method will provide some assistance for that.
> Introduce `git_signature_from_buffer`

- src/delta-apply.c
- src/delta-apply.h
- src/pack.c
When we read the header, we want to know the size and type of the
object. We're currently inflating the full delta in order to read the
first few bytes. This can mean hundreds of kB needlessly inflated for
large objects.
Instead use a packfile stream to read just enough so we can read the two
varints in the header and avoid inflating most of the delta.
---
For a particular repository which surfaced the issue, finding out the sizes for ~1300 blobs in a tree used to take ~13s whereas with this it takes under 50ms (and up to 20 of those are just the test suite starting up).
The one thing I'm not sure about is whether we can rely on zlib giving us those 16 bytes or if we should be paranoid and loop that read.
> odb: avoid inflating the full delta to read the header

- src/rebase.c
- tests/rebase/inmemory.c
- tests/rebase/merge.c
When performing an in-memory rebase, we should be able to rebase a branch with no common ancestors (that is, the first commit to rebase has no parents).
/cc @arthurschreiber
> Rebase: rebase a branch with no merge base for in-memory

- src/commit.c
- tests/commit/commit.c
When calling `git_commit_create` with an empty array of `parents` and `parent_count == 0` 
the call will segfault at https://github.com/libgit2/libgit2/blob/master/src/commit.c#L107 
when it's trying to compare `current_id` to a null parent oid. 
This just puts in a check to stop that segfault.
> Fix `git_commit_create` for an initial commit

- include/git2/tree.h
- src/tree.c
- tests/object/tree/update.c
The way we currently recommend modifying trees is via an index. This method has a couple of advantages: it's what any tool would do on their `git-commit` equivalent, and it's code that we already have and use. It does however mean doing a recursive read of the root tree, and that can get big. Modifying a file becomes more expensive as files are added to the tree regardless of where the updated file lives.
On a workdir, it's not so bad because the index is kept across operations but when doing this without the advantage of a user-provided workdir, the recursive read can become the primary cost of the update operation.
This PR adds a function which, given a baseline tree and a list of updates, reads just enough trees to perform the necessary updates.
---
This needs better history and some …
> Add a method specifically for modifying trees

- src/tree.c
- tests/object/tree/update.c
When we remove all entries in a tree, we should remove that tree from
its parent rather than include the empty tree.
> tree: handle removal of all entries in the updater

- src/tree.c
0120000 is symbolic link, not commit.
(No functional change.)
> Fix comment for GIT_FILEMODE_LINK

- tests/checkout/index.c
Haiku and Hurd both pass extra bits in struct stat::st_mode.
> test: Fix stat() test to mask out unwanted bits

- src/index.c
- src/transports/smart_pkt.c
- src/transports/smart_protocol.c
Two small fixes for invalid memory references. As always, some details are included in the commit messages.
I've pushed a fix similar to the smart-transports commit once before, but back then the fix wasn't as obvious and as I wasn't able to recap my own thought process when you asked about the non-obvious fix I simply dropped the commit. But I hope the issue should be clear now.
> Fix invalid memory references

- src/global.c
- src/transports/winhttp.c
- tests/checkout/typechange.c
This fixes all memory leaks displayed by AppVeyor's debug CRT. The winhttp-related plug is the only actual fix for memory leaks inside of libgit2 and not its tests.
> Memory leak fixes

- src/remote.c
When an existing tag is changed on the remote, the default (autotag) behavior is to not overwrite the local tag, but the update callback is still called as if the tag had been updated. This commit fixes that.
> fetch: Fixed spurious update callback for existing tags.

- include/git2/checkout.h
`git_checkout_head` is sadly misunderstood as something that can
switch branches.  It cannot.  Update the documentation to reflect this.
Fixes #2864
> documentation: improve docs for `checkout_head`

- src/checkout.c
- tests/checkout/tree.c
When no index file exists and a baseline is not explicitly provided, use an empty baseline instead of trying to use `HEAD` as the baseline.
This is for compatibility with git:
```
% git status
On branch master
nothing to commit, working directory clean
% rm .git/index
% git status
On branch master
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
deleted:    README
deleted:    branch_file.txt
deleted:    link_to_new.txt
deleted:    new.txt
Untracked files:
(use "git add <file>..." to include in what will be committed)
README
branch_file.txt
link_to_new.txt
new.txt
% git checkout HEAD
error: The following untracked working tree files would be overwritten by checkout:
README
branch_file.txt
link_to_new.txt
new.txt
Please move or remove them before you can switch branches. …
```
> checkout: use empty baseline when no index file exists

- src/transports/http.c
From RFC 2617 (my **_emphasis_**):
> 1.2 Access Authentication Framework
>
> HTTP provides a simple challenge-response authentication mechanism that MAY be used by a server to challenge a client request and by a client to provide authentication information. It uses an extensible, **_case-insensitive_** token to identify the authentication scheme, followed by a comma-separated list of attribute-value pairs which carry the parameters necessary for achieving authentication via that scheme.
> HTTP authentication scheme name is case insensitive.

- src/common.h
- src/global.c
- src/pack-objects.c
- src/thread-utils.h
- src/unix/pthread.h
- src/win32/precompiled.h
- src/win32/pthread.c
- src/win32/pthread.h
- src/win32/thread.c
- src/win32/thread.h
- tests/object/cache.c
- tests/threads/refdb.c
- tests/threads/thread_helpers.c
This PR aims to fix the namespacing-issue in issue #3825. The Windows-specific pthreads.c source file tries to re-implement the API exposed by pthreads by implementing many of the pthread-symbols with Windows-specific threading code. This unfortunately results in runtime errors when a user links his application to both libgit2 and winpthreads, causing one of both libraries to override symbols of the other library, causing inconsistencies.
Fix the issue by introducing proper namespacing to our threading API. Instead of trying to re-implement all functions, implement functions inside the `git_` namespace and adjust the `#define`s in Unix-specific code.
This solves the part where linking against both libraries causes runtime errors. What is still missing is to allow Windows-users to link …
> Thread namespacing

- CMakeLists.txt
The MSYS2 build system automatically compiles all code with position-independent
code. When we manually add the -fPIC flag to the compiler flags, MSYS2 will
loudly complain about PIC being the default and thus not required.
Fix the annoyance by stripping -fPIC in MSYS2 enviroments like it is already
done for MinGW.
> cmake: do not use -fPIC for MSYS2

- include/git2/submodule.h
- src/submodule.c
This fixes #3783. When submodule update doesn't find the target commit in the submodule, fetch from the default remote and then try to lookup the commit again.
> submodule: Try to fetch when update fails to find the target commit.

- CHANGELOG.md
- include/git2/repository.h
- src/repository.c
- tests/repo/discover.c
- tests/repo/open.c
git_repository_open_ext provides parameters for the start path, whether to search across filesystems, and what ceiling directories to stop at.  git commands have standard environment variables and defaults for each of those, as well as various other parameters of the repository. To avoid duplicate environment variable handling in users of libgit2, add a GIT_REPOSITORY_OPEN_FROM_ENV flag, which makes git_repository_open_ext automatically handle the appropriate environment variables. Commands that intend to act just like those built into git itself can use this flag to get the expected default behavior.
git_repository_open_ext with the GIT_REPOSITORY_OPEN_FROM_ENV flag respects $GIT_DIR, $GIT_DISCOVERY_ACROSS_FILESYSTEM, $GIT_CEILING_DIRECTORIES, $GIT_INDEX_FILE, $GIT_NAMESPACE, …
> Add GIT_REPOSITORY_OPEN_FROM_ENV flag to respect $GIT_* environment vars

- include/git2/repository.h
- src/repository.c
- tests/repo/discover.c
- tests/repo/open.c
(As discussed with @ethomson via Slack. Based on the branch from pull request #3711; only the last commit is new. I'd suggest merging #3711 first, then this.)
find_repo had a complex loop and heavily nested conditionals, making it
difficult to follow.  Simplify this as much as possible:
- Separate assignments from conditionals.
- Check the complex loop condition in the only place it can change.
- Break out of the loop on error, rather than going through the rest of
the loop body first.
- Handle error cases by immediately breaking, rather than nesting
conditionals.
- Free repo_link unconditionally on the way out of the function, rather
than in multiple places.
- Add more comments on the remaining complex steps.
> find_repo: Clean up and simplify logic

- src/util.c
- tests/core/strtol.c
Fixed the bug which caused `strtol()` to fail parsing `INT64_MIN`. Addressed in #3817.
Added test cases in `tests/core/strtol.c` to check for the boundary values.
> Fixed bug while parsing INT64_MIN

- CHANGELOG.md
- src/remote.c
Somehow I ended up with the following in my ~/.gitconfig:
[branch "master"]
remote = origin
merge = master
rebase = true
I assume something went crazy while I was running the git.git tests
some time ago, and that I never noticed until now.
This is not a good configuration, but it shouldn't cause problems. But
it does. Specifically, if you have this in your config, and you
perform the following set of actions:
create a remote
fetch from that remote
create a branch off of the remote master branch called "master"
delete the branch
delete the remote
The remote delete fails with the message "Could not find key
'branch.master.rebase' to delete". This is because it's iterating over
the config entries (including the ones in the global config) and
believes that there is a master branch which must …
> remote: Handle missing config values when deleting a remote

- script/user_model.c
So by now more than half of the issues reported by Coverity can be labeled as false positives as the number of issues went down. I've written a user model that I am using to fix most of these false positives in my own fork, which brings down the number of issues from 37 to 14. Most of these issues are related to either git_vector or git_buf, which seem to be too complex to handle for Coverity.
I've split up this PR into two commits. The first commit includes the user model I am actually using right now. Due to an expired license (dunno why, I've contacted Coverity support but got no feedback until now) I am not able to update the user model, though, so I cannot test changes made in the second commit.
I'd be glad if this got accepted. Accepting alone won't help, though, as there seems to …
> Coverity user model

- CHANGELOG.md
- include/git2/diff.h
- src/patch_parse.c
Move `id_abbrev` to a more reasonable place where it packs more nicely, and it matches the size of `id_abbrev` in `git_diff_options`.  Do this before the next release before anybody starts using it.
> git_diff_file: move `id_abbrev`

- src/settings.c
- src/transport.c
- src/transports/http.c
- tests/core/features.c
Unfortunately, custom TLS stream API is useless because `https` transport become disabled when [any of secure connection frameworks aren't used](https://github.com/libgit2/libgit2/blob/813d73f64d779257fd24cd70bbc281352c34812b/src/transport.c#L32).
> Enable https transport for custom TLS streams

- src/transport.c
Hey,
So this is a very trivial pr,
the original comment is from 2012 and seems to no longer apply.
The contribution guidelines suggest // style comments should be avoided,
so I figure I may as well fix that up while I'm here.
Apologies if this is a waste of reviewer time,
but I was working in the perl binding and this comment misled me.
Hope this helps! :)
> Fix outdated comment

- src/sysdir.c
- src/sysdir.h
Don't assume that an empty system directory buffer is uninitialized.
In fact, there simply may be no appropriate path for that value.
(For example, the Windows-specific programdata directory has no value
on non-Windows machines.)
This prevents us from continually trying to re-lookup these values,
which could get racy if two different threads are each calling
`git_sysdir_get` and trying to lookup / clear the value simultaneously.
Fixes #3871
> sysdir: don't assume an empty dir is uninitialized

- CHANGELOG.md
- include/git2/sys/odb_backend.h
- src/fileops.c
- src/fileops.h
- src/odb.c
- src/odb_loose.c
- src/odb_pack.c
- src/pack.h
- tests/odb/freshen.c
When writing an object, we calculate its OID and see if it exists in the object database.  If it does, we need to freshen the file that contains it.
This adds a new function to backends, `freshen`, which will freshen the object if it exists.
Previously, we would do a simple `exists` check during `git_odb_write`, after calculating the new object ID.  Now, we will use the `freshen` function if it is implemented on a particular backend (falling back to the `exists` check if it doesn't).
A slight disappointment is that we no longer look in the cache first to see if an object exists.  To do that, we would need to store more information in the cache, namely the backend that the object was found in (or else we would need to go locate the object again to freshen it, and if we do that, there would …
> odb: freshen existing objects when writing

- src/apply.c
- src/pool.h
Fixes two build warnings, for example https://travis-ci.org/libgit2/libgit2/jobs/149891598
> Patch image initialization

- tests/clar.c
When passing in a specific suite which should be executed by clar
via `-stest::suite`, we try to parse this string and then include
all tests contained in this suite. This also includes all tests
in sub-suites, e.g. 'test::suite::foo'.
In the case where multiple suites start with the same _string_,
for example 'test::foo' and 'test::foobar', we fail to
distinguish this correctly. When passing in `-stest::foobar`,
we wrongly determine that 'test::foo' is a prefix and try to
execute all of its matching functions. But as no function
will now match 'test::foobar', we simply execute nothing.
To fix this, we instead have to check if the prefix is an actual
suite prefix as opposed to a simple string prefix. We do so by by
inspecting if the first two characters trailing the prefix are
our suite …
> clar: fix parsing of test suite prefixes

- src/stransport_stream.c
The `SSLCopyPeerTrust` call can succeed but fail to return a trust
object if it can't load the certificate chain and thus cannot check the
validity of a certificate. This can lead to us calling `CFRelease` on a
`NULL` trust object, causing a crash.
Handle this by returning ECERTIFICATE.
This may or may not solve #3885 /cc @the-kenny
> SecureTransport: handle NULL trust on success

- CHANGELOG.md
- include/git2/diff.h
I neglected to document this fine API addition when I added it.
> diff: document `git_diff_from_buffer`

- src/ignore.c
- tests/status/ignore.c
The .gitignore file allows for patterns which unignore previous
ignore patterns. When unignoring a previous pattern, there are
basically three cases how this is matched when no globbing is
used:
1. when a previous file has been ignored, it can be unignored by
using its exact name, e.g.
foo/bar
!foo/bar
2. when a file in a subdirectory has been ignored, it can be
unignored by using its basename, e.g.
foo/bar
!bar
3. when all files with a basename are ignored, a specific file
can be unignored again by specifying its path in a
subdirectory, e.g.
bar
!foo/bar
The first problem in libgit2 is that we did not correctly treat
the second case. While we verified that the negative pattern
matches the tail of the positive one, we did not verify if it
only matches the basename of the positive pattern. …
> ignore: allow unignoring basenames in subdirectories

- src/iterator.c
`git_iterator_free` tries to free `iter->root` (and `iter->current_path`) via the `filesystem_iterator_free` callback after it has already been freed. I couldn't figure out what caused the `on_error` case to begin with or else I would have tried to make a test case.
> filesystem_iterator: fixed double free on error

- src/diff.h
- src/diff_generate.c
- src/diff_parse.c
- src/diff_parse.h
- src/patch.c
- src/patch_generate.c
- src/patch_generate.h
- src/patch_parse.c
- src/patch_parse.h
- tests/diff/parse.c
Ensure that `git_patch_from_diff` can return the patch for parsed diffs,
not just generate a patch for a generated diff.
> Teach `git_patch_from_diff` about parsed diffs

- src/transports/http.c
When calling `http_connect` on a subtransport whose stream is already
connected, we first close the stream in case no keep-alive is in use.
When doing so, we do not reset the transport's connection state,
though. Usually, this will do no harm in case the subsequent connect
will succeed. But when the connection fails we are left with a
substransport which is tagged as connected but which has no valid
stream attached.
Fix the issue by resetting the subtransport's connected-state when
closing its stream in `http_connect`.
> transports: http: set substream as disconnected after closing

- tests/index/collision.c
Plug a memory leak caused by re-allocating a `git_index`
structure which has already been allocated by the test suite's
initializer.
> tests: index: do not re-allocate index

- src/patch_generate.c
When generating diffs for binary files, we load and decompress
the blobs in order to generate the actual diff, which can be very
costly. While we cannot avoid this for the case when we are
called with the `GIT_DIFF_SHOW_BINARY` flag, we do not have to
load the blobs in the case where this flag is not set, as the
caller is expected to have no interest in the actual content of
binary files.
Fix the issue by only generating a binary diff when the caller is
actually interested in the diff. As libgit2 uses heuristics to
determine that a blob contains binary data by inspecting its size
without loading from the ODB, this saves us quite some time when
diffing in a repository with binary files.
> patch_generate: only calculate binary diffs if requested

- src/refspec.c
- tests/online/fetchhead.c
According to git-fetch(1), "[t]he colon can be omitted when \<dst\>
is empty." So according to git, the refspec "refs/heads/master"
is the same as the refspec "refs/heads/master:" when fetching
changes. When trying to fetch from a remote with a trailing
colon with libgit2, though, the fetch actually fails while it
works when the trailing colon is left out. So obviously, libgit2
does _not_ treat these two refspec formats the same for fetches.
The problem results from parsing refspecs, where the resulting
refspec has its destination set to an empty string in the case of
a trailing colon and to a `NULL` pointer in the case of no
trailing colon. When passing this to our DWIM machinery, the
empty string gets translated to "refs/heads/", which is simply
wrong.
Fix the problem by having the …
> refspec: do not set empty rhs for fetch refspecs

- include/git2/diff.h
- src/apply.c
- src/diff_print.c
- src/patch.c
- src/patch_generate.c
- src/patch_parse.c
- tests/patch/patch_common.h
- tests/patch/print.c
When parsing a patch file, when we encounter a diff that was produced without `--binary`, we should include a binary patch that contains no data.  This type of patch node is special, and _cannot_ be applied, but it allows us to round-trip a patch file accurately.
`git_diff_binary` objects now indicate whether they contain data or not.  They "contain data" if they were produced by us when `SHOW_BINARY` is set or when they are parsed from a patch file produced by git with `--binary` set.  They do _not_ "contain data" when they are parsed from a patch file that simply says `Binary files ... differ`.
> Read binary patches (with no binary data)

- include/git2/sys/time.h
- src/util.c
This will allow libgit2 wrappers like Rugged to implement their own custom timeout logic while reusing the work we've already done in libgit2 to provide cross-platform, accurate monotonic timers.
See: https://github.com/libgit2/rugged/pull/631
cc @brianmario @mclark @ethomson @carlosmn
> time: Export `git_time_monotonic`

- src/checkout.c
When trying to determine if we can safely overwrite an existing workdir item, we may need to calculate the oid for the workdir item to determine if its identical to the old side (and eligible for removal).
We previously did this regardless of the type of entry in the workdir; if it was a directory, we would open(2) it and then try to read(2).  The read(2) of a directory fails on many platforms, so we would treat it as if it were unmodified and continue to perform the checkout.
On FreeBSD, you _can_ read(2) a directory, so this pattern failed.  We would calculate an oid from the data read and determine that the directory was modified and would therefore generate a checkout conflict.
This reliance on read(2) is silly (and was most likely accidentally giving us the behavior we wanted), we …
> checkout: don't try to calculate oid for directories

- script/cibuild.sh
We're failing this check and I'm trying to figure out why. It might just be that the format from `ssh-keygen` changed so we need to account for that in our tests.
> [WIP] Travis Mac SSH key issues

- include/git2/common.h
We changed the defaults on strict object creation - it is enabled by default.  Update the documentation to reflect that.
> docs: GIT_OPT_ENABLE_STRICT_OBJECT_CREATION is enabled

- examples/add.c
- examples/common.c
- examples/common.h
- examples/diff.c
- examples/general.c
- examples/network/fetch.c
- script/cibuild.sh
Recently, I wanted to build our examples and was hugely annoyed by all those warnings that were spilled left and right. So I cleaned up our tests, particularly the `examples/general.c` one, so that no warnings get thrown anymore.
Furthermore, I've changed CI scripts to build all tests to catch errors early on. I know that the examples aren't of huge importance, but considering they might be the first contact point with libgit2 for new developers, I'd say they should be reasonably clean and, as a bare minimum, compile. So that's why I think it is only sensible to break our CI builds when changes inside libgit2 break our examples.
> Squelch example warnings, enable CI

- include/git2/patch.h
Fix @return description of git_patch_num_lines_in_hunk.
Issue #3965
> patch: minor documentation fix.

- tests/core/vector.c
- tests/online/fetchhead.c
There were two trivial memory leaks in our test suite. This PR fixes both :)
> Trivial memory leak fixes in test suite

- .travis.yml
- script/coverity.sh
Just realized our Coverity builds were not running for nearly three months. Seems as if Coverity did change the download URLs for their build tools. I've fixed these and re-added a check so that we only let Coverity analyze our master branch.
I also removed valgrind from the allowed failures. I didn't spot any failures from valgrinds in the last builds, so I'd argue its a good thing to do to notice new failures. I'd also like to disallow failures for Coverity, but unfortunately the build is still too unstable due to quotas and occasional problems with downloading their toolset.
> CI Improvements

- src/pqueue.c
- tests/core/pqueue.c
The `git_pqueue` struct allows being fixed in its total number of
entries. In this case, we simply throw away items that are
inserted into the priority queue by examining wether the new item
to be inserted has a higher priority than the previous smallest
one.
This feature somewhat contradicts our pqueue implementation in
that it is allowed to not have a comparison function. In fact, we
also fail to check if the comparison function is actually set in
the case where we add a new item into a fully filled fixed-size
pqueue.
As we cannot determine which item is the smallest item in absence
of a comparison function, we fix the `NULL` pointer dereference
by simply dropping all new items which are about to be inserted
into a full fixed-size pqueue.
> pqueue: resolve possible NULL pointer dereference

- src/pack.c
In `pack_entry_find_offset`, we try to find the offset of a
certain object in the pack file. To do so, we first assert if the
packfile has already been opened and open it if not. Opening the
packfile is guarded with a mutex, so concurrent access to this is
in fact safe.
What is not thread-safe though is our calculation of offsets
inside the packfile. Assume two threads calling
`pack_entry_find_offset` at the same time. We first calculate the
offset and index location and only then determine if the pack has
already been opened. If so, we re-calculate the offset and index
address.
Now the case for two threads: thread 1 first calculates the
addresses and is subsequently suspended. The second thread will
now call `pack_index_open` and initialize the pack file,
calculating its addresses …
> pack: fix race in pack_entry_find_offset

- script/cibuild.sh
- src/commit.c
- src/tree.c
These issues, though hard to trigger on someone else's machine, were assigned CVEs (CVE-2016-8568 and CVE-2016-8569) and Fedora even had an update to address these. So let's do a release with these security updates.
> Backport the object parsing fixes

- src/global.c
- tests/core/init.c
When trying to initialize and tear down global data structures
from different threads at once with `git_libgit2_init` and
`git_libgit2_shutdown`, we race around initializing data. While
we use `pthread_once` to assert that we only initilize data a
single time, we actually reset the `pthread_once_t` on the last
call to `git_libgit2_shutdown`. As resetting this variable is not
synchronized with other threads trying to access it, this is
actually racy when one thread tries to do a complete shutdown of
libgit2 while another thread tries to initialize it.
Fix the issue by creating a mutex which synchronizes `init_once`
and the library shutdown.
> global: synchronize initialization and shutdown with pthreads

- src/repository.c
The existing code would set a namespace of "" (empty string) with
GIT_NAMESPACE unset.  In a repository where refs/heads/namespaces/
exists, that can produce incorrect results.  Detect that case and avoid
setting the namespace at all.
Since that makes the last assignment to error, and the previous
assignment can potentially get GIT_ENOTFOUND, set error to 0 explicitly
to prevent the call from incorrectly failing with GIT_ENOTFOUND.
> git_repository_open_ext: fix handling of $GIT_NAMESPACE

- THREADING.md
Starting at OpenSSL 1.1.0 it is thead-safe by itself, so mention that for people linking against it, they do not need to take further steps.
Also update the cURL link which has changed its location.
I've tried to reword things a bit to make it clearer (and remove a "may" for our last-resort locking function which might be taken as too much of a promise) but knowing what to do in order to use the network safely is still a minefield where you might need to initialise threading for two different libraries, and you don't know whether you have to until runtime.
> Update THREADING for OpenSSL 1.1

- include/git2/proxy.h
- src/transports/smart_protocol.c
I've started playing around with mitmproxy to test our online protocol and was able to force libgit2 into an infinite loop on first try. The issue occurs if we fetch from a remote via the smart protocol if the last flush packet from the remote is modified.
This PR fixes the infinite loop. I'm actually not sure why we only returned an EOF before when `flush == 0`, I couldn't find any reason here. One thing I could imagine is that we actually wanted to return `0` if the last received packet was actually a flush packet _and_ the socket returned EOF so that we wouldn't produce an error if we received less flushes than expected. But we actually only use the function once and only check if the return code was an error, so we wouldn't handle positive values (e.g. there are outstanding flushes). …
> transports: smart: abort on early end of stream

- src/apply.c
- src/checkout.c
- src/common.h
- src/fetchhead.c
- src/iterator.c
- src/merge.c
- src/odb.c
- src/patch_parse.c
- src/path.c
- src/tree.c
While inspecting #4000, I've been very surprised to find out that we were passing a `git_buf` pointer to `giterr_set` without any warning of the compiler. Seems we didn't put a printf-attribute hint at the declaration, causing the compiler to accept whatever we put there.
Next to the many cases of `"%d"` instead of `"%"PRIuZ` which can cause us to overflow in the output, there were also three real errors where we passed a structure pointer to "%s" instead of the real value.
> giterr format

- src/fileops.c
- src/path.c
- src/refdb.c
- src/refdb_fs.c
- src/sortedcache.c
- tests/threads/refdb.c
There's all sorts of races in there if you run many threads which all want to create and compress references.
We start by removing a useless test which doesn't even follow our own rules for concurrency and fixing a second one to use different objects and actually perform a concurrency test.
A bunch of this is simply to bubble up error codes so we know what we're dealing with, or fixing how we report them.
This also makes the packing logic more robust and safer by ignoring transient errors (and really the non-transient ones but it's more important that we continue working) and only deleting references if they haven't changed since we packed.
We still need to make sure #1534 doesn't happen by locking the `packed-refs` file before reloading, but the test no longer fails every second run.
> Concurrency fixes for the reference db

- src/tree.c
- tests/object/tree/update.c
The loop/algo is made to assume that we have sorted inputs. We sort them to make sure but we failed to actually _use_ the sorted list. The tests were inadvertently written with inputs that did not show this bad behaviour.
This fixes #3804
> Use the sorted input in the tree updater

- src/curl_stream.c
The `CURLINFO_LASTSOCKET` information has been deprecated since
curl version 7.45.0 as it may result in an overflow in the
returned socket on certain systems, most importantly on 64 bit
Windows. Instead, a new call `CURLINFO_ACTIVESOCKET` has been
added which instead returns a `curl_socket_t`, which is always
sufficiently long to store a socket.
As the new call has only been introduced with version 7.45.0
which was released in October 2015, we cannot simply remove the
old code but instead are required to conditionally compile based
on libcurl's version.
> curl_stream: use CURLINFO_ACTIVESOCKET if curl is recent enough

- src/index.c
- src/zstream.c
`giterr_set()` is used when it is required to format a string, and since
we don't really require it for this case, it is better to stick to
`giterr_set_str()`.
This also suppresses a warning(-Wformat-security) raised by the compiler.
> use `giterr_set_str()` wherever possible

- src/global.h
- src/unix/pthread.h
- src/win32/thread.c
- src/win32/thread.h
- tests/clar_libgit2.h
- tests/core/init.c
- tests/threads/basic.c
- tests/threads/refdb.c
When running in a child thread, we cannot `clar_git_pass` (or anything that will cause clar to `longjmp` to its error handler):
> The effect of a call to `longjmp()` where initialization of the `jmp_buf` structure was not performed in the calling thread is undefined.
Instead, provide some helpers to set up an error context in the child thread that the clar execution thread can then restore and abort when safe.  Use this for the `threads::refdb` test so that it errors gracefully, instead of crashing.
Obviously this does not fix the underlying problem in the`threads::refdb` test, but it does make it easier to reason about.
> Introduce some clar helpers for child threads

- src/win32/w32_util.h
Ensure correct type is passed, no garbage text is sent, and mute compiler warning.
> Properly pass `wchar *` type to giterr_set

- src/graph.c
- src/odb_mempack.c
- src/pack.c
- src/patch_generate.c
- src/path.c
- src/revwalk.c
- src/transports/smart_protocol.c
- tests/clar_libgit2.h
The title says it all. Just played around with VS2017 RC1 and wanted to see if there's anything interesting in the warnings. Nothing too interesting, I guess. Fixes for multiple uses of uninitialized values is the most interesting outcome.
> Various fixes

- tests/threads/refdb.c
This is far from an ideal situation, but this causes issues on Windows which
make it harder to develop anything, as these tests hit issues which relate
specifically to the Windows filesystem like permission errors for files we
should be able to access. There is an issue likely related to the ordering of
the repack, but there's enough noise that it does not currently help us to run
this aspect of the test in CI.
---
This is basically an approach out of desperation. There is too much that the Windows filesystem is throwing at us for us to resolve this before the release, and these edge cases shouldn't block the release, nor should it block CI for unrelated PRs as much as it does.
> refdb: disable concurrent compress in the threading tests on Windows

- src/openssl_stream.c
- src/openssl_stream.h
A backport of the PR that lets us build against OpenSSL 1.1. It doesn't have any functional changes, but right now you have to decide between having 1.1 installed and building a released version of this library.
> Add support for OpenSSL 1.1.0 for BIO filter

- src/signature.c
Etc/GMT-14 aka UTC+14:00 is a thing....
https://en.wikipedia.org/wiki/UTC%2B14:00
Also allow offsets on the last minute (59).
Addresses: https://bugs.debian.org/841532
Fixes: #3970
> Fix off-by-one problems in git_signature__parse

- src/pack.c
When trying to uncompress deltas in a packfile's delta chain, we try to
add object bases to the packfile cache, subsequently decrementing its
reference count if it has been added successfully. This may lead to a
mismatched reference count in the case where we exit the loop early due
to an encountered error.
Fix the issue by decrementing the reference count in error cleanup.
> pack: dereference cached pack entry on error

- src/refdb_fs.c
Failure to bubble up this error means some locking errors do not get reported as
such on Windows.
There's another issue around repacking references where some seem to go missing when all the threads start compressing at the same time, but this eliminates one of the common causes of CI failing (and of course actually helps with reporting the actual error).
> refdb: bubble up recursive rm when locking a ref

- README.md
According to the Gift repo it is now deprecated in favor of SwiftGit2.
> This library isn't really maintained anymore. You should use SwiftGit2 instead.
So changing the link for that here.
> Gift deprecated in favor of SwiftGit2

- include/git2/common.h
- src/settings.c
Most importantly, clarify what we mean by HTTPS and SSH being supported.
/cc @ethomson I think this should go into the next release.
> Don't hard-code HTTPS cap & clarify the meanings of the features enum

- src/sysdir.c
- tests/core/env.c
When a user sets a search path via variable substitution, we should replace the variable with whatever they may have previously set, rather than guess again what we would have chosen.
> sysdir: don't re-guess when using variable substitution

- src/transports/http.c
We want to keep the git UA in order for services to recognise that we're
a Git client and not a browser. But in order to stop dumb HTTP some
services have blocked UAs that claim to be pre-1.6.6 git.
Thread these needles by using the "git/2.0" prefix which is still close
enough to git's yet distinct enough that you can tell it's us.
---
It was reported that at least the GNOME host blocks us due to the UA claiming to be pre-1.6.6 git. While a bit ham-fisted it sure would block clients which don't speak the smart protocol. Chances are they're not the only ones who have taken these steps so let's bump it up to 2.0 since it's made up anyway.
> http: bump the pretend git version in the User-Agent

- include/git2/describe.h
- include/git2/remote.h
- include/git2/transaction.h
Note: 8149b17 removes git_remote_rename_problem_cb. Not sure when it stopped being used though.
> Documentation fixes

- src/odb_mempack.c
A ```git_mempack``` backend is currently unusable due to the ```git_odb_backend``` version being set to ```0``` instead of ```GIT_ODB_BACKEND_VERSION```
> mempack: set the odb backend version

- src/openssl_stream.h
Hello,
I tried to build libgit2 in OpenBSD (as dependencies of rust's cargo) and found that it can't find BIO_* functions defined in openssl_stream.h. Obviously because it was guarded with openssl version check. I found a reference (below) that we can use libressl as we check openssl for version < 1.1.0. This patch does just that.
Thanks.
ref:
https://github.com/gentoo/libressl/blob/672ac74ce7b7cb2e4799b2d66bc0b1b1efa3454e/media-video/ffmpeg/files/ffmpeg-3.2-libressl.patch
> Fix BIO_* functions method linking when compiled with libressl (OpenBSD).

- examples/general.c
According to the comments in the config.h file, git_config_get_string() needs a config snapshot.  Added call to git_repository_config_snapshot() to get this snapshot.
Added a "repo" parameter to config_files(), which is used by git_repository_config_snapshot().
I also tested (but did not commit) having git_config_get_int32() use the config snapshot.  This worked, and if implemented could eliminate the "repo_path" parameter to config_files().
> Fix issue #4046 Seg fault in config_files()

- CMakeLists.txt
Currently, when building `libgit2` on windows, if building against WinHTTP, there is no option to use an external `http-parser` library, we are [locked into using the builtin `http-parser` library](https://github.com/libgit2/libgit2/blob/ae5838f118a4819e608990a815bf8fc482be5772/CMakeLists.txt#L238-L241).  I'd guess this was done because there were purportedly some differences between the third-party `http-parser` library on windows and the builtin `http-parser` library.  However, I cannot find any special treatment of the windows build of the internal `http-parser`, so it stands to reason that we should be able to use the same external `http-parser` library on windows as we do on Linux or OSX.
This patch allows searching for `http-parser` libraries on any platform.
> Allow Windows with WinHTTP to use external http-parser

- CHANGELOG.md
`proxy_opts` fields were added to 2 structs, but not mentioned in the CHANGELOG. Cross ref https://github.com/JuliaLang/julia/issues/19793.
> Mention field addition in breaking API changes

- include/git2/version.h
- src/transports/http.c
- src/transports/smart_pkt.c
- src/transports/smart_protocol.c
- tests/online/badssl.c
This fixes a buffer boundary check error and a certificate validity check which can be bogus under certain conditions.
> Security updates for v0.24

- include/git2/version.h
- src/transports/http.c
- src/transports/smart_pkt.c
- src/transports/smart_protocol.c
- tests/online/badssl.c
This fixes a buffer boundary check error and a certificate validity check which can be bogus under certain conditions.
> security updates for v0.25

- examples/network/clone.c
Format of a length of string to the correct format is:%.*s
How to reproduce? Used when compiling libgit2 AddressSanitizer flag
`-fsanitize=address -fno-omit-frame-pointer`,
then under the example program gives you.
> fix examples/network/clone.c: heap-buffer-overflow

- CHANGELOG.md
- include/git2/merge.h
- src/merge.c
- tests/merge/trees/renames.c
When `GIT_MERGE_FIND_RENAMES` is set, provide a default for `rename_threshold` when it is unset.
The merge machinery expects `rename_threshold` to be nonzero if `GIT_MERGE_FIND_RENAMES` is set.  Previously, a consumer could set `GIT_MERGE_FIND_RENAMES` but leave `rename_threshold` unset and merge would get terribly confused.
Fixes #4035
> merge: set default rename threshold

- src/checkout.c
- tests/checkout/tree.c
git_checkout_tree() sets up its working directory iterator to respect the
pathlist if GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH is present, which is great.
What's not so great is that this iterator is then used side-by-side with
an iterator created by git_checkout_iterator(), which did not set up its
pathlist appropriately (although the iterator mirrors all other iterator
options).
This could cause git_checkout_tree() to delete working tree files which
were not specified in the pathlist when GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH
was used, as the unsynchronized iterators causes git_checkout_tree() to think
that files have been deleted between the two trees.  Oops.
And added a test which fails without this fix (specifically, the final check
for "testrepo/README" to still be present fails).
> Fix handling of GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH flag.

- src/indexer.c
- tests/pack/indexer.c
This change deletes the temporary packfile that the indexer creates to
avoid littering the pack/ directory with garbage.
> Delete temporary packfile in indexer

- include/git2/tree.h
- src/tree.c
When doing many merges in parallel in a large repository, we saw performance degrade rapidly due to memory allocations in git_treebuilder_write. This change uses a shared buffer created in git_tree__write_index to avoid the small allocation per tree in git_treebuilder_write.
In our tests against that repository we saw improvements of ~50% in merges under heavy load.
> Use a shared buffer in calls of git_treebuilder_write to avoid heap contention

- include/git2/common.h
- src/refs.c
- src/refs.h
- src/settings.c
Introduce GIT_OPT_ENABLE_SYMBOLIC_REF_TARGET_VALIDATION option.
Setting this option to 0 allows
validation of a symbolic ref's target to be bypassed.
This option is enabled by default.
This mechanism is added primarily to address a discrepancy between git
behaviour and libgit2 behaviour, whereby the former allows the symbolic
ref target to carry an arbitrary string and the latter does not, so:
```
$ git symbolic-ref refs/heads/foo bar
$ cat .git/refs/heads/foo
ref: bar
```
where as attempting the same via libgit2 raises an error:
```
The given reference name 'bar' is not valid
```
this mechanism also allows those that might want to make use of
git's more lenient treatment of symbolic ref targets to do so.
> Make symbolic ref target validation optional

- src/ignore.c
- src/pack-objects.c
- src/patch_generate.c
This is a few low-hanging fruits from using Xcode "Analyze" against libgit2.
Current `master` has 85 of those, this one is 81, and I managed to get it down to 64 by having more fine-grained control over `GITERR_CHECK_ALLOC` helps. If you feel that's a worthy goal, I can make another PR with those changes.
There are a few harder things which I can't tell if they're false-positives or not.
> Clang analyzer run

- src/submodule.c
Fix the following warning emitted by clang:
```
[ 16%] Building C object CMakeFiles/libgit2_clar.dir/src/submodule.c.o
/Users/mplough/devel/external/libgit2/src/submodule.c:408:6: warning: variable 'i' is used uninitialized whenever 'if' condition is true
[-Wsometimes-uninitialized]
if ((error = load_submodule_names(names, cfg)))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mplough/devel/external/libgit2/src/submodule.c:448:20: note: uninitialized use occurs here
git_iterator_free(i);
^
/Users/mplough/devel/external/libgit2/src/submodule.c:408:2: note: remove the 'if' if its condition is always false
if ((error = load_submodule_names(names, cfg)))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mplough/devel/external/libgit2/src/submodule.c:404:17: note: initialize the …
```
> Fix uninitialized variable warning

- src/vector.c
- tests/revwalk/basic.c
> Vector reverse overflow

- include/git2/revert.h
The documentation for `git_revert` as of [v0.24.2](https://libgit2.github.com/libgit2/#v0.24.2/group/revert/git_revert) doesn't state that it can be null. However, if you look at the [code](https://github.com/libgit2/libgit2/blob/909d5494368a00809bc42f4780e86f4dd66e4422/src/revert.c#L81-L86) you will see that libgit2 will actually initialize options for the revert if `NULL` is passed into the function.
The header file should be updated as such to reflect that `given_opts` can actually be `NULL`.
> Flag given_opts in git_revert as optional

- include/git2/reset.h
The documentation for `git_reset` doesn't state that `check-out_opts` can be optional in its documentation. However, if you look at a [test file](https://github.com/libgit2/libgit2/blob/9bc8c80ffa3d20e958406a104c521e2aae0f1255/tests/reset/hard.c#L74) you will see that `NULL` is used everywhere.
The header file should be updated to reflect that `check_opts` is actually an optional argument.
> Flag checkout_opts in git_reset as optional

- src/transports/winhttp.c
Using a proxy with digest credentials was not working in Windows. It was simply always using basic auth whenever a plaintext credential mechanism was specified. Detecting whether the plaintext credential mechanism was digest or basic and applying that mechanism to `WinHttpSetCredentials` fixed the problem.
> Fix digest credentials for proxy in windows

- include/git2/stash.h
The options parameter in both [git_stash_apply](https://github.com/libgit2/libgit2/blob/0175971e91641cd07246f59003930d81019ce40b/tests/stash/apply.c#L105) and [git_stash_pop](https://github.com/libgit2/libgit2/blob/0175971e91641cd07246f59003930d81019ce40b/tests/stash/apply.c#L307) can be `NULL` as can be seen in the linked tests. The documentation in the `stash.h` header file should reflect this.
> Flag options in git_stash_apply and git_stash_pop as being optional

- src/remote.c
curl supports HTTPS_PROXY in addition to https_proxy (and their http counterparts). This change ensures parity with curl's behavior.
> Add support for lowercase proxy environment variables

- include/git2/common.h
- src/settings.c
- src/transports/smart.h
- src/transports/smart_protocol.c
This change provides an option in git_libgit2_opt_t which can be used in git_libgit2_opts to turn off/on ofs_delta capability in libGit2
This is related to Issue #1414 in libgit2Sharp repository
https://github.com/libgit2/libgit2sharp/issues/1414
> Changes to provide option to turn off/on ofs_delta

- include/git2/commit.h
- src/buffer.h
- src/commit.c
Some findings related to #4118
> Signature cleanups

- src/refdb_fs.c
The upstream git.git project currently identifies all references inside
of `refs/bisect/` as well as `HEAD` as per-worktree references. This is
already incorrect and is currently being fixed by an in-flight topic
[1]. The new behavior will be to match all pseudo-references outside of
the `refs/` hierarchy as well as `refs/bisect/`.
Our current behavior is to mark a selection of pseudo-references as
per-worktree, only. This matches more pseudo-references than current
git, but forgets about `refs/bisect/`. Adjust behavior to match the
in-flight topic, that is classify the following references as
per-worktree:
- everything outside of `refs/`
- everything inside of `refs/bisect/`
[1]: <20170213152011.12050-1-pclouds@gmail.com>
> refdb: catch additional per-worktree refs

- src/unix/posix.h
- tests/attr/ignore.c
- tests/clar_libgit2.c
- tests/clar_libgit2.h
- tests/repo/env.c
- tests/status/ignore.c
- tests/submodule/submodule_helpers.c
Provide more detailed messages when conditions pass or fail unexpectedly.  In particular, this provides the error messages when a test fails with a different error code than was expected.
`cl_git_pass` failures look unchanged:
```
1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
Function call failed: (git_patch_from_buffer(&patch, "", 0, ((void *)0)))
error -3 - no patch found
```
`cl_git_fail` messages now:
```
1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
Function call succeeded: git_patch_from_buffer(&patch, patchfile, strlen(patchfile), NULL)
no error, expected non-zero return
```
`cl_git_fail_with` messages now:
```
1) Failure:
apply::fromfile::test_name [tests/apply/fromfile.c:42]
Function call failed: (git_patch_from_buffer(&patch, "", 0, …
```
> Improve clar messages

- src/thread-utils.h
Provide a descriptive error message when compiling `THREADSAFE` on gcc versions < 4.1.  We require the atomic primitives (eg `__sync_synchronize`) that were introduced in that version.
(Note, clang setes `__GNUC__` but appears to set its version > 4.1.)
> Provide error on gcc < 4.1 when THREADSAFE

- src/pack.c
This is a crash on 32-bit and I assume that it doesn't do the right thing on
64-bit either. MSVC emits a warning for this, but of course, it's easy to get
lost among all of the similar 'possible loss of data' warnings.
> fix regression from #4092

- tests/core/posix.c
Haiku will assert in a nightly build if the "dst" input to inet_pton() is NULL.
> Fix inet_pton tests triggering an assert in Haiku

- CONVENTIONS.md
I noticed a few minor typos when reading CONVENTIONS.md and resolved them accordingly.
> Fix minor typos in CONVENTIONS.md

- tests/refs/create.c
This test ensures that it's possible to create a symbolic ref that
has arbitrary data as its target. It also ensures it's possible
to obtain the target of that symbolic reference from the git_reference
object.
> tests: Add create__symbolic_with_arbitrary_content

- src/refs.c
- tests/refs/reflog/reflog.c
> Fix: make reflog include "(merge)" for merge commits

- src/commit.c
- src/odb.c
- src/odb.h
- tests/odb/freshen.c
Freshen the tree object that a commit points to during commit time.  This can help to freshen trees when a new commit is written that points to an old tree (but that tree id was recorded, instead of being newly computed with `git_odb_write`, which would have done the tree freshening itself.)
/cc @carlosmn
> git_commit_create: freshen tree objects in commit

- src/refdb_fs.c
- tests/refs/namespaces.c
Support `git_repository_set_namespace` again (the equivalent of `GIT_NAMESPACE`); this was subtly broken with worktree support.
This adds a simple namespace test (equivalent to rugged's) and simplifies the namespace handling by simply appending the namespace (if it exists) to the gitdir and commondir.
/cc @carlosmn
> Support namespaced references again

- src/fileops.c
Don't compute the sha-1 in `git_futils_readbuffer_updated` unless the
checksum was requested.  This means that `git_futils_readbuffer` will
not calculate the checksum unnecessarily.
> git_futils_readbuffer: don't compute sha-1

- include/git2/sys/merge.h
- src/merge_driver.c
An oversight on my side regarding #4153.
> merge_driver: fix const-correctness for source getters

- src/checkout.c
- src/idxmap.c
- src/idxmap.h
- src/offmap.c
- src/offmap.h
- src/oidmap.c
- src/oidmap.h
- src/strmap.c
- src/strmap.h
I just noticed a subtle bug via Coverity which I introduced in my recent refactoring of the map interfaces. The `git_map_free` functions were implemented as macros, but in fact in a subtly wrong way where the statements were not grouped together by a `do { ... } while (0)` block. I think no real issues were introduced by this, but I took it as a hint to remove the macro altogether. One caller needed to be fixed, but this was a double-free anyway and as such wrong.
> Remove `map_free` macros

- include/git2/remote.h
Remotes are being incorrectly referred to as a `remove` instead of a `remote`. This should be fixed.
> Fix typo in remote.h API

- include/git2/transport.h
If you look at the documentation for [`git_cred_acquire_cb`](https://libgit2.github.com/libgit2/#v0.25.1/group/callback/git_cred_acquire_cb), you will see that the format is completely off with everything at the bottom with its return value and parameters undocumented. Compare this with [`git_diff_progress_cb`](https://libgit2.github.com/libgit2/#v0.25.1/group/callback/git_diff_progress_cb) where its parameters and return value is correctly documented because of its [proper use of tags](https://github.com/libgit2/libgit2/blob/adedac5aba9e4525475fd59d751cd02c6f2b3a4f/include/git2/diff.h#L359-L373) in the header file.
The documentation for `git_cred_acquire_cb` should be using standard `@param` and `@return` tags so that the documentation will be generated correctly.
> Fix the documentation for git_cred_acquire_cb

- include/git2/common.h
- include/git2/odb_backend.h
- src/config_cache.c
- src/filebuf.c
- src/filebuf.h
- src/fileops.c
- src/fileops.h
- src/indexer.c
- src/indexer.h
- src/object.c
- src/object.h
- src/odb.c
- src/odb.h
- src/odb_loose.c
- src/pack-objects.c
- src/pack-objects.h
- src/posix.c
- src/posix.h
- src/rebase.c
- src/refdb_fs.c
- src/repository.c
- src/repository.h
- src/settings.c
- src/unix/posix.h
- src/win32/posix_w32.c
- tests/odb/loose.c
- tests/pack/packbuilder.c
- tests/refs/create.c
Optionally `fsync` loose objects, packfiles and their indexes, loose references and packed reference files.  This can be enabled by setting the option `GIT_OPT_ENABLE_SYNCHRONIZED_OBJECT_CREATION`, and it is not enabled by default.
Additionally, enable the `do_fsync` option to the loose odb backend to perform similar calls.
At present, we do not honor `core.fsyncObjectFiles`, though this would be a logical next step.
> fsync all the things

- include/git2/worktree.h
- src/refdb_fs.c
- src/submodule.c
- src/worktree.c
- src/worktree.h
- tests/resources/submodules/testrepo/.gitted/config
- tests/worktree/open.c
- tests/worktree/refs.c
- tests/worktree/submodule.c
- tests/worktree/worktree.c
So this is the first batch of fixes for the worktree implementation. Fixes:
- the parent path inside of the `git_worktree` path now correctly points to the parent repository, that is it will usually point to the parent working directory
- resolving relative URLs for a working tree of a submodule now correctly resolves the URL relative to the working tree's parent working directory
- a new function `git_worktree_open_from_repository` has been added to retrieve the worktree structure from a repository, if it actually is a working tree
- non-per-worktree file references are now actually created in the common directory instead of the gitdir. This was a major oversight
- worktree link files are now resolved so that we write absolute paths instead of relative paths
- the HEAD reference for …
> Worktree fixes

- tests/core/posix.c
Address family 5 might exist on some crazy system like Haiku.
Use `INT_MAX-1` as an unsupported address family.
Fixes #3872
> inet_pton: don't assume addr families don't exist

- src/fileops.c
`O_EXCL` and `O_TRUNC` are mutually exclusive flags to open(2); you can't truncate a file if you're asserting that it can't exist in the first place.  Drop `O_TRUNC`.
Fixes #4017
> git_futils: don't O_EXCL and O_TRUNC

- src/blame_git.c
- src/worktree.c
The recent addition of an error code to `pass_whole_blame` in ff8d2eb15
(blame_git: check return value of object lookup, 2017-03-20) introduced
a spurious goto. Remove it.
Just noticed a few thousands of new memory leaks in the CI. The error is trivial and kind of embarassing - I'm surprised the compiler didn't throw any warning for unreachable code.
> Fix memory leaks

- src/tree.c
Some small refactorings and memory leak fixes for the git_treebuilder_write_with_buffer function. This was triggered by #4181, but does not actually fix the issue.
> git_treebuilder_write_with_buffer refactorings

- libgit2.pc.in
Our libgit2.pc.in file is quoting the `libdir` variable in our declared
"Libs:" line. The intention is to handle whitespaces here, but pkgconfig
already does so by automatically escaping whitespace with backslashes.
The correct thing to do is to instead quote the prefix, as this is the
one which is being substituted by CMake upon installation. As both
libdir and includedir will be expanded to "${prefix}/lib" and
"${prefix}/include", respectively, pkgconfig will also correctly escape
whitespaces.
Note that this will actually break when a user manually wants to
override libdir and includedir with a path containing whitespace. But
actually, this cannot be helped, as always quoting these variables will
actuall break the common case of being prefixed with "${prefix}". So we
just bail out here …
> pkgconfig: fix handling of prefixes containing whitespaces

- README.md
libgit2 is a mere consumer of changes which are trickling down from the
upstream git.git project. This commit documents the ramifications caused
by this relation.
> README: document our relation to changes in upstream

- src/openssl_stream.c
This fixes the issues raised by #4194. When bulding against OpenSSL without deprecated features, we currently fail. This can be provoked by defining "-DOPENSSL_API_COMPAT=0x10100000L" when OpenSSL 1.1 is installed.
> Fix building against OpenSSL v1.1

- src/filter.c
- tests/filter/custom.c
- tests/filter/custom_helpers.c
- tests/filter/custom_helpers.h
In the function `git_filter_list_stream_data`, we initialize, write and
subesquently close the stream which should receive content processed by
the filter. While we skip writing to the stream if its initialization
failed, we still try to close it unconditionally -- even if the
initialization failed, where the stream might not be set at all, leading
us to segfault.
Semantics in this code is not really clear. The function handling the
same logic for files instead of data seems to do the right thing here in
only closing the stream when initialization succeeded. When stepping
back a bit, this is only reasonable: if a stream cannot be initialized,
the caller would not expect it to be closed again. So actually, both
callers of `stream_list_init` fail to do so. The data streaming function
will …
> filter: only close filter if it's been initialized correctly

- src/fileops.c
When the `git_futils_mmap_ro_file` function encounters an error after
the file has been opened, it will do a simple returns. Instead, we
should close the opened file descriptor to avoid a leak. This commit
fixes the issue.
> fileops: fix leaking fd in `mmap_ro_file`

- src/diff_parse.c
In e7330016a (diff_parse: check return value of `git_diff_init_options`,
2017-03-20), we've introduced an error check whether we're able to
correctly initialize the diff options. This simple commit actually
introduced a segfault in that we now try to free the pointer to the
allocated diff in an error case, instead of the allocated diff itself.
This commit fixes the issue.
Kind of embarrassing... :sweat_drops:
> diff_parse: free object instead of its pointer

- src/config.c
- src/config_file.h
- tests/config/readonly.c
Configuration backends have a readonly-flag which is currently used to
distinguish configuration snapshots. But somewhat unexpectedly, we do
not use the flag to prevent writing to a readonly backend but happily
proceed to do so.
This commit modifies logic to also honor the readonly flag for
configuration setters. We will now traverse through all backends and
pick the first one which is not marked as read-only whenever we want to
write new configuration.
Implements #4134
> Honor read-only flag when writing to config backends

- src/socket_stream.c
When connecting to a remote via socket stream, we first use getaddrinfo
to obtain the possible connection methods followed by creating and
connecting the socket. But when creating the socket, we error out as
soon as we get an invalid socket instead of trying out other address
hints returned by addrinfo.
Fix this by continuing on invalid socket instead of returning an error.
This fixes connection establishment with musl libc.
> socket_stream: continue to next addrinfo on socket creation failure

- src/branch.c
- src/refs.c
- src/refs.h
- src/repository.c
- src/repository.h
- tests/worktree/refs.c
- tests/worktree/worktree.c
When renaming a branch in a repository, we have to check whether any linked worktree has that branch checked out. If so, we have to update the worktree's HEAD file to point to the renamed branch. This pull requests implements this behavior, which is the same as in upstream git.git.
This PR is currently a WIP. While it works right now, I tend to find it quite ugly. My main grief is reading the worktree HEADs. I couldn't find any way to reliably parse HEAD files at arbitrary paths, especially when it is a symref pointing to a non-existing (read as "just renamed") branch. That's why I implemented `git_reference_read_head` as well as `read_head_file`, but to be honest this feels as if I'm re-inventing the wheel. I'm not sure whether it's my misuse of the API or if we don't have support for …
> Branch renames with worktrees

- src/remote.c
The regression was introduced in 22261344de18b3cc60ee6937468d66a6a6a28875
> Do not free config when creating remote

- src/remote.c
We've been (incorrectly) using this in julia and see no errors in release builds. Given that `refspec` is only passed to `git_remote_upload` which allows a `NULL` `refspec` I think this assertion can be relaxed.
Ref https://github.com/JuliaLang/julia/issues/21639
> Allow NULL refspec in git_remote_push

- include/git2/sys/transport.h
- src/transports/smart.c
As with the callbacks, third-party implementations of smart subtransports cannot
reach into the opaque struct and thus cannot know what options the user set.
Add a getter for these options to copy the proxy options into something external
implementors can use.
> transport: provide a getter for the proxy options

- include/git2/common.h
- include/git2/errors.h
- src/odb.c
- src/odb.h
- src/settings.c
- tests/object/lookup.c
- tests/odb/backend/nonrefreshing.c
I've just been triggered by [1] to actuall check how we behave with corrupted on-disk objects. The good news is that we actually detect simple bit-flips in loose objects, but this comes for free through the zlib library, which is unable to restore contents. I've added a test which repeatedly corrupts all the bytes in an object and then tries to read it, and this one succeeds without any change whatsoever.
The bad news is that we actually fail to verify valid objects which are saved under the wrong name. E.g. when a commit "adeadbeef" is not stored in ".git/objects/ad/eabdeef" but in "git/objects/bd/eadbeef", we did not complain. Upstream git.git does actually detect this case and complain.
So I've implemented the upstream behavior, so that we now also compute and verify the object's hash …
> Verify object hashes

- src/global.c
- src/transports/ssh.c
A few small cleanups regarding libssh2 and git_buf_clear/git_buf_free confusion.
The libssh2 code did not call libssh2_exit on shutdown, which I've fixed. This still leaves us with memory leaks in libssh2/libgcrypt, though, which I cannot track down with the CI only. I'll try to fire up a VM to hunt down the remaining issues, as my host system is incompatible with valgrind due to musl libc. :/
> libssh2 shutdown

- tests/repo/discover.c
- tests/repo/open.c
Debian and Ubuntu often use schroot to build their DEB packages in a
controlled environment. Depending on how schroot is configured, our
tests regarding repository discovery break due to not being able to find
the repositories anymore. It turns out that these errors occur when the
schroot is configured to use an overlayfs on the directory structures.
The reason for this failure is that we usually refrain from discovering
repositories across devices. But unfortunately, overlayfs does not have
consistent device identifiers for all its files but will instead use the
device number of the filesystem the file stems from. So whenever we
cross boundaries between the upper and lower layer of the overlay, we
will fail to properly detect the repository and bail out.
This commit fixes the issue by …
> tests: repo: fix repo discovery tests on overlayfs

- README.md
libgit2 is no longer used in Visual Studio (the IDE), it's used in
Visual Studio Team Services.
> Update README: VS -> VSTS

- examples/network/common.c
- src/odb.c
- tests/clone/local.c
- tests/threads/basic.c
This is split out from #4211. With this, we're free of compiler warnings on Ubuntu Trusty images, which will allow us to selectively enable "-Werror" in the future.
> Fix GCC warnings

- src/revparse.c
- tests/refs/revparse.c
Support '..' and '...' ranges where one or both sides are not
specified. The unspecified side defaults to HEAD.
Closes #4223
> revparse: support open-ended ranges

- src/repository.c
- tests/repo/head.c
When `git_repository_set_head` is provided a tag reference, update the reflog with the tag name, like we do with a branch.  This helps consumers match the semantics of `git checkout tag`.
If you think of `git_repository_set_head` as an analog to `git symbolic-ref HEAD ...` then this doesn't make a lot of sense.  But I would argue that it's not a perfect analog already to `git symbolic-ref`, and this is natural for users who want to `git checkout ...` to switch branches.
See #3909
> git_repository_set_head: use tag name in reflog

- src/transports/http.c
When using an authenticated proxy and setting proxy_options `type` to `GIT_PROXY_AUTO`, the credentials, certificate check, and payload are discarded. The implication is users will not be prompted for credentials when proxy type is set to auto. I've fixed this by transferring the credentials, certificate_check, and payload to the new struct when in apply_proxy_config.
> Fix proxy auto detect not utilizing callbacks

- src/attrcache.c
- src/config.c
- src/config_file.c
- src/sysdir.c
- src/sysdir.h
- tests/config/include.c
When we need to expand a tilde-prefixed path to the home directory (eg `~/file.txt` -> `/home/ethomson/file.txt`) we currently use `git_sysdir_find_global_file`.  Unfortunately, this function will return `GIT_ENOTFOUND` if the file does not exist in the home directory, which can make the error handling odd.
As a result, we currently if a nonexistent config file is included with a `~` path, and if a non-existent attribute file is loaded by a `~`, we will (incorrectly) fall back to looking for a file with a literal `~`.
This introduces `git_sysdir_expand_global_file` so that callers can simply expand the filename and then use it in their normal error handling logic if it is ultimately not found.
This builds on the fixes in #3828, which this obsoletes.
Fixes #3681.
> Introduce home directory expansion function for config files, attribute files

- src/attr_file.c
- tests/attr/ignore.c
- tests/status/ignore.c
Observed issue: Git understands `/*/` in a ` .gitignore` file to mean "ignore all root-level directories, but include files". Published libgit2 has the same behavior _except_ when the `.gitignore` file is in a subdirectory of the repository. I reproduced this behavior with tests `master` and `0.24.3`.
I added four new tests; three of them already work in master. The one that fails w/o my change is `test_status_ignore__subdir_ignore_all_toplevel_dirs_include_files`. The other tests in status::ignore illustrate that the issue was only occurring for `.gitignore` files in subdirectories, and only for directory matches.
My proposed changed _seems_ safe to me, because `relpath` is derived from `path->path`, which is in the original code, and it only affects the case where the match is looking …
> Fix issue with directory glob ignore in subdirectories

- include/git2/worktree.h
- src/worktree.c
- tests/worktree/refs.c
- tests/worktree/submodule.c
- tests/worktree/worktree.c
The initial inspiration of this was the recently added `git worktree add --locked`, which I've added in this PR. While at it I also changed signatures of the yet-unreleased "git_worktree_add", "git_worktree_prune" and "git_worktree_is_prunable" functions to accept options structures, so that these functions are potentially extensible without breaking the API in future releases.
> Worktree options

- CMakeLists.txt
Temporarily disable the UNC tests when running in AppVeyor.  Temporary workaround for: https://github.com/appveyor/ci/issues/1579
> (Temporarily) disable UNC tests

- src/buffer.c
- src/buffer.h
- src/config_file.c
- src/pack.c
- src/transports/winhttp.c
Small-ish cleanups for growing buffers. While this is mostly done to silence Coverity, I think it even improves code by a tiny fraction.
> Buffer growing cleanups

- include/git2/common.h
- src/indexer.c
- src/object.c
- src/object.h
- src/odb_loose.c
- src/refdb_fs.c
- src/repository.c
- src/repository.h
- src/settings.c
- tests/odb/loose.c
- tests/pack/packbuilder.c
- tests/refs/create.c
Initially, the setting has been solely used to enable the use of
`fsync()` when creating objects. Since then, the use has been extended
to also cover references and index files. As the option is not yet part
of any release, we can still correct this by renaming the option to
something more sensible, indicating not only correlation to objects.
This commit renames the option to `GIT_OPT_ENABLE_FSYNC_GITDIR`. We also
move the variable from the object to repository source code.
> settings: rename `GIT_OPT_ENABLE_SYNCHRONOUS_OBJECT_CREATION`

- src/checkout.c
- src/fileops.c
- tests/checkout/head.c
A riff on #4129, with the changes discussed therein.  Opening a new PR to make sure that CI is happy before I merge it.  😄
> Update to forced checkout and untracked files

- src/indexer.c
- tests/pack/indexer.c
- tests/pack/packbuilder.c
Use the hash of the complete packfile as the filename instead of the hash of just the OIDs.  This matches the behavior of core git, which changed in 2013 in [commit 1190a1a](https://github.com/git/git/commit/1190a1acf800acdcfd7569f87ac1560e2d077414).  The message for that commit includes the reasoning behind the change.  
I ran into a problem with the current naming in an application that occasionally performs two fetches of the same remote at the same time.  The objects in the resulting packfiles are the same, so they get the same filename, but the contents are sometimes different, likely because pack building is multi-threaded.  The second fetch to complete will overwrite the `.idx` file from the first fetch, but fail to rename the `.pack` file, so the `.idx` and `.pack` files don't …
> Ensure packfiles with different contents have different names

- src/odb.c
When looking for an object by prefix, we query all the backends so that we can ensure that there is no ambiguity.  We need to reset the `error` value between backends; otherwise the first backend may find an object by prefix, but subsequent backends may not.  If we do not reset the `error` value then it will remain at `GIT_ENOTFOUND` and `read_prefix_1` will fail, despite having actually found an object.
LibGit2Sharp creates such a scenario in its tests: it sets up its own custom ODB backend, then adds an object and looks that object up again by a prefix.
> odb_read_prefix: reset error in backends loop

- src/transports/smart_protocol.c
Fix ACK parsing in `wait_while_ack()` internal function. This patch handles the case where `multi_ack_detailed` mode sends `ready` ACKs. The existing functionality would bail out too early, thus causing the processing of the ensuing packfile to fail if/when `ready` ACKs were sent.
The specification of the git pack-protocol details that for `multi_ack_detailed` mode the server ACKs refs with annotations `common` or `ready` depending on whether the commit was identified as common or if at that point in time the server had already identified a common base commit. In the `git.git` implementation of `git-upload-pack` the process rarely ever sends `ready` ACKs since it seemingly walks the entire DAG and identifies all common commits. However the client could send commits it obtained from …
> smart_protocol: fix parsing of server ACK responses

- include/git2/repository.h
- src/repository.c
- tests/network/remote/local.c
Regression:  we cannot create a configuration object against an in-memory remote, since the path to the repository configuration cannot be created.
Change `git_repository_item_path` to return `GIT_ENOTFOUND` when the path could not be constructed because the underlying directory does not exist.  (For example, when requesting the `config` file on an in-memory repository.
Add a unit test for a concrete scenario: create an anonymous remote on an in-memory repository (to allow for emulating `git ls-remote`).
> Allow creation of a configuration object in an in-memory repository

- tests/odb/backend/backend_helpers.c
- tests/odb/backend/backend_helpers.h
- tests/odb/backend/multiple.c
- tests/odb/backend/nonrefreshing.c
Inspired by #4264. Along other tests, this also adds a test which segfaults due to the error fixed in the other PR.
> Read prefix tests

- script/install-deps-osx.sh
The formulae provided by the homebrew/dupes tap are deprecated since at
least April 4, 2017, with formulae having been migrated to
homebrew/core.
Replace the deprecated reference to "homebrew/dupes/zlib" with only
"zlib".
> travis: replace use of deprecated homebrew/dupes tap

- include/git2/sys/filter.h
- src/filter.c
- tests/core/structinit.c
Adding GIT_FILTER_VERSION to GIT_FILTER_INIT. 
Stumbled on this while using custom filters via. filter struct.
Also on the recommendation of @implausible.
Similar convention seen in files:
include/git2/sys/blame.h (Line 82)
include/git2/sys/checkout.h (Line 298)
include/git2/sys/cherrypick.h (Line 37)
...
> adding GIT_FILTER_VERSION to GIT_FILTER_INIT as part of convention

- src/repository.c
- tests/repo/init.c
Closes #4271.
This is my first time contributing to this project, so I hope I did everything correctly. I also added a test, which I verified does pass with the empty-string check I added, and fails otherwise.
> Fix template dir empty string

- .travis.yml
- script/cibuild.sh
- tests/online/clone.c
Ubuntu 12.04 (Precise Pangolin) reaches end of life on April 28th, 2017.
As such, we should update our build infrastructure to use the next
available LTS release, which is Ubuntu 14.04 LTS (Trusty Tahr). Note
that Trusty is still considered beta quality on Travis. But considering
we are able to correctly build and test libgit2, this seems to be a
non-issue for us.
Switch over our default distribution to Trusty. As Precise still has
extended support for paying customers, add an additional job which
compiles libgit2 on the old release.
> travis: upgrade container to Ubuntu 14.04

- src/merge.c
The function `merge_diff_mark_similarity_exact` may error our early and,
when it does so, free the `ours_deletes_by_oid` and
`theirs_deletes_by_oid` variables. While the first one can never be
uninitialized due to the first call actually assigning to it, the second
variable can be freed without being initialized.
Fix the issue by initializing both variables to `NULL`.
> merge: fix potential free of uninitialized memory

- src/posix.c
`sin_port` should be in network byte order.
> Convert port with htons() in p_getaddrinfo()

- tests/config/readonly.c
On systems where we pull in our distributed version of the regex
library, all tests in config::readonly fail. This error is actually
quite interesting: the test suite is unable to find the declaration of
`git_path_exists` and assumes it has a signature of `int
git_path_exists(const char *)`. But actually, it has a `bool` return
value. Due to this confusion, some wrong conversion is done by the
compiler and the `cl_assert(!git_path_exists("file"))` checks
erroneously fail, even when the function does in fact return the correct
value.
The error is actually introduced by 56893bb9a (cmake: consistently use
TARGET_INCLUDE_DIRECTORIES if available, 2017-06-28), unfortunately
introduced by myself. Due to the delayed addition of include
directories, we will now find the "config.h" header inside …
> tests: config: fix missing declaration causing error

- src/signature.c
If the signature is invalid but we detect that after allocating the strings, we
free them. We however leave that pointer dangling in the structure the caller
gave us, which can lead to double-free.
Set these pointers to `NULL` after freeing their memory to avoid this.
> signature: don't leave a dangling pointer to the strings on parse failure

- include/git2/diff.h
- src/diff.c
- tests/core/structinit.c
- tests/diff/patchid.c
- tests/patch/patch_common.h
This is a work in progress. It does produce the same patch IDs for many files, but I'm not quite there yet. I've also discovered an error in parsing patches where the file names have whitespaces inside and added a test, but there is no fix yet.
> Patch ID calculation

- src/config_file.c
- tests/config/include.c
This fixes the issues causing #4247, but it does not yet fix additional issues with includes. One more issue I found was that upon refreshing a config file, we'll duplicate the includes inside the readers struct, if I'm not mistaken. I'll try to tackle this problem tomorrow, alongside with some tests for the broken behaviour.
> Configuration file fixes with includes

- CHANGELOG.md
- src/win32/posix_w32.c
When using the `do_with_retries` macro for retrying filesystem operations in the posix emulation layer, allow the remediation function to return `GIT_RETRY`, meaning that the error was believed to be remediated, and the operation should be retried immediately, without a sleep.
Use this in the `ensure_writable` remediation function - if the function is able to set the file writable, then retry the operation immediately.  This will prevent a 5ms sleep in the common case.
> win32: provide fast-path for retrying filesystem operations

- .travis.yml
- script/cibuild.sh
- script/install-deps-linux.sh
This builds with a custom version of libcurl, which includes a fix for proxies and NTLM credentials.  It comes as quite a shock to curl 7.35, but you do not need to necessarily use proxy credentials when you are using a proxy with NTLM credentials (on the overall connection) and curl's connection pooling mechanism will segfault if you in fact do not.
This fix skips a `strcmp` against `NULL` proxy username/password:
```
--- curl-7.35.0.orig/lib/url.c
+++ curl-7.35.0/lib/url.c
@@ -3135,6 +3135,11 @@ ConnectionExists(struct SessionHandle *d
/* Same for Proxy NTLM authentication */
if(wantProxyNTLMhttp) {
+          /* Both check->http_proxy.user and check->http_proxy.passwd can be
+           * NULL */
+          if(!check->proxyuser || !check->proxypasswd)
+            continue;
+ …
```
> Build with patched libcurl

- src/tsort.c
The conditional `run < minrun` can never be true directly after
assigning `run = minrun`. Remove it to avoid confusion.
> tsort: remove idempotent conditional assignment

- tests/rebase/submodule.c
Some return codes for functions which may fail are not being checked in
`test_rebase_submodule__initialize`. This may lead us to not notice
errors when initializing the environment and would possibly result in
either memory corruption or segfaults as soon as any of the
initialization steps fails. Fix this by wrapping these function calls
into `cl_git_pass`.
> tests: rebase::submodule: verify initialization method calls

- AUTHORS
- CHANGELOG.md
- include/git2/remote.h
- src/remote.c
- tests/online/remotes.c
Took over from #3855. This includes the original contents from @heavenlyhash squashed together and rebased on master. While at it, I renamed `git_remote_create_unattached` to the more common `git_remote_create_detached`. I added checks to refuse push/download/upload for detached repositories, as it would segfault otherwise. I also added a few tests for `git_remote_ls` with detached remotes and tests checking whether we correctly refuse the other actions.
> Detached remotes

- include/git2/patch.h
- src/patch_generate.c
Pointers to general data should usually be used as a void pointer such
that it is possible to hand in variables of a different pointer type
without the need to cast. This is the same when creating patches from
buffers, where the buffers may contain arbitrary data. Instead of
requiring the caller to care whether his buffer is e.g. `char *` or
`unsigned char *`, we should instead just accept a `void *`. This is
also consistent in how we tread other types like for example `git_blob`,
which also just has a void pointer as its raw contents.
---
Fixes #3986
> patch_generate: represent buffers as void pointers

- src/sha1_lookup.c
If we enter the sha1_position() function with "lo == hi", we have no elements. But the do-while loop means that we'll enter the loop body once anyway, picking "mi" at that same value and comparing nonsense to our desired key. This is unlikely to match in practice, but we still shouldn't be looking at the memory in the first place.
This bug is inherited from git.git; it was fixed there in git/git@e01580cfe01526ec2c4eb4899f776a82ade7e0e1.
> sha1_position: convert do-while to while

- src/oid.h
The open-coded version was inherited from git.git. But it turns out it was based on an older version of glibc, whose memcmp was not very optimized.
Modern glibc does much better, and some compilers (like gcc 7) can even inline the memcmp into a series of multi-byte xors.
Upstream is switching to using memcmp in git/git@0b006014c87f400bd9a86267ed30fd3e7b383884.
Note that this is definitively faster on modern Linux systems, but there's been no benchmark on other platforms. It's possible that a bad libc/compiler combination may perform worse. In my opinion it's best to trust in memcmp by default, though. The current open-coded version was certainly did _not_ come from benchmarks on non-Linux systems.
> oid: use memcmp in git_oid__hashcmp

- src/ignore.c
- tests/attr/ignore.c
- tests/status/ignore.c
Ignore rules allow for reverting a previously ignored rule by prefixing
it with an exclamation mark. As such, a negative rule can only override
previously ignored files. While computing all ignore patterns, we try to
use this fact to optimize away some negative rules which do not override
any previous patterns, as they won't change the outcome anyway.
In some cases, though, this optimization causes us to get the actual
ignores wrong for some files. This may happen whenever the pattern
contains a wildcard, as we are unable to reason about whether a pattern
overrides a previous pattern in a sane way. This happens for example in
the case where a gitignore file contains "*.c" and "!src/*.c", where we
wouldn't un-ignore files inside of the "src/" subdirectory.
In this case, the first solution …
> Fix negative ignore rules with patterns

- src/common.h
- src/unix/posix.h
In commit a390a8464 (cmake: move defines into "features.h" header,
2017-07-01), we have introduced a new "features.h" header. This file is
being generated by the CMake build system based on how the libgit2 build
has been configured, replacing the preexisting method of simply setting
the defines inside of the CMake build system. This was done to help
splitting up the build instructions into multiple separate
subdirectories.
An overlooked shortcoming of this approach is that some projects making
use of libgit2 build the library with custom build systems, without
making use of CMake. For those users, the introduction of the
"features.h" file makes their life harder as they would have to also
generate this file.
Fix this issue by guarding all inclusions of the generated header file
by the …
> features.h: allow building without CMake-generated feature header

- src/push.c
If `fetch_spec` was a non-pattern, and it is not the first iteration of `push_status` vector, then `git_refspec_transform()` would result in the new value appended via `git_buf_puts` to the previous iteration value.
Forcibly clearing the buffer on each iteration to prevent this behavior.
> Clear the remote_ref_name buffer in git_push_update_tips()

- src/diff.c
After initializing the hash context in `git_diff_patchid`, we never
proceed to call `git_hash_ctx_cleanup` on it. While this doesn't really
matter on most hash implementations, this causes a memory leak on Win32
due to CNG system requiring a `malloc` call.
Fix the memory leak by always calling `git_hash_ctx_cleanup` before
exiting.
> diff: cleanup hash ctx in `git_diff_patchid`

- src/posix.h
- src/socket_stream.c
Similar to how O_CLOEXEC is used for `open()` libgit2 should also use SOCK_CLOEXEC (when available) for opening sockets.
> Use SOCK_CLOEXEC when creating sockets

- src/refs.c
- tests/refs/peel.c
If a reference stored inside of the packed-refs file does not directly
point to a commit object, it will always have a fully-peeled value
pointing to the underlying commit object. If we peel a reference to an
object, we will use that peeled value to speed up resolving the object.
This works as intended for all objects, except for annotated tags.
As a reference for an annotated tag does not directly point to the
commit but instead to the tag object, the packed-refs file will have an
accomodating fully-peeled object ID pointing to the commit of that tag.
When we use that fully-peeled OID pointing to that commit, though, we
obviously cannot peel that to the tag anymore.
Fix this issue by not using the fully-peeled OID whenever we want to
peel to a tag. Note that this does not include the …
> refs: do not use peeled OID if peeling to a tag

- include/git2/remote.h
I added a typedef for `push_update_reference` in `remote.h` to make the callback fit with other well defined callbacks. If this is inappropriate or there is some reason for not having a typedef, let me know.
> remote: add typedef to normalize push_update_reference callback

- src/curl_stream.c
- src/proxy.c
- src/proxy.h
I was trying to reproduce the segfault we see in Travis when talking to the proxy, but instead I found a few leaks.
> Plug some leaks in curl's proxy handling

- src/checkout.c
- tests/checkout/tree.c
When performing a forced checkout, treat files as modified when the workdir or the index is identical *except for the mode*.  This ensures that force checkout will update the mode to the target.
Without this change, we examine the contents of the file on-disk and determine that it's identical to the tree we're checking out, and continue without making any changes.  By including the filemode in the difference check, checkout will now make a file executable (or remove the executable bit) as appropriate to match the checkout target.
We apply this check for regular files only: in the case where one of the items was a file and the other item was *not*, then this would be a typechange (not a file mode change) and would be handled by other codepaths.
> Checkout typechange-only deltas

- tests/checkout/tree.c
Some minor improvements upon #4369.
> tests: checkout::tree: verify status entrycount changes on chmod

- src/transports/smart_protocol.c
When we setup the revision walk for negotiating references with a
remote, we iterate over all references, ignoring tags and symbolic
references. While skipping over symbolic references, we forget to free
the looked up reference, resulting in a memory leak when the next
iteration simply overwrites the variable.
Fix that issue by more clearly scoping the leaking variable to the loop
and freeing it after every iteration.
> transports: smart: fix memory leak when skipping symbolic refs

- src/CMakeLists.txt
CMake is unable to generate a correct Xcode project when trying to link
libraries with only object libraries as its input. As our new build
infrastructure makes heavy use of object libraries now, this affects our
libgit2 library target, as well, leading to linking errors.
Fix the issue by adding a dummy file to the libgit2 objects. As we
always have the "features.h" header ready which contains defines only,
we can simply link it into the resulting library without any effect
whatsoever. This fixes building with Xcode.
---
Thanks to @tiennou. This should fix #4352.
> cmake: fix linking in Xcode with object libraries only

- src/transports/ssh.c
When trying to decode the private key it looks like LibSSH2 returns a `LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED` when the passphrase is incorrect. This change allows callback to be called again giving the user the chance to correct the passphrase or provide alternative credentials.
Additionally, switched the indentation from spaces to tabs which matches the surrounding code.
> Ask for SSH credentials again when passphrase is wrong

- PROJECTS.md
- examples/log.c
Updated the `log` example to use the `--log-size` parameter.
> example-log: add support for --log-size

- CHANGELOG.md
- src/config_file.c
- tests/config/write.c
Some keys are presented in camelCase in the configuration, so users might want to write them as such in their tool. It can be confusing if we only ever write out the normalised versions of the keys as it differs from what they'd be writing if they had manually opened the file.
This now also matches the behaviour of `git config` when given the same inputs.
```shell
% git config -f foo sOMe.ThInG foo
% git config -f foo SomE.OtheR thing
% cat foo
[sOMe]
ThInG = foo
OtheR = thing
```
This covers the confusing aspect in #4390 which don't stem from the Git config spec.
> Preserve the input casing when writing config files

- .travis.yml
Getting the key from the MIT keyserver is surprisingly unreliable.
Try getting it from my website instead...
> travis: grab pgp key from www.edwardthomson.com

- appveyor.yml
- examples/network/common.c
- script/appveyor-mingw.sh
By default, CMake will not build our examples directory. As we do not
instruct either the MinGW or MSVC builds on AppVeyor to enable building
these examples, we cannot verify that those examples at least build on
Windows systems.
Fix that by passing `-DBUILD_EXAMPLES=ON` to AppVeyor's CMake
invocation.
> appveyor: build examples

- script/cibuild.sh
The macOS tests are by far the slowest right now. This attempts to remedy the
situation somewhat by asking clar to put its test data on a ramdisk.
> travis: put clar's sandbox in a ramdisk on macOS

- src/patch_parse.c
- tests/diff/parse.c
Our code parsing Git patch headers is rather lax in parsing headers of a
Git-style patch. Most notably, we do not care for the exact order in
which header lines appear and as such, we may parse patch files which
are not really valid after all. Furthermore, the state transitions
inside of the parser are not as obvious as they could be, making it
harder than required to follow its logic.
To improve upon this situation, this patch introduces a real state
machine to parse the patches. Instead of simply parsing each line
without caring for previous state and the exact ordering, we define a
set of states with their allowed transitions. This makes the patch
parser more strict in only allowing valid successions of header lines.
As the transition table is defined inside of a single structure with …
> patch_parse: implement state machine for parsing patch headers

- src/config_file.c
- src/config_parse.c
- src/config_parse.h
- src/diff_parse.c
- src/parse.c
- src/parse.h
- src/patch_parse.c
- src/patch_parse.h
This is a first attempt at pulling out the diff-header parser and unify its interface, such that it can be reused for other code parts. In this PR I did a PoC to replace the config file parser with this common parser code, which turns out to be quite promising in that it removes roughly 150 lines of code which are not required anymore.
There are two issues left with this PR, which is why I labeled it as WIP. First, there are some small-ish issues with proper indentation when writing config files, which I'll handle as soon as the second problem is solved. The second problem is with recursive include files, where the wrong structures are touched due to our faulty include handling. These things should be fixed by #4250.
As there are quite a lot of merge conflicts due to #4250, I'll stop …
> Common parser interface

- include/git2/types.h
- src/signature.c
- tests/commit/signature.c
Git considers '-0000' a valid offset for signature lines.  They need to
be treated as _not_ equal to a '+0000' signature offset.  Parsing a
signature line stores the offset in a signed integer which does not
distinguish between `+0` and `-0`.
This patch adds an additional flag `sign` to the `git_time` in the
`signature` object which is populated with the sign of the offset.  In
addition to exposing this information to the user, this information is
also used to compare signatures.
/cc @pks-t @ethomson
> signature: distinguish +0000 and -0000 UTC offsets

- tests/clar/print.h
motivation: (for someone new to the tests) it's puzzling to find the odd 'S' interspersed in the test output
proposed alternative test output (extract):
$ cmake --build . && ./libgit2_clar -srepo -v
...
Loaded 340 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
repo::config...
repo::discover..........
repo::env.
repo::getters...
repo::hashfile..
repo::head......................
repo::headtree....
repo::init.........................S
repo::message..
repo::new..
repo::open.............
repo::pathspec..........
repo::reservedname.....
repo::setters.....
repo::shallow....
repo::state.............
> add test status codes legend to the 'Started' test trace

- src/diff_generate.c
- src/diff_parse.c
- src/patch_generate.c
- src/patch_parse.c
- src/repository.c
- src/util.h
This should at least fix a huge swath of those new warnings in Travis. For now, I didn't care to fix the rest of them, and for most it is even impossible without rewriting our inheritance-structures. I mean we _could_ probably have e.g.
```
struct git_diff {
...
void *child_data;
};
struct git_diff_parsed {
struct git_diff base;
...
};
struct git_diff *git_diff_parsed_new(void)
{
struct git_diff_parsed *parsed = malloc(sizeof(*parsed));
parsed->base.child_data = parsed;
return &parsed->base;
}
```
But I guess it's not worth it at all.
---
Strict aliasing rules dictate that for most data types, you are not
allowed to cast them to another data type and then access the casted
pointers. While this works just fine for most compilers, technically we
end up in undefined behaviour when we hurt …
> refcount: make refcounting conform to aliasing rules

- CHANGELOG.md
- include/git2/diff.h
- src/diff_xdiff.c
We default to off, but we might want to consider changing `GIT_DIFF_NORMAL` to
include it.
This is a followup to #3944  that lets consumers of the library activate it.
> diff: expose the "indent heuristic" in the diff options

- README.md
- TROUBLESHOOTING.md
Some improvements for people who are getting started with libgit2, either as contributors or simply as users building the project.  First, we bring a quick start guide to (nearly) the top of the file, outlining prerequisites and the quick build instructions.  Next, change test guidance to `ctest -V`, since it has superior output for people getting started.  Also, drop the paragraph about running `cmake` from the Visual Studio command prompt since it is inaccurate.  Finally, introduce an easily-greppable `TROUBLESHOOTING.md` with resolution steps.
These were all direct feedback or resolutions from problems witnessed at today's hackathon.
> Getting started README improvements

- include/git2.h
I'm not sure if worktree.h was intentionally left out of git2.h. Looks like an oversight since it is in fact documented.
> Include git2/worktree.h in git2.h

- CONTRIBUTING.md
While we try to conform to a certain commit message style, this style
has never been documented anywhere. Document it such that new
contributors do not have to go through another needless iteration of
their pull requests just to fix up commit messages.
---
I know you both (@carlosmn, @ethomson) are not that worried about commit message style, but I've been asked where it is actually documented while doing a review. While it is fine to be a bit lenient, I still think we should at least have it documented such that new contributors have some hints and we can point to that.
> CONTRIBUTING: add documentation of our commit message style

- src/transports/winhttp.c
As recently discussed in Slack, this makes the WinHTTP transport use the same user-specified payload as the other transports.
> Use the same cert checking payload in WinHTTP

- src/diff.c
- src/diff_generate.c
The macro `DIFF_FLAG_SET` can be used to set or unset a flag by
modifying the diff's bitmask. While the case of setting the flag is
handled correctly, the case of unsetting the flag was not. Instead of
inverting the flags, we are inverting the value which is used to decide
whether we want to set or unset the bits.
The value being used here is a simple `bool` which is `false`. As that
is being uplifted to `int` when getting the bitwise-complement, we will
end up retaining all bits inside of the bitmask. As that's only ever
used to set `GIT_DIFF_IGNORE_CASE`, we were actually always ignoring
case for generated diffs.
Fix that by instead getting the bitwise-complement of `FLAG`, not `VAL`.
> diff_generate: fix unsetting diff flags

- src/streams/openssl.c
While the OpenSSL library provides all means to work safely in a
multi-threaded application, we fail to do so correctly. Quoting from
crypto_lock(3):
OpenSSL can safely be used in multi-threaded applications provided
that at least two callback functions are set, locking_function and
threadid_func.
We do in fact provide the means to set up the locking function via
`git_openssl_set_locking()`, where we initialize a set of locks by using
the POSIX threads API and set the correct callback function to lock and
unlock them.
But what we do not do is setting the `threadid_func` callback. This
function is being used to correctly locate thread-local data of the
OpenSSL library and should thus return per-thread identifiers. Digging
deeper into OpenSSL's documentation, the library does provide a …
> openssl: fix thread-safety on non-glibc POSIX systems

- include/git2/status.h
- src/status.c
- tests/status/worktree.c
This change takes `git_status_list_new` and splits out a new function called `git_status_list_new_at` (I'm totally open to alternative names) which takes a tree parameter to compare against instead of the HEAD tree.
The purpose of this is to get a preview of an amend commit, where the supplied tree will be from the head commit's first parent.
> Add git_status_file_at

- src/indexer.c
- tests/pack/indexer.c
This change ensures that the git_packfile_stream object in
git_indexer_append() does not leak when the stream has errors.
Found using libFuzzer.
> libFuzzer: Fix a git_packfile_stream leak

- src/indexer.c
- tests/pack/indexer.c
This change fixes an invalid memory access when the trailer is missing /
corrupt.
Found using libFuzzer.
> libFuzzer: Fix missing trailer crash

- src/diff_file.c
- tests/diff/blob.c
When initializing a `git_diff_file_content` from a source whose data is
derived from a blob, we simply assign the blob's pointer to the
resulting struct without incrementing its refcount. Thus, the structure
can only be used as long as the blob is kept alive by the caller.
Fix the issue by using `git_blob_dup` instead of a direct assignment.
This function will increment the refcount of the blob without allocating
new memory, so it does exactly what we want. As
`git_diff_file_content__unload` already frees the blob when
`GIT_DIFF_FLAG__FREE_BLOB` is set, we don't need to add new code
handling the free but only have to set that flag correctly.
> diff_file: properly refcount blobs when initializing file contents

- git.git-authors
Jonathan (@jonathantanmy) has given the ok via email to be listed here.
cc @peff @vmg @brianmario
> Add Jonathan Tan to git.git-authors

- CMakeLists.txt
- src/CMakeLists.txt
Instead of forcing iconv support on macOS (by forcing `USE_ICONV`
on), set the `OPTION`'s default to `ON` on macOS, leaving its default
_off_ on other platforms.
Although macOS includes iconv by default, some macOS users may have a
deficient installation for some reason and they should be provided a
workaround to use libgit2 even in this situation.
> cmake: let USE_ICONV be optional on macOS

- src/pack.c
The type of |base_offset| in get_delta_base() is `git_off_t`, which is a
signed `long`. That means that we need to make sure that the 8 most
significant bits are zero (instead of 7) to avoid an overflow when it is
shifted by 7 bits.
Found using libFuzzer.
> libFuzzer: Prevent a potential shift overflow

- src/streams/openssl.c
First commit adds more gotos for "simplicity" (sorry about that :wink:).
I happened to stumble onto the documentation while investigating something else. Per SSL_get_peer_certificate docs:
```
The reference count of the X509 object is incremented by one, so that
it will not be destroyed when the session containing the peer certificate
is freed. The X509 object must be explicitly freed using X509_free().
```
> Free OpenSSL peer certificate

- src/indexer.c
- src/pack.c
- tests/pack/indexer.c
If an element has been cached, but then the call to
packfile_unpack_compressed() fails, the very next thing that happens is
that its data is freed and then the element is not removed from the
cache, which frees the data again.
This change sets obj->data to NULL to avoid the double-free. It also
stops trying to resolve deltas after two continuous failed rounds of
resolution, and adds a test for this.
> Fix unpack double free

- src/patch_parse.c
- tests/patch/parse.c
- tests/patch/patch_common.h
This is split out from #4272 due to some problems with ambiguous parsing of patches with whitespace and custom prefixes. This should not be merged as-is but is only intended as a reminder.
---
The patch format allows unquoted path names even when the paths contain
whitespaces in between. To disambiguate the path names in thee header,
one can simply use the slash in "a/" respectively "b/", as no file is
allowed to contain a forward slash.
While this format is distinctly parseable, we fail to do so correctly.
To determine the path length, we simply search for the first whitespace
and assume it is the delimiter between "a/foo.file b/foo.file", which
works for the simple cases. Instead, we should be searching for the
first occurrence of either ' b/' (note the leading space) or '\n' to
either …
> patch_parse: fix parsing unquoted filenames with spaces

- src/fetchhead.c
- src/fileops.c
- src/fileops.h
- src/remote.c
- tests/fetchhead/nonetwork.c
The functions that write to FETCH_HEAD assume we only handle a single refspec at a time, which means we might fail to write part of the data that should be there, or we'll overwrite one refspec's information with another's.
> FETCH_HEAD and multiple refspecs

- src/hash/hash_common_crypto.h
- src/hash/hash_win32.c
- src/object.c
- src/object.h
- src/odb_loose.c
- src/util.c
- src/util.h
- src/zstream.c
- tests/core/string.c
- tests/odb/largefiles.c
As reported at https://github.com/libgit2/libgit2sharp/issues/1515, we are unable to inflate large loose blobs (that are larger than 4GB).  (In that issue, we create a large loose blob but fail to read it immediately after that.)  The culprit, of course, is 32 bitness: in a number of places we either improperly truncate 64 bit values via casting, or fail to read/write in a loop for APIs that take blocks of data, attempting to give them the entire blob at a time.
Fix this by:
* Move the loose object backend to use the `git_zstream` API instead of using zlib directly.  The `git_zstream` API simplifies the common inflate or deflate experience and helps eliminate common problems like neglecting to loop to process the entire file.
* Update the win32 and CommonCrypto hash backends to loop over …
> Inflate large loose blobs

- src/iterator.c
- src/iterator.h
- src/refdb_fs.c
- tests/refs/iterator.c
When enumerating the references in the loose refs storage area, we should traverse symlinked directories.  eg, if I create `refs/heads/foo` -> `/tmp/refs`, and create a loose ref `/tmp/refs/asdf`, then I should be able to resolve `refs/heads/foo/asdf`.
This is @doanac's change in #4388, with some minor cleanups for error checking and adding a test to easily validate this locally.  I'm opening a PR to put it through the paces on the CI machines.
> refs: traverse symlinked directories

- src/pack-objects.c
- src/push.c
- src/transports/local.c
I have an application that uses LibGit2Sharp, and it's been having performance issues.  One thing I discovered during the investigation is that when doing a fetch using the local transport, it creates a packfile with a copy of the entire repository instead of just the deltas.  I think this is the same issue as #3932.  
The first commit attempts to address that by calling `git_revwalk_hide` on all local references.  
I also tested doing a push in the opposite direction, and saw similar issues where too many objects were sent.  In the second commit, I replaced the complex diffing in the push code with a call to `git_packbuilder_insert_walk`, and it seems to give better results with less code.  Looking through the issue history, I think this may be the change @carlosmn suggested in #2972, …
> Transfer fewer objects on push and local fetch

- include/git2/notes.h
- src/notes.c
- tests/notes/notes.c
Hi!
This is a work in progress implementation to solve issue #3782 
each new function will be added in a separate commit.
Finally existing notes functions will be reimplemented in terms of the new functions.
I'm opening this now in case anyone has any suggestions in the early stages
that will allow me to avoid rework later on.
Thanks,
Richard Ipsum
> Support using notes via a commit rather than a ref

- src/tree.c
Our standard error messages begin with a lower case letter so that they
can be prefixed or embedded nicely.
These error messages were missed during the standardization pass since
they use the `tree_error` helper function.
> tree: standard error messages are lowercase

- include/git2/tree.h
The documentation for `git_treebuilder_insert` erroneously states that
we do not validate that the entry being inserted exists.  We do, as of
https://github.com/libgit2/libgit2/pull/3633.  Update the documentation
to reflect the new reality.
> docs: git_treebuilder_insert validates entries

- src/CMakeLists.txt
Otherwise Xcode will happily not-link our git2 target, resulting in a "missing file" error when building eg. examples
> cmake: create a dummy file for Xcode

- src/diff.h
- src/diff_driver.c
- src/diff_driver.h
- src/diff_file.c
- src/diff_generate.c
When generating a diff between two trees, for each file that is to be
diffed we have to determine whether it shall be treated as text or as
binary files. While git has heuristics to determine which kind of diff
to generate, users can also that default behaviour by setting or
unsetting the 'diff' attribute for specific files.
Because of that, we have to query gitattributes in order to determine
how to diff the current files. Instead of hitting the '.gitattributes'
file every time we need to query an attribute, which can get expensive
especially on networked file systems, we try to cache them instead. This
works perfectly fine for every '.gitattributes' file that is found, but
we hit cache invalidation problems when we determine that an attribuse
file is _not_ existing. We do create an …
> diff_generate: avoid excessive stats of .gitattribute files

- src/hash/hash_openssl.h
- src/streams/openssl.c
The OpenSSL functions `SHA1_Init`, `SHA1_Update` and `SHA1_Final` all
return 1 for success and 0 otherwise, but we never check their return
values. Do so.
> hash: openssl: check return values of SHA1_* functions

- .travis.yml
I would like to host the trusty dependencies in an Azure Web App - currently I'm hosting them on a linux VM in Azure.  This is a lower-cost option that hurts my pocketbook less.
> travis: fetch trusty dependencies from Bintray

- include/git2/refs.h
- src/transports/local.c
- tests/network/fetchlocal.c
- tests/refs/iterator.c
Two fixes for memory leaks highlighted by AppVeyor.
> Memory leaks

- include/git2/message.h
We used to hard-code the octothorpe as the comment character and the
documentation still mentions this even though we accept the comment character as
a parameter.
Update the line to indicate this and clean up the first paragraph a bit.
> message: update docs for git_message_prettify

- src/refs.h
This lets git know that we do in fact have written our packed-refs file
sorted (which is apparently not necessarily the case) and it can then use the
new-ish mmaped access which lets it avoid significant amounts of effort parsing
potentially large files to get to a single piece of data.
> refs: include " sorted " in our packed-refs header

- src/branch.c
Since a625b092c (branch: correctly reject refs/heads/{-dash,HEAD},
2017-11-14), which is included in v2.16.0, upstream git refuses to
create branches which are named HEAD to avoid ambiguity with the
symbolic HEAD reference. Adjust our own code to match that behaviour and
reject creating branches names HEAD.
> branch: refuse creating branches named 'HEAD'

- src/odb.c
- src/tree.c
- tests/object/tree/write.c
- tests/odb/backend/simple.c
I've been triggered by the not-so-recent discussion in upstream git.git around null OIDs (see [1]) to implement some defensive mechanisms about ever reading or writing null OIDs either via the ODB layer or into trees. For the ODB part, I now reject writing and shorcut reading null OIDs while for trees I've only implemented the rejection on inserting entries into the treebuilder. So I've not changed the reading part for our trees.
[1]: https://marc.info/?l=git&m=151120958313567&w=2
> Special-casing null OIDs

- tests/status/renames.c
Update the status::renames test to create an NFD format filename in the `core.precomposedunicode` tests.
Previously, we would create an NFC format filename.  This was to take advantage of HFS+ filesystems, which always use canonically decomposed formats, and would actually write the filename to disk as an NFD filename.  So previously, we could create an NFC filename, but read it normally as an NFD filename.
But APFS formats do not force canonically decomposed formats for filenames, so creating an NFC filename does not get converted to NFD.  Instead, the filename will be written in NFC format.  Our test, therefore, does not work - when we write an NFC filename, it will _remain_ NFC.
Update the test to write NFD always.  This will ensure that the file will actually be canonically decomposed …
> status::renames: test update for APFS (write NFD instead of NFC filename)

- CHANGELOG.md
- include/git2/merge.h
- src/merge.c
- src/merge_file.c
- tests/merge/conflict_data.h
- tests/merge/trees/recursive.c
- tests/merge/workdir/recursive.c
When producing a virtual merge base during a recursive merge (because our branches have multiple merge bases from a criss-cross merge), our merge base may contain conflicts.
[Git updated their virtual merge base building to use 9 character conflict markers](https://github.com/git/git/commit/d694a17986a28bbc19e2a6c32404ca24572e400f), which allows users (and programs like `rerere`) to better identify conflicts that occur in the virtual merge base vs conflicts that occur in the actual merge.
> Use longer conflict markers in recursive merge base

- src/iterator.c
This should have been part of PR #3638 (for issue #3635). Without this, we still get nsec-related errors, even when using -DGIT_USE_NSEC:
`error: ‘struct stat’ has no member named ‘st_mtime_nsec’`
> Honor 'GIT_USE_NSEC' option in `filesystem_iterator_set_current`

- src/attr.c
- src/ignore.c
Depending on whether the path we want to look up an attribute for is a
file or a directory, the fnmatch function will be called with different
flags. Because of this, we have to first stat(3) the path to determine
whether it is a file or directory in `git_attr_path__init`. This is
wasteful though in bare repositories, where we can already be assured
that the path will never exist at all due to there being no worktree. In
this case, we will execute an unnecessary syscall, which might be
noticeable on networked file systems.
What happens right now is that we always pass the `GIT_DIR_FLAG_UNKOWN`
flag to `git_attr_path__init`, which causes it to `stat` the file itself
to determine its type. As it is calling `git_path_isdir` on the path,
which will always return `false` in case the path does …
> attr: avoid stat'ting files for bare repositories

- src/common.h
- src/xdiff/xdiff.h
- src/xdiff/xdiffi.c
- src/xdiff/xdiffi.h
- src/xdiff/xemit.c
- src/xdiff/xemit.h
- src/xdiff/xhistogram.c
- src/xdiff/xinclude.h
- src/xdiff/xmacros.h
- src/xdiff/xmerge.c
- src/xdiff/xpatience.c
- src/xdiff/xprepare.c
- src/xdiff/xprepare.h
- src/xdiff/xtypes.h
- src/xdiff/xutils.c
- src/xdiff/xutils.h
- tests/merge/files.c
[Git has updated xdiff](https://github.com/git/git/commit/86efa215276aaeaef0c556c73f1993b6f36dcf91) to produce conflict markers that match the EOL style in the conflicting files.  This means that if you have checked in CR/LF files into your repository, and perform a merge, you will now get a conflict file that _also_ has CR/LF line endings.  🎉 
Update our xdiff to match theirs, to give us this same functionality, and add some unit tests to ensure that it works.
> Conflict markers should match EOL style in conflicting files

- include/git2/odb.h
- include/git2/sys/odb_backend.h
- src/odb.c
- src/odb_loose.c
- src/zstream.c
- src/zstream.h
- tests/odb/largefiles.c
- tests/odb/loose.c
Change the streaming reader API a bit, to provide the type and length of the object when initializing the stream. This would be a breaking API change - except, of course, that nobody is actually using the streaming reader API since none of the backends support it. So I feel pretty good breaking this API that nobody could be using.
Add streaming reader support to the loose object ODB backend. I cleaned up a bit while I was in there to add some more tests for things like read_header which had no explicit tests (and in fact failed on some of the loose ODB test corpus), teach read_header how to cope with "packlike loose objects" (which were a weird loose object format that was attempted for a bit and will never actually be seen in the wild) and drop the odb_loose internal zstream abstraction …
> Streaming read support for the loose ODB backend

- src/hash/hash_win32.c
- src/indexer.c
- src/odb.c
- src/odb.h
- src/odb_loose.c
- tests/odb/largefiles.c
At the moment, we're swallowing the allocation failure.  We need to return the error to the caller.  (See analysis in #4470.)
> odb: error when we can't alloc an object

- src/transports/http.c
- src/transports/http.h
- src/transports/winhttp.c
The winhttp and posix http each need to add the user-agent to their requests.  Standardize on a single function to include this so that we do not get the version numbers we're sending out of sync.
Currently we send `git/2.0 (libgit2 something)` on non-Windows and `git/1.0 (libgit2 something)` on Windows.  :(
> http: standardize user-agent addition

- docs/relase.md
This should provide the release manager enough to know which steps to take when
it's time to cut a new release.
> docs: add release documentation

- src/index.c
- tests/index/filemodes.c
Ensure that the buffer given to `git_index_add_frombuffer` represents a regular blob, an executable blob, or a link.  Explicitly reject commit entries (submodules) - it makes little sense to allow users to add a submodule from a string; there's no possible path to success.
> git_index_add_frombuffer: only accept files/links

- tests/index/filemodes.c
The new index entry structure was not being initialized to all-zeroes.
As that structure is used to add a new entry to the current index, and
the hashing algorithm of the index making use of the uninitialized flags
to calculate the state, we might miscompute the hash of the entry and
add it at the wrong position. Later lookups would then fail.
Initialize the structure with `memset` to fix the test breaking on some
platforms.
> tests: index::filemodes: fix use of uninitialized memory

- src/checkout.c
- tests/checkout/head.c
When checking out a file, we determine whether the baseline (what we expect to be in the working directory) actually matches the contents of the working directory.  This is safe behavior to prevent us from overwriting changes in the working directory.
We look at the index to optimize this test: if we know that the index matches the working directory, then we can simply look at the index data compared to the baseline.
We have historically compared the baseline to the index entry by oid.  However, we must also compare the mode of the two items to ensure that they are identical.  Otherwise, we will refuse to update the working directory for a mode change.
Update this behavior and include a test to validate the behavior.
> checkout: when examining index (instead of workdir), also examine mode

- .travis.yml
Use a custom libssh package that is a backport of libssh2 1.8.0 to Ubuntu trusty.
> travis: use custom libssh2 package

- .travis.yml
To avoid pull requests needing to rebase, keep the libssh2-1-dev
package as the development package for libssh2.  Reverting to the
original Debian package structure.
> travis: use custom libssh2-1-dev package

- src/ignore.c
We presently fail to build on win32 when `STDCALL=ON`, which is what LibGit2Sharp uses.  At present, we're trying to assign a `__cdecl` function to a `__stdcall` declared function pointer.
The win32 C library is compiled cdecl, however when configured with `STDCALL=ON`, our functions (and function pointers) will use the stdcall calling convention.  You cannot set a `__stdcall` function pointer to a `__cdecl` function, so it's easier to just use our `git__strncmp` instead of sorting that mess out.
> win32: strncmp -> git__strncmp for win32 STDCALL

- tests/object/tree/write.c
Instead of laving it uninitialized and relying on luck for it to be non-zero,
let's give it a dummy hash so we make valgrind happy (in this case the hash
comes from `sha1sum </dev/null`.
This is just in the test so it's not _that_ important, but it'd be good to release with a clean valgrind output.
/cc @ethomson @pks-t this should go in before the release
> tree: initialize the id we use for testing submodule insertions

- src/global.c
- src/streams/curl.c
- src/streams/curl.h
The documentation of curl states that any program making use of libcurl
is responsible for calling `curl_global_init` previous to using any
curl functions, and `curl_global_cleanup` when the program is about to
terminate. We currently call neither. While this seems to work just
fine, Valgrind may complain about unfree'd memory.
Fix the issue by correctly setting up and tearing down libcurl.
---
Edit for the corrected reasoning behind this PR:
Our curl-based streams make use of the easy curl interface. This
interface automatically initializes and de-initializes the global curl
state by calling out to `curl_global_init` and `curl_global_cleanup`.
Thus, all global state will be repeatedly re-initialized when creating
multiple curl streams in succession. Despite being inefficient, this is
not …
> curl: initialize and cleanup global curl state

- src/config_file.c
As discussed in #4551 we were cowboying it up with the casts which meant we were passing in nonsense values for levels and reading unallocated memory for the repository pointer.
This fixes that and hardens the code a bit by casting to the common structure rather than the one for the live object.
/cc @tiennou 
//c @ethomson @pks-t this should go in before the release
> Cast less blindly between configuration objects

- deps/zlib/adler32.c
- deps/zlib/crc32.c
- deps/zlib/deflate.c
- deps/zlib/deflate.h
- deps/zlib/gzguts.h
- deps/zlib/infback.c
- deps/zlib/inffast.c
- deps/zlib/inflate.c
- deps/zlib/inflate.h
- deps/zlib/inftrees.c
- deps/zlib/trees.c
- deps/zlib/zconf.h
- deps/zlib/zlib.h
- deps/zlib/zutil.c
- deps/zlib/zutil.h
The current version of zlib bundled with libgit2 is version 1.2.8. This
version has several CVEs assigned:
- CVE-2016-9843
- CVE-2016-9841
- CVE-2016-9842
- CVE-2016-9840
Upgrade the bundled version to the current release 1.2.11, which has
these vulnerabilities fixes.
> deps: upgrade embedded zlib to version 1.2.11

- CMakeLists.txt
- include/git2/diff.h
This fixes a problem where we're potentially left shifting a signed number too far. Observed with the SUNPro compiler on Solaris:
```"deps/libgit2/include/git2/diff.h", line 214: warning: integer overflow detected: op "<<" (E_INTEGER_OVERFLOW_DETECTED)```
It also enables the warning to trap it if supported.
> Integer overflow

- src/index.c
This is the security fix regarding reading of the compressed index entries forward-ported to the master branch.
> Index parsing fixes

- include/git2/pathspec.h
By placing docs per enum value rather than in a large block,
the automated doc generation tool can make nicer docs,
as could other automated tools, such as
the mooted https://github.com/libgit2/git2go/issues/427.
The current rendering is somewhat ugly:
https://libgit2.github.com/libgit2/#HEAD/type/git_pathspec_flag_t
No textual changes, just reorganization.
> pathspec: improve git_pathspec_flag_t doc rendering

- tests/online/clone.c
At present, we have three online tests against bitbucket: one which
specifies the credentials in the payload, one which specifies the
correct credentials in the URL and a final one that specifies the
incorrect credentials in the URL.  Bitbucket has begun responding to the
latter test with a 403, which causes us to fail.
Break these three tests into separate tests so that we can skip the
latter until this is resolved on Bitbucket's end or until we can change
the test to a different provider.
> online::clone: skip creds fallback test

- src/buffer.c
- src/buffer.h
- src/netops.c
- src/netops.h
- src/transports/ssh.c
- tests/buf/percent.c
- tests/transport/register.c
`gitno_extract_url_parts` seems a little deficient in a few ways:
* This moves percent decoding into `git_buf`s.  This lets the SSH transport avoid an unnecessary small, temporary `malloc`.
* Now `gitno_extract_url_parts` uses the same buffer-based decoding
* Percent decode usernames even when passwords are not provided
* Percent decode hostnames, per RFC 3986
This builds on #4557.
> Refactor `gitno_extract_url_parts`

- tests/online/clone.c
Update the settings to use a specific read-only token for accessing our test repositories in Bitbucket.
> online tests: update auth for bitbucket test

- src/odb.c
- tests/odb/backend/mempack.c
In commit 7ec7aa4 (odb: assert on logic errors when writing objects,
2018-02-01), the check for whether we are trying to overflowing the fake
stream buffer was changed from returning an error to raising an assert.
The conversion forgot though that the logic around `assert`s are
basically inverted. Previously, if the statement
stream->written + len > steram->size
evaluated to true, we would return a `-1`. Now we are asserting that
this statement is true, and in case it is not we will raise an error. So
the conversion to the `assert` in fact changed the behaviour to the
complete opposite intention.
Fix the assert by inverting its condition again and add a regression
test.
---
/cc @ethomson
> odb: fix writing to fake write streams

- include/git2/types.h
`git_merge_result` is currently unused in the codebase and generates a blank page in the [documentation](https://libgit2.github.com/libgit2/#HEAD/type/git_merge_result).
Not sure if this type had a use at one point, but it doesn't seem to now so I figured I would remove it.
> types: remove unused git_merge_result

- src/odb_mempack.c
When a ODB mempack gets free'd, we take no measures at all to free its
contents, most notably the objects added to the database, resulting in a
memory leak. Call `git_mempack_reset` previous to freeing the ODB
structures themselves, which takes care of releasing all associated
data structures.
> odb: mempack: fix leaking objects when freeing mempacks

- src/submodule.c
- tests/submodule/add.c
This is to fix an issue where libgit2 will allow you to add a submodule even if the path you are trying add is found on the index. In the CLI we get a nice error about this, but not in libgit2.
I would obviously like some pointers on how to do this, as I do not think it is 100% correct. For one, when I add the trailing slash to the path, I feel like I could clean that up or have a better implementation. I am also unsure if there is a more streamlined routine to check the index for the path.
Some advice on how I could clean this up would be awesome.
> submodule: check index for path and prefix before adding submodule

- src/hash/sha1dc/sha1.c
This updates the version of SHA1DC to c3e1304ea3.
> sha1dc: update to fix errors with endianess

- appveyor.yml
- src/util.c
Our CI builds have intermittent failures in our online tests, e.g. with
the message "A provided buffer was too small". This is not a programming
error in libgit2 but rather an error in the SChannel component of
Windows. Under certain circumstances involving Diffie-Hellman key
exchange, SChannel is unable to correctly handle input from the server.
This bug has already been fixed in recent patches for Windows 10 and
Windows Server 2016, but they are not yet available for AppVeyor.
Manually pamper over that issue by disabling all ciphersuites using DHE
via the registry. While this disables more ciphers than necessary, we
really don't care for that at all but just want to avoid build failures
due to that bug.
See [1], [2] or [3] for additional information.
1: aws/aws-sdk-cpp#671
2: …
> appveyor: workaround for intermittent test failures

- src/streams/openssl.c
- src/streams/openssl.h
LibreSSL 2.7 adds OpenSSL 1.1 API
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>
> Fix build with LibreSSL 2.7

- appveyor.yml
Commit 723e1e976 (appveyor: disable DHE to avoid spurious failures,
2018-03-29) added a workaround to fix spurious test failures due to a
bug in Windows' SChannel implementation. The workaround only worked by
accident, though, as the registry key was in fact mistyped. Fix the
typo.
---
Sure enough #4603 succeeded three times in a row but failed as soon as I merged it to master.
> appveyor: fix typo in registry key to disable DHE

- src/diff_print.c
- tests/checkout/typechange.c
- tests/diff/stats.c
This adds the 'T' status character to git_diff_status_char() for diff entries that change type.
@ethomson This follows from our Slack chat earlier today.
> diff: Add missing GIT_DELTA_TYPECHANGE -> 'T' mapping.

- include/git2/describe.h
Both `git_describe_options` and `git_describe_formatting_options` are sanitized before they are actually used. They should be noted as being optional in the documentation.
https://github.com/libgit2/libgit2/blob/5585e358b2a240ca8ed65a00008dbc865a1381c1/src/describe.c#L641-L654
https://github.com/libgit2/libgit2/blob/5585e358b2a240ca8ed65a00008dbc865a1381c1/src/describe.c#L767-L778
> Flag options in describe.h as being optional

- src/transports/local.c
- tests/fetchhead/nonetwork.c
When fetching into a repository which has symbolic references via the
"local" transport we run into an assert. The assert is being triggered
while we negotiate the packfile between the two repositories. When
hiding known revisions from the packbuilder revwalk, we unconditionally
hide all references of the local refdb. In case one of these references
is a symbolic reference, though, this means we're trying to hide a
`NULL` OID, which triggers the assert.
Fix the issue by only hiding OID references from the revwalk. Add a test
to catch this issue in the future.
> transports: local: fix assert when fetching into repo with symrefs

- src/attr_file.c
- src/ignore.c
- tests/attr/ignore.c
When comparing whether a path matches a directory rule, we pass the
both the path and directory name to `fnmatch` with
`GIT_ATTR_FNMATCH_DIRECTORY` being set. `fnmatch` expects the pattern to
contain no trailing directory '/', which is why we try to always strip
patterns of trailing slashes. We do not handle that case correctly
though when the pattern itself has trailing spaces, causing the match to
fail.
Fix the issue by stripping trailing spaces and tabs for a rule previous
to checking whether the pattern is a directory pattern with a trailing
'/'. Add a test to catch future breakage.
> attr_file: fix handling of directory patterns with trailing spaces

- src/transports/ssh.c
The function `ssh_stream_free` takes over the responsibility of closing
channels and streams just before freeing their memory, but it does not
do so for the session. In fact, we never disconnect the session
ourselves at all, as libssh2 will not do so itself upon freeing the
structure. Quoting the documentation of `libssh2_session_free`:
> Frees all resources associated with a session instance. Typically
> called after libssh2_session_disconnect_ex,
The missing disconnect probably stems from a misunderstanding what it
actually does. As we are already closing the TCP socket ourselves, the
assumption was that no additional disconnect is required. But calling
`libssh2_session_disconnect` will notify the server that we are cleanly
closing the connection, such that the server can free his own …
>  transports: ssh: disconnect session before freeing it 

- tests/online/clone.c
Validate using the http://user:pass@host/ format in HTTP_PROXY and HTTPS_PROXY environment variables.
Note that we don't actually have a way to ensure that our proxy was contacted.  So this test would pass even if there was a code error that meant that requests went direct to the server, bypassing the proxy.
I certainly don't have a proxy-neutral way to enforce that, offhand...  I guess we could expose and endpoint in the remote code that will get headers back, and we could see if a `Via` is set.  That would probably be effective, but sort of ugh, and assumes that some transparent proxy doesn't add a `Via` header itself.
> online::clone: validate user:pass in HTTP_PROXY

- src/transports/smart.h
- src/transports/smart_protocol.c
This is extracted from my WIP shallow/smart-transport branch (a.k.a. shallow clones).
I was very confused by the "error handling" around that function, so hopefully this makes it clearer.
> Typedef git_pkt_type and clarify recv_pkt return type

- src/submodule.c
- tests/submodule/lookup.c
Issue mentioned in issue #4517 and issue #4516.
Git for Windows does report parse errors in `.gitmodules`, so should libgit2.
> Submodules-API should report .gitmodules parse errors instead of ignoring them

- src/refs.c
- src/refs.h
- tests/refs/dup.c
- tests/worktree/repository.c
This fixes a segfault in `git_reference_owner` on references returned from `git_reference__read_head` and `git_reference_dup` ones.
> refs: preserve the owning refdb when duping reference

- include/git2/worktree.h
- src/worktree.c
- tests/worktree/worktree.c
Currently, we always create a new branch after the new worktree's name
when creating a worktree. In some workflows, though, the caller may want
to check out an already existing reference instead of creating a new
one, which is impossible to do right now.
Add a new option `ref` to the options structure for adding worktrees. In
case it is set, a branch and not already checked out by another
worktree, we will re-use this reference instead of creating a new one.
> worktree: add ability to create worktree with pre-existing branch

- script/backport.sh
This adds a simple script for backporting pull requests to older
branches. It accepts as parameters a list of pull request numbers which
whose commits are to be cherry-picked. The identification of PRs
currently happens by using the commit message of the merge of the PR,
which should conform to the message "Merge pull request #<PR>".
While the heuristic works in practice, we could instead also use the
direct references from GitHub via "pull/#<PR>/head". This requires the
user to have all these references fetched, though, so we can just use
the current heuristic until we experience any issues with that.
---
Dunno if we want this. I've used this script to create #4475, and I think a bit of automation is nice to have.
> scripts: add backporting script

- src/refdb_fs.c
- tests/worktree/reflog.c
Wrong reflog for `HEAD` is read for worktree.
Fixes issue #4566.
> worktree: Read worktree specific reflog for HEAD

- src/refspec.c
- tests/worktree/worktree.c
The rest of the Valgrind + some Coverity fixes against master.
> Fix leaks in master

- src/blame_git.c
Since blame has been imported from git.git and had its first share of
refactorings in b6f60a4d9 (Clean up ported code, 2013-09-21), the code
is actually not doing the coalescing step of the generated blame. While
the code to do the coalescing does exist, it is never being called as
the function `git_blame__like_git` will directly return from its `while
(true)` loop.
The function that was being imported from git.git was the `assign_blame`
function from "builtin/blame.c" from 717d1462b (git-blame --incremental,
2007-01-28), which hasn't really changed much. Upon taking an initial
look, one can seet hat `coalesce` is actually never getting called in
`assign_blame`, as well, so one may assume that not calling `coalesce`
by accident is actually the right thing. But it is not, as `coalesce` is …
> blame_git: fix coalescing step never being executed

- include/git2/config.h
- src/config_file.c
- tests/config/read.c
I've finally pulled myself together and tackled my itch of iterating through configuration entries in the order they appear in the file. At first, I started getting annoyed again by the unnecessarily complex config file code, so I preceded the actual logic by quite a lot of refactoring and renaming of structures and functions. The result is actually very pleasant: while maintaining a second data structure alongside the map of entries, this PR still has more deletions than additions. So I definitly think that this PR helps a whole lot regarding readability.
> Configuration entry iteration in order

- src/refdb_fs.c
- tests/worktree/refs.c
libgit2 fails to delete an unrelated branch on the worktree.
Cross-ref: https://gitlab.com/tortoisegit/tortoisegit/issues/3202
> Fix deletion of unrelated branch on worktree

- include/git2/worktree.h
- src/worktree.c
- src/worktree.h
- tests/clar/sandbox.h
- tests/worktree/worktree.c
This is a reworking of my [previous PR](https://github.com/libgit2/libgit2/pull/4639) to clean up some commit history
This adds two new functions:
* `git_worktree_name` - retrieves the name from a `git_worktree` 
* `git_worktree_path` - retrieves the location on the file system from a `git_worktree`
> worktree:  add functions to get name and path

- examples/ls-files.c
Added an example to mimic `git ls-files` using the libgit2 library. It also supports the `--error-unmatch` parameter to determine if the specified paths are in the index. This will hopefully be a useful example for new libgit2 users.
> examples: ls-files: add ls-files to list paths in the index

- src/diff_xdiff.c
- src/util.c
- src/util.h
- tests/diff/patch.c
The diff driver truncates the hunk header text to 80 bytes, which
can  cut off 4-byte Unicode characters and introduce garbage characters in the
diff output. This change sanitizes the hunk header before it is displayed.
This is consistent with what git does: https://github.com/git/git/blob/e3a80781f5932f5fea12a49eb06f3ade4ed8945c/diff.c#L1927-L1941
Closes https://github.com/libgit2/rugged/issues/716
> Sanitize the hunk header to ensure it contains UTF-8 valid data

- src/repository.c
- src/worktree.c
- tests/worktree/worktree.c
Supersedes #4628, fixes #4626.
It fixes the issue by globally disabling the check in `ensure_not_bare` when working against a "worktree repo". I haven't given any thought to what this actually can provoke.
My gut feeling says it's not clean enough, as I don't like :
- all those remaining `repo->is_bare` tests which might now not work against a "worktree repo".
- you can have bare repo (`git_repository_is_bare = true`) with a workdir, since the bare-ness of the parent repo percolates down to the worktree repoes.
Maybe renaming `ensure_not_bare` to `ensure_has_workdir` and using that everywhere ? I'm unsure about the 2nd point though. Opinions, as always, welcome.
> Worktrees can be made from bare repositories

- src/streams/openssl.c
- tests/iterator/workdir.c
- tests/refs/normalize.c
Fixes required to build with -DENABLE_WERROR=ON and GCC 8.1
> Fix GCC 8.1 warnings

- src/global.c
Our global initialization functions `git_libgit2_init()` and
`git_libgit2_shutdown()` both adjust a global init counter to determine
whether we are the first respectively last user of libgit2. On
Unix-systems do not do so under lock, though, which opens the
possibility of a race between these two functions:
Thread 1                            Thread 2
git__n_inits = 0;
git_libgit2_init();
git_atomic_inc(&git__n_inits);
/* git__n_inits == 1 */
git_libgit2_shutdown();
if (git_atomic_dec(&git__n_inits) != 0)
/* git__n_inits == 0, no early exit here */
pthread_mutex_lock(&_init_mutex);
shutdown_common();
pthread_mutex_unlock(&_init_mutex);
pthread_mutex_lock(&_init_mutex);
init_once();
pthread_mutex_unlock(&_init_mutex);
So we can end up in a situation where we try to shutdown shared data …
> global: adjust init count under lock

- src/refdb_fs.c
This patch-set addresses the performance of reference iteration with a glob specified. The enhancement is specific to FS-based repositories.
libgit2 provides facilities for iterating over references of a repository. The references may be filtered using a glob, e.g. using an iterator created via `git_reference_iterator_glob_new()`. At least for FS-based repositories, all references are visited during the iteration and each of the references encountered is matches against the glob. For the general case, this is the only option.
However, a glob may also start with a literal path. In this case, we may scan only the corresponding subdirectory of `refs` rather than the entire reference space. The cost of this optimization is a single scan of the glob.
Targets #4619.
TODO:
> refdb_fs: enhance performance of globbing

- src/streams/openssl.c
The `CRYPTO_THREADID` type is no longer available in OpenSSL ≥ 1.1.0 with deprecated features disabled, and causes build failures. Since the `threadid_cb()` function is only ever called by `git_openssl_set_locking()` when `defined(OPENSSL_LEGACY_API)`, only define it then.
> streams: openssl: add missing check on OPENSSL_LEGACY_API

- api.docurium
- include/git2/attr.h
- include/git2/blame.h
- include/git2/branch.h
- include/git2/checkout.h
- include/git2/cherrypick.h
- include/git2/clone.h
- include/git2/describe.h
- include/git2/diff.h
- include/git2/merge.h
- include/git2/proxy.h
- include/git2/rebase.h
- include/git2/remote.h
- include/git2/repository.h
- include/git2/revert.h
- include/git2/stash.h
- include/git2/status.h
- include/git2/submodule.h
- include/git2/sys/index.h
- include/git2/sys/mempack.h
- include/git2/sys/merge.h
- include/git2/transaction.h
- include/git2/types.h
- include/git2/worktree.h
The first commit makes `git_oid` & `git_buf` "globally" visible (ie. less likely to be forgotten) by including them from `types.h`. If that's not really appropriate, it could be fixed more precisely by going through each error from [this script](https://gist.github.com/tiennou/fcdf9967894c5671c8c5c716405de52d).
Apart from a typechange (see `worktree:` commit), the rest is minor fixups + missing documentation.
Fixes #4213, #4495, maybe #4492.
> Fix docurium missing includes

- src/submodule.c
- tests/submodule/lookup.c
We currently have a memory leak in AppVeyor wrt handling submodules. The issue is that we're accepting duplicated submodules for the same path, silently updating an already existing key in the submodule names hash map and leaking its previous value. Git does not allow for duplicated submodule paths, so we shouldn't either.
> Detect duplicated submodules for the same path

- tests/submodule/lookup.c
The test submodule::lookup::duplicated_path, which tries to verify that
we detect submodules with duplicated paths, currently relies on the
gitmodules file of "submod2_target". While this file has two gitmodules
with the same path, one of these gitmodules has an empty name and thus
does not pass `git_submodule_name_is_valid`. Because of this, the test
is in fact dependent on the iteration order in which we process the
submodules. In fact the "valid" submodule comes first, the "invalid"
submodule will cause the desired error. In fact the "invalid" submodule
comes first, it will be skipped due to its name being invalid, and we
will not see the desired error. While this works on the master branch
just right due to the refactoring of our config code, where iteration
order is now …
> tests: submodule: do not rely on config iteration order

- src/refdb_fs.c
- tests/refs/foreachglob.c
> refdb_fs: fix regression: failure when globbing for non-existant references

- CHANGELOG.md
- include/git2/common.h
- include/git2/sys/alloc.h
- src/alloc.c
- src/alloc.h
- src/global.c
- src/settings.c
- src/stdalloc.c
- src/stdalloc.h
- src/util.h
- src/win32/w32_crtdbg_stacktrace.c
- src/win32/w32_crtdbg_stacktrace.h
- tests/trace/windows/stacktrace.c
This is an RFC regarding custom memory allocators. Existing standard allocators are being renamed to `git__stdalloc__<fn>`. By default, our usual allocators `git__<fn>` are being defined to `git__stdalloc__<fn>`. For CRTDBG, our allocators `git__<fn>` are being defined to `git__crtdbg__<fn>`.
If the CMake option "PLUGGABLE_ALLOCATORS" is set, we use an indirection. Instead of using typedefs, each of our allocator functions is not a define but instead a function pointer, which is by default set to the respecfive `git__stdalloc__<fn>` function. Our `git_libgit2_opts` function is extended by "GIT_OPT_SET_ALLOCATOR, which receives as argument a `git_allocator` structure. Its members will then be used to change the function pointers.
I don't know whether we really need to distinguish between …
> Custom memory allocators

- src/attr_file.c
- src/ignore.c
- tests/status/ignore.c
When computing whether a file is ignored, we simply search for the first
matching rule and return whether it is a positive ignore rule (the file
is really ignored) or whether it is a negative ignore rule (the file is
being unignored). Each rule has a set of flags which are being passed to
`fnmatch`, depending on what kind of rule it is. E.g. in case it is a
negative ignore we add a flag `GIT_ATTR_FNMATCH_NEGATIVE`, in case it
contains a glob we set the `GIT_ATTR_FNMATCH_HASGLOB` flag.
One of these flags is the `GIT_ATTR_FNMATCH_LEADINGDIR` flag, which is
always set in case the pattern has a trailing "/*" or in case the
pattern is negative. The flag causes the `fnmatch` function to return a
match in case a string is a leading directory of another, e.g. "dir/"
matches "dir/foo/bar.c". In …
> Fix negative gitignore rules with leading directories 

- src/path.c
- src/path.h
- tests/path/dotgit.c
Right now, there's quite a lot of different function calls to determine
whether a path component matches a specific name after normalization
from the filesystem. We have a function for each of {gitattributes,
gitmodules, gitignore} multiplicated with {generic, NTFS, HFS} checks.
In the long time, this is unmaintainable in case there are e.g. new
filesystems with specific semantics, blowing up the number of functions
we need to implement.
Replace all functions with a simple `git_path_is_gitfile` function,
which accepts an enum pointing out the filename that is to be checked
against as well as the filesystem normalizations to check for. This
greatly simplifies implementation at the expense of the caller having to
invoke a somewhat longer function call.
---
I'm rather indifferent with …
> path: unify `git_path_is_*` APIs

- src/diff_generate.c
- tests/stash/save.c
If the index contains stat data for a modified file, and the file is
not racily dirty, and there exists an untracked working tree directory
alphabetically after that file, and there are no other changes to the
repo, then git_stash_save would fail. It would confuse the untracked
working tree directory for the modified file, because they have the
same sha: zero.  The wt directory has a sha of zero because it's a
directory, and the file would have a zero sha because we wouldn't read
the file -- we would just know that it doesn't match the index.  To
fix this confusion, we simply check mode as well as SHA.
Fixes #4101
> Fix stash save bug with fast path index check

- include/git2/diff.h
The C89 standard states in §6.7.2.2 "Enumeration specifiers":
> The expression that defines the value of an enumeration constant shall
> be an integer constant expression that has a value representable as an
> int.
On most platforms, this effectively limits the range to a 32 bit signed
integer. The enum `git_diff_option_t` though recently gained an entry
`GIT_DIFF_INDENT_HEURISTIC = (1u << 31)`, which breaks this limit.
Fix the issue by using a gap in `git_diff_option_t`'s enum values. While
this has the benefit of retaining our API, it may break applications
which do not get recompiled after upgrading libgit2. But as we are
bumping the soversion on each release anyway and thus force a recompile
of dependents, this is not a problem.
---
Fixes #4657
> diff: fix enum value being out of allowed range

- docs/conventions.md
The libgit2 project mostly follows the coding style of git and thus
the linux project. While those two projects use a recommended tab width
of eight spaces, we instruct users to set their editor's tab width to
four spaces. Fix this to say eight instead.
> docs: fix statement about tab width

- .editorconfig
Markdown uses trailing whitespace to indicate context; eg, a blank line
with four spaces indicates that there is a hard break between the
(indented) lines surrounding that line.  Ensure that editors do not
remove this blank.
> editorconfig: allow trailing whitespace in markdown

- src/tree.c
- src/tree.h
Title says it all. There are two unused functions, which can just be removed
> tree: remove unused functions

- src/revwalk.c
- src/revwalk.h
As part of reducing our divergence from git, its code for revwalk was ported
into our codebase. A detail about when to limit the list was lost and we ended
up always calling that code.
Limiting the list means performing the walk and creating the final list of
commits to be output during the preparation stage. This is unavoidable when
sorting and when there are negative refs.
We did this even when asked for unsorted output with no negative refs, which you
might do to retrieve something like the "last 10 commits on HEAD" for a
nominally unsorted meaning of "last".
This commit adds and sets a flag indicating when we do need to limit the list,
letting us avoid doing so when we can. The previously mentioned query thus no
longer loads the entire history of the project during the prepare stage, …
> revwalk: avoid walking the entire history when output is unsorted

- src/transports/smart_pkt.c
If the remote sends a too-short packet, we'll allow `len` to go
negative and eventually issue a malloc for <= 0 bytes on
```
pkt->head.name = git__malloc(alloclen);
```
This was found by an oss-fuzz integration I'm working on.
> Verify ref_pkt's are long enough

- src/transports/smart.c
Nothing verifies that t->refs[0] is a GIT_PKT_REF. A remote can send
another packet type, ultimately resulting in a type confusion in
`git_smart__detect_caps`.
This was found by an oss-fuzz integration I'm working on.
> Fix type confusion in git_smart__connect

- src/transports/smart_protocol.c
I'm not sure this is the best fix, but without this fix we can cause a git2 client to spin forever allocating memory by responding with the four characters "PACK" to a smart protocol client:
```
[nelhage@penguin:~/code/libgit2]$ echo PACK | nc -l -p 9999 -q0 >/dev/null &                                                                      
[1] 22480
[nelhage@penguin:~/code/libgit2]$ build/examples/cgit2 --git-dir .git ls-remote git://localhost:9999/       
```
This bug was found by an oss-fuzz integration I'm working on.
> smart protocol: PACK packets are illegal while downloading refs

- src/transports/smart.c
- src/transports/smart_pkt.c
- src/transports/smart_protocol.c
These were all found by my work-in-progress oss-fuzz fuzzer.
> Fix assorted leaks found via fuzzing

- deps/http-parser/CMakeLists.txt
GCC 7 has introduced new warnings for implicit fallthrough in switch
statements. Whenever there is no branch in a case block, GCC will watch
out for some heuristics which indicate that the implicit fallthrough is
intended, like a "fallthrough" comment. The third-party http-parser code
manages to trick this heuristic in one case, even though there is a
"FALLTHROUGH" comment. Fortunately, GCC has also added a strictness
level to the -Wimplicit-fallthrough diagnostic, such that we can loosen
this heuristic and make it more lax.
Set -Wimplicit-fallthrough=1 in http-parser's CMake build instructions,
which is the strictest level that gets rid of the warning. This level
will treat any kind of comment as a "fallthrough" comment, which
silences the warning.
> deps: fix implicit fallthrough warning in http-parser

- src/revwalk.c
- tests/revwalk/basic.c
Sorted revwalks have their limited flag set because lazy revwalks, which are used when `limited` is not set since #4606, currently only handle `GIT_SORT_NONE`.
Revwalks persist their sorting over calls to `git_revwalk_reset`. However, the `limited` flag was unconditionally cleared during `git_revwalk_reset`, which would cause breakage.
This patch sets the limited flag for non-`GIT_SORT_NONE` revwalks in reset, and adds a test for the failing case.
I ran into this bug while making a version of `pygit2` with the mailmap changes from #4586, as pygit2 tests started failing.
> Fix interaction between limited flag and sorting over resets

- include/git2/refspec.h
- src/refspec.c
- tests/network/refspecs.c
This PR adds public apis for parsing refspec strings. This already exists but they are all internal.
I am not sure if tests are required here because I guess that the internal api must have tests already and this PR just adds trivial wrapping. But I am happy to add tests if it's really requested.
> refspec: add public parsing api

- src/streams/openssl.c
SIGSEGV otherwise...
I saw the segfault on Fedora when using libgit2 with nodegit. The segfault was in in SSL_CTX_set_verify because it was the first function that tried to actually write to the NULL pointer.
> streams: openssl: Handle error in SSL_CTX_new

- src/fetch.c
- src/push.c
- src/refspec.c
- src/refspec.h
- src/remote.c
- src/transports/smart.c
- src/transports/smart_protocol.c
- tests/network/refspecs.c
Since commit 630a67366 (refspec: add public parsing api, 2018-02-07), we
now have two functions `git_refspec_free` and `git_refspec__free`. The
difference is that the first one will free the structure itself, while
the second one will only free the structure's contents. Use our new
`dispose` naming pattern for the latter function to help avoid
confusion.
> refspec: rename `git_refspec__free` to `git_refspec__dispose`

- src/refspec.c
- tests/network/refspecs.c
per https://github.com/libgit2/libgit2/blob/b121b7ac972156cdc67b25be075fd62450b57f29/src/refspec.c#L85-L90 this is considered valid, so we should handle it downstream.
Found via triggering the assertion failure in  `git_buf_puts` in my work-in-progress fuzzer.
> git_refspec_transform: Handle NULL dst

- src/patch_parse.c
- tests/diff/parse.c
This should fix #4672. Looks like providing the "parsed" line numbers in the line struct was never actually wired (!).
> patch_parse: populate line numbers while parsing diffs

- src/streams/openssl.c
In case when the global initialization of the OpenSSL stream fails, the
user is left without any hint as to what went wrong as we do not provide
any error message at all. This commit refactors the init function to
have a common error path, which now also sets an error message including
the error string provided by OpenSSL.
> streams: report OpenSSL errors if global init fails

- include/git2/ignore.h
In attempt to provide adequate Git command analogy in regards to
ignored files handling, `git_ignore_path_is_ignored` description
mentions doing `git add .` on directory containing the file, and
whether the file in question would be added or not - but behavior of
the two matches for untracked files only, making the comparison
misleading in general sense.
For tracked files, Git doesn't subject them to ignore rules, so even
if a rule applies, `git add .` would actually add the tracked file
changes to index, while `git_ignore_path_is_ignored` would still
consider the file being ignored (as it doesn't check the index, as
documented).
Let's provide `git check-ignore --no-index` as analogous Git command
example instead, being more aligned with what `git_ignore_path_is_ignored`
is about, no …
>  ignore: improve `git_ignore_path_is_ignored` description Git analogy

- src/blame.c
- src/submodule.c
- src/transports/smart.c
- src/transports/smart_protocol.c
- tests/checkout/conflict.c
- tests/checkout/tree.c
- tests/describe/t6120.c
- tests/diff/workdir.c
- tests/mailmap/parsing.c
- tests/merge/workdir/dirty.c
- tests/stash/apply.c
This fixes May/June Coverity reports.
> Assorted Coverity fixes

- src/streams/mbedtls.c
- src/transports/smart.c
- tests/online/push.c
When running valgrind on the `online::push` tests, some leaks became apparent.  Two in the tests themselves, one in the product code that occurs when restarting a push on an existing remote.
> Squash some leaks

- src/streams/mbedtls.c
In commit 382ed1e87 (mbedtls: load default CA certificates, 2018-03-29),
the function `git_mbedtls_stream_global_init` was refactored to call out
to `git_mbedtls__set_cert_location` instead of setting up the
certificates itself. The conversion forgot to remove the now-unused
"cacert" variable, which is now only getting declared to be free'd at
the end of the function. Remove it.
> mbedtls: remove unused variable "cacert"

- src/transports/winhttp.c
Early Windows TLS 1.2 implementations have an issue during key exchange with OpenSSL implementations that cause negotiation to fail with the error "the buffer supplied to a function was too small."
This is a transient error on the connection, so when that error is received, retry up to 5 times to create a connection to the remote server before actually giving up.
We put [a bandaid on our CI servers](https://github.com/libgit2/libgit2/commit/3a72b0e2569c03ed0bd7ca63572eaf6384a2c81f) by disabling DHE.  This is good for our build servers, but end-users will still see this problem if they are running older versions of Windows.
> winhttp: retry erroneously failing requests

- src/revwalk.c
The contition cannot be reached with `commit->uninteresting` being true:
either a `break` or a `continue` statement will be hit in this case.
> revwalk: remove tautologic condition for hiding a commit

- src/transports/winhttp.c
While trying to use pygit2 with my TFS Git I stumbled accross two problems.
Whenever the server reports that it supports the NTLM and Negotiate authentication schemes both of the enum values are combined with the bitwise or assignment and the subsequent call to WinHttpSetCredentials fails.
The second problem was due to the fact that I had the python code running in PythonWin and it seems that PythonWin is setting the apartment state of the thread to single threaded. In this case the call to CoInitializeEx in the fallback credential function fails with the RPC_E_CHANGED_MODE and the fallback default credentials are never set.
> Windows: default credentials / fallback credential handling

- .travis.yml
- CHANGELOG.md
- include/git2/version.h
- src/transports/smart_pkt.c
This is a security release fixing out-of-bounds reads when
processing smart-protocol "ng" packets.
When parsing an "ng" packet, we keep track of both the current position
as well as the remaining length of the packet itself. But instead of
taking care not to exceed the length, we pass the current pointer's
position to `strchr`, which will search for a certain character until
hitting NUL. It is thus possible to create a crafted packet which
doesn't contain a NUL byte to trigger an out-of-bounds read.
The issue was discovered by the oss-fuzz project, issue 9406.
> Release v0.27.4

- .travis.yml
- CHANGELOG.md
- include/git2/version.h
- src/transports/smart_pkt.c
This is a security release fixing out-of-bounds reads when
processing smart-protocol "ng" packets.
When parsing an "ng" packet, we keep track of both the current position
as well as the remaining length of the packet itself. But instead of
taking care not to exceed the length, we pass the current pointer's
position to `strchr`, which will search for a certain character until
hitting NUL. It is thus possible to create a crafted packet which
doesn't contain a NUL byte to trigger an out-of-bounds read.
The issue was discovered by the oss-fuzz project, issue 9406.
> Release v0.26.6

- src/transports/smart_pkt.c
OSS-fuzz has reported a potential out-of-bounds read when processing a
"ng" smart packet:
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6310000249c0 at pc 0x000000493a92 bp 0x7ffddc882cd0 sp 0x7ffddc882480
READ of size 65529 at 0x6310000249c0 thread T0
SCARINESS: 26 (multi-byte-read-heap-buffer-overflow)
#0 0x493a91 in __interceptor_strchr.part.35 /src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:673
#1 0x813960 in ng_pkt libgit2/src/transports/smart_pkt.c:320:14
#2 0x810f79 in git_pkt_parse_line libgit2/src/transports/smart_pkt.c:478:9
#3 0x82c3c9 in git_smart__store_refs libgit2/src/transports/smart_protocol.c:47:12
#4 0x6373a2 in git_smart__connect libgit2/src/transports/smart.c:251:15
#5 0x57688f in git_remote_connect …
> smart_pkt: fix potential OOB-read when processing ng packet

- ci/build.sh
- src/odb.c
During the conversion of our CI scripts in bf418f09c (ci: refactor unix
ci build/test scripts, 2018-07-14), we accidentally dropped the
"-DENABLE_WERROR=ON" switch in our cmake invocation. Re-add it to help
us catch compiler warnings early.
> ci: enable compilation with "-Werror"

- .travis.yml
The new Travis cron job gets executed daily, but our current
configuration will cause each job to execute our Coverity script instead
of the default build and testing scripts. This cannot work, as Coverity
is heavily rate-limiting its API, so our cron builds are doomed to
always fail. What we want to do instead is execute our normal builds,
but add an additional Coverity jobs.
This can easily be done by adding another Coverity-specific job with a
conditional "type = cron", which sets the "COVERITY" environment
variable. Instead of checking the build type, we then simply check
whether "COVERITY" is set or not.
> travis: do not execute Coverity analysis for all cron jobs
