CHANGELOG.md
Went through the changes between 0.21 -> 0.22 and made notes of things that seemed useful to have in the changelog but were absent.
=> CHANGELOG: add missing 0.22 changes

appveyor.yml
Note that we build with VS 2012 to ensure nice backcompat with older MSVCs and their funny restrictions.
=> Add appveyor yaml

src/submodule.c
=> submodule: declare vars at top of func block

src/pool.c, src/repository.c
This removes some noise (thanks to coverity).
=> Remove logically dead code (we're already asserting)

include/git2/repository.h
=> Clarified git_repository_is_empty() documentation

src/config_file.c, tests/config/include.c
Fixes #2869.
Rewritten commit message, added a test. Review, please.
=> Reinit `reader` pointer after reading included config file

src/win32/posix_w32.c
Win32 generally ignores Unix-like mode bits that don't make any
sense on the platform (eg `0644` makes no sense to Windows).  But
WINE complains loudly when presented with POSIXy bits.  Remove them.
(Thanks @phkelley)
=> win32: limit the mode to `_wopen`/`_waccess`

include/git2/rebase.h, src/rebase.c, tests/rebase/iterator.c, tests/rebase/setup.c
A couple of minor fixups for rebase to address #2791 and feedback from @jamill as he is binding up rebase in LibGit2Sharp.
=> Fixups for rebase

src/integer.h
https://github.com/libgit2/libgit2/pull/2919 has been merged but was targeting a wip branch..
This PR proposes to merge the cherry picked work from @jeffhostetler into master.
=> Fix MAX 32 bit build problem described in libgit2/libgit2#2917

tests/clar.c, tests/clar.h
=> Update to clar 2b73f5e

examples/describe.c
Add safe function to (a,rea)llocate memory which terminate example on
memory allocation failure.
Move code to allocate commits to its own function.
=> describe example: function to add commits to opts

src/stash.c, tests/stash/save.c
Should fix #2912 
/cc @nulltoken
=> stash: correctly stash wd modified/index deleted

src/common.h, src/openssl_stream.c
This is similar to [this pull request](https://github.com/libgit2/libgit2/pull/2930) but on the master branch. There is one additional commit that fixes the build since it got broken for mingw by commit 3cda6be.
=> Fix build on mingw (master branch)

src/filter.c, tests/filter/file.c
=> Filter relative paths

src/push.c, src/remote.c
The 2nd commit looks like a big diff but it's actually trivial: I only removed the `if (status->msg == NULL)` condition and shift the block to the left.
=> Update tips fixes

src/fileops.c
Here's an alternate take on https://github.com/libgit2/libgit2/pull/2988 which fixes the original race + the case where we race because the file gets removed. I think this is less/clearer code too.
@simonsj: can you confirm this fixes your issue?
@carlosmn: can you review please?
=> mkdir-ext: Assume directories don't exist; fix all race cases

src/revwalk.c
When walking backwards and marking parents uninteresting, make sure we
detect when the list of commits we have left has run out of
uninteresting commits so we can stop marking commits as
uninteresting. Failing to do so can mean that we walk the whole history
marking everything uninteresting, which eats up time, CPU and IO for
with useless work.
While pre-marking does look for this, we still need to check during the
main traversal as there are setups for which pre-marking does not leave
enough information in the commits. This can happen if we push a commit
and hide its parent.
=> revwalk: detect when we're out of interesting commits

tests/core/mkdir.c
Fix memory leak in test/core/mkdir.c.
=> Fix memleak in test/core/mkdir reported by CRTDBG

src/config_file.c, tests/config/read.c
I rebased #2852 on master, and refactored a bit to (I hope) address @carlosmn 's concerns.
=> Handle invalid multiline configuration

examples/network/git2.c
Added forgotten call to git_libgit2_shutdown() to the /examples/network/git2.c.
Should fix #3076
=> Added call to git_libgit2_shutdown()

README.md
=> Changed README to use new OCaml bindings to git

src/indexer.c, src/odb_pack.c, src/rebase.c, src/remote.c, src/transports/ssh.c
Coverity shows a few interesting issues. Some might need more complex refactoring, but these are some changes we can do right now. I'm posting as a PR mostly for visibility, I'll merge it soonish.
=> A few fixes from Coverity

script/cibuild.sh, tests/online/clone.c, tests/online/push.c
These tests were not being taken into consideration for the failure of
the test. They've been failing for a while now, but we hadn't noticed as
Travis was reporting the builds successful.
I'm submitting this first to make sure we do fail now, I'll push up the commit which fixes the tests when that happens.
=> travis: fail if we fail the push tests

src/stransport_stream.c
=> Fixed some Secure Transport issues on OS X

tests/checkout/icase.c
Fix memory leaks in tests/checkout/icase.c
=> Fix leaks in tests/checkout/icase

src/clone.c
We use heuristics to make a decent guess at when we can save time and
space by linking object files during a clone. Unfortunately checking the
device id isn't enough, as those would be the same during e.g. a bind-mount,
but the OS still does not allow us to link between mounts of the same
filesystem.
If we fail to perform the links, fall back to copying the contents into
a new file as a last attempt.
This fixes #2797
=> clone: fall back to copying when linking does not work

.travis.yml, appveyor.yml, include/git2/reset.h, script/cibuild.sh, src/clone.c, src/fileops.c, src/ident.c, src/indexer.c, src/openssl_stream.c, src/pack.c, src/path.c, src/refspec.c, src/transports/ssh.c, tests/checkout/crlf.c, tests/filter/blob.c, tests/filter/custom.c, tests/filter/ident.c, tests/network/refspecs.c, tests/odb/foreach.c
This should be the last one before we do release v0.22.3. I'll merge when CI reports back.
=> Another round of backports

src/diff_tform.c, tests/diff/workdir.c
=> Explicitly handle GIT_DELTA_CONFLICTED in git_diff_merge()

src/diff.c, tests/diff/index.c
=> Fixed GIT_DELTA_CONFLICTED not returned in some cases

CHANGELOG.md, examples/status.c, include/git2/diff.h, include/git2/remote.h, include/git2/types.h, src/checkout.c, src/diff_file.c, src/fetch.c, src/remote.c, src/submodule.c, tests/diff/tree.c, tests/submodule/submodule_helpers.c, tests/submodule/update.c
Fallback describes the mechanism, while unspecified explains what the
user is thinking.
=> Rename FALLBACK to UNSPECIFIED

src/diff.c, src/diff.h, tests/diff/workdir.c
=> Dont update index unnecessarily

tests/stash/apply.c
Quick test to ensure that we can apply using indexes to get older stashes.  Make sure that the indexes are reflog-style, from the man page:
> stash@{0} is the most recently created stash, stash@{1} is the one before it
=> stash: test we apply using reflog-like indices

src/diff_patch.c, src/diff_print.c, src/iterator.c, tests/checkout/crlf.c, tests/diff/binary.c, tests/fetchhead/nonetwork.c, tests/index/racy.c
There's tree left, which are related to how we increment the refcount in `git_submodule_reload()` but I don't quite get how that one's supposed to work.
=> Plug a bunch of leaks

src/refspec.c
=> memory leak refspec.c

src/path.c
=> Make libgit2 work on Windows Vista again

src/filter.c
When the stream list init or write fail, we must also make sure to close
the stream, as that's the function contract.
This should fix #3176
=> filter: make sure to close the stream even on error

src/transports/http.c
=> case-insensitive check for WWW-Authenticate header

CMakeLists.txt, include/git2/repository.h, include/git2/sys/config.h, include/git2/sys/diff.h, include/git2/sys/odb_backend.h, include/git2/sys/refdb_backend.h, src/path.h, src/push.h
Also enabled `-Wdocumentation` if supported
=> Resolve documentation warnings

CMakeLists.txt, README.md, include/git2/repository.h, include/git2/sys/config.h, include/git2/sys/diff.h, include/git2/sys/odb_backend.h, include/git2/sys/refdb_backend.h, src/describe.c, src/filebuf.c, src/filebuf.h, src/index.c, src/indexer.c, src/iterator.c, src/pack-objects.c, src/pack.c, src/path.h, src/push.h, src/revwalk.c, src/transports/git.c, src/transports/http.c, src/transports/ssh.c, tests/core/filebuf.c, tests/index/bypath.c, tests/repo/iterator.c
We should also take the submodule fixes for staging and the filebuf rename one when those get merged.
=> A second round of 0.23 maint updates

src/remote.c, tests/network/fetchlocal.c
We currently skip a ref if it's a tag and the auto-follow says we don't want it, but we still need to check whether the user's refspec says we do want it.
=> remote: don't confuse tag auto-follow rules with refspec matching

src/transports/http.c
When we ask for credentials, the user may choose to return EUSER to
indicate that an error has happened on its end and it wants to be given
back control.
We must therefore pass that back to the user instead of mentioning that
it was on_headers_complete() that returned an error code. Since we can,
we return the exact error code from the user (other than PASSTHROUGH)
since it doesn't cost anything, though using other error codes aren't
recommended.
---
We do actually have  a test for this, but it's currently only run for SSH.
=> http: propagate the credentials callback's error code

src/diff.c, tests/diff/workdir.c
When we're not doing pathspec matching, we let the iterator handle
file matching for us.  However, we can only trust the iterator to
return *files* that match the pattern, because the iterator must
return directories that are not strictly in the pathlist, but that
are the parents of files that match the pattern, so that diff can
later recurse into them.
Thus, diff must examine non-files explicitly before including them
in the delta list.
=> diff: examine pathlist on non-files

src/ignore.c
This change fixes issue [libgit2#3393]
=> Fix 'If we're dealing with a directory' check

src/iterator.c
While advancing the tree iterator, if we advance over things that
we aren't interested in, then call `current`.  Which may *itself*
call advance.
Ad infinitum, or at least until you run out of stack space.
=> iterator: advance the tree iterator smartly

src/iterator.c
Similar to #3420 , avoid recursion in the fs_iterator.
Fixes #3056
=> iterator: loop fs_iterator advance (don't recurse)

tests/clar_libgit2.c, tests/clone/nonetwork.c
=> Clone test buffer

src/submodule.c
Just making sure this doesn't break other stuff.
=> submodule: plug a few leaks

src/openssl_stream.c
SSL_shutdown() does not like it when we pass an unitialized ssl context
to it. This means that when we fail to connect to a host, we hide the
error message saying so with OpenSSL's indecipherable error message.
=> openssl: don't try to teardown an unconnected SSL context

include/git2/common.h
C++ users expect to not have to worry too much about linkages.  Let's me explicit about ours.
=> api: be explicit about our C linkage

include/git2/common.h
=> inttypes.h is built-in header file since MSVC 2013

src/index.c
`git_index_read_index` wasn't updating the hash map.  It needs to, lest it remove entries from the vector but keep the hash entries around.
=> index: read_index must update hashes

src/diff_file.c, tests/diff/workdir.c, tests/index/bypath.c
On platforms where `core.symlinks=false`, diff needs to honor the fake symlinks that we (and Git for Windows) lay down, where a regular file is written with the symlink target.
At present, we propagate the mode bits from the index into diff, so that it knows that the file should be treated as a symlink.  Regrettably, diff then tries to *read the symlink*.  On platforms where `core.symlinks=false`, we should instead try to read the regular file, but preserve the mode.
There's a bonus unit test to ensure that `git_index_add_bypath` gets this right also.  (It does!)
=> Diff: Honor `core.symlinks=false` and fake symlinks

CHANGELOG.md, src/index.c, tests/index/conflicts.c
From https://github.com/libgit2/libgit2sharp/pull/345
/cc @ethomson
=> Failing test for case sensitive conflicts in the index

tests/checkout/crlf.c, tests/core/filebuf.c, tests/diff/notify.c, tests/index/racy.c
=> Fix some warnings

tests/config/global.c, tests/config/stress.c, tests/win32/longpath.c
Some fixes for memory leaks  displayed by AppVeyor CI.
=> Memleak fixes

src/tree.c
Instead of going out to strtol, which is made to parse generic numbers,
copy a parse function from git which is specialised for file modes.
---
This isn't as big of a win as I had hoped, but it's still a win. On my laptop it makes grabbing the top tree for ~41k commits (revwalk from git.git's master) go from 3.7s to 3.3s.
=> tree: use a specialised mode parse function

src/curl_stream.c
=> Free allocated pointer to curl stream on error

src/curl_stream.c, src/merge.c
Two fixes for issues displayed by Coverity.
=> Coverity fixes

src/checkout.c, src/diff.c, src/index.c, src/iterator.c, src/iterator.h, src/merge.c, src/pathspec.c, src/stash.c, src/submodule.c, tests/diff/iterator.c, tests/repo/iterator.c
This should fix #3173, https://github.com/libgit2/rugged/issues/566 and https://github.com/libgit2/rugged/pull/42
@ethomson Please take a look. I don't think this really fixes all cases where this might segfault, but it fixes the two cases that were reported by rugged users.
=> Horrible fix for #3173.

CHANGELOG.md, include/git2/rebase.h
/cc @ethomson to make sure these are indeed typos
=> Fix a few checkout -> rebase typos

CONVENTIONS.md, README.md
=> CONVENTIONS: update to include general public API principles

CMakeLists.txt, tests/index/nsec.c, tests/index/racy.c, tests/merge/workdir/dirty.c
Nanosecond resolution is now the default in git itself.  Enable this
as our default as well.
=> Enable nanosecond resolution by default

tests/index/nsec.c, tests/transport/register.c
Two memory leaks pointed out by AppVeyor. There is still one memory leak missing involving TLS and the init/shutdown logic. It somehow seems like a race condition but I haven't been able to figure it out yet as I do not have a Windows installation at hand currently.
=> Test memleaks

CONTRIBUTING.md
=> CONTRIBUTING: document the optional tests

src/iterator.c, src/tree.c, src/xdiff/xprepare.c, tests/config/write.c, tests/core/array.c, tests/iterator/index.c, tests/iterator/tree.c, tests/iterator/workdir.c, tests/status/worktree.c
=> Plug some leaks

src/checkout.c, src/delta-apply.c, src/diff.c, src/index.c, src/merge_file.c, src/odb_loose.c
Some fixes hinted at by Coverity. I want to wait for one more build from Coverity due to 153fde5, which wasn't fixed in my previous run, but I hit the analysis quota. So for now this is up for discussion only until I hear back from Coverity tomorrow.
All fixes except fcd1b78 are of non-comsetic nature, that is they fix actual bugs. Most are rather obsocure though, to be honest.
=> Misc fixes

src/tree.c, tests/object/tree/update.c
Fix removing a deep blob, as well as plug leaks in this code.
=> Tree updater fixups

appveyor.yml
Start-FileDownload maintains current directory context and allows
specifying a request timeout, see [1].
[1] https://www.appveyor.com/docs/how-to/download-file#start-filedownload-cmdlet
=> Use AppVeyor's Start-FileDownload cmdlet

src/commit.c, src/filebuf.c, src/global.c, src/rebase.c, tests/checkout/typechange.c
Gonna let this run on the CI bots to see what else is out there.
=> cleanup: unused warning

src/blame_git.c
blame: do not decrement commit refcount in make_origin
When we create a blame origin, we try to look up the blob that is
to be blamed at a certain revision. When this lookup fails, e.g.
because the file did not exist at that certain revision, we fail
to create the blame origin and return `NULL`. The blame origin
that we have just allocated is thereby free'd with
`origin_decref`.
The `origin_decref` function does not only decrement reference
counts for the blame origin, though, but also for its commit and
blob. When this is done in the error case, we will cause an
uneven reference count for these objects. This may result in
hard-to-debug failures at seemingly unrelated code paths, where
we try to access these objects when they in fact have already
been free'd.
Fix the issue by refactoring …
=> blame: increment reference count for origin's commit

script/cibuild.sh, script/install-deps-osx.sh
Install curl and zlib explicitly from homebrew, and specify their `pkg-config` configuration explicitly.
=> ci: point to the homebrew libssh2 install

src/stransport_stream.c
Some fixes to memory management I've encountered when reasoning about #3885. While these fixes probably won't fix the problems encountered in this ticket, I think they are a worthwhile improvement never the less.
=> stransport memory management improvements

CHANGELOG.md, include/git2/index.h, src/index.c, src/index.h, src/varint.c, src/varint.h, tests/core/encoding.c, tests/index/version.c
moved from https://github.com/libgit2/libgit2/pull/3789 because I no longer have access to the twitter github account.
This version leaves one in/out parameter, but I think otherwise addresses the concerns in the prev request.
=> Support index v4

src/commit.c, src/tree.c
See the commit messages for more info. These commits fix #3936 and #3937. I bet there are more issues around here which I'd like to find. I think I'll try some more fuzzing with AFL around the object-parsing logic sometimes soon.
=> Object parsing hardening

src/openssl_stream.c, src/openssl_stream.h
Closes: https://github.com/libgit2/libgit2/issues/3959
Signed-off-by: Igor Gnatenko i.gnatenko.brain@gmail.com
=> add support for OpenSSL 1.1.0 for BIO filter

src/repository.c, tests/repo/discover.c
This PR is as a response to #3994. I think it does make sense to make a repository discoverable even if initially, a path to a file inside the repository was specified.
=> Repository discovery starting from files

.github/ISSUE_TEMPLATE
Encourage people to ask questions on StackOverflow and use Issues for bug reports.
cc @carlosmn
=> Introduce a GitHub Issue Template

README.md
Make it clearer from the get-go that we do not aim to implement
user-facing commands from the git tool.
---
I'd been meaning to add some wording about this for a while.
=> README: be more explicit in the goals and scope

src/transports/winhttp.c
For username/password credentials, support NTLM or Basic (in that order of priority).  Use the WinHTTP built-in authentication support for both, and maintain a bitfield of the supported mechanisms from the response.
Fixes #4039
=> WinHTTP: support best auth mechanism

include/git2/sys/repository.h, src/repository.c, src/repository.h, src/submodule.c, src/submodule.h, tests/submodule/lookup.c
The bulk of this work was done by @bpeabody.  I just made some minor adjustments.  This fixes #3756.
=> Submodule optimization

src/indexer.c, src/pack.c, src/pack.h
=> indexer: introduce `git_packfile_close`

examples/general.c
=> Fix general example memory leaks

src/indexer.c
I have an application that uses LibGit2Sharp, and it's been having performance issues doing fetches.  Using the profiling technique of running it in the debugger and pausing it, I discovered it was spending a lot of time calling `p_write` from `append_to_pack` to write a single byte.  
I guessed that there was a cost for each call that actually extended the file, and that we could reduce the overall cost by rounding the size up so that we extend the file fewer times in larger chunks.  I'm using `mmap_alignment` for the rounding since that was used in the nearby `write_at` method, but I don't know whether or not that's an appropriate value.  
A local fetch of the libgit2 repository on my Windows 7 machine takes 307s without this change and 43s with it, for a 7x speedup, and the fetch goes …
=> Extend packfile in increments of page_size.

src/transports/winhttp.c
When SSL fails for the WinHTTP transport, by default we set the error message to the most unhelpful "user cancelled certificate check", which is set when there is no `giterr` set, even when there is no user certificate check configured.
Instead, try to capture the SSL failure to provide a more helpful error message by [setting a status callback](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384115(v=vs.85).aspx) and looking for [security failures (`WINHTTP_CALLBACK_STATUS_SECURE_FAILURE`)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383917(v=vs.85).aspx), and providing a helpful error message for them.
If the security failure is not reported, and there is no user certificate check, update the error message to not suggest that the (nonexistent) user certificate …
=> WinHTTP: set proper error messages when SSL fails

include/git2/oid.h
=> Update docs for git_oid_fromstrn and p

include/git2/index.h
I just filled in a missing word and re-wrapped.
=> Minor comment fix

src/attrcache.c, src/attrcache.h
After several hours of staring at multi-threaded attrcache, this is the depressing outcome: a few fixes to small stylistic nits which have already been bothering me the last few times I took a look at the code :/ Well, better than nothing...
=> Attrcache cleanups

appveyor.yml, script/appveyor-mingw.sh
Trying to chase down the new appveyor build failures...
=> appveyor: don't rewrite the system mingw

src/revwalk.c, tests/revwalk/basic.c
Fixes #4099
See https://github.com/libgit2/libgit2/issues/4099#issuecomment-280652168
/cc @carlosmn
=> Skip uninteresting commits in revwalk timesort iterator

src/submodule.c
When calling `git_submodule_update` on a submodule, we have to retrieve
the ID of the submodule entry in the index. If the function is called on
a submodule which is only partly initialized, the submodule entry may
not be added to the index yet. This leads to an assert when trying to
look up the blob later on.
Fix the issue by checking if the index actually holds the submodule's
ID and erroring out if it does not.
The issue has been uncovered by #4149. Even though it was incorrect usage of the API, this should not result in an assert but in an error, instead.
=> submodule: catch when submodule is not staged on update

src/diff.c, src/diff_parse.c, src/patch_generate.c, src/patch_parse.c, tests/diff/parse.c
This fixes #4158 along with some other issues
=> Diff fixes

include/git2/odb.h
=> Correct non-existent file references in `odb.h`

src/win32/posix_w32.c
This pull requests follows the pattern used in this previous pull request: https://github.com/libgit2/libgit2/pull/2211 to add retries to p_unlink and p_open.
When doing checkouts I was seeing Dropbox and/or anti-virus locking files while libgit2 was trying to call p_unlink or p_open. These changes seem to make checkout much more reliable for me on Windows.
=> Add retries to win32 p_unlink and p_open.

CHANGELOG.md
Backports #4065 to the maint/v0.25 branch.
=> Backport #4065

src/repository.c, tests/submodule/open.c
This is work in progress trying to reproduce the error reported in #4242. Please do not merge yet
=> Submodule working directory

CHANGELOG.md, include/git2/version.h
Update the version number to 0.26 in the CHANGELOG and the header.
=> Update version number to 0.26

script/install-deps-osx.sh
I can't entirely understand why this is failing, but it is.  Harumpfh.
=> travis: install openssl explicitly

include/git2/graph.h
=> Document that a commit is not a descendant of itself

examples/general.c
I rebased #4059 - I opened this PR to run it through CI.
=> Fix Issue #4047 Check return codes and free objects

src/ignore.c, tests/attr/ignore.c
=> ignore spaces in .gitignore files

include/git2/describe.h
=> describe.h: fix spelling in comments

src/streams/stransport.c
=> stransport: provide error message on trust failures

src/transports/winhttp.c
When parsing unauthorized responses, properly parse headers looking for both NTLM and Negotiate challenges.  This was not previously necessary, since we did not previously need to set HTTP credentials.)
Set the HTTP credentials to default credentials (using a `NULL` username and password) with the schemes
supported by ourselves and the server.  It's not clear why this worked previously, but we now must explicitly call this API in order to authenticate with default credentials.
=> winhttp: properly support ntlm and negotiate

include/git2/sys/mempack.h, src/odb_mempack.c
=> odb: export mempack backend

README.md
The title says it all, I guess.
=> README.md: add notes on how to report security issues

src/sysdir.c
In order to derive the location of some Git directories, we currently
use the environment variables $HOME and $XDG_CONFIG_HOME. This might
prove to be problematic whenever the binary is run with setuid, that is
when the effective user does not equal the real user. In case the
environment variables do not get sanitized by the caller, we thus might
end up using the real user's configuration when doing stuff as the
effective user.
The fix is to use the passwd entry's directory instead of $HOME in this
situation. As this might break scenarios where the user explicitly sets
$HOME to another path, this fix is only applied in case the effective
user does not equal the real user.
---
I've tested the logic of `get_passwd_home` with the following executable:
```
#include <assert.h>
#include …
```
=> sysdir: do not use environment in setuid case

src/buf_text.c, src/buf_text.h, src/config_parse.c, tests/config/read.c
=> config: handle CRLF-only lines and BOM

CHANGELOG.md
I feel like this should be the most important changes since v0.26.0.
=> CHANGELOG: update for v0.27.0

CMakeLists.txt, src/index.c, src/patch_parse.c, src/revparse.c, src/streams/openssl.c, src/tree.c, src/util.c, src/util.h
Some smallish fixes to shut up compiler warnings.
=> Fix build warnings

CHANGELOG.md, docs/release.md, include/git2/version.h
Document the version bump in "release.md" and do the bump. This will become v0.27.0-rc1
=> v0.27.0-rc1: version bump

CHANGELOG.md, include/git2/checkout.h, src/rebase.c, src/stash.c
=> checkout: change default strategy to SAFE

src/remote.c, src/transports/local.c, src/worktree.c
This fixes the 2 Valgrind-reported leaks that can be backported to v0.27.1
=> Leak fixes for v0.27.1

docs/differences-from-git.md
I synthesized these brief summaries from the conversation here: https://github.com/git-for-windows/git/pull/437. It doesn't look like much has changed since then.
=> Added note about Windows junction points to the differences from git document

.github/ISSUE_TEMPLATE
Update the issue template to point to the discussions repo.
=> github: update issue template

src/index.c
In order to avoid alignment issues on certain target architectures, it is necessary to use memcpy() when modifying elements of a struct inside a buffer returned by git_filebuf_reserve().
This fixes the testsuite on Debian mipsel and sparc64 where it crashes with "Bus error".
See: https://buildd.debian.org/status/package.php?p=libgit2&suite=sid
=> index: Fix alignment issues in write_disk_entry()

src/config_file.c, src/config_parse.c, src/config_parse.h
Two small cleanups to make code more readable in our config parser.
=> Config parser cleanups

src/delta.c, tests/delta/apply.c, tests/diff/binary.c
Fixes to the out of bounds reads. These changes are part of v0.26.5 and v0.27.3 already.
=> Delta OOB access

tests/index/conflicts.c
Commit 581d5492f (Fix leak in index.c, 2018-08-16) was fixing a memory
leak in our code adding conflicts to the index when the added index
entries have an invalid file mode. The memory leak was previously
undiscovered as there are no tests covering this scenario, which is now
being added by this commit.
=> tests: verify adding index conflicts with invalid filemodes fails

src/mailmap.c, src/remote.c, src/revwalk.c, src/transports/http.c
It's that time of the year again (it's always that time).
A few potential crashers/fixes I've been sitting on, nothing really serious since we're client only but I'll defer to you on their severity.
=> Coverity flavored clang analyzer fixes

src/config_parse.c
This can cause a stack overflow from a crafted config file.
=> config: convert unbounded recursion into a loop

src/path.c, src/streams/stransport.c, tests/core/path.c
That's the 2 warnings I know of I've hinted at recently.
=> Some warnings

src/transports/smart.h, src/transports/smart_pkt.c, src/transports/smart_protocol.c, tests/transports/smart/packet.c
These fixes were part of v0.26.7 and v0.27.5
=> Smart packet security fixes

ci/test.sh, tests/main.c
This is just a work in progress. I want to see what happens with the build with that configuration.
Ref #4859.
Note that, AFACS `-atExit` never outputs the nicer traces it does when used with a pid directely, which is a shame…
=> CI: Fix macOS leak detection

src/refdb_fs.c
The function `refdb_reflog_fs__delete` uses the `if (!error && foobar())`
pattern of checking, where error conditions are being checked by following calls
to different code. This does not match our current style, where the call-site of
a function is usually directly responsible for checking the return value.
Convert the function to use `if ((error = foobar()) < 0) goto out;` style. Note
that this changes the code flow a bit: previously, we were always trying to
delete empty reference hierarchies even if deleting the reflog entry has failed.
This wasn't much of a problem -- if deletion failed, the hierarchy will still
contain at least one file and thus the function call was an expensive no-op.
Now, we will only perform this deletion if we have successfully removed the
reflog.
=> refdb_fs: refactor error handling in `refdb_reflog_fs__delete`

tests/resources/push.sh
This changes that file to use UNIX line-endings, which makes sense since
this is a UNIXy file.
=> Convert tests/resources/push.sh to LF endings

.mailmap
My @github.com address is no more.
=> mailmap: prefer ethomson@edwardthomson.com

azure-pipelines/coverity.yml, azure-pipelines/nightly.yml, ci/test.ps1, ci/test.sh, tests/CMakeLists.txt, tests/iterator/workdir.c
This takes #4933 but only runs the invasive tests during the nightly runs.
=> ci: only run invasive tests in nightly

ci/test.ps1, ci/test.sh
Update the proxy so that we can enable a quiet mode.
=> ci: update poxyproxy, run in quiet mode

src/streams/socket.c, src/transports/winhttp.c
=> Don't use deprecated constants

AUTHORS, src/apply.c, tests/apply/fromdiff.c
=> Prevent reading out of bounds memory

src/branch.c, tests/refs/branches/lookup.c
This PR is a proposed fix for issue #4938.
=> Have git_branch_lookup accept GIT_BRANCH_ALL

include/git2/checkout.h
=> docs: clarify relation of safe and forced checkout strategy

tests/README.md
Document how to run the test suite locally with leak check detection on OSX & Linux
From https://github.com/libgit2/libgit2/pull/5022#issuecomment-500372302
=> Add memleak check docs

src/streams/socket.c, src/transports/auth_negotiate.c, src/worktree.c
Use lowercase for our error messages, per our custom.
=> errors: use lowercase

include/git2/config.h, include/git2/deprecated.h, src/checkout.c, src/config.c, src/config.h, src/config_cache.c, src/crlf.c, src/diff_file.c, src/diff_generate.c, src/diff_print.c, src/ignore.c, src/index.c, src/iterator.c, src/object.c, src/odb.c, src/pack-objects.c, src/path.c, src/refdb_fs.c, src/refs.c, src/repository.c, src/repository.h, src/stash.c, src/submodule.c, tests/checkout/conflict.c, tests/checkout/icase.c, tests/diff/workdir.c, tests/index/bypath.c, tests/repo/config.c
`cvar` is an unhelpful name.  Refactor its usage to `configmap` for more clarity.
=> configuration: cvar -> configmap

src/blame_git.c, src/indexer.c, src/merge.c, src/posix.c, src/trailer.c, src/transports/http.c, src/transports/winhttp.c, src/util.c, src/util.h, src/xdiff/xmerge.c, src/xdiff/xpatience.c, tests/core/qsort.c
Various fixes to potential memory allocation errors which were previously unchecked. Triggered by #5199 and #5164, even though I've got no idea whether it will fix these reported issues.
=> Memory allocation audit

src/diff_generate.c, src/iterator.c
Some more fixes inspired by recent crashes that have been reported
=> Memory allocation fixes for diff generator

include/git2/sys/refdb_backend.h, src/refdb.c, src/refdb_fs.c
This is the preliminary part to the reflog message PR (#4316), and is limited to documentation, QOL improvements, NFC, and some bugfixes.
(Please make sure it's it in sync with #4316 on merge, since it's likely to get rebased again).
=> git_refdb API fixes

src/cherrypick.c, src/filebuf.c, src/filebuf.h, src/merge.c, src/refdb_fs.c, src/repository.c, src/revert.c, tests/refs/transactions.c
See #5256
Should fail on Linux but be ok on Windows.
=> Fix file locking on POSIX OS

fuzzers/corpora/patch_parse/edit-file.diff, fuzzers/corpora/patch_parse/patch_fuzzer-patch.diff, fuzzers/patch_parse_fuzzer.c
I was looking at this code anyway because the sr.ht people nerdsniped
me, and it gave me that "I should fuzz this" feeling. So have a fuzzer!
=> fuzzers: add a new fuzzer for patch parsing

include/git2/apply.h, src/apply.c, tests/apply/apply_helpers.h, tests/apply/check.c
This adds an option which will check if a diff is applicable without
actually applying it; equivalent to git apply --check.
=> apply: add GIT_APPLY_CHECK

src/config_snapshot.c, tests/config/snapshot.c
=> Fix crash if snapshotting a config_snapshot

include/git2/diff.h, src/diff.c, src/diff.h, src/diff_print.c, src/patch.c, src/patch_parse.c, tests/diff/patchid.c, tests/patch/patch_common.h, tests/patch/print.c
Hi,
I noticed that git_diff_patchid wasn't returning a correct hash in some cases.
So I fixed those and added some tests for it.
Please let me know what you think.
Thanks!
=> diff: complete support for git patchid

docs/fuzzing.md
Some of the commands are now out of date.
=> fuzzers: Fix the documentation

README.md
ref https://github.com/libgit2/libgit2/pull/5345#issuecomment-590056379
=> README: add language binding link to wasm-git

include/git2/repository.h
=> repository: improve commondir docs

README.md
Add instructions for building libgit2 in MinGW environment
=> README.md: Add instructions for building in MinGW environment

src/streams/openssl.c
When converting an OpenSSL X509 certificate to our own `git_cert` structure, we forgot to call `X509_free()` on the OpenSSL cert and thus caused a memory leak, which is being fixed by this PR. Maybe we're lucky and this was the last memory leak we had in OpenSSL, so I also included a change to remove our memleak suppressions for OpenSSL. Probably not, though, so this is a shot into the blue.
Fixes #5505.
=> OpenSSL certificate memory leak

src/checkout.c, src/revparse.c, tests/refs/create.c
This is a random set of code cleanups and fixes for issues I've stumbled over while reading the sources. Nothing too breathtaking, but I guess a little cleanup here and there every once in a while can't hurt.
=> Random code cleanups and fixes

src/config_entries.c
When appending config entries, we currently always first get the
currently existing map entry and then afterwards update the map to
contain the current config value. In the common scenario where keys
aren't being overridden, this is the best we can do. But in case a key
gets set multiple times, then we'll also perform these two map
operations. In extreme cases, hashing the map keys will thus start to
dominate performance.
Let's optimize the pattern by using a separately allocated map entry.
Currently, we always put the current list entry into the map and update
it to get any overridden multivar. As these list entries are also used
to iterate config entries, we cannot update them in-place in the map and
are thus forced to always set the map to contain the new entry. But with
a separately …
=> config_entries: Avoid excessive map operations

deps/ntlmclient/compat.h
Use B_HOST_TO_BENDIAN_INT64 for that.
=> deps: ntlmclient: fix htonll for Haiku

src/transports/winhttp.c
Tested on Windows 7 and 10 (of course WIndows 7 does not support TLS1.3; for WIndows 10 TLS1.3 ATM needs to be enabled in Internet Options and manually as of 2004 cf. https://stackoverflow.com/a/59210166/3906760)
=> WinHTTP: Try to use TLS1.3

include/git2/deprecated.h
=> Fix deprecation links inside of documentation not working

src/config_parse.c, tests/config/stress.c, tests/resources/config/config12
=> Fix config file parsing with multi line values containing quoted parts

src/config.c, tests/config/read.c
=> boolean config parsing fails in some cases with mapped values

include/git2/deprecated.h
=> Fixed typo in comment

deps/pcre/LICENCE, deps/pcre/pcre.h, deps/pcre/pcre_compile.c, deps/pcre/pcre_jit_compile.c, deps/pcre/pcreposix.c
PCRE has released 8.44 with some fixes for security issues.  We should update our included PCRE to that version.
=> Update PCRE to 8.44

src/worktree.c, tests/worktree/worktree.c, tests/worktree/worktree_helpers.c
=> Add missing worktree_dir check and test case

.github/workflows/nightly.yml, src/pack-objects.c, src/runtime.c, src/thread-utils.h, src/util.h, tests/pack/threadsafety.c
Some fixes for building with `-DTHREADSAFE=OFF`, and a nightly build that exercises it.
=> Thread-free implementation

src/pack.c
Continue the zlib stream as long as we can make progress; stop when we stop getting output _or_ when zlib stops taking input from us.
From @ehuss in https://github.com/libgit2/libgit2/issues/5590#issuecomment-743495610
=> pack: continue zlib while we can make progress

src/integer.h
This causes clang to produce an undefined reference to `__mulodi4`. This
could be fixed by statically linking some compiler-rt libraries to
provide this symbol, but let's first stop the bleeding since doing the
correct long-term fix requires some non-trivial CMake knowledge which I
lack.
=> Avoid using `__builtin_mul_overflow` with the clang+32-bit combo

src/net.c, src/net.h, src/transports/httpclient.c, src/transports/winhttp.c, tests/network/urlparse.c
=> Handle ipv6 addresses

.github/workflows/main.yml, .github/workflows/nightly.yml
=> github-actions: Also rename the main branch here

README.md
A new package with libgit2 bindings for R.
=> Add new bindings for the R language

src/blame.c
I figured these calls should probably be checked, since `git_signature_dup` can have an allocation failure.
There's also one in `hunk_from_entry`, but I'm not sure if that call has to be checked because `blame_internal` doesn't check `hunk_from_entry` for any errors (should it?).
=> Check git_signature_dup failure

tests/object/tag/list.c
Typo in the name of the variable :)
=> tests: fix variable name in list.c

.devcontainer/devcontainer.json, .devcontainer/setup.sh, .vscode/launch.json, .vscode/tasks.json
Add devcontainer settings for running within a codespace.
=> WIP: .devcontainer: settings for a codespace workflow

src/remote.c, tests/remote/httpproxy.c
=> Allow proxy options when connecting with a detached remote.

src/remote.c
Using the insteadof helper would leak memory when we didn't really want
the pushInsteadOf configuration.  Refactor the choice into the function
that allocates memory (or now, not) and use a more idiomatic `int`
return code.
=> remote: refactor insteadof application

.github/workflows/nightly.yml
Align the nightly build configuration with our CI builds.
=> ci: build with ssh on nightly

src/checkout.c, src/pack-objects.h, src/rebase.c, src/transports/smart.h, src/worktree.h
Just a minor fix, technically a set signed flag can return -1.
=> c99: change single bit flags to unsigned

ci/test.sh, src/common.h, src/net.c, src/net.h, src/transports/ssh.c, tests/fetchhead/fetchhead_data.h, tests/fetchhead/nonetwork.c, tests/network/url/scp.c, tests/network/url/valid.c, tests/online/fetch.c, tests/online/fetchhead.c, tests/online/remotes.c
=> Support scp style paths with ports

src/odb.c
=> odb: check for write failures

include/git2/common.h, include/git2/errors.h, src/config.c, src/fs_path.c, src/fs_path.h, src/libgit2.c, src/repository.c, src/repository.h, tests/clar_libgit2.c, tests/clar_libgit2.h, tests/core/path.c, tests/main.c, tests/online/clone.c, tests/repo/config.c, tests/repo/open.c
Backport of #6266 to the v1.4 branch.
=> Validate repository directory ownership (v1.4)

CMakeLists.txt, docs/changelog.md, include/git2/version.h, package.json
=> v1.4.3 release

CMakeLists.txt, docs/changelog.md, include/git2/version.h, package.json
=> v1.3.1 release

include/git2/config.h
=> config: update config entry iteration lifecycle

include/git2/status.h
=> status: update documentation for default options

include/git2/version.h, package.json
Get `main` ready to rumble for the next release!
=> meta: update version number to v1.6.0-alpha

src/libgit2/repository.c, tests/libgit2/repo/open.c
=> Add support for "safe.directory *"

tests/libgit2/remote/httpproxy.c
The remote::httpproxy::env test (correctly) reset the environment before running; however the other tests are also impacted by the environment and need to have it isolated.
=> tests: always unset HTTP_PROXY before starting tests

src/libgit2/index.c
Found this randomly while debugging #6517
=> Remove unused wditer variable

README.md, docs/changelog.md, include/git2/version.h, package.json
It's been a long time since a minor release, and we've accrued some great features. Let's ship v1.7!
=> v1.7: release Kleine Raupe Nimmersatt

include/git2/sys/transport.h, src/libgit2/repository.c, src/libgit2/streams/stransport.c, src/libgit2/transports/http.c, src/libgit2/transports/httpclient.c, src/libgit2/transports/ssh.c, src/libgit2/transports/winhttp.c, src/util/net.c, src/util/net.h, tests/libgit2/online/clone.c, tests/util/url/http.c
Backporting #6597, #6599, #6600, #6608, #6610
=> Backports for v1.7

tests/resources/push.sh
The test/Resources/push.sh calls pushd/popd, which is not a POSIX shell feature but a Bash extension.
=> Use #!/bin/bash for script with bash-specific commands

.github/release.yml
Add a compatibility label to the release.yml to describe things that are for improved cross-platform compatibility.
=> release: add a compatibility label

deps/ntlmclient/crypt_commoncrypto.c, include/git2/sys/stream.h, src/cli/opt.c, src/cli/opt.h, src/libgit2/config_parse.c, src/libgit2/refdb_fs.c, src/libgit2/transports/smart.h, src/util/net.c, src/util/process.h, tests/clar/clar.c, tests/clar/clar/fixtures.h, tests/clar/clar/fs.h
* Update the versions of clar and ntlmclient.
* Ensure that we properly use `unsigned int` for bitfields.
* Update an unused (unread) variable
=> Several compatibility fixes

.github/workflows/main.yml
Our workflows push documentation changes; ensure that they are allowed to do so.
=> ci: allow workflows to push changes

src/libgit2/repository.c
Handles case where determining path to grafts files for shallow clones may fail with 'path cannot exist in repository' for an in-memory repository that doesn't have any directories.
To cater for this, empty grafts are created/set on the repository, and if they're already set, are refreshed upfront rather than attempting to derive the path again.
This change is not intended to support shallow clones for in-memory repositories, rather it's intended to preserve prior behavior where we can at least still perform a full clone for an in-memory repository with a custom database backend, without any files stored on-disk.
If a shallow clone were attempted in this scenario, it's likely/expected to fail when attempting to write grafts to file at the end of the clone.  Recommend consideration be …
=> Bypass shallow clone support for in-memory repositories

include/git2/attr.h
=> docs: fix mistake in attr.h

.github/workflows/benchmark.yml, tests/benchmarks/benchmark.sh
Publish a static API with benchmark run results, and a site to view the results interactively.
=> Benchmarks: add a site to view results

include/git2/common.h, src/libgit2/transports/ssh_libssh2.c
fixes https://github.com/libgit2/libgit2/issues/6708 ?
=> set SSH timeout

src/libgit2/repository.c
=> Fix memory leaks

tests/libgit2/pack/packbuilder.c
The packbuilder tests should be deterministic. This comment suggests that they are:
```
/*
* By default, packfiles are created with only one thread.
* Therefore we can predict the object ordering and make sure
* we create exactly the same pack as git.git does when *not*
* reusing existing deltas (as libgit2).
*
* $ cd tests/resources/testrepo.git
* $ git rev-list --objects HEAD | \
*  git pack-objects -q --no-reuse-delta --threads=1 pack
* $ sha1sum pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.pack
* 5d410bdf97cf896f9007681b92868471d636954b
*
*/
```
but it is disappointingly incorrect. As is evidenced by the fact that -- at least on _my_ machine -- that command does not actually produce that output any longer.
Variations in things like the which compression library is actually used, and …
=> packbuilder: adjust nondeterministic tests

src/libgit2/config.c, tests/libgit2/config/configlevel.c
Also, add a test for fetching the `GIT_CONFIG_HIGHEST_LEVEL`.
=> config: correct fetching the HIGHEST_LEVEL config

deps/ntlmclient/ntlm.c, src/libgit2/config.c, src/libgit2/config_parse.c, src/libgit2/path.c, src/libgit2/trailer.c, src/libgit2/transports/smart_pkt.c, src/util/ctype_compat.h, src/util/date.c, src/util/git2_util.h, src/util/str.c, src/util/util.h, tests/libgit2/repo/open.c
An iteration on #6679 to tidy up in advance of v1.8.
=> cast characters to unsigned when classifying characters

src/libgit2/pack.c
Fixes: https://github.com/libgit2/libgit2/issues/6795
=> Bounds check for pack index read

src/util/array.h
Avoid sloppy aliasing in our (re-)allocation, which is undefined behavior. This has been problematic before and was helped by `volatile` (see b62a6a13b2f9a40e6ea4bf7bc2a9255429fb0bd6) but that is not technically correct, and some compilers / architectures do not understand that `ptr` is changing due to its aliasing.
Just make `git_array_alloc` behave like `realloc`, taking a `void *` and returning a `void *`.
=> Update git_array allocator to obey strict aliasing rules

CMakeLists.txt, docs/changelog.md, include/git2/version.h, package.json
Update changelog and version numbers to release v1.8.1
=> libgit2 v1.8.1

include/git2/email.h, include/git2/odb.h, src/libgit2/diff.c, src/libgit2/email.c, src/libgit2/odb.c, tests/libgit2/email/create.c
A small cleanup for libgit2 headers
=> Headers cleanup

src/util/hashmap.h
Quiet down static code analysis.
=> hashmap: asserts

src/util/hashmap.h
Continue to quiet down mediocre static code analysis.
=> hashmap: further asserts

.github/workflows/main.yml, CMakeLists.txt, README.md, cmake/SetCStandard.cmake, deps/ntlmclient/utf8.h, examples/CMakeLists.txt, fuzzers/CMakeLists.txt, include/git2/stdint.h, src/cli/CMakeLists.txt, src/libgit2/CMakeLists.txt, src/util/CMakeLists.txt, tests/headertest/CMakeLists.txt, tests/libgit2/CMakeLists.txt, tests/libgit2/grafts/shallow.c, tests/libgit2/index/tests256.c, tests/util/CMakeLists.txt
Make c standard configurable; defaulting to an extension-free c90
=> Configurable C standard

.github/workflows/benchmark.yml, src/cli/cmd_blame.c, src/cli/cmd_cat_file.c, src/cli/cmd_clone.c, src/cli/cmd_config.c, src/cli/cmd_hash_object.c, src/cli/cmd_help.c, src/cli/cmd_index_pack.c, src/cli/common.h, src/cli/main.c, src/cli/opt_usage.c, src/cli/opt_usage.h, tests/benchmarks/benchmark.sh, tests/benchmarks/benchmark_helpers.sh, tests/benchmarks/blame__git_cached, tests/benchmarks/blame__linux_cached, tests/benchmarks/blame__simple_cached
You can't improve what you can't measure; our blame implementation has historically been a poor performer. Add a benchmark suite so that we can start to track improvements.
=> Add benchmarks for blame

CMakeLists.txt, docs/changelog.md, include/git2/version.h, package.json, src/libgit2/transports/httpparser.c
=> http: Backport `on_status` initialize fix for http-parser

CMakeLists.txt, docs/changelog.md, examples/merge.c, include/git2/commit.h, include/git2/version.h, package.json, src/libgit2/commit.c, src/libgit2/commit.h, src/libgit2/notes.c, src/libgit2/rebase.c, src/libgit2/stash.c, tests/libgit2/checkout/tree.c, tests/libgit2/cherrypick/workdir.c, tests/libgit2/commit/commit.c, tests/libgit2/commit/write.c, tests/libgit2/diff/rename.c, tests/libgit2/odb/freshen.c, tests/libgit2/rebase/sign.c, tests/libgit2/refs/reflog/messages.c, tests/libgit2/revert/workdir.c, tests/libgit2/revwalk/basic.c
=> libgit2 v1.8.4

.github/workflows/documentation.yml, script/api-docs/docs-generator.js, script/api-docs/generate, script/api-docs/package-lock.json, script/api-docs/package.json, script/api-docs/search-generator.js
During documentation generation, create a search page, and add search suggestions to a search box field in each page. Search will be handled on the client side (in browser) by minisearch, using the index we generate.
=> Add search functionality to our docs generator

src/cli/cmd.h, src/cli/cmd_init.c, src/cli/main.c, src/cli/opt_usage.c
Provide a `git init` command. This has been very useful, and has elucidated problems which these PRs address:
- https://github.com/libgit2/libgit2/pull/6981
- https://github.com/libgit2/libgit2/pull/6982
- https://github.com/libgit2/libgit2/pull/6983
=> CLI: introduce `init` command

CMakeLists.txt, docs/changelog.md, include/git2/version.h, package.json
Getting the bits lined up for a v1.9.0 release!
=> libgit2 v1.9

tests/libgit2/config/global.c, tests/libgit2/filter/systemattrs.c
Keep tests contained within our sandbox.
=> Test updates

include/git2/version.h
=> Include common.h in version.h

tests/clar/clar.c, tests/clar/clar.h, tests/clar/clar/fixtures.h, tests/clar/clar/fs.h, tests/clar/clar/print.h, tests/clar/clar/sandbox.h, tests/clar/clar/summary.h, tests/clar/clar_libgit2.c, tests/libgit2/CMakeLists.txt, tests/util/CMakeLists.txt
Update to the latest version (in HEAD) of clar. This affords us improved test directory creation, and the `cl_invoke` helper macro.
=> clar: update to latest version
