libgit2/libgit2

src/diff_tform.c

The function `git_diff_find_similar` keeps a function of cache
similarity metrics signatures, whose size depends on the number of
deltas passed in via the `diff` parameter. In case where the diff is
empty and thus doesn't have any deltas at all, we may end up allocating
this cache via a call to `git__calloc(0, sizeof(void *))`. At least on
AIX, allocating 0 bytes will result in a `NULL` pointer being returned,
which causes us to erroneously return an OOM error.
Fix this situation by simply returning early in case where we are being
passed an empty diff, as we cannot find any similarities in that case
anyway.
---
This should fix #4748

diff: fix OOM on AIX when finding similar deltas in empty diff

---

ci/coverity.sh

As per https://travis-ci.org/libgit2/libgit2/jobs/415921269, which is the cron job.
```
Emitted 525 C/C++ compilation units (100%) successfully
525 C/C++ compilation units (100%) are ready for analysis
The cov-build utility completed successfully.
Build successfully submitted.
Received error code 200 from Coverity
travis_time:end:14cf6373:start=1534254309066933889,finish=1534254728190974302,duration=419124040413
The command "if [ -n "$COVERITY" ]; then ../ci/coverity.sh; fi" exited with 1.
travis_time:start:01ed61d4
$ if [ -z "$COVERITY" ]; then ../ci/build.sh && ../ci/test.sh; fi
travis_time:end:01ed61d4:start=1534254728197560961,finish=1534254728202711214,duration=5150253
The command "if [ -z "$COVERITY" ]; then ../ci/build.sh && ../ci/test.sh; fi" exited with 0.
Done. Your build exited …
```

ci: Correct the status code check so Coverity doesn't force-fail Travis

---

src/config_file.c
tests/config/read.c
tests/resources/config/config-nosection

config_file: Don't crash on options without a section

---

src/parse.c

String operations in libgit2 are supposed to never receive `NULL`, e.g. they are not `NULL`-save. In the case of `git__linenlen()`, invocation with `NULL` leads to undefined behavior.
In a `git_parse_ctx` however, the `content` field used in these operations was initialized to `NULL` if the `git_parse_ctx_init()` was called with `NULL` for `content` or `0` for `content_len`. For the latter case, the initialization function even contained some logic for initializing `content` with `NULL`.
This commit mitigates triggering undefined behavior by rewriting the logic. Now `content` is always initialized to a non-null buffer. Instead of a null buffer, an empty string is used for denoting an empty buffer.
Supersedes #4733. Resolves #4726.

parse: Do not initialize the content in context to NULL

---

.travis.yml

With the recent addition of VSTS to our CI infrastructure, we now have
two cron jobs running regular Coverity analysis. It doesn't really make
a lot of sense to upload two different analysis on our sources to
Corverity, though:
- in the worst case, Coverity will be repeatedly confused when different
sets of sources get analyzed and uploaded
- in the best case, nothing is gained because the sources have already
been analyzed via the other job
Let's just use a single cron job for Coverity. Considering that VSTS
seems to be the more beefy and flexible platform, it is more likely to
be our future target CI platform. Thus, we retain its support for
Coverity and instead remove it from Travis.

travis: remove Coverity cron job

---

tests/threads/diff.c
tests/threads/iterator.c

Our thread policies state that we cannot re-use the `git_repository`
across threads.  Our tests cannot deviate from that.

threads::diff: use separate git_repository objects

---

src/transports/smart_pkt.c

Fix 'invalid packet line' for ng packets containing errors

---

src/worktree.c
tests/worktree/worktree.c

The documentation states that git_worktree_unlock returns 0 on success,
and 1 on success if the worktree wasn't locked. Turns out we were
returning 0 in any of those cases.
Found it while writing test cases for Objective-Git.

worktree: unlock should return 1 when the worktree isn't locked

---

cmake/Modules/FindIconv.cmake

While most systems provide a separate iconv library against which
applications can link, musl based systems do not provide such a library.
Instead, iconv functions are directly included in the C library. As our
current CMake module to locate the iconv library only checks whether a
library exists somewhere in the typical library directories, we will
never build libgit2 with libiconv support on such systems.
Extend the iconv module to also search whether libc provides iconv
functions, which we do by checking whether the `iconv_open` function
exists inside of libc. If this is the case, we will default to use the
libc provided one instead of trying to use a separate libiconv. While
this changes which iconv we use on systems where both libc and an
external libiconv exist, to the best of my …

cmake: detect and use libc-provided iconv

---

examples/network/index-pack.c
include/git2/indexer.h
src/blob.c
src/blob.h
src/commit.c
src/commit.h
src/indexer.c
src/object.c
src/object.h
src/odb_pack.c
src/pack-objects.c
src/pack-objects.h
src/tag.c
src/tag.h
src/tree.c
src/tree.h
tests/pack/indexer.c
tests/pack/packbuilder.c

Warning: this is ugly and, at least to me, in many places it feels like I'm doing hacks over hacks to work around our object system. The main problem here is that we currently cannot parse objects which are not owned by the ODB system, because our objects point into the reference-counted memory of the ODB. So when I try to parse an object which is not owned by the ODB, then this will crash later on after `git_odb_object_deref`, as it tries to free objects which aren't owned by itself or not even part of the heap. So yeah, this doesn't look as nice as it could in an ideal world.
On the other hand, this seems to work just fine right now. After nearly a whole day of cursing and debugging I think I've finally got it right. So what do I do? This is mostly the implementation of `git index-pack …

Pack file verification

---

.vsts-ci.yml
.vsts-nightly.yml

The VSTS YAML syntax has evolved to use "pool" instead of "queue" and "job" instead of "phase".  Additionally, this PR adds use of the "Ubuntu 16.04" pool which has performance benefits over "Hosted Linux Preview."

Update VSTS YAML files with the latest syntax

---

src/odb_pack.c

When running repack while doing repo writes, `packfile_load__cb()` can see some temporary files in the directory that are bigger than the usual, and makes `memcmp` overflow on the `p->pack_name` string. ASAN detected this. This just uses `strncmp`, that should not have any performance impact and is safe for comparing strings of different sizes.
```
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61200001a3f3 at pc 0x7f4a9e1976ec bp 0x7ffc1f80e100 sp 0x7ffc1f80d8b0
READ of size 89 at 0x61200001a3f3 thread T0
SCARINESS: 26 (multi-byte-read-heap-buffer-overflow)
#0 0x7f4a9e1976eb in __interceptor_memcmp.part.78 (/build/cfgr-admin#link-tree/libtools_build_sanitizers_asan-ubsan-py.so+0xcf6eb)
#1 0x7f4a518c5431 in packfile_load__cb …
```

Prevent heap-buffer-overflow

---

src/config_file.c

In case where we add multiple configuration entries with the same key to
a diskfile backend, we always need to iterate the list of this key to
find the last entry due to the list being a singly-linked list. This
is obviously quadratic behaviour, and this has sure enough been found by
oss-fuzz by generating a configuration file with 50k lines, where most
of them have the same key. While the issue will not arise with "sane"
configuration files, an adversary may trigger it by providing a crafted
".gitmodules" file, which is delivered as part of the repo and also
parsed by the configuration parser.
The fix is trivial: store a pointer to the last entry of the list in its
head. As there are only two locations now where we append to this data
structure, mainting this pointer is trivial, too. We …

config_file: fix quadratic behaviour when adding config multivars

---

src/push.c
src/push.h
src/remote.c
src/remote.h

This makes it easier to pass connection-related options around (proxy & custom headers for now).
This fixes a bug in `git_push_finish`, which didn't reuse the provided proxy if the connection closed between the call to `git_remote_push` and the finish step.

remote: store the connection data in a private struct

---

include/git2/revwalk.h

Show more directly what the sorting modes correspond to in git's `rev-list` as
that's the reference implementation for what the possible sorting orders are.

revwalk: refer the sorting modes more to git's options

---

src/path.c

ARM treats its `char` type as `unsigned type` by default; as a result, testing a `char` value as being `< 0` is always false.  This is a warning on ARM, which is promoted to an error given our use of `-Werror`.
Per ISO 9899:199, section "6.2.5 Types":
> The three types char, signed char, and unsigned char are collectively
> called the character types. The implementation shall define char to
> have the same range, representation, and behavior as either signed
> char or unsigned char.
>
...
> Irrespective of the choice made, char is a separate type from the other
> two and is not compatible with either.

path validation: `char` is not signed by default.

---

src/revwalk.c

When porting, we overlooked that the difference between git's and our's time
representation and copied their way of getting the max value.
Unfortunately git was using unsigned integers, so `~0ll` does correspond to
their max value, whereas for us it corresponds to `-1`. This means that we
always consider the last date to be smaller than the current commit's and always
think commits are interesting.
Change the initial value to the macro that gives us the maximum value on each
platform so we can accurately consider commits interesting or not.
The second commit is mostly just to reduce the drift from git, the actual perf difference should be negligible.
This fixes #4740 and we should backport it as it fixes a regression.

Fix revwalk limiting regression

---

CMakeLists.txt

We do not currently have any warnings in this regard, but it's good practice to
have them on in case we introduce something.
Ideally we would also have `-Wformat-nonliteral` but we actually use it a lot and at least GCC cannot differentiate between static strings and stuff we've accepted from users, unfortunately.

cmake: enable -Wformat and -Wformat-security

---

src/remote.c

This is to improve performance of `git_remote_prune`. Before this change it got **O(n * n)**  complexity, now it is **O(n * logn)**.

git_remote_prune to be O(n  * logn)

---

tests/online/clone.c

Before resetting the url and username, ensure that we free them in case they were set by environment variables.  (This is definitely a bit ugly, but since the callbacks make use of the globals, this was the most straightforward way to keep that consistent without leaking.)

online::clone: free url and username before resetting

---

src/index.c
src/vector.c
tests/core/vector.c

Previously we would assert in index_free because the reader incrementation would not be balanced. Release the snapshot normally, so the variable gets decremented before the index is freed.
Fixes #4802.

index: release the snapshot instead of freeing the index

---

src/config.c
src/config.h
src/config_backend.h
src/config_entries.c
src/config_entries.h
src/config_file.c
src/config_file.h
src/config_mem.c
src/config_parse.c
src/config_parse.h
src/submodule.c
tests/config/memory.c
tests/config/readonly.c
tests/config/write.c

So finally I hold true to my promise to refactor our config code (once again) and create an in-memory configuration backend. I think the result is quite pleasant due to the refactorings, and in fact the in-memory backend implementation is only a bit more than a hundred lines of code (excluding the stubs).
This series has three phases:
1. Refactorings to make our config file more generic with regards to names. Most importantly, many things are renamed from "git_config_file_*" to "git_config_backend_*" to express that they are actually backend-agnostic.
2. I pull out the "config_entries" store from the "git_config_file" backend that abstracts iteration order and memory management for config entries.
3. I create the "git_config_mem" backend based on that store, which is rather trivial to do …

In-memory configuration

---

include/git2/checkout.h
include/git2/config.h
include/git2/transport.h

While looking at the worktree documentation, I managed to listen to a few of the "undocumented" warnings my tweaked docurium raises. So here's a few smallish additions/fixes to documentation comments.

Documentation fixups

---

src/pack-objects.c

Blobs that have been marked as uninteresting should not be inserted into packbuilder
when inserting a tree. The check as to whether a blob was uninteresting looked at
the status for the tree itself instead of the blob.
This could cause significantly larger packfiles.

fix check if blob is uninteresting when inserting tree to packbuilder

---

src/config_file.c
tests/config/include.c

config_file: properly ignore includes without "path" value
In case a configuration includes a key "include.path=" without any
value, the generated configuration entry will have its value set to
`NULL`. This is unexpected by the logic handling includes, and as soon
as we try to calculate the included path we will unconditionally
dereference that `NULL` pointer and thus segfault.
Fix the issue by returning early in both `parse_include` and
`parse_conditional_include` in case where the `file` argument is `NULL`.
Add a test to avoid future regression.
The issue has been found by the oss-fuzz project, issue 10810.

config_file: properly ignore includes without "path" value

---

src/submodule.c
tests/submodule/inject_option.c

These can be used to inject options in an implementation which performs a
recursive clone by executing an external command via crafted url and path
attributes such that it triggers a local executable to be run.
The library is not vulnerable as we do not rely on external executables but a
user of the library might be relying on that so we add this protection.
This matches this aspect of git's fix for CVE-2018-17456.
---
This has been released as part of v0.26.7 and v0.27.5

submodule: ignore path and url attributes if they look like options

---

src/transports/http.c

``auth_context_match`` returns -1 when the authentication context is not supported,
but this made ``parse_authenticate_response`` fail in situations where some authentication
contexts are supported and others are not.
``parse_authenticate_response`` will instead ignore authentication contexts where
``auth_context_match`` returns -1
This specifically handles recent changes to visualstudio.com that responds with:
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/a4c0aef7-6fdd-4c0e-b678-0dd23c73d08a
WWW-Authenticate: Basic realm=\"https://tfsprodweu2.app.visualstudio.com/\"
WWW-Authenticate: TFS-Federated
when asking for authentication and the http transport didn't know what to do with ``WWW-Authenticate: Bearer`` returning ``error=-1`` …

ignore unsupported http authentication contexts

---

tests/core/rmdir.c

**Update**: I cannot reproduce the issue any more which was the initial reason for this MR, however, this is a good extension for the test cases now...
**old**: When working on another issue I found that git_futils_rmdir_r does not delete an empty path hierarchy, just the last folder

Add some more tests for git_futils_rmdir_r and some cleanup

---

fuzzers/config_file_fuzzer.c
src/config_backend.h
src/config_mem.c
tests/config/memory.c

In quick testing, I see this hitting up to about 10k exec/s starting with an empty corpus on one core of my laptop, versus about 1500 for the old one.

config: Port config_file_fuzzer to the new in-memory backend.

---

CMakeLists.txt

We use libssh2.  We do not use libssh.  Make sure to disambiguate them correctly.

cmake: correct comment from libssh to libssh2

---

include/git2/sys/path.h
src/path.h

These checks are preformed by libgit2 on checkout, but they're also useful for
performing checks in applications which do not involve checkout.
Expose them under `sys/` as it's still fairly in the weeds even for this
library.

path: export the dotgit-checking functions

---

src/config_parse.c
tests/config/read.c

This is an quirk of the config format, but you are allowed to do
[some] var = true
and have `some.var` exist. Our parser currently assumes everything is line-based and completely ignores anything past the closing bracket.
So this changes the section parser functions to return how far we should advance and then we restart. For the "normal" case, we'll detect the rest is an empty line and immediately jump to the next line and if we do find this situation we'll run the loop as though this were a brand new line.

Configuration variables can appear on the same line as the section header

---

azure-pipelines.yml
ci/setup-osx.sh

A quick attempt at #4838. This also explicitly selects OpenSSL as a backend, just to make sure it doesn't auto-disable it.

Ninja build

---

src/merge.c
tests/merge/workdir/simple.c

When the index in memory diverges from the index in disk `git_merge`
aborts with `GIT_ECONFLICT`. More details about this are found in the 
issue #4203, which this PR attempts to fix.
A further discussion is needed wether this behaviour is actually desired.
(Suppose someone actually is writing something to the index in memory
and a concurrent task is merging. A possible argument is that the index
should be written to disk then.)
Closes #4203

merge: reload index before git_merge

---

include/git2/common.h
src/alloc.c
tests/buf/oom.c

Create a custom allocator for the `buf::oom` tests that will fail with out-of-memory errors in predictable ways.  We were previously trying to guess the way that various allocators on various platforms would fail in a way such that `malloc`/`realloc` would return `NULL` (instead of aborting the application, or appearing suspicious to various instrumentation or static code analysis tools like valgrind.)
Introduce a fake `malloc` and `realloc` that will return `NULL` on allocations requesting more than 100 bytes.  Otherwise, we proxy to the default allocator.  (It's important to use the _default_ allocator, not just call `malloc`, since the default allocator on Windows CI builds may be the debugging C runtime allocators which would not be compatible with a standard `malloc`.)

 buf::oom tests: use custom allocator for oom failures

---

ci/test.ps1

PowerShell can _read_ top-level variables in functions, but cannot _update_ top-level variables in functions unless they're explicitly prefixed with `$global`.

Windows CI: fail build on test failure

---

azure-pipelines/nightly.yml
ci/test.ps1
ci/test.sh

With the recent v0.26 and v0.27 point releases, it became obvious that the `ctest` invocation code in our CI builds was fraught.  Reject invalid / not found test names immediately and clearly.
Additionally, update the nightly build template path.

ci: Fix some minor issues

---

README.md

Doesn't strictly depend on #4798 but it probably makes more sense to wait until that's merged.

README: more CI status badges

---

src/tree.c
src/util.c
tests/core/strtol.c
tests/object/tree/parse.c

Various fixes to our parser of tree objects. Many of them have been pointed out by oss-fuzz and are of out-of-bounds nature. But in fact, they aren't really harmful: The object parsing fuzzer intentionally uses a buffer that may _not_ be NUL terminated, while objects from the ODB will always have a trailing NUL byte and thus the OOB reads will never happen in real-world code.

Tree parsing fixes

---

src/transports/smart.c

After creating a transport for a server, we expect to be able to call
`connect`, then invoke subsequent `action` calls.  We provide the URL to
these `action` calls, although our built-in transports happen to ignore
it since they've already parsed it into an internal format that they
intend to use (`gitno_connection_data`).
In ca2eb4608243162a13c427e74526b6422d5a6659, we began clearing the URL
field after a connection, meaning that subsequent calls to transport
`action` callbacks would get a NULL URL, which went undetected since the
builtin transports ignore the URL when they're already connected
(instead of re-parsing it into an internal format).
Downstream custom transport implementations (eg, LibGit2Sharp) did
notice this change, however.
Since `reset_stream` is called even when we're …

smart transport: only clear url on hard reset (regression)

---

tests/apply/both.c
tests/apply/partial.c
tests/apply/workdir.c

Some minor fixups in the "apply" test suite that have been noticed by Coverity.

apply: small fixups in the test suite

---

src/patch_parse.c
src/util.c
tests/core/strtol.c

When parsing a number, we accept a leading plus or minus sign to return
a positive or negative number. When the parsed string has such a leading
sign, we set up a flag indicating that the number is negative and
advance the pointer to the next character in that string. This misses
updating the number of bytes in the string, though, which is why the
parser may later on do an out-of-bounds read.
Fix the issue by correctly updating both the pointer and the number of
remaining bytes. Furthermore, we need to check whether we actually have
any bytes left after having advanced the pointer, as otherwise the
auto-detection of the base may do an out-of-bonuds access. Add a test
that detects the out-of-bound read.
Note that this is not actually security critical. While there are a lot
of places where …

strntol: fix out-of-bounds reads when parsing numbers with leading sign

---

src/netops.c
src/netops.h
src/transports/http.c

When the port is omitted, the server assumes the default port for the
service is used (see
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host). In
cases where the client provided a non-default port, it should be passed
along.
This hasn't been an issue so far as the git protocol doesn't include
server-generated URIs. I encountered this when implementing Rust
registry support for Sonatype Nexus. Rust's registry uses a git
repository for the package index. Clients look at a file in the root of
the package index to find the base URL for downloading the packages.
Sonatype Nexus looks at the incoming HTTP request (Host header and URL)
to determine the client-facing URL base as it may be running behind a
load balancer or reverse proxy. This client-facing URL base is then used
to …

transport/http: Include non-default ports in Host header

---

include/git2/worktree.h

This change adds missing `GIT_EXTERN` declaration to `git_worktree_add_init_options` function.

worktree: Expose git_worktree_add_init_options

---

src/streams/openssl.c

Reading #4644 was eerily familiar, so it made me start looking for "that patch I had written but now I can't find it" 😉.
This is extracted from #4786, I'm not sure if it is the complete story, but at least it would help downstream (and us) to pinpoint the reason for those failures.

Some OpenSSL issues

---

src/apply.c
tests/apply/fromfile.c

Handle two null argument cases that occur in the unit tests.
One is in library code, the other is in test code.
Detected by running unit tests with undefined behavior sanitizer:
```bash
mkdir build && cd build
cmake -DBUILD_CLAR=ON -DCMAKE_C_FLAGS="-fsanitize=address \
-fsanitize=undefined -fstack-usage -static-libasan" ..
cmake --build .
ASAN_OPTIONS="allocator_may_return_null=1" ./libgit2_clar
...
............../libgit2/src/apply.c:316:3: runtime error: null pointer \
passed as argument 1, which is declared to never be null
...................../libgit2/tests/apply/fromfile.c:46:3: runtime \
error: null pointer passed as argument 1, which is declared to never be null
```

tests: 🌀 address two null argument instances

---

include/git2/index.h
include/git2/types.h
src/index.c
src/index.h
tests/index/tests.c

Provide a public git_index_iterator API that is backed by an index snapshot.  This allows consumers to provide a stable iteration even while manipulating the index during iteration.

index: introduce git_index_iterator

---

src/repository.c

Introduced in commit b433a22a979ae78c28c8b16f8c3487e2787cb73e.

Fix warning C4133 incompatible types in MSVC

---

include/git2/errors.h
include/git2/sys/transport.h
include/git2/types.h
src/transports/http.c
src/transports/smart.c
src/transports/ssh.c
src/transports/winhttp.c

Custom transports may want to ask libgit2 to invoke a configured credential or certificate callback; however they likely do not know if a callback was actually configured.  Return a sentinal value (greater than zero) if there is no callback configured instead of crashing.
With this, we want to define what `> 0` means for these callbacks, because they themselves might return it.  Credential callbacks are already defined to return `> 0` to defer these checks, but they were only inconsistently implemented (winhttp supported this, http and ssh transports did not).  Add this support consistently to all transports for both credential callbacks and certificate checking.

Allow certificate and credential callbacks to decline to act

---

src/config.c
tests/config/read.c

When we try to add a configuration file with `git_config_add_file_ondisk`, we
treat nonexisting files as empty. We do this by performing a stat call, ignoring
ENOENT errors. This works just fine in case the file or any of its parents
simply does not exist, but there is also the case where any of the parent
directories is not a directory, but a file. So e.g. trying to add a
configuration file "/dev/null/.gitconfig" will fail, as `errno` will be ENOTDIR
instead of ENOENT.
Catch ENOTDIR in addition to ENOENT to fix the issue. Add a test that verifies
we are able to add configuration files with such an invalid path file just fine.
This should probably fix #4897.

config: fix adding files if their parent directory is a file

---

include/git2/revwalk.h
src/revwalk.c
tests/revwalk/hidecb.c

Remove the check for existing `hide_cb` and conditionally set the `limited` flag.
Fixes https://github.com/libgit2/libgit2/issues/4887

revwalk: Allow changing hide_cb

---

include/git2/merge.h
src/merge.c
src/refs.c
src/refs.h
src/repository.c
tests/merge/workdir/analysis.c

This adds a new `git_merge_analysis_any` function that can be used to check a merge against any given reference, as right now we only support checking `HEAD`.
Inspired by https://github.com/libgit2/objective-git/pull/629.

Allow merge analysis against any reference

---

src/filter.c

When a `git_filter_apply_fn` callback returns a error while smudging `proxy_stream_close`
ends up [returning](https://github.com/libgit2/libgit2/blob/master/src/filter.c#L829) without closing the stream. This is turn makes `blob_content_to_file`
crash as it [asserts](https://github.com/libgit2/libgit2/blob/master/src/checkout.c#L1555) the stream being closed whether there are errors or not.
Closing the target stream on error fixes this problem, with the downside being that
error strings set by `proxy_stream->target->close()` will override ones set by `git_filter_apply_fn`
callback.

make proxy_stream_close close target stream even on errors

---

src/odb_loose.c

If the routine exits with error before stream or hash_ctx is initialized, the
program will segfault when trying to free them.

Fix segfault in loose_backend__readstream

---

include/git2/refs.h
src/annotated_commit.c
src/refs.c
tests/merge/annotated_commit.c

This got a bit messy with the `const`ness of `git_reference_peel` and I'm happy to move that to its own PR if y'all want.
The crux of this is to use `git_reference_peel` instead of `git_reference_resolve` so we get the id of the commit regardless of how much wrapping there is around it.
This fixes #4909

Support creating annotated commits from annotated tags

---

src/refdb_fs.c
tests/refs/branches/delete.c

Remove empty (sub-)directories when deleting refs

---

src/transports/smart.c

After creating a transport for a server, we expect to be able to call
`connect`, then invoke subsequent `action` calls.  We provide the URL to
these `action` calls, although our built-in transports happen to ignore
it since they've already parsed it into an internal format that they
intend to use (`gitno_connection_data`).
In ca2eb4608243162a13c427e74526b6422d5a6659, we began clearing the URL
field after a connection, meaning that subsequent calls to transport
`action` callbacks would get a NULL URL, which went undetected since the
builtin transports ignore the URL when they're already connected
(instead of re-parsing it into an internal format).
Downstream custom transport implementations (eg, LibGit2Sharp) did
notice this change, however.
Since `reset_stream` is called even when we're …

smart transport: only clear url on hard reset

---

src/global.c
src/hash.h
src/hash/hash_collisiondetect.h
src/hash/hash_common_crypto.h
src/hash/hash_generic.h
src/hash/hash_mbedtls.h
src/hash/hash_openssl.h

It randomly occurred to me that we can avoid manually updating the `MAX_SHUTDOWN_CB` macro whenever we add a new global initializer by just declaring the initializers as an array and then using the initializer array's size to declare the shutdown array. This PR does exactly that as a small cleanup.

Shutdown callback count

---

src/apply.c
tests/index/crlf.c

This change fixes -Wmaybe-uninitialized and -Wdeprecated-declarations
warnings on Linux builds.

Fix Linux warnings

---

src/crlf.c

All other places don't use git_cvar_value as type.

Fix warning 'function': incompatible types - from 'git_cvar_value *' to 'int *' (C4133) on VS

---

CMakeLists.txt

Just noticed that while investigating #4924.
After taking into consideration the following, I think this should be removed :
- OpenSSL isn't the default on Apple platforms
- you have to jump through hoops to get CMake to use OpenSSL on macOS (headers aren't in `/usr/include`, so you have to provide `-DOPENSSL_*` overrides)
- users are likely (as getting anywhere near the installed 0.9.8 version is insanity IMHO) to package a "modern" version, which wouldn't be marked as deprecated
There might be a way to detect which version is getting used, or maybe `#pragma` the deprecation warnings out of `openssl.c` instead.

Remove unconditional -Wno-deprecated-declaration on macOS

---

src/transports/http.c
tests/online/clone.c

This broke recently. If no proxy is detected, the URL remains unset but it still gets into `gitno_connection_data_from_url` which has `assert(url)`.

Fix crash on remote connection when GIT_PROXY_AUTO is set but no proxy is detected

---

azure-pipelines/coverity.yml
azure-pipelines/nightly.yml
ci/test.ps1
ci/test.sh
tests/CMakeLists.txt
tests/iterator/workdir.c

Since Coverity is down at the moment with no timeframe, isolate it from the nightly run. I think it also makes sense from a concern-separation POV, as it insulates the Azure "hosted" pipelines from flakyness.
This also attempts to enable the few `GITTEST_INVASIVE_FS_SIZE` (though I'm not sure how Azure will react, or if my `run_test` invocation is valid 🤞).

Some CI enhancements

---

examples/cat-file.c
examples/common.c
examples/for-each-ref.c
examples/general.c
examples/log.c
examples/merge.c
examples/tag.c
fuzzers/objects_fuzzer.c
fuzzers/packfile_fuzzer.c
include/git2/types.h
src/annotated_commit.c
src/object.c
src/object.h
src/odb.c
src/odb_loose.c
src/pack.c
src/revparse.c
src/tag.c
tests/object/raw/data.h
tests/object/raw/type2string.c

Some further tweaks on moving to `git_object`.  We use the term "invalid" to refer to bad or malformed data, eg `GIT_REF_INVALID` and `GIT_EINVALIDSPEC`.  Since we're changing the names of the `git_object_t`s in this release, update it to be `GIT_OBJECT_INVALID` instead of `BAD`.
Per @tiennou's [note](https://github.com/libgit2/libgit2/pull/4917#discussion_r246396591) in #4917, I've also updated the compatibility declarations to be `static const int`s instead of `#define`s, allowing us to mark them as deprecated using `GIT_DEPRECATED`.
Doing so illustrated some places where we were continuing to use the old names internally; they've also been updated.

More `git_obj` to `git_object` updates

---

examples/for-each-ref.c
examples/general.c
include/git2/refs.h
include/git2/types.h
src/branch.c
src/refdb_fs.c
src/refs.c
src/refs.h
src/refspec.c
src/remote.c
src/repository.c
src/transaction.c
src/transports/local.c
src/transports/smart_protocol.c
tests/checkout/checkout_helpers.c
tests/commit/write.c
tests/network/fetchlocal.c
tests/online/clone.c
tests/rebase/merge.c
tests/refs/branches/delete.c
tests/refs/create.c
tests/refs/normalize.c
tests/refs/overwrite.c
tests/refs/read.c
tests/refs/rename.c
tests/refs/setter.c
tests/refs/update.c
tests/repo/init.c

Again, for consistency:  our reference function names are all `git_reference_*`.  This PR updates the `git_ref_t` enum to be named `git_reference_t`; its values are now `GIT_REFERENCE_*`.  In addition, `GIT_REF_OID` has been renamed to `GIT_REFERENCE_DIRECT` for standardization with other git and libgit2 terminology.
The old names forward to the new names, but are now marked as deprecated.

Move `git_ref_t` to `git_reference_t`

---

src/odb.c
src/odb_pack.c
tests/odb/foreach.c

Hi,
This should be fix for #4946 .
I'm not familiar with internals, but all tests pass and I did add one new for this case. I don't like that copy/paste, so I was thinking about using struct (or 2 int array) so that only one callback exists in test. What do you think about that?
Also, should anything else be changed?
Thank you.

odb: Fix odb foreach to also close on positive error code

---

src/errors.c

Fix VS warning C4098: 'giterr_set_str' : void function returning a value

---

CMakeLists.txt
docs/changelog.md
examples/general.c
fuzzers/objects_fuzzer.c
include/git2.h
include/git2/buffer.h
include/git2/deprecated.h
include/git2/errors.h
include/git2/index.h
include/git2/refs.h
include/git2/sys/stream.h
include/git2/types.h
src/streams/registry.c
tests/stream/deprecated.c
tests/stream/registration.c

Provide a new kindler, gentler deprecation policy for the upcoming release.
1. Move deprecated bits into their own header file `deprecated.h`.
2. Remove the `GIT_DEPRECATED` attribute from the deprecated bits.  This will allow users to more gently move into the new functions at their leisure.  We have no hurry in removing the old functions or values, so let's not rush things.
3. Allow users to opt-in to a harder deprecation, by defining `GIT_DEPRECATE_HARD` to completely remove the deprecated functions.
4. Enable `GIT_DEPRECATE_HARD` ourselves to ensure that we don't use them in the library code, tests, or examples.
I've kept the `GIT_DEPRECATED` macro so that we can mark something as properly deprecated, using the compiler attributes, in the future if we desire.

Deprecate functions and constants more gently

---

azure-pipelines/nightly.yml

I was originally trying to get the ppc64 builds working, but the emulator seems to not love emulating that platform.  I'm abandoning that but taking the update to use the `latest` images.

Nightlies: use `latest` docker images

---

CMakeLists.txt
src/apply.c
src/attr_file.c
src/blame.c
src/blob.c
src/blob.h
src/buffer.c
src/delta.c
src/describe.c
src/diff.c
src/diff_generate.c
src/diff_stats.c
src/filter.c
src/index.c
src/iterator.c
src/notes.c
src/odb.c
src/odb_loose.c
src/patch_parse.c
src/reader.c
src/streams/mbedtls.c
src/streams/openssl.c
src/streams/socket.c
src/streams/stransport.c
src/transports/git.c
src/tree.c
src/win32/msvc-compat.h
tests/core/zstream.c
tests/index/racy.c

This cleans up some warnings encountered building on Win32 with MSVC.  This PR attacks all the x86 warnings.  (Some remain on amd64.)

Clean up some warnings

---

azure-pipelines.yml

Run docurium as part of the build.  The goal of this is to be able to evaluate the documentation in a given pull request; as such, this does not implement any sort of deployment pipeline.
This will allow us to download a snapshot of the documentation from the CI build and evaluate the docs for a particular pull request; before it's been merged.

ci: run docurium to create documentation

---

azure-pipelines/nightly.yml

Like 811c1c0f8f80521dccc746a7bff180cd77a783ff, disable the SSH tests on macOS until we can resolve the newly introduced infrastructure issues.

ci: skip ssh tests on macOS nightly

---

include/git2/common.h
src/pack.c
src/settings.c
tests/pack/packbuilder.c

Retrieving commits involving looking for pack files. Any file operation for git repositories accessed over NAS has a huge performance impact.
For repositories which do not require retaining pack files, we can avoid a call to check for existence of '.keep' file and reduce the overall latency.

Allow bypassing check for '.keep' file

---

src/branch.c
src/refs.c
src/repository.c
src/repository.h
src/worktree.c
tests/refs/branches/checkedout.c
tests/worktree/worktree.c

Previously, we have determined whether a branch is checked out or not by simply checking the repo and all its worktree HEADs. This is the wrong thing to do in case where we have a bare repo, as a bare repo's HEAD will not be checked out but only indicate the "default" branch. This is getting fixed by this PR.
Furthermore, we'll now verify a given ref when adding new worktrees before creating the on-disk data structures. In case where the ref is invalid, we'll now stop leaving behind those files.
This fixes #4977

Enable creation of worktree from bare repo's default branch

---

azure-pipelines.yml

When a commit is pushed or merged into one of the release branches (`master`, `maint/*`) then push the documentation update to gh-pages.

ci: publish documentation on merge

---

src/odb.c

This change fixes a mostly theoretical memory leak in got_odb_new()
that can only manifest if git_cache_init() fails due to running out of
memory or not being able to acquire its lock.

Fix a _very_ improbable memory leak in git_odb_new()

---

src/stdalloc.c

This change avoids calling realloc(3) in more than one place.

Make stdalloc__reallocarray call stdalloc__realloc

---

src/odb.c
tests/odb/mixed.c

This change frees a copy of a cached object in odb_otype_fast().

Fix a memory leak in odb_otype_fast()

---

src/cache.c
src/cache.h
src/odb.c
src/repository.c

Functions that free a structure's contents but not the structure
itself shall be named `dispose` in the libgit2 project, but the
function `git_cache_free` does not follow this naming pattern.
Fix this by renaming it to `git_cache_dispose` and adjusting all
callers to make use of the new name.

cache: fix misnaming of `git_cache_free`

---

src/refdb_fs.c

This is a different approach to #4981 that should correctly fix the issues described by @peff. 
There had been an ordering dependency between loading loose and packed refs in that loading loose refs set the PACKREF_SHADOWED flag in already loaded packed refs. Upon reloading packed refs, this flag gets reset. Due to that, we always had to load loose and packed refs in the wrong order. This PR fixes this dependency and thus allows us to first load the loose refs and only afterwards load the packed refs, effectively mitigating the race.
It also fixes the same race condition in the `exists` callback that has been pointed out by @peff, too.

refdb_fs: fix loose/packed refs lookup racing with repacks

---

examples/clone.c
examples/fetch.c
examples/index-pack.c
fuzzers/packfile_fuzzer.c
include/git2/deprecated.h
include/git2/indexer.h
include/git2/odb.h
include/git2/odb_backend.h
include/git2/pack.h
include/git2/remote.h
include/git2/sys/odb_backend.h
include/git2/sys/transport.h
include/git2/types.h
src/fetch.c
src/indexer.c
src/odb.c
src/odb_pack.c
src/pack-objects.c
src/remote.c
src/remote.h
src/transports/local.c
src/transports/smart.h
src/transports/smart_protocol.c
tests/clone/nonetwork.c
tests/network/fetchlocal.c
tests/online/clone.c
tests/online/fetch.c
tests/pack/indexer.c
tests/pack/packbuilder.c

While going through the API, I found it strange that object database functions took a "transfer progress" callback.  In fact, this is a callback for _indexer_ progress that happened to start life as reporting for transfers.
Rename it as such, updating the internal usages and creating a typedef for the old names for backward compatibility.

Rename git_transfer_progress to git_indexer_progress

---

include/git2/sys/odb_backend.h
src/odb.c

The `git_odb_backend_malloc` name is a system function that is provided for custom ODB backends and allows them to allocate memory for an ODB object in the read callback.  This is important so that libgit2 can later free the memory used by an ODB object that was read from the custom backend.
(Simply taking data from the backend that _it_ allocated means that we don't know how to free it, we could be using two different allocators if the library was built "normally" and the app in question has an instrumented allocator for debugging then libgit2 could not `free` the data allocated by the custom backend.)
However, if an error occurs in the custom backend after the memory has been allocated for the custom object but before it's returned to libgit2, the custom backend has no way to free that …

odb: provide a free function for custom backends

---

include/git2/deprecated.h
include/git2/remote.h

For consistency with other "type" enums, rename `git_remote_completion_type` to `git_remote_completion_t`.

remote: Rename git_remote_completion_type to _t

---

README.md

The old URL points to https://github.com/alexcrichton/git2-rs, which is redirected to https://github.com/rust-lang/git2-rs. This fix avoids the recirect.

[Doc] Update URL to git2-rs

---

src/hash.h
src/hash/hash_win32.c
src/hash/hash_win32.h

This means the forward declaration isn't necessary.  The forward
declaration can cause compilation errors as it conflicts with the
`GIT_INLINE` declaration (the signatures are different).
/cc @rafeca

Each hash implementation should define `git_hash_global_init`

---

src/xdiff/xdiffi.c

Fixes a typo that was introduced in f347a441c81c4e16dd54de07c5070eca8fccd5c8
I found this when the R bindings [git2r](https://github.com/ropensci/git2r) (bundles libgit2) failed to build on Solaris using Oracle Developer Studio 12.6.

xdiff: fix typo

---

src/util.c
src/util.h

See https://github.com/libgit2/libgit2/issues/4230#issuecomment-471710359 for context. This is diff optimization PR 1/3. The smallest of the three both in terms of code delta and impact.
Three hand-rolled string comparison functions -- git__prefixcmp, git__strcmp and git__strncmp -- are showing up on the CPU profile when scanning working directory of chromium repository on Linux. This PR optimizes git__prefixcmp and replaces the other two functions with standard equivalents (unless `GIT_WIN32` is defined).
Test:
```zsh
cd ~/libgit2
mkdir build
cd build
cmake \
-DUSE_ICONV=OFF           \
-DBUILD_CLAR=ON           \
-DUSE_SSH=OFF             \
-DUSE_HTTPS=OFF           \
-DTHREADSAFE=OFF          \
-DBUILD_SHARED_LIBS=OFF   \
-DUSE_EXT_HTTP_PARSER=OFF \
-DUSE_BUNDLED_ZLIB=ON     \ …
```

Optimize string comparisons

---

src/patch_parse.c
tests/diff/parse.c
tests/patch/patch_common.h

The diff header format is a strange beast in that it is inherently
unparseable in an unambiguous way. While parsing
a/file.txt b/file.txt
is obvious and trivially doable, parsing a diff header of
a/file b/file ab.txt b/file b/file ab.txt
is not (but in fact valid and created by git.git).
Due to that, we have relaxed our diff header parser in commit 80226b5f6
(patch_parse: allow parsing ambiguous patch headers, 2017-09-22), so
that we started to bail out when seeing diff headers with spaces in
their file names. Instead, we try to use the "---" and "+++" lines,
which are unambiguous.
In some cases, though, we neither have a useable file name from the
header nor from the "---" or "+++" lines. This is the case when we have
a deletion or addition of a file with spaces: the header is …

patch_parse: fix parsing addition/deletion of file with space

---

tests/config/global.c
tests/repo/open.c

My failed tries to reproduce #5033. I guess it's worthwhile to include them anyway, even though they didn't uncover any errors.

Tests for symlinked user config

---

src/posix.c
src/posix.h
src/win32/posix_w32.c
tests/core/posix.c
tests/object/tree/read.c

This is the test case for #4615, ported to clar.
Now I'm hoping `fcntl` is something portable 🤞.

Test that largefiles can be read through the tree API

---

src/ignore.c
tests/attr/ignore.c

The function `git_ignore_path_is_ignored` is there to test the
ignore status of paths that need not necessarily exist inside of
a repository. This has the implication that for a given path, we
cannot always decide whether it references a directory or a file,
and we need to distinguish those cases because ignore rules may
treat those differently. E.g. given the following gitignore file:
*
!/**/
we'd only want to unignore directories, while keeping files
ignored. But still, calling `git_ignore_path_is_ignored("dir/")`
will say that this directory is ignored because it treats "dir/"
as a file path.
As said, the `is_ignored` function cannot always decide whether
the given path is a file or directory, and thus it may produce
wrong results in some cases. While this is unfixable in the
general …

ignore: treat paths with trailing "/" as directories

---

src/hash/hash_win32.c
src/hash/hash_win32.h

Users of the Win32 hash cannot be inlined, as it uses a static struct.
Don't inline it, but continue to declare the function in the header.
/cc @csware

sha1: don't inline `git_hash_global_init` for win32

---

src/patch_parse.c
tests/diff/parse.c
tests/patch/patch_common.h

This becomes a segfault later (in `check_prefix`) when parsing patches where a file was added. CRLF seems to be handled fine otherwise. Added test which demonstrates the segfault.
Supporting CRLF is important because patches are often emailed - and emails use CRLF.

patch_parse.c: Handle CRLF in parse_header_start

---

src/config_file.c

`git_array_alloc` can return `NULL` if no memory is available, causing a segmentation fault in memset. This adds `GIT_ERROR_CHECK_ALLOC` similar to how other parts of the code base deal with the return value of `git_array_alloc`.
This is my first contribution to libgit2, please let me know if I made a mistake.

config_file: check result of git_array_alloc

---

src/fileops.c
tests/repo/init.c

Stop traversing the filesystem at the Windows directory root.  We were calculating the filesystem root for the given directory to create, and walking up the filesystem hierarchy.  We intended to stop when the traversal path length is equal to the root path length (ie, stopping at the root, since no path may be shorter than the root path).
However, on Windows, the root path may be specified in two different ways, as either `Z:` or `Z:\`, where `Z:` is the current drive letter. `git_path_dirname_r` returns the path _without_ a trailing slash, even for the Windows root.  As a result, during traversal, we need to test that the traversal path is _less than or equal to_ the root path length to determine if we've hit the root to ensure that we stop when our traversal path is `Z:` and our …

git_repository_init: stop traversing at windows root

---

examples/blame.c
examples/common.c
examples/common.h
examples/merge.c

I've been asked how to implement SSH authentication with libgit2. I've thus decided to implement that support for our examples code, so that one may now clone SSH repos via the lg2 executable.

examples: implement SSH authentication

---

src/config_file.c
src/iterator.c
src/refdb_fs.c
src/transports/http.c
src/transports/smart.c
src/transports/ssh.c
src/util.h

In some parts of our code, we make rather heavy use of downcasting
structures to their respective specialized implementation. One example
is the configuration code with the general `git_config_backend` and the
specialized `diskfile_header` structures. At some occasions, it can
get confusing though with regards to the correct inheritance structure,
which led to the recent bug fixed in 2424e64c4 (config: harden our use
of the backend objects a bit, 2018-02-28).
Object-oriented programming in C is hard, but we can at least try to
have some checks when it comes to casting around stuff.
Thus, this commit introduces a `GIT_DOWNCAST` macro, which accepts as
parameters the pointer that is to be casted, the pointer it should be
cast to as well as the member inside of the target structure that is …

[RFC] util: introduce GIT_DOWNCAST macro

---

src/config_file.c
tests/config/global.c

Opening a default config when ~/.gitconfig doesn't exist, locking it,
and attempting to write to it causes an assertion failure.
Treat non-existent global config file content as an empty string.

Correctly write to missing locked global config

---

include/git2/rebase.h
src/rebase.c
tests/rebase/merge.c

The rebase struct stores fields with information about the current
rebase process, which were not accessible via a public interface.
Accessors for getting the `orig_head` and `onto` branch
names and object ids have been added.

rebase: orig_head and onto accessors

---

src/win32/posix_w32.c

PR #4713 had one thing missing, which is correctly setting the `SYMBOLIC_LINK_FLAG_DIRECTORY` for directories, as Windows weirdly handles symlinks differently than unix-like systems.
This issue is discussed with @ethomson in #4713.

Support symlinks for directories in win32

---

src/revwalk.c
tests/revwalk/basic.c

If someone passes just one ref (i.e. "master") and misses passing the
range we should be nice and return an error code instead of crashing.
I am not sure if this is being overly protective, but IMO a library should not crash just because the content in a string is wrong.

git_revwalk_push_range: do not crash if range is missing

---

src/win32/posix_w32.c

Some older MinGW toolchains may not have it defined:
```
deps/libgit2/src/win32/posix_w32.c: In function 'p_symlink':
deps/libgit2/src/win32/posix_w32.c:409:14: error: 'SYMBOLIC_LINK_FLAG_DIRECTORY' undeclared (first use in this function); did you mean 'SYMLINK_FLAG_RELATIVE'?
dwFlags |= SYMBOLIC_LINK_FLAG_DIRECTORY;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
SYMLINK_FLAG_RELATIVE
deps/libgit2/src/win32/posix_w32.c:409:14: note: each undeclared identifier is reported only once for each function it appears in
```

Define SYMBOLIC_LINK_FLAG_DIRECTORY if required

---

src/attr_file.c
tests/status/ignore.c

When parsing an ignore or attribute file, we should skip a UTF8 BOM.
Fixes #5071

Skip UTF8 BOM in ignore files

---

include/git2/remote.h
src/remote.c
src/remote.h
tests/network/remote/remotes.c
tests/online/push_util.h

This is #5056, in 3 commits:
- add a helper to upgrade options structures if needed
- update the git_remote_callback users to the autoupgrader
- add a callback to `git_remote_callbacks` to change the URL before the connection is made.

Remote URL last-chance resolution

---

src/refs.c
src/refspec.c
tests/network/refspecs.c
tests/refs/normalize.c

Upstream has changed the restrictions on wildcard "*" refspecs. Previously, a wildcard in a refspec was only allowed if it was the only character in a component. This restriction has been lifted to allow wildcards to be nested between other characters in that component with cd377f45c9 (refs: loosen restriction on wildcard "*" refspecs, 2015-07-22).
More details in the commits.
Fixes #5058

Loosen restriction on wildcard "*" refspecs

---

src/config_parse.c
tests/config/read.c

When parsing configuration section headers, we previously stopped at the first space, and skipped to the first quotation mark.  This allows us to support valid section headers like `[foo "bar"]` or `[foo        "bar"]`.
However, by skipping from the end of the section name to the first quotation mark, we ignore any invalid characters there.  For example, `[foo skipped "bar"]` which is not legal.
Validate that there is only whitespace between the end of the section name and the first quotation mark.  This also adds additional tests that were useful for my understanding and should help prevent regression.
Fixes #5072

Configuration parsing: validate section headers with quotes

---

deps/pcre/CMakeLists.txt

Our PCRE dependency has uncommented fallthroughs in switch statements.
Turn off warnings for those in the PCRE code.
(These failed in the nightly.)

cmake: disable fallthrough warnings for PCRE

---

src/repository.c

error was never initialized and a garbage value returned on success.

repository: fix garbage return value

---

src/posix.c

NetBSD 7 added support for ```posix_fallocate```.
See:
https://www.netbsd.org/changes/changes-7.0.html
http://www.cpantesters.org/cpan/report/ca7e64c8-7d3a-11e9-9ccb-b1ae95f66eb9

Restore NetBSD support

---

README.md
SECURITY.md

GitHub has recently introduced a new set of tools that aims to
ease the process around vulnerability reports and security fixes.
Part of those tools is a new security tab for projects that will
display contents from a new SECURITY.md file.
Move relevant parts from README.md to this new file to make use
of this feature.

SECURITY.md: split out security-relevant bits from readme

---

src/cache.c
tests/blame/simple.c

When evicting cache entries, we first retrieve the object that is
to be evicted, delete the object and then finally delete the key
from the cache. In case where the cache eviction caused us to
free the cached object, though, its key will point to invalid
memory now when trying to remove it from the cache map. On my
system, this causes us to not properly remove the key from the
map, as its memory has been overwritten already and thus the key
lookup it will fail and we cannot delete it.
Fix this by only decrementing the refcount of the evictee after
we have removed it from our cache map. Add a test that caused a
segfault previous to that change.
Fixes #5081

cache: fix cache eviction using deallocated key

---

src/attr_file.c
tests/attr/file.c
tests/iterator/workdir.c
tests/resources/attr/attr4
tests/status/ignore.c
tests/status/ignore.c.bak

Whitespace is significant in ignore files.  Per the documentation, "trailing spaces are ignored".  But leading spaces are not.  Ensure that we do _not_ skip leading spaces in ignore files.
(However, in a cruel yet typical joke, for _attribute_ files, "leading and trailing whitespaces are ignored".  So I've added a test to ensure that we didn't break _that_.)
Fixes #5069

Ignore files: don't ignore whitespace

---

tests/online/clone.c

GitHub recently changed their behavior from returning 401s for private or nonexistent repositories on a clone to returning 404s.  For our tests that require an auth failure (and 401), move to GitLab to request a missing repository.  This lets us continue to test our auth failure case, at least until they decide to mimic that decision.
I loathe that we're adding a new dependency on _yet another_ provider.  At some point, I would like to spin up our own git server over HTTP (ideally one that could be configured to send a variety of complete garbage responses).  But in the meantime, this will turn our red builds to green.

online tests: use gitlab for auth failures

---

src/attr_file.c
tests/status/ignore.c

Per #5070, we should not treat multiple leading slashes as identical to a single leading slash.  One leading slash indicates the directory root, but _only the first_ should indicate that.
Fixes #5070

Ignore: only treat one leading slash as a root identifier

---

src/attr_file.c
tests/attr/ignore.c

The gitignore's pattern format specifies that "Trailing spaces
are ignored unless they are quoted with backslash ("\")". We do
not honor this currently and will treat a pattern "foo\ " as if
it was "foo\" only and a pattern "foo\ \ " as "foo\ \".
The current gitignore format does offer some very special
surprises, though: given a pattern "foo \ ", upstream git will in
fact strip all spaces and treat it as "foo", only.
Fix our code to handle those special cases and add tests to avoid
regressions.

ignore: handle escaped trailing whitespace

---

tests/checkout/index.c

The function `populate_symlink_workdir` creates a new
"symlink.git" repository with a relative path "../symlink.git".
As the current working directory is the sandbox, the new
repository will be created just outside of the sandbox.
Fix this by using `clar_sandbox_path`.

tests: checkout: fix symlink.git being created outside of sandbox

---

include/git2/deprecated.h
include/git2/trace.h
include/git2/transport.h
src/trace.c
src/trace.h
src/transports/cred.c

The credential and trace callbacks should match the other callback naming conventions, using the `_cb` suffix instead of a `_callback` suffix.

Callback type names should be suffixed with `_cb`

---

src/hash/sha1dc/sha1.c

Update our copy of sha1dc to the upstream commit 855827c (Detect
endianess on HP-UX, 2019-05-09). Changes include fixes to endian
detection on AIX and HP-UX systems as well as a define that
allows us to force aligned access, which we're not using yet.

sha1dc: update to fix endianess issues on AIX/HP-UX

---

tests/generate.py
tests/object/cache.c

tests: allow for simple data-driven tests
Right now, we're not able to use data-driven tests at all. E.g.
given a set of tests which we'd like to repeat with different
test data, one has to hand-write any outer loop that iterates
over the test data and then call each of the test functions. Next
to being bothersome, this also has the downside that error
reporting is quite lacking, as one never knows which test data
actually produced failures.
So let's implement the ability to re-run complete test modules
with changing test data. To retain backwards compatibility and
enable trivial addition of new runs with changed test data, we
simply extend clar's generate.py. Instead of scanning for a
single `_initialize` function, each test module may now implement
multiple `_initialize_foo` functions. …

Data-driven tests

---

deps/ntlmclient/CMakeLists.txt

The ntlmclient dependency has quite a lot of places with implicit
fallthroughs. As at least modern GCC has enabled warnings on
implicit fallthroughs by default, the developer is greeted with a
wall of warnings when compiling that dependency.
Disable implicit fallthrough warnings for ntlmclient to fix this
issue.

deps: ntlmclient: disable implicit fallthrough warnings

---

src/posix.c
src/posix.h
src/win32/posix_w32.c
tests/core/posix.c
tests/object/tree/read.c

The `p_fallocate` platform is currently in use in our tests,
only, but it proved to be quite burdensome to get it implemented
in a cross-platform way. The only "real" user is the test
object::tree::read::largefile, where it's used to allocate a
large file in the filesystem only to commit it to the repo and
read its object back again. We can simplify this quite a bit by
just using an in-memory buffer of 4GB. Sure, this cannot be used
on platforms with low resources. But creating 4GB files is not
any better, and we already skip the test if the environment
variable "GITTEST_INVASIVE_FS_SIZE" is not set. So we're arguably
not worse off than before.
Supersedes #5087

Removal of `p_fallocate`

---

include/git2/deprecated.h
include/git2/object.h
src/object.c

We don't use double-underscores in the public API.

object: rename git_object__size to git_object_size

---

include/git2/attr.h
include/git2/deprecated.h
src/attr.c
src/crlf.c
src/diff_driver.c
src/filter.c
src/merge_driver.c
tests/attr/attr_expect.h
tests/attr/file.c
tests/attr/flags.c
tests/attr/lookup.c
tests/attr/repo.c

Our enumeration values are not generally suffixed with `T`.  Further,
our enumeration names are generally more descriptive.

attr: rename constants and macros for consistency

---

CMakeLists.txt

If building libgit2 with `-DUSE_HTTPS=NO`, then CMake will
generate an error complaining that there's no usable HTTPS
backend for NTLM. In fact, it doesn't make sense to support NTLM
when we don't support HTTPS. So let's should just have
NTLM default to OFF when HTTPS is disabled to make life easier
and to fix our OSSFuzz builds failing.

cmake: default NTLM client to off if no HTTPS support

---

include/git2/deprecated.h
include/git2/net.h

This callback is never used.  Move it over to `deprecated.h`.

net: remove unused `git_headlist_cb`

---

tests/object/tree/read.c

Don't try to feed 4 GB of data to APIs that only take a `size_t` on 32-bit platforms.

largefile tests: only write 2GB on 32-bit platforms

---

ci/test.ps1
ci/test.sh

Re-run the flaky online integration tests.  Since these hit actual network endpoints and those may be occasionally down, we want to re-run them up to 5 times.  This prevents us from failing the builds just because the badssl endpoint is down, for example.

Re-run flaky tests

---

include/git2/apply.h
include/git2/buffer.h
include/git2/checkout.h
include/git2/remote.h
include/git2/status.h
include/git2/sys/alloc.h
include/git2/transport.h

I've added a "missing field documentation" warning to Docurium, and this is a first pass at it.
I've noticed that Docurium seems to dislike the `GIT_CALLBACK` macro when it's used in a struct definition. Typedefs of those seems to be fine though.

More documentation

---

examples/init.c
examples/merge.c

Using cppcheck on libgit2 sources indicated two warnings in example code.
`merge.c` was reported as having a memory leak. Fix applied was to apply git_commit_free to value of variable `parents`.
`init.c` was reported as having a null pointer dereference on variable `arg`. Function `usage` was being called with a null variable. Changed supplied parameter to empty string.

Resolve static check warnings in example code

---

src/hash.c

When no hash algorithm has been initialized in a given hash context,
then we will simply `assert` and not return a value at all. This works
just fine in debug builds, but on non-debug builds the assert will be
converted to a no-op and thus we do not have a proper return value.
Fix this by returning an error code in addition to the asserts.

hash: fix missing error return on production builds

---

src/attr.c
src/attr_file.c
tests/attr/repo.c

Regression introduced in commit 5452e49fce21f726bec19519da7f012e3f19e736 on PR #4967.
I don't know how to provide a test for this.

Fix Regression: attr: Correctly load system attr file (on Windows)

---

ci/build.ps1
examples/blame.c
examples/clone.c
examples/describe.c
examples/general.c
examples/index-pack.c
examples/merge.c
examples/show-index.c
src/win32/w32_stack.c
src/win32/w32_stack.h
tests/clar.c
tests/clar.h
tests/clar/print.h
tests/trace/windows/stacktrace.c

Build with -Werror's equivalent (/WX) on MSVC.
I neglected to do this in the previous warnings PR, oops.  I think that there are also some lingering issues in things like examples that I didn't build locally with `/WX` and missed since I didn't add this in the CI setup.

ci: build with ENABLE_WERROR on Windows

---

cmake/Modules/FindStatNsec.cmake
examples/common.h
examples/config.c
examples/lg2.c
src/config_file.c
src/config_parse.h
tests/clar_libgit2.h
tests/config/stress.c

To decide whether a config file has changed, we always hash its
complete contents. This is unnecessarily expensive, as
well-behaved filesystems will always update stat information for
files which have changed. So before computing the hash, we should
first check whether the stat info has actually changed for either
the configuration file or any of its includes. This avoids having
to re-read the configuration file and its includes every time
when we check whether it's been modified.
Tracing the for-each-ref example previous to this commit, one can
see that we repeatedly re-open both the repo configuration as
well as the global configuration:
$ strace lg2 for-each-ref |& grep config
access("/home/pks/.gitconfig", F_OK)    = -1 ENOENT (No such file or directory) …

config_file: implement stat cache to avoid repeated rehashing

---

src/config_file.c
src/config_mem.c
src/config_parse.c
src/config_parse.h
src/parse.h

This is the missing piece to really separate the configuration parser and the configuration file backend. Goal is to make the code easier to understand as well as to enable easier refactoring. But I guess the result speaks for itself.
Note: this PR includes the two commits from #5132. I wanted to avoid having to fix conflicts, as I expect that #5132 will land quite fast.

Config parser separation

---

ci/build.ps1
fuzzers/config_file_fuzzer.c
fuzzers/download_refs_fuzzer.c
fuzzers/packfile_fuzzer.c
fuzzers/standalone_driver.c

This fixes our fuzzers so that they build on Win32 platforms and enables fuzzer building in our CI.

win32: fix fuzzers and have CI build them

---

src/fileops.c
tests/repo/init.c

In commit 45f24e787 (git_repository_init: stop traversing at
windows root, 2019-04-12), we have fixed `git_futils_mkdir` to
correctly handle the case where we create a directory in
Windows-style filesystem roots like "C:\repo".
The problem here is an off-by-one: previously, to that commit,
we've been checking wether the parent directory's length is equal
to the root directory's length incremented by one. When we call
the function with "/example", then the parent directory's length
("/") is 1, but the root directory offset is 0 as the path is
directly rooted without a drive prefix. This resulted in `1 == 0 +
1`, which was true. With the change, we've stopped incrementing
the root directory length, and thus now compare `1 <= 0`, which
is false.
The previous way of doing it was kind of …

fileops: fix creation of directory in filesystem root

---

src/pack-objects.c

The packbuilder code allocates memory in chunks. When it needs to allocate, it tries to add 1024 to the number of objects and multiply by 3/2. However, it actually multiplies by 1 instead, since it performs an integral division in the expression "3 / 2" and only then multiplies by the increased number of objects.
The current behavior causes the code to waste massive amounts of time copying memory when it reallocates, causing inserting all non-blob objects in the Linux repository into a new pack to take some indeterminate time greater than 5 minutes instead of 52 seconds. (I was impatient and didn't want to wait much longer than 5 minutes for my job to run.)
Correct this error by first dividing by two, and only then multiplying by 3. We still check for overflow for the multiplication, …

Allocate memory more efficiently when packing objects

---

tests/generate.py

Failing to do that makes clar miss the last of the suites, as all duplicated "data" would have not been accounted for.

clar: correctly account for "data" suites when counting

---

.gitignore

When using VS2017 there are some files in the libgit2 folder which should be ignored.

Ignore VS2017 specific files and folders

---

tests/generate.py

Fixes #5168 and #5098. Without this, some tests do not get executed at all.

clar: fix suite count

---

src/cache.c

When our object cache is full, we pick eight items (or the whole cache, if there are fewer) and evict them. For small cache sizes, this is fine, but when we're dealing with a large number of objects, we can repeatedly exhaust the cache and spend a large amount of time in `git_oidmap_iterate` trying to find items to evict.
Instead, let's assume that if the cache gets full, we have a large number of objects that we're handling, and be more aggressive about evicting items. Let's remove one item for every 2048 items, but not less than 8. This causes us to scale our evictions in proportion to the size of the cache and significantly reduces the time we spend in `git_oidmap_iterate`.
Before this change, a full pack of all the non-blob objects in the Linux repository took in excess of 30 minutes …

Evict cache items more efficiently

---

src/patch_parse.c
tests/patch/parse.c

When parsing a patch from a buffer, we let the patch lines point into
the original buffer. While this is efficient use of resources, this also
ties the lifetime of the parsed patch to the parsed buffer. As this
behaviour is not documented anywhere in our API it is very surprising to
its users.
Untie the lifetime by duplicating the lines into the parsed patch. Add a
test that verifies that lifetimes are indeed independent of each other.
---
Noticed while testing #5125

patch_parse: do not depend on parsed buffer's lifetime

---

src/apply.c
src/diff.c
src/patch_generate.c
src/patch_parse.c
tests/patch/parse.c
tests/patch/patch_common.h

When either the old or new file contents have no newline at the end of
the file, then git-diff(1) will print out a "\ No newline at end of
file" indicator. While we do correctly handle this in the case where the
new file has this indcator, we fail to parse patches where the old file
is missing a newline at EOF.
Fix this bug by handling and missing newline indicators in the old file.
Add tests to verify that we can parse such files.
---
I've tried to modify our patch printing logic to also emit the "No newline at end of file" markers, but it turned out to be non-trivial. Many of the diff/patch structs are part of our public API and thus cannot be easily changed, so I didn't quite know where to put the missing newline indicators. So I've stopped short of actually verifying that we …

patch_parse: handle missing newline indicator in old file

---

src/ignore.c
tests/ignore/path.c

When computing whether we need to store a negative pattern, we iterate
through all previously known patterns and check whether the negative
pattern undoes any of the previous ones. In doing so we call `wildmatch`
and check it's return for any negative error values. If there was a
negative return, we will abort and bubble up that error to the caller.
In fact, this check for negative values stems from the time where we
still used `fnmatch` instead of `wildmatch`. For `fnmatch`, negative
values indicate a "real" error, while for `wildmatch` a negative value
may be returned if the matching was prematurely aborted. A premature
abort may for example also happen if the pattern matches a prefix of the
haystack if the pattern is shorter. Returning an error in that case is
the wrong thing to do. …

ignore: fix determining whether a shorter pattern negates another

---

src/patch_parse.c

With commit dedf70ad2 (patch_parse: do not depend on parsed buffer's
lifetime, 2019-07-05), all lines of the patch are allocated with
`strdup` to make lifetime of the parsed patch independent of the buffer
that is currently being parsed. In patch b08932824 (patch_parse: ensure
valid patch output with EOFNL, 2019-07-11), we introduced another
code location where we add lines to the parsed patch. But as that one
was implemented via a separate pull request, it wasn't converted to use
`strdup`, as well. As a consequence, we generate a segfault when trying
to deallocate the potentially static buffer that's now in some of the
lines.
Use `git__strdup` to fix the issue.
---
This bug has been introduced due to #5158 and #5159 having bad interactions with each other.

patch_parse: fix segfault due to line containing static contents

---

fuzzers/download_refs_fuzzer.c

Updated after the renamification in #5151

fuzzer: use futils instead of fileops

---

src/config_file.c
tests/config/stress.c
tests/remote/list.c

When creating a new iterator for a config file backend, then we should
always make sure that we're up to date by calling `config_refresh`.
Otherwise, we might not notice when another process has modified the
configuration file and thus will represent outdated values.
Add two tests to config::stress that verify that we get up-to-date
values when reading configuration entries via `git_config_iterator`.
---
I think this wasn't caused by #5132 but was a pre-existing issue already. There simply was no code path that would've called `config_refresh` when creating a new iterator.
Fixes #5167

config_file: refresh when creating an iterator

---

include/git2/deprecated.h
include/git2/object.h
src/object.c

In #5118 we remove the double-underscore to make it a normally-named public
function. However, this is not an interesting function outside of the library
and it takes up a name for something that could be more useful.
Remove the single-underscore version as we have not done any releases with it.

object: deprecate git_object__size for removal

---

src/config_backend.h
src/config_entries.c
src/config_entries.h
src/config_file.c
src/config_snapshot.c

This completely tears apart the shared code between config file (`diskfile_backend`) and config snapshots (`diskfile_readonly_backend`). The previous code was hard to understand with the `diskfile_header` structure, error prone and didn't have proper separation of concerns. With this, we now have a completely backend-agnostic snapshotting backend that can create a read-only snapshot of any other config backend.
This PR doesn't yet go the extra step of making use of that extra functionality, but only does refactorings that should keep all semantics in place. But hopefully with less bugs and more enlightenment when one reads the code.
/cc @csware

config: separate file and snapshot backends

---

examples/common.c
examples/common.h
examples/diff.c
examples/for-each-ref.c
examples/general.c
examples/index-pack.c
examples/status.c

Adding compare buffers feature in diff example
This tries to mimic `git diff --no-index`
```
echo hello > file1
echo bye > file2
git diff --no-index file1 file2
diff --git 1/file1 2/file2
index 5c1b14949..b023018ca 100644
--- 1/file1
+++ 2/file2
@@ -1 +1 @@
-hello
+bye
```
Right now this patch does:
```
$ ./diff --files --text --color
buf: diff --git a/file1 b/file2
index ce01362..b023018 100644
--- a/file1
+++ b/file2
@@ -1 +1 @@
-hello
+bye
diff --git a/file1 b/file2
index ce01362..b023018 100644
--- a/file1
+++ b/file2
@@ -1 +1 @@
-hello
+bye
```
Actual problems:
-  Read real files
- Do not detect buffers as binary files
- Use `--no-index` as parameter
- Check two files are passed and they exists

Compare buffers in diff example

---

.editorconfig

Update editorconfig to match our coding style. Most importantly, we set
up the tab width to be 8 characters instead of the default and use
2 spaces to indent YAML files.

editorconfig: update to match our coding style

---

examples/checkout.c

Make the example program for checkout follow git syntax, where "--" indicates a file.  This was likely just a strcmp return value confusion.

Fix example checkout to forbid rather than require --

---

src/sysdir.c

On macOS the $HOME environment variable returns the path to the sandbox
container instead of the actual user $HOME for sandboxed apps.
To get the correct path, we have to get it from the password file entry.
Closes #5190

config: check if we are running in a sandboxed environment

---

examples/clone.c
examples/fetch.c
examples/index-pack.c

Static analysis of example code found multiple findings of `printf` usage
where filling value is members of git_indexer_progress object. Specifier
used was for signed int but git_indexer_progress members are typed as
unsigned int. `printf` specifiers were altered to match type.

Adjust printf specifiers in examples code

---

src/remote.c

In "remote.c", we have a chunk of code that is #ifdef'fed out via
`#if 0` with a comment that we could export it as a helper function.
The code was implemented in 2013 and ifdef'fed in 2014, which shows that
there's clearly no interest in having such a helper at all.
As this block has recently created some confusion about `p_getenv` due
to it containing the only reference to that function in our codebase,
let's remove this block altogether.
Triggered by #5191

remote: remove unused block of code

---

include/git2/commit.h
include/git2/rebase.h
src/commit.c
src/rebase.c
tests/rebase/sign.c

This PR aims to add the ability to sign a rebase commit using the git_rebase_commit API. It seemed most convenient to extend the method to take a signature callback and signature_field callback, which help provide the signature data for `git_commit_create_with_signature` API.
The general flow is that if you have options and you have a `signature_cb`, then `git_rebase_commit` will call that `signature_cb` with the commit content buffer retrieved from `git_commit_create_buffer`, providing an opportunity to sign the commit content. The owner of the `signature_cb` is expected to create a string, though if GIT_PASSTHROUGH is specified, the signing process will fallback to creating an unsigned commit. If a signature is provided from the `signature_cb`, the `signature_field_cb` will be called if …

Add sign capability to git_rebase_commit

---

src/apply.c
src/errors.c
src/errors.h
src/parse.h
src/patch_parse.c
src/unix/posix.h

The macro `git_parse_error` is implemented in a variadic way so
that it's possible to pass printf-style parameters.
Unfortunately, variadic macros are not defined by C89 and thus we
cannot use that functionality. But as we have implemented
`git_error_vset` in the previous commit, we can now just use that
instead.
Convert `git_parse_error` to a variadic function and use
`git_error_vset` to fix the compliance violation.
---
Edit: fixed more locations to be compliant

Variadic macros

---

examples/common.h
examples/lg2.c
examples/stash.c
src/stash.c

When creating a new stash, we need to create there separate
commits storing differences stored in the index, untracked
changes as well as differences in the working directory. The
first two will only be done conditionally if the equivalent
options "git stash --keep-index --include-untracked" are being
passed to `git_stash_save`, but even when only creating a stash
of worktree changes we're much slower than git.git. Using our new
stash example:
$ time git stash
Saved working directory and index state WIP on (no branch): 2f7d9d47575e Linux 5.1.7
real    0m0.528s
user    0m0.309s
sys     0m0.381s
$ time lg2 stash
real    0m27.165s
user    0m13.645s
sys     0m6.403s
As can be seen, libgit2 is more than 50x slower than git.git!
When creating the stash commit that includes all worktree
changes, …

stash: avoid recomputing tree when committing worktree

---

docs/changelog.md
src/commit_list.c
src/config.c
src/path.c
src/path.h

Security updates ported from the 0.28.3 branch:
* A carefully constructed commit object with a very large number
of parents may lead to potential out-of-bounds writes or
potential denial of service.
* The ProgramData configuration file is always read for compatibility
with Git for Windows and Portable Git installations. The ProgramData
location is not necessarily writable only by administrators, so we
now ensure that the configuration file is owned by the administrator
or the current user.

Security updates from 0.28.3

---

src/path.c

This recently added include broke compilation on mingw32 with case-sensitive filesystems. Lowercasing here fixes compilation for me and mingw32 standardizes on lowercase include paths, so this seems like the right thing to do.

Fix include casing for case-sensitive filesystems.

---

src/transports/auth.c
src/transports/http.c

Don't try to select the "best" scheme that the server offers us without taking into account the credentials that the user has selected.  Otherwise, the "best" scheme may not support the given credentials.
eg, many servers use both Negotiate and NTLM as a fallback.  Negotiate _only_ works with default credentials, while our NTLM implementation _only_ works with username/password credentials.  As a result, our caller has given us a particular kind of credentials and we must match those credentials to the schemes offered.
Instead of using the "best" overall scheme, use the "best" scheme (ordered first) that our credentials support.
Fixes #5178

Use an HTTP scheme that supports the given credentials

---

src/ignore.c
tests/ignore/status.c

problem:
filesystem_iterator loads .gitignore files in top-down order.
subsequently, ignore module evaluates them in the order they are loaded.
this creates a problem if we have unignored a rule (using a wild card)
in a sub dir and ignored it again in a level further below (see the test
included in this patch).
solution:
process ignores in reverse order.
closes #4963

ignore: correct handling of nested rules overriding wild card unignore

---

src/apply.c
tests/apply/fromdiff.c
tests/patch/patch_common.h

Use of apply's API can lead to an improper patch application and a corruption
of the modified file.
The issue is caused by mishandling of the end of file changes if there are
several hunks to apply. The new line character is added to a line from a wrong
hunk.
The solution is to modify apply_hunk() to add the newline character at the end
of a line from a right hunk.

apply: Fix a patch corruption related to EOFNL handling

---

src/repository.c
tests/repo/open.c

There is an example on the website for checking if a directory looks like a repository:
https://libgit2.org/docs/guides/101-samples/#repositories_openable
This example leaks memory. This pull request includes a test point which leaks memory and is caught by valgrind, plus a fix in git_repository_open_ext to dispose of buffers on the early return.

open:fix memory leak when passing NULL to git_repository_open_ext

---

src/transports/auth_negotiate.c

Should have been part of 8bf0f7eb26c65b2b937b1f40a384b9b269b0b76d, which I missed by having relied too much on Xcode's refactorer (#blameitontheIDE).

cred: add missing private header in GSSAPI block

---

src/buffer.c
tests/core/buffer.c

This fixes two issues with `git_buf`:
1. An infinite loop when allocating a huge amount of bytes close to `SIZE_MAX`. While obviously a bogus scenario, I still think the fix is worthwhile.
2. We failed to correctly ensure sizes of OOM'd buffers, which resulted in us writing into the `git_buf__oom` buffer.
Found while investigating #5199 once again. This is probably not the cause for the observed crashes, though, as the stack traces point somewhere else.

buffer: fix writes into out-of-memory buffers

---

script/valgrind.supp

On Ubuntu, the combination of libgcrypt and libssh2 is quite old and
known to contain memory leaks. We thus have several functions listed in
our suppressions file that are known to leak. Due to a recent update of
libssh2 or libgcrypt, there now is a new memory leak caused by
libssh2_session_handshake that causes the CI to fail.
Add a new suppression to fix the issue.

valgrind: suppress memory leaks in libssh2_session_handshake

---

include/git2/blob.h
include/git2/diff.h
include/git2/merge.h
include/git2/stash.h
src/diff.c

Using an `enum` causes trouble when used with C++ as bitwise operations are not possible w/o casting (e.g., `opts.flags &= ~GIT_BLOB_FILTER_CHECK_FOR_BINARY;` is invalid as there is no `&=` operator for `enum`).
I'm unsure whether `uint32_t` is a good way, because then I get "signed/unsigned" warnings in the case above - no warnigns would be generated with a plain `int` (cf. the following is needed with `uint32_t`: `opts.flags &= ~static_cast<uint32_t>(GIT_BLOB_FILTER_CHECK_FOR_BINARY);`).

Don't use enum for flags

---

azure-pipelines.yml
azure-pipelines/coverity.yml
azure-pipelines/docker.yml
azure-pipelines/docker/bionic
azure-pipelines/docker/entrypoint.sh
azure-pipelines/docker/xenial

Right now, all tests in libgit2's CI are being executed as root
user. As libgit2 will usually not run as a root user in "normal"
usecases and furthermore as there are tests that rely on the
ability to _not_ be able to create certain paths, let's instead
create an unprivileged user "libgit2" and use that across all
docker images.

azure: avoid building and testing in Docker as root

---

src/commit.c
src/commit.h
src/commit_list.c
src/commit_list.h
src/integer.h

Splitted from #4331. See this PR for context.
This adds a "quick" mode to our commit parsing machinery, and makes the revwalk code instead of going with its own. The outcome is a nice, single place where grafts can be handled.

DRY commit parsing

---

src/patch_parse.c
tests/diff/parse.c

Patches containing additions of empty files will not contain diff data
but will end with the index header line followed by the terminating
sequence "-- ". We follow the same logic as in cc4c44a and allow "-- "
to immediately follow the index header.

patch_parse: handle patches with new empty files

---

include/git2/submodule.h
src/clone.c
src/clone.h
src/submodule.c
tests/clone/nonetwork.c
tests/submodule/add.c

While working on the submodule-in-worktree issue, I had to finagle with #4149. So let's add that to the API.
Arguably, it could be named `git_submodule_add` and perform all the steps by itself.

Provide a wrapper for simple submodule clone steps

---

src/patch_parse.c
tests/diff/parse.c
tests/patch/patch_common.h

Extended header lines (especially the "index <hash>..<hash> <mode>") are
not required by "git apply" so it import patches. So we allow the
from-file/to-file lines (--- a/file\n+++ b/file) to directly follow the
git diff header.
This fixes #5267.

patch_parse: handle patches without extended headers

---

src/transaction.c
tests/refs/transactions.c

Refs which are locked in a transaction without an altered target,
still should to be unlocked on `git_transaction_commit`.
`git_transaction_free` also unlocks refs but the moment of calling of `git_transaction_free`
cannot be controlled in all situations.
Some binding libs call `git_transaction_free` on garbage collection or not at all if the
application exits before and don't provide public access to `git_transaction_free`.
It is better to release locks as soon as possible.

refs: unlock unmodified refs on transaction commit

---

src/integer.h
src/patch_parse.c
tests/patch/parse.c
tests/patch/patch_common.h

These are the first results of #5269.

patch_parse: fixes for fuzzing errors

---

src/commit.c
tests/commit/write.c

There can be a significant difference between the system where we created the                                                                              
buffer (if at all) and when the caller provides us with the contents of a                                                                                  
commit.
Verify that the commit we are being asked to create references objects which do
exist in the target repository.
This is not terribly efficient since we allocate a commit, but AFAICT it's what we have available. Obviously our test suite fails with these changes because we were creating commits that referenced non-existent trees and commits.
Fixes #5288

commit: verify objects exist in git_commit_with_signature

---

src/config_file.c
src/config_snapshot.c

When creating a configuration file iterator, then we first refresh the
backend and then afterwards duplicate all refreshed configuration
entries into the iterator in order to avoid seeing any concurrent
modifications of the entries while iterating. The duplication of entries
is not guarded, though, as we do not increase the refcount of the
entries that we duplicate right now. This opens us up for a race, as
another thread may concurrently refresh the repository configuration and
thus swap out the current set of entries. As we didn't increase the
refcount, this may lead to the entries being free'd while we iterate
over them in the first thread.
Fix the issue by properly handling the lifecycle of the backend's
entries via `config_file_entries_take` and `git_config_entries_free`, …

config_file: fix race when creating an iterator

---

src/patch_parse.c
tests/patch/parse.c
tests/patch/patch_common.h

When parsing header paths from a patch, we reject any patches with empty
paths as malformed patches. We perform the check whether a path is empty
before sanitizing it, though, which may lead to a path becoming empty
after the check, e.g. if we have trimmed whitespace. This may lead to a
segfault later when any part of our patching logic actually references
such a path, which may then be a `NULL` pointer.
Fix the issue by performing the check after sanitizing. Add tests to
catch the issue as they would have produced a segfault previosuly.

patch_parse: fix segfault when header path contains whitespace only

---

src/config_mem.c
tests/config/snapshot.c

Similar as in commit dadbb33b6 (Fix crash if snapshotting a
config_snapshot, 2019-11-01), let's implement snapshots for in-memory
configuration entries. As this deletes more code than it adds, it
doesn't make any sense to not allow for this and allows users to treat
config backends mostly the same.

config_mem: implement support for snapshots

---

src/futils.c

IIRC I got a strange return once from lstat, which translated in a weird
error class/message being reported. As a safety measure, enforce a -1 return in
that case.

fileops: correct error return on p_lstat failures when mkdir

---

src/transports/winhttp.c

CC #4675. The issue is closed by #4848 but WinHTTP was forgotten.
The issue caused failures of GitLab repository fetching on Windows.

Follow 308 redirect in WinHTTP transport

---

src/patch_parse.c
tests/patch/parse.c
tests/patch/patch_common.h

For some patches, it is not possible to derive the old and new file
paths from the patch header's first line, most importantly when they
contain spaces. In such a case, we derive both paths from the "---" and
"+++" lines, which allow for non-ambiguous parsing. We fail to use these
paths when parsing binary patches without data, though, as we always
expect the header paths to be filled in.
Fix this by using the "---"/"+++" paths by default and only fall back to
header paths if they aren't set. If neither of those paths are set, we
just return an error. Add two tests to verify this behaviour, one of
which would have previously caused a segfault.
---
Sigh. Still not quite fixed, the fuzzer managed to find another variation that causes a segfault. Hopefully this here is the last one.

patch_parse: use paths from "---"/"+++" lines for binary patches

---

include/git2/deprecated.h

Some libraries haven't updated to git_attr_value_t and break.  Adding
the comapt typedef as suggested.
@pks-t please let me know if there's anything else needed.  I took a brief look but didn't see an obvious place where to add tests.  If required please let me know.

Add compat typdef for git_attr_t

---

include/git2/cert.h
src/transports/ssh.c

libssh2 1.9.0 supports SHA-256 host key fingerprints and by checking if LIBSSH2_HOSTKEY_HASH_SHA256 is defined this can be included in git_cert_hostkey when libssh2 supports this without breaking builds when older versions of libssh2 does not.

ssh: include sha256 host key hash when supported

---

tests/config/stress.c

The test in config::stress::huge_section_with_many_values takes quite a
long time to execute. Hide it behind the GITTEST_INVASIVE_SPEED
environment varibale to not needlessly blow up execution time of tests.
As this environment variable is being set by the continuous integration,
we will execute it regularly anyway.

tests: config: only test parsing huge file with GITTEST_INVASIVE_SPEED

---

tests/clar_libgit2_trace.c

If building libgit2's test suite with tracing disabled, then the
compiler will emit a warning due to the unused `message_prefix`
function. Fix the issue by wrapping the whole file into ifdef's for
`GIT_TRACE` and providing separate empty function implementations for
both `cl_global_trace_register` and `cl_global_trace_disable`.

tests: fix compiler warning if tracing is disabled

---

src/patch_parse.c
tests/patch/parse.c
tests/patch/patch_common.h

The patch format for binary files is a simple Base85 encoding with a
length byte as prefix that encodes the current line's length. For each
line, we thus check whether the line's actual length matches its
expected length in order to not faultily apply a truncated patch. This
also acts as a check to verify that we're not reading outside of the
line's string:
if (encoded_len > ctx->parse_ctx.line_len - 1) {
error = git_parse_err(...);
goto done;
}
There is the possibility for an integer underflow, though. Given a line
with a single prefix byte, only, `line_len` will be zero when reaching
this check. As a result, subtracting one from that will result in an
integer underflow, causing us to assume that there's a wealth of bytes
available later on. Naturally, this may result in an out-of-bounds …

patch_parse: fix out-of-bounds reads caused by integer underflow

---

include/git2/cherrypick.h

Updates the docstring of `git_cherrypick_commit` to fix some incorrect mentions of reverting

Fix copy&paste in git_cherrypick_commit docstring

---

src/global.c
src/global.h
src/win32/thread.c

On Windows platforms, we automatically clean up the thread-local storage
upon detaching a thread via `DllMain()`. The thing is that this happens
for every thread of applications that link against the libgit2 DLL, even
those that don't have anything to do with libgit2 itself. As a result,
we cannot assume that these unsuspecting threads make use of our
`git_libgit2_init()` and `git_libgit2_shutdow()` reference counting,
which may lead to racy situations:
Thread 1                    Thread 2
git_libgit2_shutdown()
DllMain(DETACH_THREAD)
git__free_tls_data()
git_atomic_dec() == 0
git__free_tls_data()
TlsFree(_tls_index)
TlsGetValue(_tls_index)
Due to the second thread never having executed `git_libgit2_init()`, the
first thread will clean up TLS data and as a result also free the …

global: convert to fiber-local storage to fix exit races

---

azure-pipelines.yml

Users may fork libgit2 and run libgit2's CI on that, which is
delightful!  However, if they do, we'll fail the documentation publish
phase, which is correct (because we don't allow them to publish _their_
version of the docs) but regrettable (since it should not fail).
Only run the documentation publish phase when we merge branches into the
libgit2/libgit2 repo.

ci: only push docs from the libgit2/libgit2 repo

---

docs/release.md

Note that for security releases, we update the two most recent major release branches.

release.md: note that we do two security releases

---

src/attrcache.c
tests/attr/macro.c

In Git the binary macro was updated to including unsetting merge:
https://github.com/git/git/commit/155a4b712efd3d917c228d155ec57ec2c09d7ac0
They have also removed crlf, but won't do that here. Link for removal in Git:
https://github.com/git/git/commit/5ec3e67052289217c84e53d2cda90d939ac5725b

attr: Update definition of binary macro

---

examples/checkout.c

This pull request implements the guess heuristic used by upstream's git-checkout(1) and git-switch(1), respectively. It will automatically create local branches from existing remote branches if any ref exists that matches. Honestly, I think that this is kind of complex as part of our examples, and I feel like it might be sensible to provide e.g. a flag in `git_checkout` that enables the guessing heuristic.
Fixes #5277, I guess?

examples: checkout: implement guess heuristic for remote branches

---

include/git2/branch.h
src/branch.c
src/refdb_fs.c
src/refs.c
src/refs.h
tests/refs/basic.c

This comes after looking around at #5283, just a few documentation and commentation done.
It seems there's no "create the tracking branch for that branch using that remote" function, which is the low-level operation that's missing from people workflows — right now you can use `git_branch_set_upstream` to do the "verifications & configuration updating", but you have to have created a reference deemed worthwhile of that code to succeed, which is 😒.

branch: clarify documentation around branches

---

src/transports/smart_pkt.c

When parsing OK packets, we copy any information after the initial "ok "
prefix into the resulting packet. As newlines act as packet boundaries,
we also strip the trailing newline if there is any. We do not check
whether there is any data left after the initial "ok " prefix though,
which leads to a pointer overflow in that case as `len == 0`:
if (line[len - 1] == '\n')
--len;
This out-of-bounds read is a rather useless gadget, as we can only
deduce whether at some offset there is a newline character. In case
there accidentally is one, we overflow `len` to `SIZE_MAX` and then
write a NUL byte into an array indexed by it:
pkt->ref[len] = '\0';
Again, this doesn't seem like something that's possible to be exploited
in any meaningful way, but it may surely lead to inconsistencies or DoS.
Fix …

smart_pkt: fix overflow resulting in OOB read/write of one byte

---

src/patch_parse.c

Doing arithmetic with NULL pointers is undefined behaviour in the C
standard. We do so regardless when parsing patches, as we happily add a
potential prefix length to prefixed paths. While this works out just
fine as the prefix length is always equal to zero in these cases, thus
resulting in another NULL pointer, it still is undefined behaviour and
was pointed out to us by OSSfuzz.
Fix the issue by checking whether paths are NULL, avoiding the
arithmetic if they are.

patch_parse: fix undefined behaviour due to arithmetic on NULL pointers

---

include/git2/branch.h

The name of the parameter in the `git_branch_set_upstream` function is `branch_name` and not `name`.

Correct typo in name of referenced parameter

---

src/transports/http.c
src/transports/winhttp.c

Prior to this change, given a remote url with a trailing slash,
such as http://localhost/a/, service requests would contain a
double slash: http://localhost/a//info/refs?service=git-receive-pack.
Prevent that.
I was unable to test the winhttp.c changes locally. I trust that CI will cover that.
Updates #5321
cc @ethomson

http: avoid generating double slashes in url

---

src/submodule.c
tests/submodule/modify.c

git_submodule_sync should resolve submodule before writing to .git/config
to have the same behavior as git_submodule_init, which does the right thing.
This should solve issue #5301

Fix git_submodule_sync with relative url

---

src/pack.c
src/pack.h
src/zstream.c
src/zstream.h
tests/pack/packbuilder.c

While investigating #5324, I noticed that the zlib-related code in packfile looks mighty complicated and could use some love. I thus refactored it to use our own `git_zstream` abstraction, which is a much nicer interface.

Refactor packfile code to use zstream abstraction

---

src/netops.c
tests/network/redirect.c

Some servers leave the query parameters intact in the
Location header when responding with a redirect.
The service_suffix removal check as written assumed
that the server removed them.
Handle both cases.
Along with PR #5325, this fixes #5321.
Please review skeptically; my C is extremely rusty.

netops: handle intact query parameters in service_suffix removal

---

src/transports/ssh.c

Needed to make eg. 2FA work
Fixes the following problem:
- An SSH server has multiple authentication mechanisms configured (`pubkey` and `keyboard-interactive`, both are required).
1. When connecting to the server it responds sends only `pubkey` as an available mechanism
2. libgit correctly invokes `cred_acquire_cb` with `GIT_CREDTYPE_SSH_KEY` set and `GIT_CREDTYPE_SSH_INTERACTIVE` unset.
3. The `pubkey` authentication is completed successfully, but the server responds with a failure code since not all mechanisms have successfully completed.
4. The connection's available mechanisms are updated to only include `keyboard-interactive` on the server side.
5. libgit incorrectly invokes `cred_acquire_cb` with `GIT_CREDTYPE_SSH_KEY` set and `GIT_CREDTYPE_SSH_INTERACTIVE` unset.
- This repeats …

Adds support for multiple SSH auth mechanisms being used sequentially

---

deps/ntlmclient/ntlm.c

Pull in commit
https://github.com/ethomson/ntlmclient/commit/e7b2583e1bc28c33c43854e7c318e859b4e83bef
to fix #5353.

ntlm: prevent (spurious) compiler warnings

---

src/win32/posix_w32.c
tests/core/posix.c

On Windows platforms, we need some logic to emulate symlink(3P) defined
by POSIX. As unprivileged symlinks on Windows are a rather new feature,
our current implementation is comparatively new and still has some
rough edges in special cases.
One such case is relative symlinks. While relative symlinks to files in
the same directory work as expected, libgit2 currently fails to create
reltaive symlinks pointing into other directories. This is due to the
fact that we forgot to translate the Unix-style target path to
Windows-style. Most importantly, we are currently not converting
directory separators from "/" to "\".
Fix the issue by calling `git_win32_path_canonicalize` on the target.
Add a test that verifies our ability to create such relative links
across directories.
Fixes #5252.

win32: fix relative symlinks pointing into dirs

---

src/commit.c
src/object.c

The same error message appears in other places with the word `"the"` included. API consumers in higher-level languages such as JavaScript (via nodegit) might consume these strings, so they should be consistent.

Make type mismatch errors consistent

---

src/index.c

Traditionally, our maps were mostly implemented via macros that had
weird call semantics. This shows in our index code, where we have macros
that insert into an index map case-sensitively or insensitively, as they
still return error codes via an error parameter. This is unwieldy and,
most importantly, not necessary anymore, due to the introduction of our
high-level map API and removal of macros.
Replace them with inlined functions to make code easier to read.

index: replace map macros with inline functions

---

src/refs.c
tests/iterator/workdir.c
tests/refs/delete.c
tests/refs/list.c
tests/refs/races.c
tests/resources/testrepo/.gitted/refs/symref

This requires adding a new symbolic ref to the testrepo fixture.
Some of the existing tests attempt to delete HEAD, expecting a different failure. Introduce and use a non-HEAD symbolic ref instead.
Adjust a few other tests as needed.
Fixes #5357

refs: refuse to delete HEAD

---

src/repository.c
tests/repo/open.c

Regression introduced in commit dde6d9c706bf1ecab545da55ab874a016587af1f.
This issue causes lots of crashes in TortoiseGit.

Do not return free'd git_repository object on error

---

include/git2/sys/merge.h
src/merge_driver.c

Because this accessor is const, I can't do something like this in the git merge driver without casting away const:
```cpp
int CustomApply(git_merge_driver* self,
const char** path_out,
uint32_t* mode_out,
git_buf* merged_out,
const char* filter_name,
const git_merge_driver_source* src) {
const git_repository* repo = git_merge_driver_source_repo(src);
git_config* cfg;
// ERROR! repo is const!
int errorCode = git_repository_config(&cfg, repo);
git_config_free(cfg);
return 0;
}
```
The definition of git_merge_driver_source has git_repository as non-const:
```
struct git_merge_driver_source {
git_repository *repo;
const char *default_driver;
const git_merge_file_options *file_opts;
const git_index_entry *ancestor;
const git_index_entry *ours;
const git_index_entry *theirs;
};
```

merge: Return non-const git_repository from accessor method

---

src/diff.h
src/diff_file.c
src/diff_file.h
src/diff_generate.c
src/diff_tform.c
src/iterator.c
src/iterator.h
src/merge.h
src/pathspec.c
src/rebase.c
src/status.c
src/transports/auth.c
src/transports/auth.h
src/transports/auth_negotiate.c
src/transports/auth_ntlm.c
src/transports/http.c
tests/merge/merge_helpers.h

libgit2 does not use `type_t` suffixes as it's redundant; thus, rename some internal types to remove `type` from the name.
* `git_http_authtype_t` -> `git_http_auth_t`
* `git_iterator_type_t` -> `git_iterator_t`
* `git_rebase_type_t` -> `git_rebase_t`
* `git_merge_diff_type_t` -> `git_merge_diff_t`

internal types: change enums from `type_t` to `_t`

---

include/git2/attr.h
include/git2/common.h
include/git2/errors.h
include/git2/oid.h
include/git2/remote.h
include/git2/revwalk.h
include/git2/sys/index.h
include/git2/sys/mempack.h
include/git2/sys/repository.h
include/git2/tree.h
src/attrcache.c
src/errors.c
src/index.c
src/odb_mempack.c
src/oid.c
src/remote.c
src/repository.c
src/revwalk.c
src/settings.c
src/tree.c

Return `int` from all the functions that aren't `dispose` or `free` functions.  This allows us to gracefully fail on bad inputs (instead of an `assert` or crashing with a segmentation fault).
Only functions that cannot fail will remain void.  This includes:
* `*_dispose` and `*_free`: which should gracefully take `NULL` pointers, ignore them, and continue.
* `giterr_clear`: which cannot fail (since it just updates pointers in global state)
* `giterr_set_oom`: which cannot fail (since it just updates pointers in global state)

Return int from non-free functions

---

README.md

https://github.com/libgit2/libgit2#language-bindings mentions the Julia binding to be at https://github.com/jakebolewski/LibGit2.jl , which doesn't exist anymore. LibGit2.jl has been merged into the Julia standard library (inside the main Julia language repo). Updated the link to the new location in this PR.

Update link to libgit2 Julia language binding

---

azure-pipelines.yml

To allow testing against a Kerberos instance, we have added variables
for the Kerberos password to allow authentication against LIBGIT2.ORG in
commit e5fb5fe5a (ci: perform SPNEGO tests, 2019-10-20). To set up the
password, we assign
"GITTEST_NEGOTIATE_PASSWORD=$(GITTEST_NEGOTIATE_PASSWORD)"
in the environmentVariables section which is then passed through to a
template. As the template does build-time expansion of the environment
variables, it will expand the above line verbosely, and due to the
envVar section not doing any further expansion the password variable
will end up with the value "$(GITTEST_NEGOTIATE_PASSWORD)" in the
container's environment.
Fix this fixed by doing expansion of GITTEST_NEGOTIATE_PASSWORD at
build-time, as well.

azure-pipelines: properly expand negotiate passwords

---

src/fetchhead.c
tests/fetchhead/nonetwork.c
tests/online/fetchhead.c

If fetching from an anonymous remote via its URL, then the URL gets
written into the FETCH_HEAD reference. This is mainly done to give
valuable context to some commands, like for example git-merge(1), which
will put the URL into the generated MERGE_MSG. As a result, what gets
written into FETCH_HEAD may become public in some cases. This is
especially important considering that URLs may contain credentials, e.g.
when cloning 'https://foo:bar@example.com/repo' we persist the complete
URL into FETCH_HEAD and put it without any kind of sanitization into the
MERGE_MSG. This is obviously bad, as your login data has now just leaked
as soon as you do git-push(1).
When writing the URL into FETCH_HEAD, upstream git does strip
credentials first. Let's do the same by trying to parse the remote URL
as …

fetchhead: strip credentials from remote URL

---

src/transports/http.c
tests/online/clone.c

In commit b9c5b15a7 (http: use the new httpclient, 2019-12-22), the HTTP
code got refactored to extract a generic HTTP client that operates
independently of the Git protocol. Part of refactoring was the creation
of a new `git_http_request` struct that encapsulates the generation of
requests. Our Git-specific HTTP transport was converted to use that in
`generate_request`, but during the process we forgot to set up custom
headers for the `git_http_request` and as a result we do not send out
these headers anymore.
Fix the issue by correctly setting up the request's custom headers.
---
Fixes #5385.

transports: http: fix custom headers not being applied

---

tests/iterator/workdir.c

The testcase iterator::workdir::filesystem_gunk sets up quite a lot of
directories, which is why it only runs in case GITTEST_INVASIVE_SPEED is
set in the environment. Because we do not run our default CI with this
variable, we didn't notice commit 852c83ee4 (refs: refuse to delete
HEAD, 2020-01-15) breaking the test as it introduced a new reference to
the "testrepo" repository.
Fix the oversight by increasing the number of expected iterator items.

tests: iterator: fix iterator expecting too few items

---

azure-pipelines/docker/bionic
azure-pipelines/docker/entrypoint.sh
azure-pipelines/docker/xenial
azure-pipelines/test.sh

Azure Pipelines will report all messages printed to stderr at the end of a pipeline step, leading to output like below. It's convoluted, hard to read and ultimately completely pointless clutter that points to nonexistent errors. So let's fix all instances that caused prints to stderr without any real (or at least with irrelevant) reason.
```
Total Test time (real) =   0.05 sec
Cleaning up...
Stopping git daemon...
Stopping SSH...
Done.
Some tests failed.
/home/libgit2/source/azure-pipelines/test.sh: line 317:    26 Terminated              git daemon --listen=localhost --export-all --enable=receive-pack --base-path="${GITDAEMON_DIR}" "${GITDAEMON_DIR}" 2> /dev/null
##[error]useradd: warning: the home directory already exists.
##[error]Not copying any file from skel directory into it. …
```

azure: fix misleading messages printed to stderr being

---

.editorconfig
script/release.py

The current release process is not documented in any way. As a result,
it's not obvious how releases should be done at all, like e.g. which
locations need adjusting.
To fix this, let's introduce a new script that shall from now on be used
to do all releases. As input it gets the tree that shall be released,
the repository in which to do the release, credentials to
authenticate against GitHub and the new version. E.g. executing the
following will create a new release v0.32:
$ ./script/release.py 0.32.0 --user pks-t --password ****
While the password may currently be your usual GitLab password, it's
recommended to use a personal access token intead.
The script will then perform the following steps:
1. Verify that "include/git2/version.h" matches the new version.
2. Verify that …

Release script

---

azure-pipelines/docker/entrypoint.sh

In commit 01a834066 (azure: docker: fix ARM builds by replacing gosu(1),
2020-02-18), we've switched our entrypoint from gosu(1) to use sudo(1)
instead to fix our ARM builds. The switch introduced an incompatibility
that now causes our Coverity builds to fail, as the "--preserve-env"
switch will also keep HOME at its current value. As a result, Coverity
now tries to set up its configuration directory in root's home
directory, which it naturally can't write to.
Fix the issue by adding the "--set-home" flag to sudo(1).

azure: docker: set up HOME variable to fix Coverity builds

---

README.md

As noted in docs/release.md, we only provide security updates for the
latest two releases. Let's thus drop the build status of both v0.27 and
v0.26 branches, adding the new v0.99 branch instead.

README: update our build matrix to reflect current releases

---

tests/diff/tree.c
tests/diff/workdir.c

While it is not allowed for a tree to have an empty tree as child (e.g.
an empty directory), libgit2's tree builder makes it easy to create such
trees. As a result, some applications may inadvertently end up with such
an invalid tree, and we should try our best and handle them.
One such case is when diffing two trees, where one of both trees has
such an empty subtree. It was reported that this will cause our diff
code to fail. While I wasn't able to reproduce this error, let's still
add a test that verifies we continue to handle them correctly.
---
Fixes #3933 
The test is a near 1:1 translation of the Gist provided in that issue and I've added some more checks to verify that our behaviour is correct. I'd thus think that the issue has been fixed since.

tests: diff: verify that we are able to diff with empty subtrees

---

cmake/Modules/PkgBuildConfig.cmake

Remove using custom PKG_BUILD_PREFIu, PKG_BUILD_LIBDIR and
PKG_BUILD_INCLUDEDIR variables.
Use cmake CMAKE_INSTALL_PREFIX, LIB_INSTALL_DIR, INCLUDE_INSTALL_DIR instead.
This patch fixes install libgit2.pc file in correct location and simpifies
cmake module.
When typical rpm package is build is passed typical set of cmakle switches. with base paths:
```
$ rpm -E %cmake | grep -- -D
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_AR=${AR} \
-DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" \
-DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" \
-DCMAKE_Fortran_FLAGS_RELEASE="-DNDEBUG" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_NM=${NM} \
-DCMAKE_RANLIB=${RANLIB} \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DINCLUDE_INSTALL_DIR=/usr/include \
-DLIB_INSTALL_DIR=/usr/lib64 \
-DLIB_SUFFIX=64 \
-DSHARE_INSTALL_PREFIX=/usr/share \ …
```

Fix #5410: fix installing libgit2.pc in wrong location

---

deps/ntlmclient/compat.h
src/transports/auth_ntlm.c

The ntlmclient dependency defines htonll on Linux-based systems, only.
As a result, non-Linux systems will run into compiler and/or linker
errors due to undefined symbols.
Fix this issue for FreeBSD, OpenBSD and SunOS/OpenSolaris by including
the proper headers and defining the symbol accordingly.
---
We should probably merge this upstream first, but given that upstream means @ethomson I've decided to create the PR here first to let people in #5414 verify the fix more easily.
Fixes #5414

deps: ntlmclient: fix missing htonll symbols on FreeBSD and SunOS

---

azure-pipelines/docker/xenial

[tls.mbed.org](tls.mbed.org) is not providing their [full certificate chain](https://www.ssllabs.com/ssltest/analyze.html?d=tls.mbed.org).  Download their intermediate cert and use it (and the normal cacert list) during the mbedTLS download.

azure-pipelines: download GlobalSign's certificate manually

---

deps/ntlmclient/compat.h

In commit 3828ea67b (deps: ntlmclient: fix missing htonll symbols on
FreeBSD and SunOS, 2020-02-21), we've fixed compilation on BSDs due to
missing `htonll` wrappers. While we are now using `htobe64` for both
Linux and OpenBSD, we decided to use `bswap64` on FreeBSD. While correct
on little endian systems, where we will swap from little- to big-endian,
we will also do the swap on big endian systems. As a result, we do not
use network byte order on such systems.
Fix the issue by using htobe64, as well.
---
@mfechner: could you please confirm that this still works as expected?
@ethomson: this is the follow-up to #5417

deps: ntlmclient: fix htonll on big endian FreeBSD

---

azure-pipelines/docker/bionic

tls.mbed.org has neglected to send their full certificate chain.  Add their intermediate cert manually.  🙄

ci: provide globalsign certs for bionic

---

src/transports/httpclient.c

Use a 16kb read buffer for compatibility with macOS SecureTransport.
SecureTransport `SSLRead` has the following behavior:
1. It will return _at most_ one TLS packet's worth of data, and
2. It will try to give you as much data as you asked for
This means that if you call `SSLRead` with a buffer size that is smaller than what _it_ reads (in other words, the maximum size of a TLS packet), then it will buffer that data for subsequent calls.  However, it will also attempt to give you as much data as you requested in your SSLRead call.  This means that it will guarantee a network read in the event that it has buffered data.
Consider our 8kb buffer and a server sending us 12kb of data on an HTTP Keep-Alive session.  Our first `SSLRead` will read the TLS packet off the network.  It will return …

httpclient: use a 16kb read buffer for macOS

---

src/win32/path_w32.c
src/win32/path_w32.h
src/win32/posix_w32.c
tests/core/posix.c
tests/path/win32.c

Our path canonicalization (beginning in  cceae9a) was meant to deal with absolute paths, converting things like `C:\Foo\Bar` into `\\?\C:\Foo\Bar` so that we could avoid some of the dangers of NTFS (like eliding trailing dots in filenames).  But by using those paths, we need to do canonicalization ourselves, as giving `\\?\C:\Foo\..\Bar` to the filesystem APIs will return an error instead of resolving the path.
These canonicalization function were not meant to deal with relative paths.  In particular, this means that leading ".." segments at the beginning of paths were removed, to translate `C:\..\..\..\` into the correct `\\?\C:\`.  (This is despite having some tests around relative path components, they were not well thought out since they were not intended to be used.)
Update the …

win32: don't canonicalize relative paths

---

src/refdb_fs.c

While the `git_refdb_backend()` struct has a version, we do not
initialize it correctly when calling `git_refdb_backend_fs()`. Fix this
by adding the call to `git_refdb_init_backend()`.

refdb_fs: initialize backend version

---

src/transports/httpclient.c

Whilst doing the update in Debian, I found this spelling error.
Thus this PR fixes the same :)

Fix spelling error

---

include/git2/deprecated.h

The credential structures are now opaque and defined in `sys/credential.h`.  However, we should continue to provide them for backward compatibility, unless `GIT_DEPRECATED_HARD` is set.
Fixes #5415

credentials: provide backcompat for opaque structs

---

include/git2/sys/refdb_backend.h

The callbacks are currently sparsely documented, making it really hard
to implement a new backend without taking a look at the existing
refdb_fs backend. Add documentation to make this task hopefully easier
to achieve.
Fixes #5457 
/cc @ddevault

refdb_backend: improve callback documentation

---

docs/changelog.md
include/git2/version.h

This is in preparation for v1.0, including the update to our changelog and the version bump. I don't think we settled for any name yet, so I just chose a temporary one ("Aprilscherz" -> April Fools' joke). @carlosmn, you always manage to come up with weird German words, so if you want to give this a go I'd be happy to change it ;)
Right now, it looks like we should be able to release both v1.0 and v0.28.5 right on schedule on April 1st.

Release v1.0

---

src/diff_print.c
src/patch_parse.c
tests/patch/patch_common.h
tests/patch/print.c

When generating a patch for a renamed file whose mode bits have changed
in addition to the rename, then we currently fail to parse the generated
patch. Furthermore, when generating a diff we output mode bits after the
similarity metric, which is different to how upstream git handles it.
Fix both issues by adding another state transition that allows
similarity indices after mode changes and by printing mode changes
before the similarity index.
---
Fixes #5460

patch: correctly handle mode changes for renames

---

src/repository.c
tests/repo/open.c

Git has supported repository format version 1 for some time.  This format is just like version 0, but it supports extensions. Implementations must reject extensions that they don't support.
Add support for this format version and reject any extensions but extensions.noop, which is the only extension we currently support.
This is a prerequisite to adding SHA-256 support.

Handle repository format v1

---

src/merge.c
tests/merge/trees/renames.c

When computing renames, we cache the hash signatures for each of the
potentially conflicting entries so that we do not need to repeatedly
read the file and can at least halfway efficiently determine whether two
files are similar enough to be deemed a rename. In order to make the
hash signatures meaningful, we require at least four lines of data to be
present, resulting in at least four different hashes that can be
compared. Files that are deemed too small are not cached at all and
will thus be repeatedly re-hashed, which is usually not a huge issue.
The issue with above heuristic is in case a file does _not_ have at
least four lines, where a line is anything separated by a consecutive
run of "\n" or "\0" characters. For example "a\nb" is two lines, but
"a\0\0b" is also just two lines. …

merge: cache negative cache results for similarity metrics

---

tests/repo/open.c

Update the test cases to check the `git_repository_open` return code.

repo::open: ensure we can open the repository

---

src/indexer.c
src/pack.c
src/pack.h

This change moves the responsibility of setting the error upon failures
of get_delta_base() to get_delta_base() instead of its callers. That
way, the caller chan always check if the return value is negative and
mark the whole operation as an error instead of using garbage values,
which can lead to crashes if the `.pack` files are malformed.

pack: Improve error handling for get_delta_base()

---

src/worktree.c

Commit 0b5ba0d replaced this function with an "option_init"
equivallent, but misspelled the replacement function. As a result, this
symbol has been missing from libgit2.so ever since.

Fix typo causing removal of symbol 'git_worktree_prune_init_options'

---

src/sysdir.c
src/sysdir.h

This appears to be leftover from when we exposed this to the user.  We've moved to `git_buf`.

sysdir: remove unused git_sysdir_get_str

---

deps/ntlmclient/compat.h

unbreaks the build. should probably use this by default with the operating systems that don't have it being the exception.

deps: ntlmclient: use htobe64 on NetBSD too

---

src/util.c

When debugging issues, `git__hexdump` can be useful, but its format is unlike the familiar `hexdump` command-line tool.  If you wanted to parse this output, it would be more helpful if it matched.
Update it to match `hexdump -C`.

git__hexdump: better mimic `hexdump -C`

---

CMakeLists.txt

This feature requires Visual Studio 2015 (`MSVC_VERSION` = 1900) or later. As the minimum required CMake version is currently less than 3.7, `GREATER_EQUAL` is not available to us and we must invert the result of the `LESS` operator.

MSVC: Enable Control Flow Guard (CFG)

---

docs/coding-style.md

For years, we've repeatedly had confusion about what our actual coding
style is not only for newcomers, but also across the core contributors.
This can mostly be attributed to the fact that we do not have any coding
conventions written down. This is now a thing of the past with the
introduction of a new document that gives an initial overview of our
style and most important best practices for both our C codebase as well
as for CMake.
While the proposed coding style for our C codebase should be rather
uncontroversial, the coding style for CMake might be. This can be
attributed to multiple facts. First, the CMake code base doesn't really
have any uniform coding style and is quite outdated in a lot of places.
Second, the proposed coding style actually breaks with our existing one:
we …

docs: add documentation for our coding style

---

src/checkout.c
tests/checkout/index.c

During checkout with GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH, we were previously applying the pathspec filter for the baseline iterator during checkout, as well as the target **tree**.  (We were not applying the pathspecs when the target was not a tree.)
This was an oversight; in fact, we should apply the pathspec filter to _all_ checkout targets, not just trees.
Add a helper function to set the iterator pathspecs from the given checkout pathspecs, and call it everywhere.
Includes the test provided by https://github.com/libgit2/libgit2/commit/f37c77b4186714b0a973cab1c0a9dcf8efd19fae with some minor modifications.

Honor GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH for all checkout types 

---

src/stash.c

I was playing around with some new static analyzer features in Visual C++ and used libgit2 as a guinea pig. The only really interesting thing flagged was the function `stash_to_index` in [stash.c](https://github.com/libgit2/libgit2/blob/284816093ee733490d2129031cb2634b0ac61f6d/src/stash.c#L171).
At the start of the function we say: if the repo is *not* bare, then get a pointer to the index and put it in `repo_index`. If that fails, return the error. OK, but if the repo *is* bare, `repo_index` remains uninitialized stack memory.
Later we must pass the boolean `trust_mode` parameter to `git_index_entry__init_from_stat`. The expression used is `(repo_index != NULL || !repo_index->distrust_filemode)`. This seems like it must be wrong. It says: if `repo_index` is not `NULL`, pass `true`. If …

Fix uninitialized stack memory and NULL ptr dereference in stash_to_index

---

tests/merge/trees/renames.c

We currently use `PRIuMAX` to print an integer of type `size_t` in
merge::trees::rename::cache_recomputation. While this works just fine on
64 bit arches, it doesn't on 32 bit ones. As a result, our nightly
builds on x86 and arm32 fail.
Fix the issue by using `PRIuZ` instead.

tests: merge: fix printf formatter on 32 bit arches

---

script/release.py

Following up  #5511. This pull request update `script/release.py` to check the version in `package.json` before release.

Check the version in package.json

---

src/futils.c
src/futils.h

While the function `git_futils_fake_symlink` is declared with arguments
`new, old`, the implementation uses the reverse order `old, new`. Let's
fix the ordering issues to be `new, old` for both, which matches what
symlink(3P) has. While at it, we also rename these parameters: `old` and
`new` doesn't really make a lot of sense in the context of symlinks,
which is why this commit renames them to be called `target` and `path`.
Fixes #5489

futils: fix order of declared parameters for `git_futils_fake_symlink`

---

src/checkout.c
tests/checkout/index.c

The test checkout::index::can_disable_pathspec_match creates a set of
files, rewrites them and then checks them out again with a pathspec with
the expectancy that a subset of files matching the pathspec is restored
to their original contents. One implementation detail of the test is
that both original content and modified content have the same number of
bytes. As a result, we'll only regard these files as changed in case
their mtime doesn't match what's in the index. And, if we do not think a
file was modified, we'll not restore its contents, resulting in a racy
test setup.
Fix the issue by using differently sized contents for original and
modified content. Like this, the stat cache will always be different and
not depend on the mtime anyomre, fixing the raciness.
Fixes #5514

tests: checkout: fix flaky test due to mtime race

---

src/index.c
tests/index/version.c

In v4 index, the path of an entry is prefix-compressed relative to the
path for the previous entry.
According to index-format.txt from git, the path of an entry is prefixed with N, where N indicates the length of bytes to be stripped from the previous path, not the length in common.
Given the `paths=[aaabbb,aaacc,aaaddd]`, correct index entries are `[(0)aaabbb,(3)cc,(2)ddd]`.
However, the index entries generated are `[(0)aaabbb,(3)cc,(3)ddd]`.
The following code snippet works now:
```c
git_repository *repo = NULL;
git_repository_open(&repo, ".");
git_repository_index(&index, repo));
git_index_write(index);              // wrote an invalid index
git_index_free(index);
git_repository_free(repo);
git_repository_open(&repo, ".");     // reopen repo
git_repository_index(&index, repo);  // …
```

Make git_index_write() generate valid v4 index

---

src/config_file.c
tests/config/read.c

A quick cleanup of #5503, with an added test case.

Handle unreadable configuration files

---

tests/diff/workdir.c

The static test data is erroneously initialized with a length of 0 for three of the strings.  This means the tests are not actually examining those strings.  Provide the length.

diff::workdir: actually test the buffers

---

src/apply.c
src/attr_file.c
src/attrcache.c
src/checkout.c
src/diff_generate.c
src/diff_parse.c
src/diff_tform.c
src/index.c
src/iterator.c
src/merge.c
src/pack-objects.c
src/pathspec.c
src/pool.c
src/pool.h
src/refdb_fs.c
src/revwalk.c
src/sortedcache.c
src/transaction.c

`git_pool_init` should be allowed to fail.  At the moment, `git_pool_init` will `assert` that the given arguments are correct.  We would like to use `GIT_ASSERT` instead.
This change is in preparation for removing uses of `assert` and replacing them with our `GIT_ASSERT`, however that requires a function that returns a value.

git_pool_init: allow the function to fail

---

examples/checkout.c
examples/general.c
examples/remote.c
examples/tag.c
include/git2/deprecated.h
include/git2/strarray.h
src/branch.c
src/remote.c
src/repository.c
src/strarray.c
src/transports/local.c
src/transports/smart.c
src/util.c
tests/network/fetchlocal.c
tests/network/remote/remotes.c
tests/network/remote/rename.c
tests/object/tag/list.c
tests/online/fetchhead.c
tests/online/remotes.c
tests/refs/list.c
tests/refs/listall.c
tests/refs/namespaces.c
tests/remote/create.c
tests/remote/list.c
tests/submodule/add.c
tests/worktree/bare.c
tests/worktree/refs.c
tests/worktree/worktree.c

We standardized on `dispose` as the verb for freeing the contents of a structure, but not the structure itself.  Thus, `git_strarray_free` should be `git_strarray_dispose`.  While we're here, we shouldn't offer the `git_strarray_copy` function publicly; there's no value in it for users.

strarray refactoring

---

tests/clar/fs.h

clar has historically shelled out to `/bin/cp` to copy test fixtures into a sandbox and `/bin/rm` to clean them up.  This has two deficiencies:
1. `/bin/cp` is slower than simply opening the source and destination and copying them in a read/write loop.  On my Mac, the `/bin/cp` based approach takes ~2:40 for a full test pass.  Using a read/write loop to copy the files ourselves takes ~1:50.  Similarly, `/bin/rm` is slower than doing this internally.  Moving to an internal traversal shaves another 20 seconds off.
These numbers are less impressive on Linux, but using `sendfile` there makes a notable improvement.
2. It's noisy.  Since the leak detector follows fork/exec, we'll end up running the leak detector on `/bin/cp` and `/bin/rm`.  This would be fine, except that the leak detector …

clar: use internal functions instead of /bin/cp and /bin/rm

---

src/odb_mempack.c

The mempack ODB backend creates a packbuilder internally to write out a
pack; call git_packbuilder_set_threads on that packbuilder, to use
threads for packing if available.

mempack: Use threads when building the pack

---

include/git2/pack.h
src/pack-objects.c
tests/pack/packbuilder.c

If given a NULL path, write to the object path of the repository.
Includes tests.

git_packbuilder_write: Allow setting path to NULL to use the default path

---

src/transports/httpclient.c
tests/online/clone.c

After the [great smart http refactoring of 2020](https://github.com/libgit2/libgit2/pull/5286), we [no longer support googlesource](https://github.com/libgit2/libgit2/issues/5525).  It turns out that google code - by default - sends very large data packets (65520) which is very neat to the upper limit of a packet size for a git data packet over the smart protocols.  This illustrates some problems in our handling of very large data packets.
In particular, we read a block of data from the client and try to put it in the output buffer.  When the output buffer (for data packets, this is a buffer of 65536) is nearly full, we do not take that into account and do a read of a block, despite the fact that we cannot fit it into the caller's output buffer.  We then discard what cannot be sent back. …

httpclient: support googlesource

---

tests/clar.c

When using `-s` to specify a particular test, it will do a prefix match.
Thus, `-sapply::both::rename_a_to_b_to_c` will match both a test named
`test_apply_both__rename_a_to_b_to_c` and a test that begins with that
name, like `test_apply_both__rename_a_to_b_to_c_exact`.
Permit a trailing `$` to `-s` syntax.  This allows a user to specify
`-sapply::both::rename_a_to_b_to_c$` to match _only_ the
`test_apply_both__rename_a_to_b_to_c` function.
We already filter to ensure that the given prefix matches the current
test name.  Also ensure that the length of the test name matches the
length of the filter, sans trailing `$`.
Fixes https://github.com/clar-test/clar/issues/83

tests: offer exact name matching with a `$` suffix

---

deps/ntlmclient/compat.h
docs/changelog.md
script/release.py
src/config_file.c
src/index.c
src/merge.c
src/stash.c
src/transports/httpclient.c
src/worktree.c
tests/config/read.c
tests/index/version.c
tests/merge/trees/renames.c
tests/online/clone.c

This includes the following changes, cherry-picked from the PRs that have been labeled `release-1.0.1`, and includes a changelog.
11dca3ca20af4bfa74d926db5693ed2314ecceb2 v1.0.1: prepare the changelog
79507cd8b2fb89555fa1a900d84f24e629fdf902 httpclient: clear the read_buf on new requests
bc61161b9879e03842a8df6764d40a49497e765e httpclient: don't read more than the client wants
ed045f0912ad6cbc512a98ebfbdd6ea08682f4ad httpclient: read_body should return 0 at EOF
7a6566e391f50845ea81e3dc18d0da69790c31ee online::clone: test a googlesource URL
3939e810493b4dde595f9b523e24ad1b684ba9bb tests: index::version: write v4 index: re-open repo to read written v4 index
e2294859bdd1a9f65d04e1b132c2a0466b0c2bd1 index: write v4: bugfix: prefix path with strip_len, not same_len …

Release v1.0.1

---

tests/diff/parse.c

We don't call any internal functions in the test; we don't need to
include `../src/diff.h`.

diff::parse: don't include `diff.h`

---

tests/checkout/crlf.c
tests/clar.c
tests/clar.h
tests/clar/print.h
tests/clar_libgit2.c
tests/clar_libgit2.h
tests/core/mkdir.c
tests/core/structinit.c
tests/core/wildmatch.c
tests/core/zstream.c
tests/diff/parse.c
tests/diff/submodules.c
tests/ignore/path.c
tests/ignore/status.c
tests/index/addall.c
tests/index/crlf.c
tests/index/filemodes.c
tests/object/commit/commitstagedfile.c
tests/object/tree/write.c
tests/refs/reflog/reflog_helpers.c
tests/repo/env.c
tests/status/status_helpers.h
tests/status/submodules.c
tests/submodule/submodule_helpers.c
tests/submodule/submodule_helpers.h

This adds a new command-line option to clar, `-t`, which will produce output in the popular TAP format, which can be used by multiple different frontends to display test output.
This retroactively names the existing clar output format as "clap" (the "clar protocol"), and adds support for tap (the [test anywhere protocol](https://testanything.org/)).
This adds support for [TAP version 13](https://testanything.org/tap-version-13-specification.html).
It includes the optional YAML block to provide more information about test failures.  Since this is not yet standardized, we have copied the output format of the popular [node tap](https://node-tap.org/tap-protocol).

clar: add tap output option

---

examples/log.c

Docurium seems to be confused by our use of `/** comment */;` use in the
log example. Let's just switch it around to help Docurium get this
right.
---
This is rather a shot in the dark, but lets see if it's enough to fix #4918 and fix #5538

examples: log: fix documentation generation

---

.github/workflows/main.yml
azure-pipelines.yml
azure-pipelines/build.sh
azure-pipelines/docker/bionic
azure-pipelines/docker/xenial
azure-pipelines/getcontainer.sh
azure-pipelines/setup-mingw.sh

I've been a bit frustrated with the way we use docker containers in our build.  Previously, we would have to manually pre-build the docker containers any time they changed.  This was - obviously - disappointing because any workflow that involves the world "manual" is incredibly disappointing - but it had the advantage of not needing to build the containers as part of the CI process.  We moved to a process where we build the containers and then run them every time.  This mitigated the manual processes but it increased the build time for our Linux builds rather substantially.
We tried to mitigate this by caching some of the layers of the image, but there's a limited amount of cache space available.  But we _could_ save them instead in a package service colocated with our CI.  (Numbers after …

Introduce CI with GitHub Actions

---

include/git2/index.h

This change makes the docs reflect reality. The id and size were never
updated in the entry!

index: Update the documentation for git_index_add_from_buffer()

---

src/diff_print.c

This is some random fixes for the diff-printing code:
- removed a call to abort and replace it with `GIT_ASSERT`
- fix silent success when printing to a file fails
- detection of an out-of-memory situation when printing binaries
- some fixes to our code style

Random fixes for diff-printing

---

deps/ntlmclient/ntlm.c

This change makes the code pass the libgit2 tests cleanly when
MSan/UBSan are enabled. Notably:
* Changes malloc/memset combos into calloc for easier auditing.
* Makes `write_buf` return early if the buffer length is empty to avoid
arithmetic with NULL pointers (which UBSan does not like).
* Initializes a few arrays that were sometimes being read before being
written to.

Make NTLMClient Memory and UndefinedBehavior Sanitizer-clean

---

src/CMakeLists.txt
src/win32/git2.rc

The approach is similar to the one taken by zlib:
https://github.com/madler/zlib/blob/master/win32/zlib1.rc
Also, the LIBGIT2_FILENAME macro needs to be stringized for windres.exe to understand it.

Enable building git2.rc resource script with GCC

---

src/apply.c
src/buffer.c
src/index.c

This change makes the tests run cleanly under
`-fsanitize=undefined,nullability` and comprises of:
* Avoids some arithmetic with NULL pointers (which UBSan does not like).
* Avoids an overflow in a shift, due to an uint8_t being implicitly
converted to a signed 32-bit signed integer after being shifted by a
32-bit signed integer.
* Avoids a unaligned read in libgit2.
* Ignores unaligned reads in the SHA1 library, since it only happens on
Intel processors, where it is _still_ undefined behavior, but the
semantics are moderately well-understood.
Of notable omission is `-fsanitize=integer`, since there are lots of
warnings in zlib and the SHA1 library which probably don't make sense to
fix and I could not figure out how to silence easily. libgit2 itself
also has ~100s of warnings which are …

Make the tests run cleanly under UndefinedBehaviorSanitizer

---

src/refdb.c
src/refdb.h
src/refdb_fs.c
src/refs.c
tests/refs/reflog/messages.c

I've decided to pull out some of the preliminary work for the reftable backend in order to keep #5462 focussed on the already-intense refdb logic. This PR is what I ended up with. I did several refactorings to pull out functions that are commonly needed for refdb backend implementations and moved the resolving logic from the refs code into the refdb code, mostly in order to deduplicate the three different symref resolvers we had. This also fixes a bug where we could spin indefinitely resolving symrefs in case there's a symref loop in our repo.

refdb: a set of preliminary refactorings for the reftable backend

---

src/branch.c
src/refs.c
src/refs.h
src/repository.c
src/repository.h
tests/worktree/refs.c
tests/worktree/repository.c
tests/worktree/worktree.c

There's quite a few places where we're accessing HEAD directly via the filesystem, which is completely broken in case repos use a different refdb backend than the filesystem-based one. This pull request addresses a subset of these which is updating HEAD in the context of worktrees.

Access HEAD via the refdb backends

---

.github/workflows/main.yml
azure-pipelines/build.sh
azure-pipelines/docker/focal
script/sanitizers.supp

This change adds two new build targets: MSan and UBSan. This is because
even though OSS-Fuzz is great and adds a lot of coverage, it only does
that for the fuzz targets, so the rest of the codebase is not
necessarily run with the Sanitizers ever :( So this change makes sure
that MSan/UBSan warnings don't make it into the codebase.
As part of this change, the Ubuntu focal container is introduced. It
builds mbedTLS and libssh2 as debug libraries into /usr/local and as
MSan-enabled libraries into /usr/local/msan. This latter part is needed
because MSan requires the binary and all its dependent libraries to be
built with MSan support so that memory allocations and deallocations are
tracked correctly to avoid false positives.

Add CI support for Memory and UndefinedBehavior Sanitizers

---

.github/workflows/main.yml

We don't build with SPNEGO enabled on our focal-based sanitizer builds,
so we need to disable the negotiate tests.

sanitizer ci: skip negotiate tests

---

src/pack.c

Our processing loop in git_zstream_get_output_chunk does not handle
`Z_BUF_ERROR` appropriately at the end of a compressed window.
From the zlib manual, inflate will return:
> Z_BUF_ERROR if no progress was possible or if there was not enough
> room in the output buffer when Z_FINISH is used. Note that Z_BUF_ERROR
> is not fatal, and inflate() can be called again with more input and
> more output space to continue decompressing.
In our loop, we were waiting until we got the expected size, then
ensuring that we were at `Z_STREAM_END`.  We are not guaranteed to be,
since zlib may be in the `Z_BUF_ERROR` state where it has consumed a
full window's worth of data, but it doesn't know that it's really at the
end of the stream.  There _could_ be more compressed data, but it
doesn't _know_ that …

zstream: handle Z_BUF_ERROR appropriately in get_output_chunk

---

src/mwindow.c

If `*out_window` was already non-null, then this function would always return true.
This was causing `git_mwindow_close_lru_window` to not remove the correct window from the list, leading to a double free.
Fixes #5591

Fix `git_mwindow_scan_recently_used` spuriously returning true

---

src/describe.c

The argument "opts" can be NULL, which selects default options. Do not access
"opts" directly but only the normalized copy.

Fix crash in git_describe_commit when opts are NULL.

---

src/net.c

`default_port_for_scheme` returns NULL if the scheme is not one of the
builtin ones. This may cause a segmentation fault if a custom transport
URL happens to contain a port number, and this code path is triggered
(e.g. by setting git_fetch_options->update_fetchhead to 1).

Return false instead of segfaulting when checking for default port

---

src/transports/httpclient.c

cf. RFC7230 section 6.7, an Upgrade header in a normal response merely informs the client that the server supports upgrading to other protocols, and the client can ask for such an upgrade in a later request. The server requiring an upgrade is via the 426 Upgrade Required response code, not the mere presence of the Upgrade response header.
(closes issue #5573)
Signed-off-by: Sven Strickroth <email@cs-ware.de>

Don't fail if a HTTP server announces he supports a protocol upgrade

---

tests/clar/fs.h

Please review this request that fixes the includes in `tests/clar/fs.h` for FreeBSD. See issue #5627.

Fixed includes for FreeBSD

---

src/patch_parse.c
src/refs.c
src/sysdir.c

This fixes some warnings generated by GCC when building with `-DCMAKE_BUILD_TYPE=Release`.

Fix release build warnings

---

src/patch_parse.c
tests/diff/parse.c

This follows up on 11de594f85479e4804b07dc4f7b33cfe9212bea0 which added support for parsing patches without extended headers (the "index <hash>..<hash> <mode>" line); issue #5267.
We now allow transition from "file mode" state to "path" state directly if there is no "index", which will happen for patches adding or deleting files as demonstrated in added test case.

patch_parse: handle absence of "index" header for new/deleted cases

---

src/clone.c
src/refs.h
src/remote.c
src/repository.c
src/repository.h
tests/clone/empty.c
tests/repo/init.c

The git project is moving towards [more inclusive language](https://github.com/git/git/commit/11cbda2add5d3eb7c415f1f6dd8186181a7f9874).  In particular, they're making the name of the "default" branch (currently "master") configurable with the `init.defaultBranch` setting.
We should follow suit for compatibility.

Respect `init.defaultBranch` setting

---

src/transports/httpclient.c

Prior to this commit we freed both the server and proxy auth challenges
in git_http_client_read_response. This works when the proxy needs auth
or when the server needs auth, but it does not work when both the proxy
and the server need auth as we erroneously remove the server auth
challenge before we have added them as server credentials. Instead only
remove the challenges for the current_server type.
Co-authored-by: Stephen Gelman <ssgelm@gmail.com>
We used `libgit2_clar -sonline::clone::proxy_credentials_in_url` to test:
Before the commit with debug output:
```
XXX NO REQ CREDS
XXX CURRENT_SERVER PROXY
XXX APPLY_CREDS FOR localhost
XXX NO AUTH CONTEXT
XXX CHALLENGES: 0
XXX RESP HEADER Proxy-Authenticate
XXX NO REQ CREDS
XXX CURRENT_SERVER PROXY
XXX APPLY_CREDS FOR localhost
XXX NO AUTH …
```

httpclient: only free challenges for current_server type

---

src/patch_generate.c
tests/diff/format_email.c
tests/diff/stats.c

Fixes #5493 where a changed binary file's content in the working tree isn't displayed correctly, instead showing an OID of zero, and with its path being reported incorrectly as "/dev/null".
Initial focus was on the `maybe_modified` function in `diff_generate.c`: the binary file is stat'd, but because `modified_uncertain` is set to 0, `maybe_modified` does not (further down) calculate the relevant OID. Setting `modified_uncertain` to 1 rectifies the issue, but the test suite suggests an increased load on OID calculations which I suspect is best avoided where possible.
Instead, `patch_generate.c` can be adjusted to fix the problem by ensuring that for binary files both old **and** new files are loaded. This PR supplies that fix.
Note: with this fix in place, two tests then failed. On …

Fix binary diff showing /dev/null

---

src/path.c

The info pointer was allocated with git__malloc, so needs to be free'd with git__free.
This bug can lurk pretty easily since if there's no custom allocator this is fine.

Change bare free to allocator free (fixes #5653)

---

src/repository.c

`git_repository_open_ext` and `repo_init_config` were returning 1 instead of -1 when there is an unsupported extension in the config.

Fix error return for invalid extensions.

---

src/cache.c
src/global.c
src/odb.c
src/pool.c
src/pool.h
src/thread-utils.h
src/util.h

This change:
* Starts using GCC's and clang's `__atomic_*` intrinsics instead of the
`__sync_*` ones, since the former supercede the latter (and can be
safely replaced by their equivalent `__atomic_*` version with the
sequentially consistent model).
* Makes `git_atomic64`'s value `volatile`. Otherwise, this will make
ThreadSanitizer complain.
* Adds ways to load the values from atomics. As it turns out,
unsynchronized read are okay only in some architectures, but if we
want to be correct (and make ThreadSanitizer happy), those loads
should also be performed with the atomic builtins.
* Fixes two ThreadSanitizer warnings, as a proof-of-concept that this
works:
- Avoid directly accessing `git_refcount`'s `owner` directly, and
instead makes all callers go through the `GIT_REFCOUNT_*()` …

Improve the support of atomics

---

src/clone.c
tests/online/clone.c

Update the origin's HEAD as a symbolic reference pointing to the origin's default branch at clone time.  This involves populating `refs/remotes/origin/HEAD` as a symref to `refs/remotes/origin/<default>`.
It looks like the machinery was _almost_ there to do this, so either we did this once and regressed due to lack of testing, or it was just never completed.  In either case, I hoisted the incomplete pieces into their own function, finished it up, and included a test.
Fixes #5646

clone: update origin's HEAD

---

CMakeLists.txt
docs/changelog.md
include/git2/version.h
package.json

Release libgit2 1.1 ("Fernweh"), because it's been a while since our last release.

libgit2 v1.1.0

---

deps/ntlmclient/compat.h
deps/ntlmclient/crypt_openssl.c
deps/ntlmclient/ntlm.c
deps/ntlmclient/util.c
deps/ntlmclient/util.h

Update ntlm to include an htonll that is not dependent on system
libraries.

ntlm: update ntlm dependency for htonll

---

src/thread-utils.h

This should allow folks that build in non-thread-safe environments to
still be able to build the library.
Fixes: #5663

Define `git___load` when building with `-DTHREADSAFE=OFF`

---

src/win32/w32_crtdbg_stacktrace.c
tests/repo/init.c
tests/trace/windows/stacktrace.c

This change:
* Increases MY_ROW_LIMIT to 2M, since it has been failing in #5595's
tests since it's _super_ close to the limit.
* Calls `git_repository_free()` on a `git_repository` that was being
leaked only in Windows.
* Marks the global `git_repository` on `tests/repo/init.c` as `NULL`
after being freed to make any accidental access more noisy.
* Uses `cl_assert_equal_i()` in `test_trace_windows_stacktrace__leaks`
to make the test failures more actionable.
* Renames the globals in `tests/repo/init.c` so that they don't start
with an underscore.

Make the Windows leak detection more robust

---

src/threadstate.c

threadstate: rename tlsdata when building w/o threads

---

docs/changelog.md
include/git2/branch.h
include/git2/deprecated.h
include/git2/refs.h
include/git2/remote.h
include/git2/tag.h
src/branch.c
src/fetch.c
src/refs.c
src/refs.h
src/refspec.c
src/remote.c
src/repository.c
src/tag.c
tests/network/refspecs.c
tests/network/remote/isvalidname.c
tests/online/push_util.c
tests/refs/branches/name.c
tests/refs/isvalidname.c
tests/refs/tags/name.c

`git_reference_is_name_valid` and `git_remote_is_name_valid` can fail due to issues like out-of-memory, but cannot communicate this failure to the user.  Replace them with functions that can communicate failure as usual (with an integer return value) and communicate validity with an out param.
The new functions are `name_is_valid`, which better communicates that you're checking the validity of a given name, not checking the name's validity of a given reference/remote.
Include #5625, but with the new format.

Deprecate `is_valid_name` functions; replace with `name_is_valid` functions

---

src/runtime.c
src/thread-utils.h

This change avoids using the `(void)0` construct for some of the mutex
`#define`s, since that makes the "return type" of those "functions" to
be `void` instead of `int`.

Fix the `-DTHREADSAFE=OFF` build

---

.github/workflows/main.yml
script/thread-sanitizer.supp

This change adds a ThreadSanitizer CI build rule. It's informative for
now because there are still known places where there are races.
Part of: #5592

Add a ThreadSanitizer build

---

src/hash.c

The `ENABLE_WERROR=ON` build has been failing with the following error:
```shell
FAILED: src/CMakeFiles/git2internal.dir/hash.c.o
/usr/bin/cc -DHAVE_QSORT_R_GNU -DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\" -DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\" -DSHA1DC_NO_STANDARD_INCLUDES=1 -D_FILE_OFFSET_BITS=64 -Isrc -I../src -I../include -I../deps/pcre -I../deps/http-parser -D_GNU_SOURCE -fsanitize=thread -fno-optimize-sibling-calls -fno-omit-frame-pointer -Werror -Wall -Wextra -fvisibility=
hidden -fPIC -Wno-documentation-deprecated-sync -Wno-missing-field-initializers -Wstrict-aliasing -Wstrict-prototypes -Wdeclaration-after-statement -Wshift-count-overflow -Wunused-const-variable -Wunused-function -Wint-conversion -Wformat -Wformat-security -Wmissing-declarations -g -D_DEBUG -O0 …
```

Fix the `ENABLE_WERROR=ON` build in Groovy Gorilla (gcc 10.2)

---

include/git2/cert.h
src/transports/ssh.c

`git_cert_x509` has the raw encoded certificate. Let's do the same for
the SSH certificate for symmetry.

Also add the raw hostkey to `git_cert_hostkey`

---

script/thread-sanitizer.supp
src/config_cache.c
src/odb.c
src/odb.h
src/pack.c
src/repository.c

This change adds all the necessary locking to the odb to avoid races in
the backends.
Part of: #5592

Make the odb race-free

---

script/thread-sanitizer.supp
src/config_cache.c
src/indexer.c
src/mwindow.c
src/mwindow.h
src/odb.c
src/odb.h
src/pack.c
src/pack.h
src/repository.c
src/unix/map.c
tests/pack/filelimit.c
tests/pack/threadsafety.c

This change fixes a packfile heap corruption that can happen when interacting
with multiple packfiles concurrently across multiple threads. This is
exacerbated by setting a lower mwindow open file limit.
This change:
* Renames most of the internal methods in pack.c to clearly indicate
that they expect to be called with a certain lock held, making
reasoning about the state of locks a bit easier.
* Splits the `git_pack_file` lock in two: the one in `git_pack_file`
only protects the `index_map`. The protection to `git_mwindow_file` is
now in that struct.
* Explicitly checks for freshness of the `git_pack_file` in
`git_packfile_unpack_header`: this allows the mwindow implementation
to close files whenever there is enough cache pressure, and
`git_packfile_unpack_header` will reopen the …

Make the pack and mwindow implementations data-race-free

---

src/alloc.c
src/allocators/failalloc.c
src/allocators/failalloc.h
src/errors.c
src/libgit2.c
src/libgit2.h
src/runtime.c
src/runtime.h

We require the library to be initialized with git_libgit2_init before it is functional.  However, if a user tries to uses the library without doing so - as they might when getting started with the library for the first time - we will likely crash.
This PR attempts to set up some guard rails to help a user out in this case.
Now, instead of having _no_ allocator by default, we'll have an allocator that always fails, and never tries to set an error message (since the thread-local state is set up by git_libgit2_init).  We've modified the error retrieval function to (try to) ensure that the library has been initialized before getting the thread-local error message.
(Unfortunately, we cannot determine if the thread local storage has actually been configured, this does require initialization by …

Friendlier getting started in the lack of git_libgit2_init

---

git.git-authors

It reads nicer and makes it inclusive.

git.git-authors: Replacing his/her with their

---

src/transports/winhttp.c

Some reverse proxies/applications can be configured to require client certificates (mutual TLS authentication). It's also possible that the server requests a client certificate, but doesn't require it (allowing anonymous access). For example, an HAProxy frontend can be configured as so: `  bind *:8443 ssl crt /etc/ssl/certs/server.pem ca-file /etc/ssl/certs/ca.crt verify required`. `verify required` indicates that the server requires a valid client certificate to continue. Changing `verify required` to `verify optional` causes the server to request a client certificate, but allow anonymous access as well. In either case, `WinHttpSendRequest` will return `ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED`. If this is returned, the request can be retried after setting the option …

winhttp: support optional client cert

---

src/integer.h
src/util.c

This change uses compiler intrinsics to detect overflows instead of
using divisions to detect potential overflow. This makes the code faster
and makes it easier to read as a bonus side-effect!
Some of the things this quickens:
* Config parsing.
* Tree parsing.
* Smart protocol negotiation.
\* Measured by running `libgit2_clar` with `-fno-optimize-sibling-calls
-fno-omit-frame-pointer` under `perf(1)`:
```shell
$ perf diff --symbols=git__strntol64 --compute=ratio \
--percentage=absolute baseline.data perf.data
#
#
0.25%        0.321836  libgit2_clar
```

Make git__strntol64() ~70%* faster

---

src/diff_generate.c
src/repository.c
src/submodule.c
src/submodule.h

This change makes that anything that calls `git_diff__from_iterators`
(any of the `git_diff_xxx` functions) only need to parse the
`.gitmodules` file once. This can be avoided by calling
`git_repository_submodule_cache_all(...)`, but we can do that safely for
the user with no change in semantics.
Fixes: #5725

Cache the parsed submodule config when diffing

---

tests/online/badssl.c

We disabled this test while dealing with a security issue. Enable it again and make the error handling in the OpenSSL stream let us return the actual error due to trying to talk to RC4.
`GIT_ECERTIFICATE` is likely not _really_ the right thing to return here since it's not really about the certificate but about not supporting our cipherlist. We will likely want a specific error code for this (or we can overload this one, but TLS is confusing enough as it is).

Re-enable the RC4 test

---

src/config_cache.c
src/repository.h

Since we're using atomic primitives to read and write into the config map cache, we need to read/write something pointer-sized.  Use an `intptr_t` for the config map cache.
Fixes #5745

repository: use intptr_t's in the config map cache

---

tests/clar/fs.h
tests/clar/sandbox.h
tests/clar_libgit2.c

This change makes it possible to build with newer versions of gcc
without warnings. There were two warnings issued:
* gcc 8 added
[`-Wstringop-truncation`](https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/),
which warns if a call to `strncpy(3)` is prone to accidentally
truncating the destination string, since `strncpy(3)` does NOT add a
terminating `NULL` if the destination buffer is not large enough to
hold the input.
This change uses the pattern suggested in
https://us-cert.cisa.gov/bsi/articles/knowledge/coding-practices/strncpy-and-strncat
to fix the locations flagged by gcc.
* There was a potentially uninitialized access of `dest` in `fs_copy`.

Fix the `-DENABLE_WERROR=ON` build for gcc 10.2

---

ci/docker/focal
include/git2/cert.h
src/transports/ssh.c

The raw hostkey in the certificate is incredibly useful to subsequently compare and add it to a known_hosts file. However, the current code only support RSA and DSS typed keys. LibSSH2 supports a few more, including ED25519 which is the default hostkey type for many systems (macOS, for example, and I believe Raspbian as well).
This patch adds support for ECDSA_256, ECDSA_384, ECDSA_521 and ED25519 hostkey types on top of the already existing ones.

Add support for additional SSH hostkey types.

---

.github/workflows/nightly.yml
src/indexer.c
src/posix.c
src/posix.h
src/unix/posix.h
src/win32/posix_w32.c

This patch fixes building libgit2 without mmap (NO_MMAP)
Since 'mmap' does not update the position in file descriptor. Hence, we have to capture and restore the position of file descriptor in 'mmap' emulation.

Build with NO_MMAP

---

include/git2/blob.h
src/blob.c
tests/core/structinit.c

"The struct version; set to `GIT_BLOB_FILTER_OPTIONS_VERSION`."
Resolves #5756.

Add documentation for git_blob_filter_options.version

---

include/git2/blob.h
include/git2/deprecated.h
src/blob.c
tests/filter/bare.c

`GIT_BLOB_FILTER_ATTTRIBUTES_FROM_HEAD` is misspelled, it should be `GIT_BLOB_FILTER_ATTRIBUTES_FROM_HEAD`, and it would be if it were not for the MacBook Pro keyboard and my inattentiveness.
Fixes #5755

blob: fix name of `GIT_BLOB_FILTER_ATTRIBUTES_FROM_HEAD`

---

src/remote.c
src/repository.c
tests/fetchhead/nonetwork.c
tests/repo/init.c

Previously, when `init.defaultbranch` was present in the config but set to an empty string, we treated it as if the empty string was the default branch.  This meant we set `HEAD` to `refs/heads/`.  Instead, when `init.defaultbranch` is empty, we should ignore it.
Also, fetch should not try to create `FETCH_HEAD` entries that include an invalid branch.
Fixes #5761

Cope with empty default branch

---

README.md

Most users of libgit2 are probably using it via a language binding.  And many others may not want to do the dirty work of compiling the library themselves.  Let's call out the simple options in the first paragraph.
A response to #5245

README: instructions for using libgit2 without compiling

---

src/indexer.c
src/midx.c
src/pack.c

This change stops using the seek+read/write combo to perform I/O with an
offset, since this is faster by one system call (and also more atomic
and therefore safer).

Use `p_pwrite`/`p_pread` consistently throughout the codebase

---

src/clone.c
tests/clone/nonetwork.c

When a branch is specified to check out in clone, update the remote tracking `HEAD` to point to it.  This mimics git's behavior, when `git clone -b <name>` is used.
Fixes #5751

clone: set refs/remotes/origin/HEAD when branch is specified

---

src/midx.c
tests/pack/midx.c

The very last check in the freshness check for the midx was wrong ><
This was also because this function was not tested.

midx: Fix a bug in `git_midx_needs_refresh()`

---

.github/workflows/main.yml
.github/workflows/nightly.yml
ci/build.sh

Ninja is not installed by default on the macOS machines; stop trying to
use it.  Instead just use `make -j` when we're doing a `Unix Makefiles` build

ci: don't use ninja on macOS

---

src/mwindow.c

This change now updates the `lru_window` variable to match the current
file's MRU window. This makes it such that it doesn't always choose the
file that happened to come last in the list of window files, and instead
should now correctly choose the file with the least-recently-used one.

mwindow: Fix a bug in the LRU window finding code

---

examples/blame.c
examples/log.c
examples/rev-list.c
examples/rev-parse.c
include/git2/deprecated.h
include/git2/revparse.h
src/revparse.c
src/revwalk.c
tests/refs/revparse.c

The information about the type of a revision spec is not information
about the parser.  Name it accordingly, so that `git_revparse_mode_t`
is now `git_revspec_t`.  Deprecate the old name.

revspec: rename git_revparse_mode_t to git_revspec_t

---

src/refdb_fs.c

To prevent a race condition, these lock calls should probably be checked for errors.

refdb_fs: Check git_sortedcache wlock/rlock errors

---

src/index.c

If I'm understanding this right, `git_vector_sort` will segfault when allocating `case_sorted.contents` fails

index: Check git_vector_dup error in write_entries

---

include/git2/repository.h

The enum 'git_repository_init_flag_t', 'git_repository_init_mode_t' and
the structure 'git_repository_init_options' does not follow the format
used by docurium.

Fix documentation formating on repository.h

---

include/git2/config.h
include/git2/index.h
include/git2/refs.h
include/git2/transport.h

Just a few typo fixes within the `include` directory :)

include: fix typos in comments

---

examples/checkout.c
examples/common.h
examples/tag.c
src/cc-compat.h
src/refs.c
src/remote.c
src/transports/winhttp.c
src/win32/w32_leakcheck.c

This PR fixes some typos in libgit2. Most of these are in comments. One of these typos is a method name, but it's in the example code, not the `src` folder, so it doesn't break compatibility or anything.

Fix some typos

---

src/merge.c

`insert_head_ids` can fail due to allocation error

merge: Check insert_head_ids error in create_virtual_base

---

src/transports/winhttp.c
tests/online/clone.c

In some circumstances (e.g. when proxies are involved), winhttp will fail to reach the WINHTTP_CALLBACK_STATUS_SENDING_REQUEST phase. If this occurs, we'll error with ERROR_WINHTTP_INCORRECT_HANDLE_STATE when attempting to query the server certificate context (see https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpsendrequest#remarks).
To avoid this, verify that WinHttpSendRequest has reached the WINHTTP_CALLBACK_STATUS_SENDING_REQUEST phase before checking the certificate. Since we're using WinHTTP in synchronous mode, we know for sure that once WinHttpSendRequest returns we've either sent it successfully or not.
NOTE: WINHTTP_CALLBACK_STATUS_SENDING_REQUEST appears to be deprecated with no direct replacement. WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE is only …

winhttp: skip certificate check if unable to send request

---

.github/workflows/main.yml
include/git2/deprecated.h
include/git2/tree.h
src/tree.c
src/tree.h

The function `git_treebuilder_write_with_buffer` is unnecessary; we
always write with a buffer, so we might as well keep it around in the
treebuilder struct instead of recreating it.  Move the buffer as the
trebuilder as a cache, meaning the `write_with_buffer` function is
unnecessary.

tree: deprecate `git_treebuilder_write_with_buffer`

---

src/repository.c
tests/repo/getters.c

`git_repository_is_empty` is returning `false` if `init.defaultBranch` is set to `""`. It probably shouldn't be an empty string, but work around this like in the referenced issue/PR.
See:
- https://github.com/libgit2/libgit2/issues/5761
- https://github.com/libgit2/libgit2/pull/5770

Default to GIT_BRANCH_DEFAULT if init.defaultBranch is empty string

---

include/git2/diff.h

This just fixes a typo in the documentation, actual rename change was
done in 5f69a31f

Fix diff_entrycount -> diff_num_deltas doc typo

---

src/repository.c

We don't want the default branch's refname here but its name as branch.
Returning an error saying it's not a valid reference here suggests we want the
value of `init.defaultbranch` to be something like `refs/heads/default` which is
not the case.

repo: specify init.defaultbranch is meant to be a branch name

---

src/repository.c

This error code is for callbacks where we should act as though the callback was
not set. This is not something that makes sense for a `_foreach` and checking
for that error message to bubble up mostly is happenstance precisely because
this is not an error code we expect in the callback.
As part of removing this, let's also remove a use of foreach as we can open-code
this check.
I just found this while double-checking this empty heuristic and was confused by the pass-through here. It looks like it was changed from this `EUSER`

repo: remove an inappropriate use of PASSTHROUGH

---

src/runtime.h
src/transports/httpclient.h

Just two small typos in the header files :)

src: fix typos in header files

---

include/git2/refs.h
src/refdb_fs.c
tests/refs/races.c

This is pretty useful in avoiding races: I want to create a ref only if
it doesn't already exist.  I can't check first because of TOCTOU -- by
the time I finish the check, someone else might have already created
the ref.  And I can't take a lock because then I can't do the create,
since the create expects to take the lock.
The semantics are inspired by git update-ref, which allows an all-zero old
value to mean that the ref must not exist.

git_reference_create_matching: Treat all-zero OID as "must be absent"

---

README.md

Delphi/Free pascal bindings targeting the latest version of libgit2

Update README.md for additional Delphi bindings

---

src/transports/httpclient.c

**Issue 1**
When skipping the body, we used to wait for the `on_message_complete` callback to have been triggered, which set `parse_finished`. After the refactor with `httpclient`, we stopped relying on this value, and thus we no longer consume the entire body when skipping it in the client. Here's where we used to consume the body https://github.com/libgit2/libgit2/blob/bf55facf15e5b6897ff7305162a77d92089f6c82/src/transports/http.c#L956
This shows up as an issue primarily when working with the proxy connection workflow, where we need to discard the entire body (completely drain the socket of the response) before we start the retry with credentials.
**Issue 2**
We used to mutate `proxy_opts.type` to `GIT_PROXY_NONE` after successfully connecting the tunnel. After the httpclient refactor, …

Fix issues with Proxy Authentication after httpclient refactor

---

.gitignore
include/git2/diff.h
src/diff_xdiff.c

I found out that we have defined the parameter  (`XDF_IGNORE_BLANK_LINES`) is in `src/xdiff/xdiff.h`.
I added support for this parameter(`GIT_DIFF_IGNORE_BLANK_LINES`) in `include/git2/diff.h` and `src/diff_xdiff.c`
This is my first PR, if there is anything wrong, please point it out and I will be happy to improve it.😊

diff:add option to ignore blank line changes

---

docs/coding-style.md

The broken ending marker would cause the rest of the file to be parsed as part of the comment.

docs: fix incorrect comment marker

---

src/odb.c

This creates compatibility with systems that overestimate the symlink path's size, such as Android (https://issuetracker.google.com/189629152).
The GNU coreutils `stat` tool is similarly tolerant of `readlink` returning a path that is smaller than reported by `st_size`:
- https://github.com/coreutils/coreutils/blob/370c294018316f005bb259f51024497333d24ee0/src/stat.c#L1482
- https://github.com/coreutils/gnulib/blob/c45faf7f48bcbe57df3bbf8df81a016c5f15df55/lib/areadlink-with-size.c#L97-L99
Without this change, I observed that [Cargo](https://github.com/rust-lang/cargo) (which is built on libgit2) would tend to fail many commands with "failed to read symlink data for '...'" on Android in repositories containing symlinks.

Tolerate readlink size less than st_size

---

include/git2/index.h

In https://github.com/libgit2/libgit2/pull/5723/files/fc46dc06f52f854f74371682f911f13856c68edb#r540092847, I was confused by the semantics of `git_index_find`. The documentation says both that it returns the output value in `at_pos` and that it returns it directly as an `int`. This is incorrect; the return value is only returned via `at_pos`.

Fix misleading doc for `git_index_find`

---

docs/contributing.md
docs/release.md

The name of libgit2's main branch is now "main" but contributing.md and
release.md still reference "master" as the main branch.  Fix it.

docs: stop mentioning libgit2's "master" branch

---

include/git2/cert.h
include/git2/sys/transport.h

This adds a few missing includes so that Docurium doesn't skip some documentation when parsing.

docs: fix some missing includes that cause Docurium to error out

---

src/futils.h
tests/status/worktree.c

This is what git.git does, so we should follow suit.

Consider files executable only if the user can execute them

---

src/util.h

The ITimer interface is specific to AmigaOS4 and doesn't exist on 3.x and lower.

git__timer: Limit ITimer usage to AmigaOS4

---

src/transports/smart.c
tests/online/fetch.c

The call to git_proxy_options_dup will replace the url pointer of the
proxy.
But if the url pointer is already set, the old address will be lost
forever and will never be free.

Fix memory leak in git_smart__connect

---

src/config_file.c
tests/config/include.c

If an included config is refreshed twice, the second update is not taken
into account.
This is because the list of included files is cleared after re-reading
the new configuration, instead of being cleared before.
Fix it and add a test case to check for this bug.
This was probably introduced by commit a0dc3027f118119d3336db08251c646291f2c098

config: fix included configs not refreshed more than once

---

src/date.c

This function doesn't interoperate with any system functions that use the system `time_t`, but rather only works with the `git_time_t` type in libgit2, which could be a different width than the system one. Fixes a compile warning.

Fix wrong time_t used in function

---

src/ignore.c
tests/ignore/path.c

A gitignore rule like "*.txt" should be negated by "!dir/test.txt" even though one is inside a directory since *.txt isn't restricted to any directory.
This is fixed by making wildcard match treat * like ** by excluding the WM_PATHNAME flag when the rule isn't for a full path.
This problem can be replicated with a repository with the following .gitignore file:
*.txt
!/dir/test.txt
by creating a `dir/test.txt` file.
Commandline Git shows `dir/test.txt` as untracked while libgit2 without this PR shows it as ignored.

fix check for ignoring of negate rules

---

src/pack-objects.c
src/transports/smart_protocol.c
src/util.h

Makes usage of CLOCK_MONOTONIC conditional.
Functions that uses git__timer checks for negative time difference to handle clock synchronization when a non-monotonic timer is used.
According to [opengroup.org](https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html) gettimeofday() have unspecified behaviour if tzp is set to anything but NULL.

git__timer: Allow compilation on systems without CLOCK_MONOTONIC

---

src/trace.h

This refactors this to a wrapper function, as well as changing the existing API have a va_list and ... version.
Fixes #5947

Variadic arguments aren't in C89

---

include/git2/submodule.h
src/submodule.c
tests/submodule/lookup.c

[Submodule] Git submodule dup

---

fuzzers/commit_graph_fuzzer.c
include/git2/odb.h
include/git2/sys/commit_graph.h
include/git2/types.h
src/commit_graph.c
src/commit_graph.h
src/commit_list.c
src/commit_list.h
src/odb.c
src/odb.h
tests/graph/commit_graph.c

This change makes revwalks a bit faster by using the `commit-graph` file
(if present). This is thanks to the `commit-graph` allow much faster
parsing of the commit information by requiring near-zero I/O (aside from
reading a few dozen bytes off of a `mmap(2)`-ed file) for each commit,
instead of having to read the ODB, inflate the commit, and parse it.
Part of: #5757

commit-graph: Use the commit-graph in revwalks

---

src/commit_list.c
src/commit_list.h
src/graph.c
src/merge.c

This change makes calculations of merge-bases a bit faster when there
are complex graphs and the commit times cause visiting nodes multiple
times. This is done by visiting the nodes in the graph in reverse
generation order when the generation number is available instead of
commit timestamp. If the generation number is missing in any pair of
commits, it can safely fall back to the old heuristic with no negative
side-effects.
Part of: #5757

commit-graph: Introduce `git_commit_list_generation_cmp`

---

include/git2/graph.h
src/graph.c
src/merge.c
src/merge.h
tests/graph/reachable_from_any.c

This change introduces a new API function
`git_graph_reachable_from_any()`, that answers the question whether a
commit is reachable from any of the provided commits through following
parent edges.
This function can take advantage of optimizations provided by the
existence of a `commit-graph` file, since it makes it faster to know
whether, given two commits X and Y, X cannot possibly be an reachable
from Y.
Part of: #5757

graph: Create `git_graph_reachable_from_any()`

---

src/common.h

C99 and later have a proper inline keyword we can use for GIT_INLINE

common.h: use inline when compiling for C99 and later

---

include/git2/branch.h
src/branch.c
tests/refs/branches/upstream.c

It is a convenient accessor for merge branch name.

[Branch] Branch upstream with format

---

tests/refs/branches/upstream.c

There was one test that wasn't correctly disposing of the repository.

Fix one memory leak in master

---

include/git2/common.h

Like on Windows ':' is used for volume names in absolute paths.

amiga: use ';' as path list separator on AmigaOS

---

.github/workflows/main.yml
.github/workflows/nightly.yml
ci/docker/bionic
ci/docker/entrypoint.sh
ci/docker/focal
ci/docker/xenial

Omitting an entrypoint.sh to configure the container and instead
depending on docker primitives allows us to be more portable.  (If a
distribution uses a different mechanism for adding users, we need not
have multiple entrypoint.sh files or invariants within it; instead we
can configure that in the dockerfile itself along with all the other
distribution specific components.)

docker: remove the entrypoint

---

src/transports/http.c

Attempt authentication when a username is presented but a password is
not; this can happen in particular when users are doing token
authentication and specifying the token in the URL itself.  For example,
`https://token@host/` is a valid URI and should be treated as a username
of `token` with an empty password.
Fixes #5967

http: don't require a password

---

src/hash/sha1/sha1dc/sha1.c

src/hash/sha1/sha1dc/sha1.c is testing if \_\_unix\_\_ is defined before including <sys/types.h>
Since it is included unconditionally elsewhere it isn't necessary to include it conditionally and it prevents systems that doesn't define \_\_unix\_\_ from specifying endianess in the include files.

sha1dc: remove conditional for <sys/types.h>

---

src/streams/openssl.c

During valgrind runs, we try to swap out the OpenSSL allocators for our
own.  This allows us to avoid some unnecessary warnings about usage.
Unfortunately, many builds of OpenSSL do not allow you to swap
allocators; for example FIPS builds and the builds running in CentOS.
Try to swap the allocators, but do not fail when they cannot be
customized.

openssl: don't fail when we can't customize allocators

---

CMakeLists.txt
src/hash.c
src/hash.h

GCC and Clang defaults to allowing some C11 specific extensions even if C99 is specified
This PR enables warnings when compiling with Clang.
To enable warnings for GCC -Wc99-c11-compat has to be added, but this reveals a similar issue in win32/reparse.h. That code seems to be pulled in from the Windows 2000 SDK. Is it safe to fix this?
This is the same code as in #5912, but since it was 3 different issues baked into one and the array related test needed some more thought I decided to split it up in separate PR.

C11 warnings

---

.github/workflows/main.yml
CMakeLists.txt
src/CMakeLists.txt
src/features.h.in
src/posix.c
src/refdb_fs.c
src/win32/posix_w32.c
src/worktree.c
tests/iterator/workdir.c
tests/merge/workdir/setup.c
tests/odb/foreach.c
tests/worktree/merge.c
tests/worktree/worktree.c

As mentioned in issue #5920 there are a couple of places that tries to open paths containing empty path segments.
It would be nice if this could be caught in testing.
This PR uses the linker to overload the open() function and tests path for empty segment.
The idea is that we could add input validation to more POSIX calls to catch usage that is implementation defined or have unspecified behavior.
Maybe there is a more generic way to test for this?
We could check for _DEBUG and add the test to the p_open() function and let it fail if the path looks malformed.
Unfortunately that wouldn't have any impact on test cases where p_open() is expected to fail for other reasons but maybe that is a smaller problem.

open: input validation for empty segments in path

---

include/git2/common.h
src/cc-compat.h
src/common.h
src/odb.c
src/path.c
src/refdb_fs.c
src/sortedcache.h
src/vector.h
src/win32/path_w32.h
tests/core/sha1.c
tests/core/sortedcache.c
tests/core/vector.c
tests/fetchhead/nonetwork.c
tests/index/addall.c
tests/index/bypath.c

This change adds the GIT_WARN_UNUSED_RESULT annotation, which makes the
compiler warn when a return result is not used. This avoids bugs.

Introduce GIT_WARN_UNUSED_RESULT

---

tests/config/read.c
tests/remote/fetch.c

A couple of c99 comments have snuck their way into tests/config/read.c and tests/remote/fetch.c

tests: change comments to c89 style

---

include/git2/checkout.h
src/checkout.c
tests/checkout/tree.c

With `GIT_CHECKOUT_NONE` you do get notified about conflicts but that's pretty much it. 
With this simple addition one can set `GIT_CHECKOUT_DRY_RUN` which will notify following the normal checkout routines but breaks just before the working directory gets touched. 
This becomes really handy when you want to do a proper checkout dry run to see what will be changed

Checkout dry-run

---

include/git2/remote.h
src/remote.c
tests/network/remote/remotes.c
tests/online/push_util.h

As part of my goal of making `git_buf` a data structure that we use to provide data to users, instead of taking data _from_ users, this deprecates the `resolve_url` callback.  It provides a replacement callback `git_remote_ready_cb` that is fired at the same time.  Users can then call the new `set_instance_url` functions on a remote to update the URLs if they so desire.

remote: introduce remote_ready_cb, deprecate resolve_url callback

---

include/git2/commit.h
include/git2/deprecated.h
include/git2/rebase.h
src/rebase.c
tests/rebase/sign.c

Deprecate the `signing_cb` in `git_rebase`.  Instead, provide users the opportunity to extend commit creation in arbitrary ways, by providing a `create_commit_cb`.  If users wish to perform signing, they can do so in that callback.

Introduce `create_commit_cb`, deprecate `signing_cb`

---

include/git2/sys/filter.h
src/crlf.c
src/filter.c
src/filter.h
src/ident.c
tests/filter/custom_helpers.c
tests/filter/wildcard.c

Deprecate the custom filter's `apply` function; this requires users to take the entire file, filter it, and then return the entire filtered contents.  This is appropriate for small files, but not large ones.  Further, it uses our `git_buf` for input and output; I would like to remove occurrences of `git_buf` being used as input to the library.  (Only as output to users that they can manage the lifecycle of.)  This will simplify our API surface and the `git_buf` usage significantly.
Note that I'm not _particularly_ bullish about the removal of the `apply` function.  It _is_ simpler in many ways; one option is to deprecate it and replace it with a function that works with some other buffer type (eg, `git_filter_buf`) that users can write to.  I would prefer targeted buffers in the `sys` …

filter: filter drivers stop taking git_buf as user input

---

include/git2/deprecated.h
src/buffer.h

A `git_buf` is now a read-only structure as far as callers are concerned.  This is a mechanism that we can return data to callers using memory that is owned by the library and can be cleaned up by callers (using `git_buf_dispose`).
A `git_buf` can no longer be allocated by callers or provided to the library.
This change simplifies the `git_buf` lifecycle and public API surface, giving us more flexibility in internal refactorings.

buf: deprecate public git_buf writing functions

---

src/transports/httpclient.c

Prior to this change, for CONNECT requests, the Host header was set to
the host and port of the target http proxy. However, per the rfc7230 for
HTTP/1.1 this is incorrect as the Host header should match the target of
the CONNECT request, as detailed in section 5.3.3 & 5.4.
5.3.3.  authority-form
The authority-form of request-target is only used for CONNECT
requests (Section 4.3.6 of [RFC7231]).
authority-form = authority
When making a CONNECT request to establish a tunnel through one or
more proxies, a client MUST send only the target URI's authority
component (excluding any userinfo and its "@" delimiter) as the
request-target.  For example,
CONNECT www.example.com:80 HTTP/1.1
5.4.  Host
<snip>
A client MUST send a Host header field in all HTTP/1.1 request
messages.  If the target URI …

Set Host Header to match CONNECT authority target

---

src/repository.c

This is intended to fix #5851, which highlights an assertion within git_path_prettify that occurs during git_repository_foreach_worktree when it attempts to open the repository because repo->commondir is null.  This occurs in contexts where the repository has been created explicitly in conjunction with a custom odb/refdb backend.
git_repository_foreach_worktree has been changed to check when commondir is null, and in that case apply the callback operation to the repository supplied only, as it would appear there are no linked worktrees to iterate.

Fix worktree iteration when repository has no common directory

---

src/commit_graph.c

This change fixes a possible null pointer dereference if anything inside
`git_commit_graph_writer_add_index_file` fails before the packfile being
valid.
https://scan6.coverity.com/reports.htm#v52218/p10377/fileInstanceId=122935896&defectInstanceId=32525576&mergedDefectId=1461634

Fix a possible null pointer dereference

---

src/threadstate.c

This follows the same principle as `buffer.c` where the same check is done before freeing the buffer. It fixes the crash described in #6028.

#6028: Check if `threadstate->error_t.message` is not `git_buf__initbuf` before freeing.

---

include/git2/remote.h

This change makes `git_remote_name_is_valid` be part of the public
interface of the library. This is needed for other language bindings to
be able to find this symbol (like in git2go, when linking against
libgit2 dynamically).

remote: Mark `git_remote_name_is_valid` as `GIT_EXTERN`

---

src/notes.c

Code cleanup to use `git_buf`s instead of simple c strings.

notes: use a buffer internally

---

include/git2/common.h
src/libgit2.c
src/repository.c
src/repository.h
tests/core/opts.c
tests/repo/extensions.c
tests/repo/open.c

Allow users to specify additional repository extensions that they want to support.  For example, callers can specify that they support `preciousObjects` and then may open repositories that support `extensions.preciousObjects`.
Similarly, callers may opt out of supporting extensions that the library itself supports.

Support custom git extensions

---

src/indexer.c

This change makes `append_to_pack` completely rely on `p_pwrite` to do
all its I/O instead of splitting it between `p_pwrite` and a
`mmap(2)`/`munmap(2)`+`memcpy(3)`. This saves a good chunk of user CPU
time and avoids making two syscalls per round, but doesn't really cut
down a lot of wall time (~1% on cloning the
[git](https://github.com/git/git.git) repository).
Part of: #6038
Fixes: #5556

indexer: Avoid one `mmap(2)`/`munmap(2)` pair per `git_indexer_append` call

---

src/cc-compat.h
src/util.h

For issue: https://github.com/libgit2/libgit2/issues/6040
This PR converges on the use of `__typeof__` instead of `typeof` for ISO C compatibility with this GCC extension.
All uses of `typeof` or `__typeof__` are presently confined to `#if defined(__GNUC__) / #endif` blocks, which should limit the impact of this change.
Details:
- Remove the `GIT_TYPEOF` macro, since this is not used in the libgit2 project.
- Replace all occurrences of `typeof(x)` with `__typeof__(x)`.

Use __typeof__ GNUC keyword for ISO C compatibility

---

src/blob.c
tests/win32/longpath.c

Fixes #6054.
An alternative might be to handle the null git_repository case in the longpath check ((bool) should_validate_longpaths(git_repository *repo)). Could also put an assert on "repo" argument in should_validate_longpaths.

Longpath filter bug

---

include/git2/stdint.h

This PR hides header content from non-Windows builds.
( Well, it is better to include this header via "relative" search path ).

Stdint header condition has been reverted.

---

src/util.c

A length of 0 indicates an error and GetLastError() will be set.  If
GetLastError() is unset then the environment variable has a length of 0.

win32: allow empty environment variables

---

ci/docker/centos7
ci/docker/centos8
ci/docker/focal
ci/docker/xenial

libssh2.org and www.libssh2.org were previously identical; now this is a
redirect.

ci: pull libssh2 from www.libssh2.org

---

include/git2/diff.h

`GIT_DIFF_IGNORE_BLANK_LINES` needs to be within a (signed) int, per the `enum` definition of ISO C.
Fixes #6057

diff: update `GIT_DIFF_IGNORE_BLANK_LINES`

---

src/buffer.c
src/buffer.h
src/pathspec.c
tests/core/buffer.c

`git_strarray` is a public-facing type.  Change
`git_buf_text_common_prefix` to not use it, and just take an array of
strings instead.

buf: common_prefix takes a string array

---

include/git2/repository.h
src/attr.c
src/blob.c
src/checkout.c
src/repository.c
src/win32/posix_w32.c
tests/repo/hashfile.c

We previously (erroneously) passed absolute paths to attribute lookup functions.  This sometimes led to ridiculous paths being constructed, like taking an absolute path within a workdir and prefixing the workdir to it.  Always provide attribute lookups with a relative path, and enforce in the attribute lookup code that we have done so.

Attribute lookups are always on relative paths

---

src/attr.c
src/attr_file.c
src/attr_file.h
src/ignore.c
tests/attr/lookup.c

When looking up attributes for a file, we construct an absolute path
to the queried file within the working directory so that we can accept
both absolute paths and working directory relative paths.  We then trim
the leading working directory path to give us an in-repo path.
Since we only want the in-repo path to look up attributes - and not to
read it from disk - we don't need to validate its length.

Handle long paths when querying attributes

---

include/git2/deprecated.h
include/git2/oidarray.h
src/merge.c
src/oidarray.c
tests/revwalk/mergebase.c

Since users are disposing the _contents_ of the oidarray, not freeing
the oidarray itself, the proper cleanup function is
`git_oidarray_dispose`.  Deprecate `git_oidarray_free`.

oidarray: introduce `git_oidarray_dispose`

---

.github/workflows/main.yml

Only update the documentation on a `push`.  We were previously updating the documentation only when not in a `pull_request`, which meant that we would push documentation updates in manual build triggers.

ci: only update docs on push

---

docs/threading.md

Commit 4ae41f9c639d246d34dac89c3f1d9451c9cfa8d3 made `git_odb`
race-free, and added internal locking. Update `docs/threading.md`
accordingly, so that APIs built atop libgit2 (e.g. language bindings)
can count on this.
(This appears to be true as far as I can tell, at least.)

Document that `git_odb` is thread-safe

---

include/git2/odb.h
include/git2/sys/odb_backend.h
src/odb.c
tests/odb/backend/backend_helpers.c
tests/odb/backend/backend_helpers.h
tests/odb/backend/multiple.c
tests/odb/backend/refreshing.c
tests/odb/backend/simple.c

Support checking for object existence without refresh
Looking up a non-existent object currently always invokes `git_odb_refresh`. If looking up a large batch of objects, many of which may legitimately not exist, this will repeatedly refresh the ODB to no avail.
Add a `git_odb_exists_ext` that accepts flags controlling the ODB lookup, and add a flag to suppress the refresh. This allows the user to control if and when they refresh (for instance, refreshing once before starting the batch).
Add tests for ODB refresh.
Update documentation for the ODB backend refresh logic: Commit b1a6c316a6070fac4ab1ec5792979838f7145c39 moved auto-refresh into the pack backend, and added a comment accordingly. Commit 43820f204ea32503b4083e3b6b83f30a0a0031c9 moved auto-refresh back *out* of backends into the …

Support checking for object existence without refresh

---

src/str.c

`git_str_free` was never a function.  Remove it.

str: git_str_free is never a function

---

src/threadstate.c

When building under gcc 11, there is a warning about a misaligned guard clause
because there were mixed spaces and tabs:
```
[128/634] Building C object src/CMakeFiles/git2internal.dir/threadstate.c.o
../src/threadstate.c: In function ‘threadstate_dispose’:
../src/threadstate.c:39:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
39 |     if (threadstate->error_t.message != git_str__initstr)
|     ^~
../src/threadstate.c:41:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
41 |         threadstate->error_t.message = NULL;
|         ^~~~~~~~~~~
../src/threadstate.c: At top level:
```
This change indents the code with tabs for consistency with the rest of the
code, which makes the warning go away.

Fix a gcc 11 warning in src/threadstate.c

---

src/thread.h

When building under gcc 11, there is a warning about an incompatible pointer
type, since
[`__atomic_exchange`](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html)
does not take `volatile` pointers:
```
In file included from ../src/common.h:81,
from ../src/transports/winhttp.c:8:
../src/thread-utils.h: In function ‘git___swap’:
../src/thread-utils.h:168:9: warning: argument 3 of ‘__atomic_exchange’ discards ‘volatile’ qualifier [-Wincompatible-pointer-types]
168 |         __atomic_exchange(ptr, &newval, &foundval, __ATOMIC_SEQ_CST);
|         ^~~~~~~~~~~~~~~~~
```
This change drops the `volatile` qualifier so that the pointer type matches
what `__atomic_exchange` expects.

Fix a gcc 11 warning in src/thread.h

---

src/tag.c

`git_tag_name_is_valid` needs to set validity to 0 when it
short-circuits.

tag: set validity to 0 by default

---

CMakeLists.txt
cmake/SelectWinHTTP.cmake
tests/CMakeLists.txt

Re-enable WinHTTP support when `USE_WINHTTP` is specified.
Additionally, ensure that we `enable_testing()` at the top-level CMakeLists.txt or
else we'll need to navigate within the build directory to the correct
place in the hierarchy to run `ctest`.  Now we can `ctest` at the
top-level again.

cmake: re-enable WinHTTP

---

src/repository.c
tests/repo/template.c

This PR changes the behaviour of libgit2 to match that of `git`. See below for details.
With a git config containing:
```ini
[init]
templatedir = "/tmp/DoesNotExist"
```
`git init` prints a warning but still successfully initalises the git directory:
```sh
> git init -q foo
warning: templates not found in /tmp/DoesNotExist
> find foo
foo
foo/.git
foo/.git/objects
foo/.git/objects/info
foo/.git/objects/pack
foo/.git/config
foo/.git/HEAD
foo/.git/refs
foo/.git/refs/tags
foo/.git/refs/heads
```
git source for reference: https://github.com/git/git/blob/5d5b1473453400224ebb126bf3947e0a3276bdf5/builtin/init-db.c#L121-L125
However with `libgit2` this throws an error and the directory is not initialised as expected:
```c
// source code for reproducer
#include <assert.h>
#include <git2.h>
#include …
```

Fix repo init when template dir is non-existent

---

include/git2/object.h
include/git2/signature.h
src/commit.c
src/commit_list.c
src/indexer.c
src/object.c
src/signature.c
src/tag.c
src/tree.c
tests/object/validate.c

Refactor object validation so that we can provide a mechanism to determine whether a given buffer is a valid object,

Introduce `git_object_rawcontent_is_valid`

---

src/remote.c
tests/remote/insteadof.c
tests/resources/testrepo2/.gitted/config

a repo has a url, and a named repo may also have a pushurl.
each of these can be matched by insteadOf/pushInsteadOf configuration.
this means that want to test:
- an anonymous repo (a url)
- a named repo with a url
- a named repo with a url and pushurl
and for each of these matching configuration:
- only insteadOf
- only pushInsteadOf
- both insteadOf and pushInsteadOf
this changeset updates the tests to test all of these combinations,
and updates the implementation so the tests pass.
all expectations have been checked against the git command line client,
the results of which cna be checked with this script (run from the build directory):
```sh
#!/bin/bash
export GIT_DIR=../tests/resources/testrepo2/.gitted
for remote in insteadof-{,push}url-{fetch,push,both}; do
echo $remote
git remote …
```

remotes: fix insteadOf/pushInsteadOf handling

---

src/commit.c
tests/commit/commit.c

git_commit_summary: ignore lines with spaces

---

include/git2/blob.h
src/blob.c
tests/diff/blob.c

Introduce `git_blob_data_is_binary` to examine a blob's data, instead of the blob itself.  A replacement for `git_buf_is_binary`.

blob: identify binary content

---

README.md

PSGit is not using libgit2 library. It is stub of a library and is not developed further.

Remove PSGit from Language Bindings section of README

---

deps/ntlmclient/crypt_openssl.c

Made a PR from the patch provided by @Nuadh in #6134
libressl still declares HMAC_CTX_cleanup so we can't create the dummy function in that case.

ntmlclient: fix linking with libressl

---

include/git2/status.h
src/status.c
tests/status/renames.c

Adds the `rename_threshold` option to `git_status_options`, that works in a similar way to `git_diff_find_options` and core git's `-M` option.

Add `rename_threshold` to `git_status_options`.

---

src/config_file.c
tests/config/conditionals.c

When a config file contains `[includeIf]` (with no condition), we should
treat that as a falsey value.  This means that we should properly parse
a config value of `includeIf.path`.
Fixes #6162

config: handle empty conditional in includeIf

---

ci/test.sh
docs/api-stability.md
include/git2/remote.h
include/git2/sys/transport.h
src/fetch.c
src/fetch.h
src/net.c
src/net.h
src/proxy.c
src/proxy.h
src/push.c
src/push.h
src/remote.c
src/remote.h
src/transports/http.c
src/transports/local.c
src/transports/smart.c
src/transports/smart.h
src/transports/smart_protocol.c
src/transports/ssh.c
src/transports/winhttp.c
tests/network/url/redirect.c
tests/online/clone.c
tests/online/fetch.c

Add support for initial redirects, so that some remote set to `https://git.example.com/repo.git` can redirect to `https://github.com/example/repo.git` on an initial connection.  Initial redirects are now supported by default, but can be disabled by setting `http.followRedirects=false`.
This does not add support for `http.followRedirects=true`, which would support subsequent redirects.  Yet trickier refactoring is required for this, and as it either requires expect/continue or a complete re-POST, there is little interest in supporting it.

remote: support `http.followRedirects` (`false` and `initial`) and follow initial redirects by default

---

docs/api-stability.md
include/git2/remote.h
include/git2/sys/transport.h
src/fetch.c
src/fetch.h
src/proxy.c
src/proxy.h
src/push.c
src/push.h
src/remote.c
src/remote.h
src/transports/http.c
src/transports/local.c
src/transports/smart.c
src/transports/smart.h
src/transports/smart_protocol.c
src/transports/ssh.c
src/transports/winhttp.c

The existing mechanism for providing options to remote fetch/push calls, and subsequently to transports, is unsatisfactory.  It requires an options structure to avoid breaking the API and callback signatures.
1. Introduce `git_remote_connect_options` to satisfy those needs.
2. Add a new remote connection API, `git_remote_connect_ext` that will take this new options structure.  Existing `git_remote_connect` calls will proxy to that.  `git_remote_fetch` and `git_remote_push` will proxy their fetch/push options to that as well.
3. Define the interaction between `git_remote_connect` and fetch/push. Connect _may_ be called before fetch/push, but _need not_ be.  The semantics of which options would be used for these operations was not specified if you specify options for both connect _and_ …

Introduce `git_remote_connect_options`

---

src/diff_driver.c

C99 doesn't allow structures with flexible length array to be placed in an array.

diff_driver: split global_drivers array into separate elements

---

COPYING

We now bundle PCRE for our regular expression implementation; include
that copyright notice and remove the now-unused regular expression
copyright.

COPYING: remove regex copyright, add PCRE copyright

---

docs/changelog.md
src/refdb_fs.c
tests/refs/crashes.c
tests/resources/peeled.git/packed-refs
tests/resources/testrepo.git/packed-refs
tests/resources/testrepo/.gitted/packed-refs
tests/resources/testrepo2/.gitted/packed-refs

Currently ref lookups require loading the entire packed-refs file into
a hashmap in memory. For repos with large numbers of refs this can be
painfully slow.
This patch replaces the existing lookup code and instead mmap()'s the
packed-refs file and performs a binary search to locate the ref entry.
Git uses a similar approach.
The old hash table codepath is still used for unsorted packed-refs files.
A number of the test fixture repos were updated with the `sorted` trait so
that this new path is properly exercised.
This patch also fixes a minor bug where the "peeled" trait is never
parsed correctly.

refs: Speed up packed lookups.

---

src/CMakeLists.txt
src/transports/smart_protocol.c

Setting `C_EXTENSIONS` to `OFF` turns off some extensions and will catch the C++ comments. Probably some more things, but nothing that we currently use.
Since it is on the git2internal target it won't apply do deps/
I guess anything in deps is currently compiled with whatever `CMAKE_C_STANDARD` and `CMAKE_C_EXTENSIONS` defaults to.
A side point here is that we should probably set `C_STANDARD` to `99` when building for release.
Otherwise `__STDC_VERSION__` wont be set to `199901` and we need to rely on rely on "hacky" `__GNUC__` checks to get flexible arrays and inline to work.
C90 is still nice for syntax checking.

cmake: disable some gnu extensions

---

src/futils.c
src/posix.h
tests/core/futils.c

Modification of  #5350 with ~~tempnam()~~ mktemp() since tempnam() isn't supported on the macos and windows builds.
For some reason the test doesn't fail when used on its own. Maybe something have changed since then?
~~[The Open Group Base Specifications Issue 7](https://pubs.opengroup.org/onlinepubs/9699919799/functions/tempnam.html) marks tempnam() as obsolescent and states that "The tempnam() function may be removed in a future version."
It also limits the prefix to 5 bytes so appending "\_git2\_" to the prefix is a bit pointless.~~

futils_mktmp: don't use umask

---

include/git2/checkout.h
include/git2/merge.h
src/CMakeLists.txt
src/blame_git.c
src/checkout.c
src/diff_xdiff.c
src/merge_file.c
src/patch_generate.c
src/patch_generate.h
src/xdiff/git-xdiff.h
src/xdiff/xdiff.h
src/xdiff/xdiffi.c
src/xdiff/xemit.c
src/xdiff/xhistogram.c
src/xdiff/xinclude.h
src/xdiff/xmerge.c
src/xdiff/xpatience.c
src/xdiff/xprepare.c
src/xdiff/xutils.c
tests/merge/conflict_data.h
tests/merge/files.c
tests/merge/workdir/simple.c

Add support for zdiff3 using the xdiff from git v2.35.0.
Update to the xdiff used in git v2.35.0, with updates to our build configuration to ignore the sort of warnings that we normally care about (signed/unsigned mismatch, unused, etc.)
Any git-specific abstraction bits are now redefined for our use in `git-xdiff.h`.  It is a (wildly optimistic) hope that we can use that indirection layer to standardize on a shared xdiff implementation.

merge: support zdiff3 conflict styles

---

src/merge.c
tests/cherrypick/workdir.c
tests/merge/workdir/simple.c
tests/revert/workdir.c

git has started adding comment markers to its conflict lines in `MERGE_MSG`.  Match that behavior.
Fixes #6131

merge: comment conflicts lines in MERGE_MSG

---

src/streams/mbedtls.c
src/xdiff/git-xdiff.h

To be able to use unmodified xdiff code together with git-xdiff.h we need to make sure that `inline` exists with C90 (Or switch to C99)
This PR does the former.
deps/ntmlclient is left alone for now but it has the same problem.
We could consider doing something similar with the `GIT_INLINE(type)` macro but that would be a lot of changes for no particular benefit.

C90: add inline macro to xdiff and mbedtls

---

src/revparse.c
tests/refs/revparse.c

A bare '@' revision syntax represents HEAD.  Support it as such.
Fixes #6123

revparse: support bare '@'

---

examples/index-pack.c
fuzzers/packfile_fuzzer.c
include/git2/index.h
include/git2/indexer.h
include/git2/pack.h
src/branch.c
src/commit_graph.c
src/commit_graph.h
src/config_file.c
src/hash.c
src/hash.h
src/index.c
src/index.h
src/indexer.c
src/midx.c
src/midx.h
src/pack-objects.c
src/pack-objects.h
src/reset.c
tests/checkout/crlf.c
tests/diff/workdir.c
tests/graph/commitgraph.c
tests/pack/indexer.c
tests/pack/packbuilder.c

This splits out some of the early grounding work in #6191 so that we can include it in the next minor release.
Notably, this makes our checksums simple byte arrays instead of them being `git_oid`s.  (Our file checksums are _not_ object IDs, after all).  It's important to get this in to the next release to mark functions like `git_index_checksum` as deprecated for their eventual removal.

SHA256: early preparation

---

src/pack-objects.c
src/pack-objects.h
src/transports/smart_protocol.c

For large pushes, preparing the pack can take a while. Currently we send the pack header first, followed by preparing the pack and then finally sending the pack. Unfortunately github.com will terminate a git-receive-pack command over http if it is idle for more than 10 seconds. This is easily exceeded for a large push, and so the push is rejected with a Broken Pipe error.
This patch moves the pack preparation ahead of sending the pack header, so that the timeout is avoided.
`prepare_pack()` can be called multiple times but will only do the work once, so the original `PREPARE_PACK` call inside `git_packbuilder_foreach()` remains.
Resolves https://github.com/libgit2/libgit2/issues/5905 .

push: Prepare pack before sending pack header.

---

include/git2/sys/remote.h
include/git2/sys/transport.h
src/fetch.c
src/oid.h
src/remote.c
src/remote.h
src/transports/local.c
src/transports/smart.c
src/transports/smart.h
src/transports/smart_protocol.c
tests/core/oid.c
tests/fetch/local.c
tests/online/fetch.c

Support object ids in refspecs for servers that support  `allow-tip-sha1-in-want` or `allow-reachable-sha1-in-want`.

Fetch by object id

---

.github/release.yml

Let's let GitHub handle our release notes as much as possible:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

meta: add a release configuration file

---

include/git2/merge.h
src/merge.c
src/merge.h
src/merge_driver.c

Somewhere along the line `GIT_MERGE_FILE_FAVOR__CONFLICTED` seems to have moved from `git_merge_file_favor_t` to `git_merge_file_flag_t` without changing value, causing a possible conflict in `file_opts.flags`
This PR allocates flags in the enums of `git2/merge.h` for internal usage but marks them as such to avoid overlapping bits in the future.
The flags are `#defined` to their previous descriptive names in `src/merge.h` to keep their enum type.

merge: fix overlap between GIT_MERGE_FILE_FAVOR__CONFLICTED and GIT_MERGE_FILE_SIMPLIFY_ALNUM

---

cmake/SelectHTTPParser.cmake

Fix building against system http-parser library by fixing
the find_package() argument.  It seems to have been accidentally changed
from HTTPParser to HTTP_Parser in de178d36f, effectively making
the build against system library fail to find it:
```
CMake Warning at cmake/SelectHTTPParser.cmake:3 (find_package):
By not providing "FindHTTP_Parser.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"HTTP_Parser", but CMake did not find one.
Could not find a package configuration file provided by "HTTP_Parser" with
any of the following names:
HTTP_ParserConfig.cmake
http_parser-config.cmake
Add the installation prefix of "HTTP_Parser" to CMAKE_PREFIX_PATH or set
"HTTP_Parser_DIR" to a directory containing one of the above files.  If …
```

cmake: Fix package name for system http-parser

---

src/xdiff/xdiff.h
src/xdiff/xmerge.c

We've added a lovely abstraction layer in xdiff so that it can call our
allocation functions.  But it also needs to call our free functions.  We
missed some `free` calls in `xmerge.c`.  Update them to use `xdl_free`.
Without this, we will pass a pointer allocated with a custom allocator
to the system free function.  :bomb:

xdiff: use xdl_free not free

---

src/win32/findfile.c
tests/win32/systemdir.c

Allow for no Git for Windows installation.  When there is no GfW found
in the path or registry, `git_win32__find_system_dirs` would return a
`GIT_ENOTFOUND`.  Callers were not expecting this.  Since this is no
error, we simply return `0` so that callers can move on with their
lives.
Fixed #6225

win32: `find_system_dirs` does not return `GIT_ENOTFOUND`

---

CMakeLists.txt

If users are using us as a direct dependency (via `add_subdirectory`)
then they may want to know the libraries to link to; tell them.

cmake: export libraries needed to compile against libgit2

---

src/cli/opt_usage.c
src/libgit2/object.c
src/libgit2/refdb_fs.c
src/libgit2/transports/httpclient.c
src/util/assert_safe.h
src/util/fs_path.c
tests/util/assert.c

Mostly this adds a few guards for things that coverity flagged.  The only big change here is the addition of `GIT_ASSERT_WITH_CLEANUP()` which will run the block when the assertion failed.  Now that we do "safe" assertions (returning to the caller with an error) whenever possible, we may need to unlock a mutex.  This allows for this.

Some minor fixes for issues discovered by coverity

---

src/libgit2/repository.c

As builtin extensions are evaluated in the latter half of `check_valid_extension`, a string `cfg` is concatenated with the static string 'extension.' and the value from `builtin_extension`, before being compared with the configured value. This string is not being cleared while iterating through the names of the extensions. Because there is currently only one extension (`noop`), the bug was never noticeable.
This patch corrects the behavior by clearing the string on each iteration, as is done in for user extensions in the preceding block.

Fix a string concatenation bug when validating extensions

---

src/libgit2/fetch.c
src/libgit2/remote.c
tests/libgit2/online/fetch.c

Support the ability to create a refspec that is a single object ID
without a destination.
Fixes #6243

fetch: support OID refspec without dst

---

tests/libgit2/diff/workdir.c

Our CI test infrastructure virtualizes arm32 in docker, which is a
sometimes imperfect situation. In `diff::workdir::can_diff_empty_file`,
avoid the stat to ensure that the file is zero bytes; there is an odd
issue running in qemu when emulating arm32 that we should skip.

diff: don't stat empty file on arm32 (flaky test)

---

.github/workflows/main.yml
.github/workflows/nightly.yml
tests/libgit2/diff/workdir.c
tests/util/copy.c

The 32-bit ARM QEMU builds are flaky when running `lstat`. Disable those
testing `lstat`'s `st_size` temporarily.

tests: support flaky stat

---

src/libgit2/diff_print.c
tests/libgit2/diff/parse.c
tests/libgit2/patch/patch_common.h

This PR fixes a null pointer deref in the following scenario:
1. Write a patch that creates or deletes a file (with `new file mode ...` or `delete file mode ...`), **and** has unquoted filenames with spaces in the 1st line of the header.
For example, take PATCH_ORIGINAL_NEW_FILE_WITH_SPACE in patch_common.h:
```patch
diff --git a/sp ace.txt b/sp ace.txt
new file mode 100644
index 000000000..789819226
--- /dev/null
+++ b/sp ace.txt
@@ -0,0 +1 @@
+a
```
2. Get a `git_diff` from the patch with `git_diff_from_buffer`
3. Regenerate a patch with `git_diff_to_buf`
I'm not sure the proposed fix is optimal, since it doesn't reproduce the same `diff --git` header line. But, it at least prevents the crash, and vanilla `git apply` accepts the resulting patch.

Fix crash when regenerating a patch with unquoted spaces in filename

---

include/git2/common.h
include/git2/errors.h
src/libgit2/config.c
src/libgit2/libgit2.c
src/libgit2/repository.c
src/libgit2/repository.h
src/util/fs_path.c
src/util/fs_path.h
tests/clar/clar_libgit2.c
tests/clar/clar_libgit2.h
tests/clar/main.c
tests/libgit2/repo/config.c
tests/libgit2/repo/open.c
tests/util/path.c

Validate that the repository (the `.git` folder for bare repositories, or its parent, the working directory, for non-bare repositories) is owned by the current user. This prevents a class of attacks where an attacker creates a `.git` directory in a shared folder (eg `/tmp`) with a malicious configuration. Other users on the system who run git commands in `/tmp` would then be vulnerable.

Validate repository directory ownership

---

include/git2/common.h
include/git2/errors.h
src/config.c
src/libgit2.c
src/path.c
src/path.h
src/repository.c
src/repository.h
tests/clar_libgit2.c
tests/clar_libgit2.h
tests/core/path.c
tests/fetchhead/fetchhead_data.h
tests/fetchhead/nonetwork.c
tests/main.c
tests/online/clone.c
tests/online/fetch.c
tests/online/fetchhead.c
tests/online/remotes.c
tests/repo/config.c
tests/repo/open.c

Backport of #6266 to the v1.3 branch.

Validate repository directory ownership (v1.3)

---

src/describe.c

When the passed object fails to be peeled into a commit pointer,
the cleanup code still tries to free the (uninitialized) pointer.
See #6272

Bug #6272 - fix crash in git_describe_commit.

---

fuzzers/packfile_fuzzer.c
src/libgit2/commit_graph.c
src/libgit2/commit_graph.h
src/libgit2/index.c
src/libgit2/indexer.c
src/libgit2/iterator.c
src/libgit2/midx.c
src/libgit2/midx.h
src/libgit2/oid.c
src/libgit2/oid.h
src/libgit2/oidmap.c
src/libgit2/pack.c
src/libgit2/pack.h
src/libgit2/remote.c
src/libgit2/tree-cache.c
src/libgit2/tree.c
src/libgit2/tree.h
tests/libgit2/iterator/tree.c
tests/libgit2/object/raw/hash.c
tests/libgit2/object/raw/short.c
tests/libgit2/object/tree/parse.c
tests/libgit2/pack/packbuilder.c

Instead of treating `git_oid` as if it's simply an array of bytes, actually look at the internal byte array member. This is critical if we add additional data to the `git_oid` (like a type enum).
(This is broken out of #6191.)

sha256: refactoring in preparation for sha256

---

include/git2/sys/transport.h

6fc6eeb66c40310086c8f059cae41de69ad4c6da replaced the remote options
with `git_remote_connect_options`. The function definitions were
removed, but one function declaration remained, causing linker errors if
one tried to use it.
This change removes the declaration of
`git_transport_smart_proxy_option` to better reflect reality.

remote: Delete a now-inexistent API declaration

---

include/git2/sys/transport.h

`#include <git2/sys/transport.h>` leads to the following error message:
```
compiling test.c
In file included from test.c:2:
/opt/homebrew/Cellar/libgit2/1.4.2_1/include/git2/sys/transport.h:38:9: error: unknown type name 'git_remote_connect_options'
const git_remote_connect_options *connect_opts);
^
```
`git_remote_connect_options` is defined in `git2/remote.h`
Including `"git2/remote.h"` in `include/git2/sys/transport.h` fixes the issue

Fix missing include

---

src/libgit2/midx.c

It's insufficient to only check if the offset high order bit is set, as some object offsets may have their high order bit set but still not use the large offsets table.
We must also check to see if object_large_offsets are in use.
This can cause libgit2 to falsely claim objects do not exist when they actually do, because it is unable to find the object in the index.
cc: @lhchavez as the original author of MIDX support.

midx: fix large offset table check.

---

src/libgit2/midx.c

This is something we only want to do during explicit verification rather than on
every load.
Verifying does not seem like a big deal when we're running with test workloads
but once your `multi-pack-index` reaches gigabytes, we spend more time hashing
this than doing any work.
This is basically what we do for single-pack index files as well. We trust that he checksum is fine while running regularly.
cc @lhchavez as author of our implementation

midx: do not verify the checksum on load

---

tests/libgit2/refs/revparse.c

Originally introduced in: 776a6a8e5f8e258d31aded73c0ce38df6ac7bdc4
This test case has recently been fixed in bdab22384cc61d315005a65456a9f9563bb27c8f, but that fix will only last for a year. Next year the same problem will crop up and the test will need to be re-edited.
This is not ideal as
- This test case becomes an unnecessary burden for developers
- Downstream distros or even just users who want to build older versions of libgit2 are guaranteed to have this test fail
Furthermore, this test case is entirely unnecessary, as the functionality that was originally (see 776a6a8e5f8e258d31aded73c0ce38df6ac7bdc4) intended to be tested is well-covered by subsequent tests which specify a date instead of a "x ago" specification.

revparse: Remove error-prone, redundant test

---

src/libgit2/refdb_fs.c

Super minor but it appears the packed ref lookup rewrite(#6138) didn't set the "not found" error message correctly and it broke a test in nodegit :sweat_smile:
I haven't checked for other missing errors in this file but when I get some time I can look it over just in case

refs: fix missing error message

---

src/cli/progress.c
src/cli/progress.h

* Use `PRIuZ` format for printing progress on 32 bit machines
* Update bandwidth / throughput once per second to avoid unnecessary noise on the console

CLI: progress updates

---

.clang-format

I started with the https://github.com/git/git `.clang-format`, with a few tweaks.  This still isn't quite right, but it's a little bit closer.  This feels like a thing that we can iterate on here.

Add a .clang-format with our style

---

src/libgit2/mwindow.c
src/libgit2/mwindow.h

I was looking at this code and found a couple of places where we've way too verbose for what we're doing and figured we can make this easier to read.
The first change makes us include the hash/extra size in the window "contains" check as we only ever use them (and would want to use them) in pairs.
The second change eliminates some rather verbose comparisons in favour of maths. The values are already `1` and `-1` so we can multiply instead of chaining several comparisons. This is likely to be gentler on the branch predictor due to fewer conditional jumps but that's unlikely to be measurable.

A couple of simplications around mwindow

---

include/git2/sys/remote.h
include/git2/sys/transport.h
src/libgit2/remote.h
src/libgit2/transports/smart.c
tests/libgit2/transport/register.c

6fc6eeb66c40310086c8f059cae41de69ad4c6da removed
`git_transport_smart_proxy_option`, and there was nothing added to
replace it. That made it hard for custom transports / smart
subtransports to know what remote connect options to use (e.g. proxy
options).
This change introduces `git_transport_smart_remote_connect_options` to
replace it.

transport: introduce `git_transport_smart_remote_connect_options`

---

src/libgit2/repository.c
tests/libgit2/repo/open.c

Update our ownership checks that were introduced in libgit2 v1.4.3
(to combat CVE 2022-24765). These were not compatible with git's; git
itself allows administrators to own the path. Our checks now match
this behavior.
Fixes #6279

repo: allow administrator to own the configuration

---

src/libgit2/filter.c

Registering a git_filter without setting the `stream` callback causes the git_filter_list_apply_* functions(which eventually call filter.c:setup_stream) to call buffered_legacy_stream_new which sets the legacy_write_fn callback instead of the write_fn callback. but buffered_stream_close will only ever call write_fn callback...thus the segfault.
This appears to have been introduced with the git_buf/git_str split.
Hopefully I've taken the right approach here? I ran this against the nodegit test suite(which hasn't implemented filter streaming yet) and it fixed the crashes I was experiencing.

filter: Fix Segfault

---

src/libgit2/config.c

This change is intended to fix what appears to be a regression introduced as part of changes to distinguish git_buf/str.
I discovered the public git_config_find_system_file function wasn't working as advertised while attempting to this to find/use the system configuration file in combination with a custom config backend I use otherwise (in conjunction with a custom ODB backend).
When looking into the history of the code changes, I noticed both the git_config_find_system_file & git_config_find_xdg_file previously used corresponding git_sysdir_find* functions, but when change was made to use GIT_BUF_WRAP_PRIVATE, they've ended up using git_sysdir_find_global_file, which this change should hopefully correct for both scenarios (this at least worked in my case when looking for the system …

Fix internal git_sysdir_find* function usage within public git_config_find* functions

---

src/libgit2/rebase.c

fix: https://github.com/libgit2/libgit2/issues/6127

fix interactive rebase detect.

---

cmake/FindPCRE.cmake
cmake/FindPCRE2.cmake

since f585b12 neither PCRE nor PCRE2 backends rely on POSIX regex, so
reflect it in library detection logic

cmake: drop posix dependency from pcre* detection

---

src/libgit2/config.c
src/libgit2/repository.c
src/util/fs_path.c
src/util/fs_path.h
tests/libgit2/repo/open.c

In #6321, I allowed root or administrator groups to own the repository, meaning that a repository directory needed to be owned _either_ by the user opening the repository _or_ the administrator. This did not match git's semantics, which only allows _either_ the user opening the repository _or_ the administrator _if and only if_ the current user is in the administrator group.
In other words, when you `runas` with an administrator account, you need to be able to both _create_ and then _use_ a git repository. But you should not trust any repository owned by an administrator.
Match this behavior on libgit2.
_Actually_ fix #6279.

Fix erroneously lax configuration ownership checks

---

tests/libgit2/online/clone.c

Either:
1. SecureTransport sucks, or
2. Google Source sucks, or
3. they both suck, or
4. they merely hate each other.
🤷‍♂️  Skip the tests on macOS.

tests: skip flaky-ass googlesource tests

---

tests/libgit2/CMakeLists.txt

The ftruncate test have been moved to util and shouldn't/can't be done from the libgit2 tests anymore

clar: remove ftrunacte from libgit2 tests

---

src/util/rand.c

Ensure the needed wincrypt.h is included.
Without this, rand.c will not compile if -DWIN32_LEAN_AND_MEAN is set in the compile flags.

fix compile on Windows with -DWIN32_LEAN_AND_MEAN

---

src/util/regexp.c

`data` is allocated using `pcre2_match_data_create` but not freed in all code paths

Fix memory leak

---

src/libgit2/worktree.c
tests/libgit2/worktree/worktree.c

Rationale: I preferred to not touch the function I mention in #6366 since that check mostly assumes the directory exists and is checking its contents (for corrupted worktrees, etc). So I added an additional check specific to the lookup function. If the directory does not exist, it means the worktree does not exist as well.

#6366: When a worktree is missing, return GIT_ENOTFOUND.

---

cmake/ExperimentalFeatures.cmake
include/git2/experimental.h
src/libgit2/experimental.h.in
tests/libgit2/core/oid.c
tests/libgit2/odb/loose.c

Provide an empty `include/git2/experimental.h` file for users who do not build with cmake. When building with cmake, we will generate the `experimental.h`, prefer it during builds, and install it with `cmake --target install`.
A different implementation to solve #6378

Support non-cmake builds with an in-tree `experimental.h`

---

src/libgit2/commit_graph.c
src/libgit2/commit_graph.h
tests/libgit2/graph/commitgraph.c

It is expensive to compute the sha1 of the entire commit-graph file each time we open it. Git only does this if it is re-writing the file.
This patch will only verify the checksum when calling the external API git_commit_graph_open(), which explicitly says it opens and verifies the commit graph in the documentation.
For internal library calls, we call git_commit_graph_get_file(), which mmaps the commit-graph file in read-only mode. Therefore it is safe to skip the validation check there.
Tests were added to check that the validation works in the happy path, and prevents us from opening the file when validation fails.
(Note from Derrick Stolee: This patch was applied internally at GitHub after we recognized the performance impact it had during an upgrade of libgit2. The original author …

commit-graph: only verify csum on git_commit_graph_open().

---

src/libgit2/repository.c
tests/libgit2/repo/open.c

Fixes an issue identified where a not found error is returned from the repo ownership validation when 'safe.directory' isn't configured, rather than the more meaningful ownership error (GIT_EOWNER).

Ignore missing 'safe.directory' config during ownership checks

---

src/libgit2/tag.c

If the tag already exists and we are not forcing overwrite we need to free ref_name buffer before return the "tag already exists" error.

Fix leak in git_tag_create_from_buffer

---

src/libgit2/transports/http.c
src/libgit2/transports/httpclient.c
src/libgit2/transports/httpclient.h

Httpclient internally stores a copy of the `certificate_check` callback and payload. When connecting via HTTPS, and if the server sends back `"Connection: close"` after the first request, the following request would attempt to re-use the httpclient and call the (now outdated) callback. In particular for pygit2 this is a problem, since callbacks / payloads are only valid for the duration of a libgit2 call, leading to a `ffi.from_handle()` error and crashing the Python interpreter.
The error looks like this:
> Fatal Python error: b_from_handle: ffi.from_handle() detected that the address passed points to garbage. If it is really the result of ffi.new_handle(), then the Python object has already been garbage collected
Possibly related to https://github.com/libgit2/pygit2/issues/1001.

http: Update httpclient options when reusing an existing connection.

---

COPYING

The `git_fs_path_basename_r()` function in `src/util/fs_path.c` says it's based on Android code using the 2-clause BSD license, so I suppose that means the COPYING file should include that.

add 2-clause BSD license to COPYING

---

src/util/net.c
src/util/net.h
tests/util/url/joinpath.c
tests/util/url/parse.c
tests/util/url/pattern.c
tests/util/url/redirect.c
tests/util/url/scp.c
tests/util/url/valid.c

Google Code allows you to put `@` in usernames, and git supports urls like `ssh://user@domain@host/...` because - fuck you, RFCs. Add our own URL parsing so that we can cope with this madness. 😭 
Fixes #6199

URL parsing for google-compatible URLs

---

src/libgit2/transports/smart_protocol.c

This looks like a typo to me, from what i can see these lines were added at the same time and because of how capabilities are calculated, it's likely that this code will work in situations where these capabilities were the last ones.

transport: fix capabilities calculation

---

src/util/thread.h
src/util/util.h

`git__noop` takes no arguments, so a simple `#define func(a) git__noop` will produce warnings about the unused `a`. Introduce `git__noop_args` to swallow arguments and avoid that warning.

thread: avoid warnings when building without threads

---

src/libgit2/push.c
tests/libgit2/online/push.c

I want to push a commit by OID to a remote branch. Currently, push parses the refspecs such that the source must be the name of a ref (it uses git_reference_name_to_id to resolve it). This commit changes it so push uses git_revparse_single to resolve the source of the refspec. This allows for OIDs or other revs (e.g. `HEAD~2`) to be pushed.

push: revparse refspec source, so you can push things that are not refs

---

src/libgit2/push.c

211c97195e2ebcf68e27782715eb756823ad5a91 attempts to use the parsed OID but inverted the arguments to `git_oid_cpy`.

push: use resolved oid as the source

---

tests/clar/clar.c
tests/clar/clar.h
tests/clar/clar/print.h
tests/clar/clar/summary.h

Update to the latest main version of clar, which includes improved xml summary output.

tests: update clar test runner

---

.github/workflows/main.yml

When the dependent jobs fail -- possibly due to test failures -- we should still produce the job summary that shows those test failures.

ci: always create test summaries, even on failure

---

src/libgit2/submodule.c

`git_clone` checks for existence of (non-empty) directories that would clash with what is about to be cloned.
This is problematic when cloning submodules since they make sense in the context of a parent module, so they should not use the current working dir.
Since in `git_submodule_update` we clone the submodule only when it is not yet initialized we do not need to perform directory checks.
Fixes #5830

Use `git_clone__submodule` to avoid file checks in workdir

---

README.md

Updates the README.md language binding section to include an additional project providing PHP bindings at https://github.com/RogerGee/php-git2.
I've been working on PHP language bindings for `libgit2` since late 2016. I started the project because the existing support for PHP was incomplete, and I wanted to create more complete, full-featured and stable support for PHP. Since then, the project has really come a long way, and I'd like to incorporate it into the list of PHP language bindings in the `libgit2` README so others can more easily find it.
I plan on maintaining this project in the future as much as possible. Here are a few highlights:
- Coverage of the `libgit2` API (`v1.5.0`) is around 70% at the time of this writing
- The extension provides reference-counting functionality to …

Add new PHP bindings project to language bindings section of README.md

---

src/libgit2/streams/openssl.c
src/libgit2/streams/openssl_dynamic.c
src/util/hash/openssl.c

Try to load OpenSSL 3 libraries when compiled with OpenSSL-Dynamic
support.
Handle the deprecated symbol renaming of SSL_get_peer_certificate to
SSL_get1_peer_certificate -- try to load the old name and if it fails,
use the new one.

Support OpenSSL 3 in dynamic loading mode

---

src/libgit2/diff_file.c
tests/libgit2/diff/workdir.c

This PR fixes a crash and a failed assert in the following scenario:
1. create an **empty** untracked file in a repo;
2. call `git_diff_index_to_workdir`;
3. feed the diff to `git_patch_from_diff`;
4. free the resulting patch.
Currently, this use case raises two issues:
- `git_diff_file_content__unload` may attempt to free `git_str__initstr` (a statically-allocated array)
- or, `GIT_MMAP_VALIDATE` may fail
The outcome depends on whether or not filters (such as “core.crlf”) were installed:
- With filters, [`fc->map.data` ultimately points to `git_str__initstr`](https://github.com/libgit2/libgit2/blob/v1.5.1/src/libgit2/diff_file.c#L371-L381) because the file is empty (convert_buf doesn’t touch “out”). However, `GIT_DIFF_FLAG__FREE_DATA` is set; so, when time comes to free the patch, …

diff_file: Fix crash when freeing a patch representing an empty untracked file

---

src/cli/CMakeLists.txt
src/libgit2/CMakeLists.txt

Fixes #6254 
It seems like EMBED_SSH_PATH broke because the CLI is also building its own copy of libgit2 but the headers weren't being included.
In order to get EMBED_SSH_PATH working again I've removed duplicated code in the libgit2 specific `CMakeLists.txt` file and ensured that the CLI also builds with the correct include paths.

Fix build failure with -DEMBED_SSH_PATH

---

src/util/posix.h

`off64_t` is `long long` on AIX, see `/usr/include/sys/types.h` on AIX.

 Define correct off64_t for AIX

---

include/git2/strarray.h
src/libgit2/describe.c
src/libgit2/remote.c
src/libgit2/strarray.c
src/libgit2/strarray.h

`git_strarray_copy` is deprecated (and has been included in `deprecated.h` for some time). It should not have remained in the public `strarray.h`. Remove it.

strarray: remove deprecated declaration

---

include/git2/stash.h
src/libgit2/stash.c
tests/libgit2/core/structinit.c
tests/libgit2/stash/save.c

There's this concept called partial stashing in Git where users are able to stash desired files without having to stash and also reset the entire workdir. I based my implementation on tiennou's suggestion from #4725. This introduces options to `git_stash_save` where developers are able to supply the paths that they want to have stashed from the workdir. I could have gone further and have exposed a `git_index*` option  as tiennou suggested, but I chose not to at this moment. Let me know if I should expose a `git_index*` option so that users can supply an arbitrary index to be stashed.
I also introduced `GIT_STASH_KEEP_ALL`, which prevents resetting the index and workdir once a stash has been completed.

stash: partial stash specific files

---

src/libgit2/repository.c
src/util/fs_path.c

With some paths on Win32, we cannot identify the owner because it's on a file share (WSL2 or UNC). In that case, don't fail, but identify that the current user does not own the path. This matches Git for Windows behavior.
Fixes #6468

Handle Win32 shares

---

README.md

We say that you can link libgit2 "unmodified"... "without having to release its source code". Clarify that you can modify libgit2 - but you must release _its_ source code back - and you can link libgit2 without having to release _your software's_ source code.

README: clarify the linking exception

---

src/libgit2/transports/ssh.c

Fixes https://github.com/libgit2/libgit2/issues/3866
Has been applied in all Julia builds since 2017:
https://github.com/JuliaLang/julia/pull/17459
Authored-by: Keno Fischer <kfischer@college.harvard.edu>

Make failure to connect to ssh-agent non-fatal

---

include/git2/odb_backend.h
src/libgit2/odb.c

`git_odb_stream` should have an `oid_type` to disambiguate; that's not necessary on non-experimental SHA256 builds. Avoid unnecessary ABI breakage for consumers and hide it behind an ifdef for now.

odb: don't unconditionally add oid_type to stream

---

include/git2/repository.h

This improves the documentation for `git_repository_is_empty` which currently does not accurately describe libgit2's definition of "empty".
It says that HEAD must point to the "unborn master branch", when in fact, this is not the case if the repo's `init.defaultBranch` configuration is set. If it is set, it will check that HEAD points there. Only if it is not set does it fall back to `master`.

Correct the definition of "empty" in the docs for `git_repository_is_empty`

---

src/libgit2/transports/ssh.c
src/util/net.c
src/util/net.h
tests/libgit2/online/clone.c

This is a patch that has been applied for 2 years in Julia. Quoting from @StefanKarpinski in his original pull request:
> It seems that no one actually verifies SSH host identity with libgit2 because the callback doesn't give enough information do so correctly:
> 
> * It doesn't give the actual host key fingerprint, but rather three
>   different hashes thereof. This means we cannot distinguish a known
>   hosts entry that has a different type (`ssh-rsa`, `ssh-dsa`, etc.)
>   from an entry with a matching type and a fingerprint mismatch: the
>   former should be treated as an unknown host whereas the latter is a
>   host key mismatch; they cannot be distinguished without this patch.
> * If the user connects on a non-default port (i.e. not 22), this is not
>   passed to the callback in any …

Pass hostkey & port to host verify callback

---

src/libgit2/remote.c

In b1e83cca1bbc255627950b4e8d4fdb1174bf7a12 we erroneously stopped setting the old ID to zero; correct that.

remote: always populate old id in update tips

---

src/libgit2/transports/ssh.c
tests/libgit2/online/clone.c

Introducing #6503 regrettably meant that host:port was ambiguous with IPv6 addresses. (See #6510.) Revert until we can sort out a proper path forward in v1.7.

Revert #6503

---

src/libgit2/odb_loose.c
tests/libgit2/odb/backend/loose.c

`git_odb_backend_loose` was erroneously removed during a refactoring; add it back.
Fixes #6509

Add `git_odb_backend_loose` back

---

src/libgit2/CMakeLists.txt

The library name is correctly libgit2 (not git2) or libgit2-experimental depending on configuration.
Fixes #6507

meta: configure pkg-config .pc correctly

---

tests/util/path.c

The `git_fs_path_owner_is_current_user` expects the root dir on unix (`/`) to be owned by a non-current user. This makes sense unless root (or euid == 0) is running the tests, which often happens during distro build / packaging scripts. Allow them to run the tests.

fs_path: let root run the ownership tests

---

src/libgit2/odb.c
tests/libgit2/odb/open.c

`git_odb_open` was erroneously removed during a refactoring; add it back.
Fixes #6519

odb: restore `git_odb_open`

---

src/libgit2/index.c
tests/libgit2/index/addall.c

When all files beneath a directory are ignored, our diff machinery will return the directory itself. Obviously we do not operate on directories in the index, so `git_index_add_all` should ignore this case.
Fixes #6517

Ensure that `git_index_add_all` handles ignored directories

---

src/libgit2/sysdir.h

These declaration poses problems on some embedded or retro Linux systems that deliberately disable support for wchar_t from their libc.
```
<overlong path>/libgit2-1.6.2/src/libgit2/sysdir.h:138:53: error: unknown type name ‘wchar_t’
138 | extern int git_win32__set_registry_system_dir(const wchar_t *mock_sysdir);
|                                                     ^~~~~~~
```

sysdir: Do not declare win32 functions on non-win32 platforms

---

src/cli/CMakeLists.txt
src/libgit2/CMakeLists.txt
src/util/CMakeLists.txt

Including the `include/git2` build path is a seemingly unnecessary oversight to include the generated `experimental.h` file.

cmake: don't include `include/git2`

---

src/libgit2/pack.c

Keeping it as a 32-bit value means the min size calculation overflows or gets truncated which can lead to issues with large packfiles.
--
It's a bit disappointing that the compiler doesn't seem to care that we've been cutting off this value when we have a lot of objects.

pack: use 64 bits for the number of objects

---

src/libgit2/repository.c
src/libgit2/repository.h
tests/libgit2/repo/discover.c
tests/libgit2/repo/env.c

Refactor `GIT_REPOSITORY_OPEN_FROM_ENV` behavior.
* Remove `_git_repository_open_ext_from_env` which opens repository _differently_, using a _separate_ mechanism, so has different behaviors from the normal `git_repository_open_ext` behavior. Now the behavior is to look at environment variables to override the normal behavior of `git_repository_open_ext`.
* Add support for `GIT_WORK_TREE` and `GIT_COMMON_DIR`.
* Add support for `GIT_CONFIG_GLOBAL`, `GIT_CONFIG_SYSTEM`, and `GIT_CONFIG_NOSYSTEM`

repo: honor environment variables for more scenarios

---

src/libgit2/config.c
tests/libgit2/config/find.c

When the programdata path is missing, ensure that we pass down the `GIT_ENOTFOUND` error to the caller instead of converting it to a generic `-1`.

config: return `GIT_ENOTFOUND` for missing programdata

---

CMakeLists.txt
docs/changelog.md
include/git2/version.h
package.json

The new LibGit2Sharp is seeing numerous complaints of being unable to open ProgramData config on Windows. Prepare a point release for them.

v1.6.4 with a fix for ProgramData configs on Windows

---

src/libgit2/repository.c

... otherwise git_tree__parse_raw() will fail to obtain the correct oid size, which causes the entire parse to fail.
Fixes issue https://github.com/libgit2/libgit2/issues/6553.

Fix missing oid type for "fake" repositories

---

src/CMakeLists.txt
src/util/git2_features.h.in
src/util/util.c

As reported in https://bugs.freebsd.org/271234, recent versions of FreeBSD have adjusted the prototype for `qsort_r()` to match the POSIX interface. This causes libgit2's CMake configuration check to fail to detect `qsort_r()`, making it fall back to `qsort_s()`, which in libgit2 also has an incompatible interface. With recent versions of clang this results in a "incompatible function pointer types" compile error.
Summarizing, there are four variations of 'qsort-with-context':
* old style BSD `qsort_r()`, used in FreeBSD 13 and earlier, where the comparison function has the context parameter first
* GNU or POSIX `qsort_r()`, also used in FreeBSD 14 and later, where the comparison function has the context parameter last
* C11 `qsort_s()`, where the comparison function has the context …

util: detect all possible qsort_r and qsort_s variants

---

include/git2/oid.h
src/libgit2/errors.c
src/libgit2/indexer.c
src/libgit2/odb.c
src/libgit2/oid.c
src/libgit2/repository.c
src/libgit2/threadstate.h

We never error-check our "threadstate" thread-local storage, where we keep a few reusable buffers and the thread's current error message.  Make sure that we have a threadstate data instance before reading to it or writing from it.
Depends on #5720

Thread-local storage: handle failure cases

---

src/libgit2/midx.c

These chunks work like extensions where it's fine not to know what one means. We can skip over it and keep processing the file instead of erroring out.
---
I think there's probably a different bug here as well where erroring out of the midx means we don't really keep looking, as the bug I found here is that having a midx with REIDX, aka reverse index meant that we couldn't find an object, but IIUC we should have been able to fall back on to the per-pack index there.

midx: allow unknown chunk ids in multi-pack index files

---

cmake/SelectSSH.cmake

Fixes "CMake Error: could not resolve ssh2" on Windows-MSVC.
Fixes #5981

CMake: Search for ssh2 instead of libssh2.

---

src/libgit2/pack.c

Similar to a previous change where we had to change the casting when loading the index file, we also need to make sure we don't restrict the numbers to 32-bit when looking up objects in packfiles.
This was done about three years ago in git itself, but we never got he update in this library.
---
This is the potential bug I mention in #6583 where failing to parse the multi-pack index we then failed to parse the regular index as well. This is what git did in https://github.com/git/git/commit/f86f769550ef7fb5162a9cd4be5e2be7981d063b

pack: cast the number of objects to size_t

---

src/libgit2/midx.c

Similar to previous issues around doing way too much verification at loading time, checking whether the object index chunk is monotonic is better left for git-fsck instead of every single time we want to look at something in the repository.
As midx files grow, this starts taking more and more times. As an example, I went looking for this because it's taking about 1.5s to do a single object lookup in a repository that's ended up with a 7G multi-pack-index file.
----
For comparison without this loop we're down to 40ms. There's another loop for the fanout that I've left since `perf` didn't show pretty much any of `git2 cat-file` and it's not that terrible to have a little bit of checking to see that we didn't load complete nonsense.

midx: do not try to look at every object in the index

---

src/libgit2/commit_list.c
src/libgit2/commit_list.h
src/libgit2/revwalk.c

This commit fixes the following issues:
1. In `git_revwalk__push_commit`, if `opts->insert_by_date` is true, `git_commit_list_insert_by_date` is called. However, by this point the commit wasn’t parsed yet, so the `time` field still has 0 as value. Solved by parsing the commit immediately if `opts->insert_by_date` is true.
2. In the same function, there was an error in the boolean logic. When `opts->insert_by_date` was true, the commit would be inserted twice, first “by date” (not really, due to the issue described above) and then in the first position again. Logic was corrected.
3. In `prepare_walk`, when processing `user_input` and building the `commits` list, the order was being inverted. Assuming both fixes above, this would mean we would start negotiation by the oldest reference, not …

Partial fix for #6532: insert-by-date order.

---

include/git2/sys/alloc.h
src/libgit2/threadstate.c
src/util/alloc.c
src/util/alloc.h
src/util/allocators/failalloc.c
src/util/allocators/failalloc.h
src/util/allocators/stdalloc.c
src/util/allocators/win32_leakcheck.c
tests/clar/clar_libgit2_alloc.c
tests/clar/clar_libgit2_alloc.h
tests/util/alloc.c
tests/util/str/oom.c

Rebasing / refactoring #5263.
In particular, getting rid of this terrifying warning from the original PR:
```
/*
* This here is probably not quite obvious. If executing
* libgit2_clar -score::alloc, then the allocation tests
* are the first to get executed. Thus, we do not yet
* have encountered any errors yet, and thus there is no
* global state allocated yet.
*
* Now for the funny thing: if the first error that we
* encounter is an out-of-memory error, then we call
* `git_error_set_oom`. This again calls `GIT_GLOBAL`,
* which requests the current global state. If there is
* none, then we try to allocate one. Guess what? We're
* out of memory, so this fails and we call
* `git_error_set_oom`. Ad infinitum, until we crash
* because of recursion.
*
* This is why we just explicitly request …
```

tests: add allocator with limited number of bytes

---

include/git2/sys/transport.h

Add a missing include for `git2/oidarray.h` so build doesn't fail on using `git_oidarray` when using custom transports.
Fixes #6607

fix: Add missing include for oidarray.

---

src/libgit2/streams/stransport.c

- Constant only available in 10.13+, causing build failures for older macOS releases
- Fixes: [Issue 6606 - Use of macOS constant errSSLNetworkTimeout causes build failures for macOS 10.8 thru 10.12](https://github.com/libgit2/libgit2/issues/6606)

stransport: macOS: replace errSSLNetworkTimeout, with hard-coded value

---

src/libgit2/transports/ssh.c

In _git_ssh_setup_conn, known_hosts is allocated by _git_ssh_session_create. However, known_hosts is only cleaned up in the case of error.
This moves the cleanup code for known_hosts so that its run in the error an success case.
Fixes #6598

ssh: fix known_hosts leak in _git_ssh_setup_conn

---

src/libgit2/transports/http.c
src/libgit2/transports/httpclient.c
src/libgit2/transports/winhttp.c
src/util/net.c
src/util/net.h
tests/libgit2/online/clone.c
tests/util/url/http.c
tests/util/url/parse.c

I see the following behaviour in 1.7.0 but not in 1.5.0.
If the user's Git config specifies the proxy like this then libgit2 now crashes:
```
[http]
proxy = myhost:1234
```
The scheme (and port) are required but many users leave it off (curl defaults to http I read in the man pages).
In this pull request I propose checking the validity of the url after parsing it. Something similar is done in winhttp.c, so I replaced that with a call to git_net_url_valid but not sure if that's the right thing to do.

proxy: Return an error for invalid proxy URLs instead of crashing.

---

src/util/integer.h

In some projects ENABLE_INTSAFE_SIGNED_FUNCTIONS might already be defined...

Avoid macro redefinition of ENABLE_INTSAFE_SIGNED_FUNCTIONS

---

src/util/errors.c
src/util/fs_path.c
src/util/futils.h
src/util/net.c
src/util/regexp.c
src/util/unix/process.c

A couple of warnings were uncovered in #6655
This should take care of the easy ones.
The larger problem is the ctype warnings where we have a bit of a mix between using the proper `isalnum()` and rolling our own with `git__isalnum()`
The posix versions take an integer in to be able to handle EOF from `fgetc()` so when a char is passed it has to be casted to unsigned so that 128-255 isn't extended to negative integers.
The `git__isalnum()` function takes care of it by simply not handling characters outside of the ascii set and will behave incorrectly on systems using ISO-8859-1 or other charsets using more than 7 bits.
I'm not entirely sure why we have the `git__isalnum()` functions. I assume it is to support systems where `ctype.h` isn't available?
In that case I think the current …

util: suppress some uninitialized variable warnings

---

src/libgit2/push.c

When a user returns `-1` in a `push_negotiation` callback, we set the error to whatever's hanging out in the buffer, probably something about a missing configuration entry.
Clear the error buffer before invoking the callback, so that if a user does not set an error message in their callback that we can detect. If there is no error but `-1` is returned, set a generic error message.
Fixes #6672

push: set generic error in push_negotiation cb

---

include/git2/sys/repository.h
src/libgit2/repository.c
src/libgit2/repository.h
tests/libgit2/network/remote/local.c
tests/libgit2/odb/backend/nobackend.c
tests/libgit2/repo/new.c

This change adds support for setting oid type when creating an in-memory repository using git_repository_new (in conjunction with using custom backends).
Needed to prevent "ambiguous lookup - OID prefix is too short" error during git_object_lookup_prefix.

Support setting oid type for in-memory repositories

---

src/libgit2/clone.c
tests/libgit2/online/clone.c

New attempt at solving #5982, this time using `git_net_str_is_url` from util
Essentially it tries to sort out if we should clone locally without asking the filesystem until it is absolutely necessary since linux can be a bit unreliable on paths containing `://` and treat them as `:/`

clone: don't mix up "http://url" with "http:/url" when figuring out if we should do a local clone

---

src/libgit2/signature.c
tests/libgit2/commit/signature.c

`Sammy Davis Jr. Jr.` is a valid name and the dot shoud not be trimmed.
This makes libgit2 a bit more compatible with the git parsing.
See: https://github.com/git/git/blob/master/ident.c#L275

Do not trim dots from usernames

---

.github/workflows/benchmark.yml
.github/workflows/main.yml
.github/workflows/nightly.yml

Our CI workflows consume and will automatically generate their build containers. Ensure that they can do so.

ci: allow workflows to read and write packages

---

src/libgit2/attr.c
tests/libgit2/attr/repo.c

Fixes obscure bug caused by change shown below in 54a22f536557b9a25752c6b59829dff4cbee99e0.
For an in-memory repository without an index setup, nor any directory on-disk, git_repository_index_weakptr can now fail with a not found error returned by repository_index_path, as a consequence of this, attr_setup returns the not found error in this scenario, which then results in an error when attempting to lookup the driver for comparing a file during a diff.
Elsewhere, the not found errors are ignored within attr_setup directly, or indirectly by callers of that, but error is escaping via the diff driver lookup, hence fix added to ignore it directly within attr_setup.

Fix 'path cannot exist in repository' during diff for in-memory repository

---

README.md

master is no more; GitButler is a new client using libgit2.
Fixes #6689

README: replace gmaster with GitButler

---

src/util/unix/process.c

`process->status` is a status value; we were mistakenly trying to close it as a file descriptor, as if it were the `status` self-pipe that we open during process creation.
Instead, don't try to close it, as it's not a file descriptor.
Fixes #6686

process: don't try to close the status

---

src/util/unix/posix.h
tests/clar/clar.c
tests/util/string.c

strcasecmp is a posix function, testing it doesn't make sense.
Functions that needs unsigned compare should use git__strcasecmp()
If people are using signed chars then they will probably run into some issue where sorted strings end up in a different order but this is a problem with the functions calling strcasecmp instead of git__strcasecmp, not strcasecmp itself.

tests: remove test for strcasecmp

---

.gitattributes
.github/actions/run-build/action.yml
.github/workflows/main.yml
.github/workflows/nightly.yml
ci/build.sh

Splitting some of the more general CI improvements out of #6685 to keep it focused on Cygwin support

ci: improvements to prepare for Cygwin support

---

src/libgit2/iterator.c
src/libgit2/refs.c
src/libgit2/refs.h
src/util/util.c
tests/libgit2/iterator/workdir.c
tests/libgit2/network/remote/rename.c
tests/libgit2/odb/sorting.c
tests/libgit2/remote/fetch.c

After upgrading the undefined behavior scanner to LLVM 14, we see some warnings reported. These warnings are correct; this PR fixes them.

Fix some bugs caught by UBscan

---

src/libgit2/diff_tform.c
tests/libgit2/diff/rename.c

Unmodified deltas are not always removed by git_diff_find_similar() when GIT_DIFF_FIND_REMOVE_UNMODIFIED is set. It only works correctly when a rename or copy is found in the diff. Somewhat understandably, this is the only case covered by the unit tests.
Non-blob deltas also avoid removal because of the way they are excluded as rename candidates. I've added a test for this using the "submodules" fixture. Maybe there's a simpler way to test for non-blob deltas?

git_diff_find_similar doesn't always remove unmodified deltas

---

src/libgit2/transports/httpclient.c

Some static code analysis complains that we're putting a stack variable into client->parser.data (which persists past the function calls). Clear that on function exit to avoid confusion.

httpclient: clear client->parser.data after use

---

.github/workflows/main.yml
.github/workflows/nightly.yml
ci/docker/centos7
ci/docker/centos8
ci/docker/focal
ci/docker/noble
ci/docker/xenial
ci/test.sh

This makes several changes to our CI builds:
1. Our sanitizer builds are now running in Ubuntu Noble (24.04), which has newer GCC and Clang versions. This has already caught several problems!
2. All platforms are now building libssh2 v1.11.0. Generally, our Xenial builds are meant to run _the oldest possible_ versions of things for compatibility testing. But given the weak cipher compatibility in libssh2, it's simply not possible to use older versions with modern OpenSSH or hosting providers.
2. We now run a mix of newest Ubuntu (Noble) and oldest supported Ubuntu (Xenial) for our CI builds. This helps us use newer compilers, toolchains, etc, in addition to older ones, to catch a broader set of problems.

Yet more CI improvements

---

examples/push.c

This adds basic support for user/password and SSH authentication to the push example. Authentication is implemented by using the [`cred_acquire_cb` credential callback defined in `examples/common.c`](https://github.com/libgit2/libgit2/blob/868f4bcb4d3290f4b5320f030fccdf1e7fc8ac8a/examples/common.c#L179-L226).
We think that supporting authentication is valuable because pushing to a target repository requires authentication in most practical applications (especially for testing). Also, we would like to use this extended version of the push example in a reproduction step of an issue we are going to submit (this makes reproducing the issue easier than having to build and debug a separate code example).

Support authentication in push example

---

include/git2/commit.h
include/git2/repository.h
src/libgit2/commit.c
src/libgit2/repository.c
tests/libgit2/repo/getters.c

* Emulating `git commit` is clunky - identifying your commit's parents is part of the problem. Provide a helper to give you the parents given the current repository state.

Add `git_repository_commit_parents` to identify the parents of the next commit given the repository state

---

src/libgit2/repository.c
tests/libgit2/repo/open.c

Vanilla Git does not do it either (cf. https://github.com/gitster/git/blob/master/setup.c#L1150) and calling git_fs_path_prettify_dir can cause performance issues (cf. issue #6649).
Still needed: expansion of "~/"... (but not this PR)

Do not normalize safe.directory paths

---

examples/merge.c
include/git2/commit.h
include/git2/errors.h
src/libgit2/commit.c
src/libgit2/commit.h
src/libgit2/notes.c
src/libgit2/rebase.c
src/libgit2/repository.c
src/libgit2/repository.h
src/libgit2/stash.c
tests/clar/clar_libgit2.h
tests/libgit2/checkout/tree.c
tests/libgit2/cherrypick/workdir.c
tests/libgit2/commit/commit.c
tests/libgit2/commit/create.c
tests/libgit2/commit/write.c
tests/libgit2/diff/rename.c
tests/libgit2/odb/freshen.c
tests/libgit2/rebase/sign.c
tests/libgit2/refs/reflog/messages.c
tests/libgit2/revert/workdir.c
tests/libgit2/revwalk/basic.c

Provide a simple helper method that allows users to create a commit from
the current index with minimal information.

commit: introduce git_commit_create_from_stage

---

src/libgit2/clone.c

When determining whether to check out a branch, we did not actually look at `should_checkout`'s possible error condition. Disconnect the boolean "should checkout" value from the potential error code so that it no longer looks like a function that can be treated as if it returns a boolean.

clone: don't swallow error in should_checkout

---

src/libgit2/index.c
tests/libgit2/index/add.c

`has_dir_name` is used to check for directory/file collisions, and attempts to determine whether the index contains a file with a directory name that is a proper subset of the new index entry that we're trying to add.
To determine directory name, the function would walk the path string backwards to identify a `/`, stopping at the end of the string. However, the function assumed that the strings did not start with a `/`. If the paths contain only a single `/` at the beginning of the string, then the function would continue the loop, erroneously, when they should have stopped at the first character.
Correct the order of the tests to terminate properly.
Thanks to the Amazon AWS Security team for finding and responsibly disclosing this.

Correct index add directory/file conflict detection

---

src/util/rand.c

CMakeLists.txt is looking for `unistd.h` (where the `getentropy` function is present for at least Linux and OpenBSD).
It isn't necessary to include `sys/random.h` (which is Linux only).
It unbreak the build on OpenBSD.

GIT_RAND_GETENTROPY: do not include sys/random.h

---

src/libgit2/config.c
tests/libgit2/config/multivar.c
tests/libgit2/refs/branches/delete.c

Renaming a config section or deleting its content removes each entry after copying it in its new place if needed. However, since each entry may be part of a multivar, deletion must only remove the exact entry that has just been copied.
Fix #6722

config: properly delete or rename section containing multivars

---

src/libgit2/revparse.c
tests/libgit2/refs/revparse.c

Support a revspec of '@' to mean 'HEAD', but ensure that it's at the start of the revspec. Previously we were erroneously allowing 'foo@' to mean 'HEAD' as well. Instead, 'foo@' should be rejected.
Fixes #6735

revparse: ensure bare '@' is truly bare

---

src/libgit2/repository.c
tests/libgit2/repo/init.c

Given a win32 path, ensure that we can initialize it. This involves a posix-style path conversion at the beginning of our initialization.
Fixes #5241

repo: ensure we can initialize win32 paths

---

src/libgit2/patch_parse.c
tests/libgit2/diff/parse.c

Generating a diff using `git_diff_tree_to_tree` and `git_diff_from_buffer` return different result for the same patch of:
```
$ git diff 17ec0f3 394a717
diff --git a/.env b/.env
index f9fb22f..ed7b51e 100644
--- a/.env
+++ b/.env
@@ -1 +1 @@
-hello=12345
+hello=123456
\ No newline at end of file
```
Diff:
```
from repo:::
- hello=12345
+ hello=123456<                // Notice missing \n and `<` origin, meaning deletion
\ No newline at end of file
.
from buff:::
- hello=12345
+ hello=123456
> \ No newline at end of file
```
We didn't add the LF, we deleted it!

Swap `GIT_DIFF_LINE_(ADD|DEL)_EOFNL` to match other Diffs

---

src/libgit2/transports/http.c
src/libgit2/transports/winhttp.c
tests/libgit2/online/fetch.c

An empty `http.proxy` config setting should be treated like a missing `http.proxy` config setting.
Fixes #5220

http: support empty http.proxy config setting

---

src/libgit2/diff_print.c
tests/libgit2/diff/workdir.c

When all contents of a diff are ignored, the resulting buffer should be empty but is instead malformed (includes a header but no hunks).
(This adds a failing test only at this point.)

Ensure that completely ignored diff is empty

---

src/libgit2/submodule.c
tests/libgit2/submodule/lookup.c

Fix broken regexp that matches submodule names containing ".path"

---

include/git2/worktree.h
src/worktree.c
tests/worktree/worktree.c

When adding a worktree using `git worktree add <path>`, if a reference
named `refs/heads/$(basename <path>)` already exist, it is checkouted in
the worktree.
Mimic this behavior in libgit2.

worktree: mimic 'git worktree add' behavior.

---

src/libgit2/refdb_fs.c
tests/libgit2/worktree/refs.c

This makes refdb_fs fully aware of per worktree refs (fixes issue #5492).
The code has some duplication but does the trick.

Make refdb_fs (hopefully) fully aware of per worktree refs

---

examples/log.c

- Parse correctly options
- Use correctly repo loaded in general runner.
- Add `--oneline` option

fix log example

---

include/git2/errors.h
src/libgit2/transports/local.c
tests/libgit2/clone/local.c

We don't support shallow clones for the local transport, currently. Fail, instead of silently ignoring the depth option.

fetch: fail on depth for local transport

---

src/libgit2/trailer.c
tests/libgit2/message/trailer.c

Update message trailer parsing to match git behavior for ignoring patch attachments.
Fixes #6760

Fix message trailer parsing

---

.github/workflows/main.yml
.github/workflows/nightly.yml
ci/setup-sanitizer-build.sh

Linux updated its ASLR randomization in a way that is incompatible with TSAN. See https://github.com/google/sanitizers/issues/1716
Reducing the randomness for ASLR allows the sanitizers to cope.

ci: reduce ASLR randomization for TSAN

---

src/libgit2/config.c
src/libgit2/config_parse.c
src/libgit2/path.c
src/libgit2/trailer.c
src/libgit2/transports/smart_pkt.c
src/util/date.c
src/util/str.c
src/util/util.h
tests/libgit2/repo/open.c

ctype classification takes an integer in as returned from getc() if we just sign extend characters to integers 128-255 will be misclassified. (255 will become EOF)
Newlib in particular doesn't like this since they uses the value as an index in a lookup table.

ctype: cast characters to unsigned when classifying characters

---

.github/workflows/experimental.yml
.github/workflows/main.yml

Split the SHA256 builds into their own workflow; since they're experimental (and have proven to be flaky) they shouldn't be used as signal that there's a problem with a PR.

ci: split SHA256 builds out into their own workflow

---

.github/workflows/benchmark.yml
.github/workflows/nightly.yml

Update the nightly and benchmark workflows to only run steps in libgit2/libgit2 by default. Also update the benchmark workflow to use the latest download-artifact version.

ci: update nightly workflows

---

.github/workflows/nightly.yml

The new upload-artifact action fails on conflicting names; ensure that we give each artifact a unique name (keyed off the id).

ci: give all nightly builds a unique id

---

src/libgit2/CMakeLists.txt

Attempting to build static libraries with the ARM MSVC command prompt fails because of this old workaround. According to the bug report linked in the comment (http://public.kitware.com/Bug/view.php?id=11240), the bug was fixed in CMake 3.4. This *should* no longer be necessary now that the required CMake version is 3.5.1.

cmake: remove workaround that isn't compatible with Windows on ARM

---

src/util/unix/process.c

https://github.com/libgit2/libgit2/commit/bc97d01c039f004a05a5457bace11f3c3e26beb5 commit introduced `environ` usage which is not compatible with some version of macOS. In result `libgit2` cannot be built.
Fix that: use a MacOS-specific symbol on macOS.

process.c: fix environ for macOS

---

src/libgit2/transports/local.c
src/libgit2/transports/ssh_libssh2.c
src/libgit2/transports/winhttp.c

Since 3618a2a, `git_error_last` does not return NULL when there was no error. Adapt to this when testing for a user cancelling a callback but not setting an error message, testing for `klass` of `GIT_ERROR_NONE`.

transport: provide a useful error message during cancellation

---

src/libgit2/revparse.c
tests/libgit2/refs/revparse.c

libgit2 doesn't accept refs with an '@' at the end in `git_revparse_single`.
cross-ref: https://gitlab.com/tortoisegit/tortoisegit/-/issues/4133

Revparse: Correctly accept ref with '@' at the end

---

include/git2/remote.h
src/libgit2/remote.c

In attempting to make a clever change that added fetch options as flags, while keeping ABI and API compatibility, we screwed up. Bitfields in structs are implementation-specific and are not necessarily ABI compatible across compilers.
Make `update_fetchhead` a flags value which is weirdly named, but that's a future problem. This removes the `report_unchanged` option from API.

remote: drop bitfields in git_remote_fetch_options

---

src/libgit2/tree.c

Promote mode to `uint32_t` before comparing it to an `uint16_t` to avoid mixed signed comparison warnings.

tree: avoid mixed signedness comparison

---

src/util/alloc.c
src/util/allocators/debugalloc.c
src/util/allocators/debugalloc.h
src/util/allocators/stdalloc.c
src/util/unix/realpath.c
tests/clar/clar_libgit2_alloc.c
tests/libgit2/checkout/conflict.c
tests/libgit2/checkout/icase.c
tests/libgit2/remote/fetch.c

Introduce a new debugging allocator that:
1) internally tracks allocation size — this is helpful both to be able to track internally, but also to ensure that the pointer returned from the custom `malloc` is _not_ the same pointer that the underlying system `malloc` used, and is therefore incompatible with the system `free`. This helps catch inconsistent use of system malloc and the libgit2-configured malloc.
2) forces `realloc` to always reallocate (it will explicitly `malloc`, `memcpy`, and `free` the previous pointer)
Also, update some inconsistent use of allocators caught by 1.

Introduce a stricter debugging allocator for testing

---

examples/merge.c
include/git2/commit.h
src/libgit2/commit.c
src/libgit2/commit.h
src/libgit2/notes.c
src/libgit2/rebase.c
src/libgit2/stash.c
tests/libgit2/checkout/tree.c
tests/libgit2/cherrypick/workdir.c
tests/libgit2/commit/commit.c
tests/libgit2/commit/write.c
tests/libgit2/diff/rename.c
tests/libgit2/odb/freshen.c
tests/libgit2/rebase/sign.c
tests/libgit2/refs/reflog/messages.c
tests/libgit2/revert/workdir.c
tests/libgit2/revwalk/basic.c

This reverts commit cf19ddc52227f4ec2efd4c0a84aa5d2362f0ffc7, which was breaking for several projects.

 Fix constness issue introduced in #6716

---

include/git2/odb.h

I believe the original docs for the return value of `git_odb_stream_read` might be incorrect. It currently says that it returns 0 on success. However, that means there would be no way to know how many bytes were actually saved to the buffer. `loose_backend__readstream_read` appears to return the total number of bytes read. I don't know if there are any other backends that implement readstream (I don't see any).

Fix docs for git_odb_stream_read return value.

---

src/libgit2/odb.c

As discussed in https://github.com/libgit2/libgit2/discussions/6835
When `git_odb_stream` is a read stream, `hash_ctx` is not used. Therefore, check if `hash_ctx` can be freed during the release. This allows implementers of custom ODB backends to not worry about the creation of `hash_ctx` for now.

odb: conditional git_hash_ctx_cleanup in git_odb_stream

---

src/libgit2/transports/smart_protocol.c
tests/libgit2/online/shallow.c

Fixes issue where the shallow roots array size wasn't being copied as part of preparing to perform a fetch.
This resulted in the shallow roots file being removed unexpectedly at the end of the fetch, even though there's still one or more shallow root commits as they weren't included/ancestors of the branches/commits fetched, which subsequently led to invalid/missing object errors.

Fix shallow root maintenance during fetch

---

README.md

To build the examples, they must be included in the main build using the following command:
cmake -DBUILD_EXAMPLES=True ..

docs: Add instructions to build examples

---

src/util/net.c
src/util/net.h
tests/util/url/parse.c
tests/util/url/scp.c

When parsing URLs, track whether the port number was explicitly specified or not. We track this separately from whether the port is the _default_ port. This is so that we can discern between URLs that have the default port explicitly specified or not.
For example: scp://host:22/foo and scp://host/foo are equivalent in terms of functionality, but are not semantically equivalent.
A user might wish to specify scp://host:22/foo in order to explicitly ensure that we connect on port 22, which might override (for example) a different configuration option.

url: track whether url explicitly specified a port

---

src/libgit2/transports/httpparser.c

Fixes a bug likely introduced in
d396819101a67c652af0fa0ae65cda19a2c0430a (in **1.8.1**) whereby `proxy_settings.on_status` would be left uninitialized when using the ‘http-parser’ backend (`-DUSE_HTTP_PARSER=http-parser`), eventually leading to a segfault in `http_parser_execute`.  Valgrind would report use of the uninitialized value like so:
```
Conditional jump or move depends on uninitialised value(s)
at 0x50CD533: http_parser_execute (http_parser.c:910)
by 0x4928504: git_http_parser_execute (httpparser.c:82)
by 0x4925C42: client_read_and_parse (httpclient.c:1178)
by 0x4926F27: git_http_client_read_response (httpclient.c:1458)
by 0x49255FE: http_stream_read (http.c:427)
by 0x4929B90: git_smart__recv (smart.c:29)
by 0x492C147: git_smart__store_refs (smart_protocol.c:58)
by 0x4929F6C: …
```

http: Initialize ‘on_status’ when using the http-parser backend.

---

src/libgit2/index.c

In truncate_racily_clean, when git_diff_index_to_workdir fails, we leak the local variable git_vector paths.

Leak in truncate_racily_clean in index.c

---

src/libgit2/transports/ssh_exec.c

Currently, when using `GIT_SSH_EXEC` feature, `libgit2` doen't respect a `Port` config in ssh config because it always insert `-p 22` option to a ssh command if there is no port value in a git remote url (e.g. `git@my-custom-domain.org:user/path`). I've experienced this for my company's GHE.
~One caveat of this implementation is that if you specify port `22` in a remote url despite a different port in ssh config, it will be ignored.~
~For example, in `~/.ssh/config`:~
```
Host my-custom-domain.org
Port 1234
```
~and if you try to fetch or push with a remote url `ssh://git@my-custom-domain.org:22/user/path`, the port `1234` will be used.~
~It would be unlikely someone tries to do this though, I guess.~
EDITED:
Now `-p <port>` option is added only when the port is specified in a remote url.

ssh: Omit port option from ssh command unless specified in remote url

---

src/libgit2/diff_print.c
tests/libgit2/diff/header.c

diff: print the file header on GIT_DIFF_FORMAT_PATCH_HEADER
In `diff_print_patch_file` we try to avoid printing the file if we're not sure
that there will be some content. This works fine if we have any later functions
that might get called as part of printing. But when given the format
`GIT_DIFF_FORMAT_PATCH_HEADER`, this is the only function to get called.
Add the binary and hunk functions to those to be called when given this option
and have them exit after printing the header. This takes care of printing the
header if we would be issuing a hunk, but we skip that part.
This is an alternative to #6887 which is a bit more wasteful of function calls but it shouldn't regress the issue that was originally intended to fix when introducing this regression by only printing the header if we …

diff: print the file header on GIT_DIFF_FORMAT_PATCH_HEADER

---

include/git2/config.h
include/git2/sys/config.h
src/libgit2/config.c
src/libgit2/config_backend.h
src/libgit2/config_file.c
src/libgit2/config_list.c
src/libgit2/config_list.h
src/libgit2/config_mem.c
src/libgit2/config_snapshot.c

While looking at the documentation, it became clear that the `git_config_entry` function was strange...
This is a leftover leaky abstraction. If consumers aren't meant to _call_ the `free` function then they shouldn't _see_ the free function. Move it out into a `git_config_backend_entry` that is, well, produced by the config backends.
This makes our code messier but is an improvement for consumers.

config: remove `free` ptr from `git_config_entry`

---

AUTHORS
src/libgit2/streams/stransport.c

This pull request ensures errors from `SecureTransport` on macos are handled properly when `CFStringGetCStringPtr` returns `null`. This occurs when the string encoding conversion is not cheap/efficient. 
I am making this pull request after encountering a `SecureTransport error: (null); class=Net (12)` while working on https://github.com/mitre/hipcheck. With these changes, I now get an error message from macos instead of `(null)`.

Add more robust reporting to SecureTransport errors on macos

---

src/libgit2/repository.c
tests/libgit2/core/opts.c
tests/libgit2/repo/extensions.c

libgit2 implicitly supports precious objects, since there's no gc command, nor even any option in our object database functionality to delete an object from the odb.
In the future, when we support deleting objects, or a gc functionality, we will need to honor the preciousObjects extension and reject those APIs when it is set. In the meantime, since users cannot use libgit2 (directly) to delete an object, we can simply add this to our allowlist.

repo: support the preciousObjects extension

---

src/libgit2/streams/stransport.c

The unused variables in the stransport code should be initialized to avoid compiler warnings. :eyeroll:

stransport: initialize for iOS

---

src/libgit2/remote.c

In case when `unpack_ok` is false push status can be non-empty and contains important information about unpacking failure cause. For example, Azure DevOps git server behave like that. 
There is an example of error message is provided by Azure:
"The blob object e4f9f86ce8fcaa697809bcb6efbd91eddc50b04a was rejected: VS403658: The object is 1074200997 bytes, which is greater than the 10485760 byte limit for objects in this repository." 
If we go to cleanup immediately it will be no information about the cause for client.

push: report a push status even the push has failed

---

src/libgit2/transports/local.c
tests/libgit2/network/remote/local.c

Let `git_object_type()` do the filtering instead.
Fixes: https://github.com/libgit2/libgit2/issues/6275

transport: do not filter tags based on ref dir in local

---

include/git2/sys/mempack.h
src/libgit2/odb_mempack.c

Unlike existing functions, this produces a _thin_ packfile by making use of the fact that only new objects appear in the mempack Object Database.
A thin packfile only contains certain objects, but not its whole closure of references. This makes it suitable for efficiently writing sets of new objects to a local repository, by avoiding many small I/O operations.
This relies on `write_pack` (e.g. `git_packbuilder_write_buf`) to implement the "recency order" optimization step.
Basic measurements comparing against the writing of individual objects show a speedup during when writing large amounts of content on machines with comparatively slow I/O operations, and little to no change on machines with fast I/O operations.
I have used this in https://github.com/NixOS/nix/pull/11330, in conjunction …

Add `git_mempack_write_thin_pack`

---

include/git2/checkout.h
include/git2/clone.h
include/git2/rebase.h
include/git2/stash.h
include/git2/submodule.h
src/libgit2/apply.c
src/libgit2/checkout.c
src/libgit2/checkout.h
src/libgit2/cherrypick.c
src/libgit2/clone.c
src/libgit2/clone.h
src/libgit2/merge.c
src/libgit2/revert.c
tests/libgit2/checkout/binaryunicode.c
tests/libgit2/checkout/conflict.c
tests/libgit2/checkout/head.c
tests/libgit2/checkout/icase.c
tests/libgit2/checkout/index.c
tests/libgit2/checkout/tree.c
tests/libgit2/cherrypick/workdir.c
tests/libgit2/clone/local.c
tests/libgit2/clone/nonetwork.c
tests/libgit2/merge/workdir/dirty.c
tests/libgit2/merge/workdir/renames.c
tests/libgit2/merge/workdir/simple.c
tests/libgit2/online/clone.c
tests/libgit2/online/fetchhead.c
tests/libgit2/perf/helper__perf__do_merge.c
tests/libgit2/revert/workdir.c

Make `GIT_CHECKOUT_SAFE` the default.  `NONE` is never what the user wants _by default_; people expect checkout to, well, check things out. Instead, it should be an opt-in "dry run" mode.
But, in fact, it should be a dry run and fire notifications.  So we keep `DRY_RUN` and remove the `NONE` mode entirely.
This removes some odd code in internal callers of `checkout` that takes a `git_checkout_options` and updates the mode to `SAFE`.  This is now unnecessary since everything has better defaults.

checkout: make safe checkout the default

---

examples/fetch.c
include/git2/remote.h
src/libgit2/push.c
src/libgit2/remote.c
tests/libgit2/network/fetchlocal.c
tests/libgit2/online/clone.c
tests/libgit2/online/fetch.c
tests/libgit2/online/push_util.c
tests/libgit2/online/push_util.h
tests/libgit2/submodule/update.c

`git` shows the _remote_ and _local_ ref information during a fetch. For example:
```
* [new branch]          ethomson/nonblocking   -> origin/ethomson/nonblocking
```
This is not information that users of libgit2 can currently surface since our `update_tips` callback includes only src/dest OIDs, and the _local_ ref name. Nor can one reliably reverse engineer the remote branch name, since a remote configuration could map two remote specs to a local spec. For example:
```
fetch = +refs/pull/*/head:refs/remotes/asdf/*
fetch = +refs/heads/*:refs/remotes/asdf/*
```
In this case, given `refs/remotes/asdf/foo` in the `update_tips`, a caller would have no idea whether the remote was `refs/pull/foo/head` or `refs/heads/foo`.
Provide the matching remote `git_refspec` so that callers can …

remote: add update_refs with git_refspec

---

.github/workflows/experimental.yml

The Windows SHA256 gitdaemon seems to crash; remove from CI while we troubleshoot.

ci: don't run Windows SHA256 gitdaemon tests

---

README.md

I was curious about how we fair against OpenSSF Best Practices. Pretty good, which I'm proud of but not particularly surprised by. Let's add the badge to our README so that we can track conformance.

readme: add OpenSSF best practices badge

---

src/util/win32/posix_w32.c

I'm afraid people do put Git repos on OneDrive... It seems to like to prevent folders from being deleted, causing libgit2 operations to handle ERROR_ACCESS_DENIED, and preventing us from switching branches/merging etc.
I think this change brings libgit2 in line with the behaviour of Git for Windows. The rmdir function is located [here](https://github.com/git-for-windows/git/blame/85dac07b93425aba69537d42ef036aa8413ae37c/compat/mingw.c#L593). The function is_file_in_use_error not only checks for ERROR_SHARING_VIOLATION, but also ERROR_ACCESS_DENIED:
```cpp
static inline int is_file_in_use_error(DWORD errcode)
{
switch (errcode) {
case ERROR_SHARING_VIOLATION:
case ERROR_ACCESS_DENIED:
return 1;
}
return 0;
}
```
Completely understand any hesitation about merging this, but thought it might …

util/win32: Continue if access is denied when deleting a folder.

---

include/git2/merge.h

Sorry for loosing track of this one. I've moved over the documentation I added about the same thing on git2-rs.
* Closes https://github.com/libgit2/libgit2/issues/6899
Let me know if there are any style changes I need to make, or if there are other locations in regards to merge_base_many which could do with updating.

Update documentation of `merge_base_many`

---

.github/workflows/documentation.yml

Ensure that workflows where the main branch exists (eg, anything except PR workflows) don't try to recreate the main branch. Add a concurrency token so that we don't have conflicts generating documentation.

Update documentation generation workflow

---

src/libgit2/transports/ssh_libssh2.c

User sees this error when trying to clone a repository using SSH:
failed to start SSH session: Unable to exchange encryption keys (-1x23)
This particular server only accepts these host key algorithms (output from ssh executable):
debug2: host key algorithms: rsa-sha2-256,rsa-sha2-512
"Normally" you might see others but what causes the error is the absence of "ssh-rsa" from the accepted list of host key algorithms.
Calling libssh2_session_method_pref with a list of methodsunfortunately isn't just preferring those methods, it means it accepts ONLY those methods. This pull request fixes that by adding rsa-sha2-256 and rsa-sha2-512 to the list.
This could be optimised by only calling libssh2_knownhost_checkp once for LIBSSH2_KNOWNHOST_KEY_SSHRSA and appending all of rsa-sha2-256, …

ssh: Include rsa-sha2-256 and rsa-sha2-512 in the list of hostkey types

---

script/api-docs/docs-generator.js

Array.sort() mutates the array _and_ returns it; don't mutate the version array.

Documentation: don't resort versions

---

include/git2/sys/refdb_backend.h

Parameters are documented by `@param`, not `@arg`

Documentation: update refdb_backend docs

---

include/git2/common.h
src/libgit2/odb_mempack.c
src/util/git2_util.h
src/util/util.h

The `GIT_WIN32` macro should only be used internally; keep it as such.

Make `GIT_WIN32` an internal declaration

---

.github/workflows/documentation.yml
script/api-docs/docs-generator.js

Clean up the outdated documentation folder before re-generating it in place. This accomodates a deleted API.

Documentation: clean up old documentation

---

src/libgit2/refs.c
tests/libgit2/refs/normalize.c

Negative refspecs were added in Git v2.29.0 which allows refspecs to be
prefixed with `^`[^1]. Currently, the library is unable to normalize
negative refspecs which causes errors in different tools that rely on
`libgit2`. Specifically, when the library attempts to parse and
normalize a negative refspec, it returns a `GIT_EINVALIDSPEC` code.
Add the ability to correctly normalize negative refspecs. While this PR
will not update the behavior of `fetch`, or other actions that rely on
negative refspecs, this allows us to be able to successfully parse and
normalize them. A future change will handle updating the individual
actions.
[^1]: https://github.com/git/git/commit/c0192df6306d4d9ad77f6015a053925b13155834

refs: Handle normalizing negative refspecs

---

src/libgit2/config_cache.c
src/libgit2/diff_print.c
src/libgit2/object.c
src/libgit2/object.h
src/libgit2/repository.c
src/libgit2/repository.h
tests/libgit2/object/shortid.c

Fixes #6878.
Not sure if I went to far here, I noticed core.abbrev was used by diff_print.c. If the user sets core.abbrev to an integer outside of the allowed range that will now error.
I also added GIT_ABBREV_MINIMUM, which Git sets to 4. libgit2 was allowing anything above zero.

 object: git_object_short_id fails with core.abbrev string values

---

tests/libgit2/repo/pathspec.c

We did not have (obvious) pathspec wildcard tests for `**/foo` behavior. Add some based on git's observed behavior.

pathspec: additional pathspec wildcard tests

---

src/libgit2/transports/smart_protocol.c
tests/libgit2/online/clone.c

Fixes #6889.
I'm not sure why this works with https and not ssh. There are claims it works with the ssh "exec" backend but that wasn't the case for me.
Because we don't clear the data buffer, the "wants" get sent twice to the server. The second time is the call to  git_smart__negotiation_step in line 568 of smart_protocol.c

Clear data after negotiation

---

script/api-docs/api-generator.js

For enum values that are constructed, not literal integers, we need to parse the inner / implicit expression. For example:
```
GIT_DIFF_REVERSE = (1u << 0)
```
Fixes #6970

docs: properly parse enum values

---

src/libgit2/transports/smart_protocol.c
tests/libgit2/online/shallow.c

In RPC mode (https), the client sends its list of shallow commits at the beginning of each request during packfile negotiation, so that the remote endpoint keeps context.  This causes the remote to prepend appropriate shallow/unshallow packets to each response sent back to the client.
However, the store_common() helper function (used in multi_ack mode) does not cater for this, returning as soon as it encounters any packet different than an ACK packet and therefore leaving the rest of the HTTP buffer unprocessed.  This in turn causes subsequent iterations of the while loop processing ACK packets to process data returned by older HTTP requests instead of the current one, messing up the packfile negotiation process.  Given that the wait_while_ack() helper function (called after the client …

smart: ignore shallow/unshallow packets during ACK processing

---

include/git2/refspec.h
src/libgit2/refspec.c
src/libgit2/refspec.h
src/libgit2/remote.c
tests/libgit2/refs/normalize.c
tests/libgit2/remote/fetch.c

Add support for fetching with negative refspecs. Fetching from the
remote with a negative refspec will now validate any references fetched
do not match _any_ negative refspecs and at least one non-negative
refspec. As we must ensure that fetched references do not match any of
the negative refspecs provided, we cannot short-circuit when checking
for matching refspecs.
https://github.com/libgit2/libgit2/issues/6741

remote: Handle fetching negative refspecs

---

src/libgit2/repository.c
tests/libgit2/repo/template.c

When a `template_path` is explicitly specified, don't _also_ require an option to indicate that we should use templates. We, obviously, should.

repo: don't require option when `template_path` is specified

---

src/libgit2/repository.c
tests/libgit2/repo/init.c
tests/libgit2/repo/setters.c
tests/libgit2/submodule/add.c
tests/libgit2/submodule/repository_init.c

The `.git` file, when containing a `gitdir: ` link, should be suffixed with a trailing newline.

repo: put a newline on the .git link file

---

docs/changelog.md
include/git2/version.h

Regarding our SONAME policy, it was suggested to me that even if we're doing it wrong, we've been doing it _consistently_ wrong. And that changing our behavior could be a breaking change for consumers who are expecting such consistency. 🥴 
Thus, changing our SONAME / ABI version update policy without an announcement is a breaking change. We'll continue our existing SONAME versioning for v1.9 and will announce this for our next version update.

meta: revert soname version update

---

CMakeLists.txt
cmake/SelectHashes.cmake
docs/changelog.md

git's hash algorithm is sha1dc, it is not sha1. Per Linus:
> Honestly, git has effectively already moved from SHA1 to SHA1DC.
>
> So the actual known attack and weakness of SHA1 should simply not be
> part of the discussion for the next hash. You can basically say "we're
> _already_ on the second hash, we just picked one that was so
> compatible with SHA1 that nobody even really noticed.
Warn users who try to compile with SHA1 instead of SHA1DC.

cmake: warn for not using sha1dc

---

.github/workflows/documentation.yml

Don't build docs on pushes to maint branches; those docs should only be built _on release_. In addition, be safer about not creating an existing branch from a tracking branch.

ci: only build docs on main branch pushes

---

include/git2/deprecated.h
include/git2/repository.h
src/cli/cmd_init.c
src/libgit2/repository.c
src/libgit2/submodule.c
tests/libgit2/repo/init.c

When specifying a separate working directory path, the given repository path should never have a `.git` directory created beneath it. That simply doesn't make sense.

No `.git` for separate workdir

---

src/util/hash/builtin.c

Our bundled SHA256 implementation passes a `size_t` as an `unsigned int`. Stop doing that.

hash: allow `unsigned int` != `size_t` in sha256

---

src/cli/cmd.h
src/cli/cmd_version.c
src/cli/main.c

Move the `--version` information into its own command, so that we can support `--build-options`.

cli: add version command

---

include/git2/stdint.h

f1cac063baada36900fa1060c665c36281a8168b, which converted the style of code comments, introduced an issue where one of the comments was not closed. This created an imbalance of opening `#ifdef` and closing `#endif` at line -222/+224 to -224/+226:
https://github.com/libgit2/libgit2/commit/f1cac06#diff-c4c8617f383bc7d0f8826c53706fc10ae74b83bc0ca961382782c4da81de1da0L222
This commit closes the comment, fixing the imbalance.

include: Fix code comment termination

---

tests/libgit2/transport/register.c

GIT_ERROR_CHECK_ALLOC was added to check the return value of git__calloc().
Return value of git__calloc() is usually checked for NULL.

FIx potential null dereference

---

docs/changelog.md

In v1.9, we failed to document that `update_refs` was a breaking change. Add information about this change to the ABI breaking changes section.

docs: add `update_refs` as ABI breaking change

---

src/libgit2/CMakeLists.txt

libdir can be something else than /usr/lib, e.g. /usr/lib64 or similar.

src/libgit2/CMakeLists.txt: install cmake files into configured libdir

---

tests/benchmarks/benchmark.sh

The `fullpath` function takes the cli, but doesn't keep the cli.

benchmarks: update path to baseline cli

---

src/cli/opt.c

I tried to build my libgit2-1.9.0 package for CYGWIN but I got an error.
This message appears when compiling:
```
[199/671] Building C object src/cli/CMakeFiles/git2_cli.dir/opt.c.o libgit2-1.9.0/src/cli/opt.c:
In function ‘cli_opt_parse’: libgit2-1.9.0/src/cli/opt.c:564:23: warning: implicit declaration of function ‘alloca’; did you mean ‘malloc’? [-Wimplicit-function-declaration]
564 |         given_specs = alloca(sizeof(const cli_opt_spec *) * (args_len + 1));
|                       ^~~~~~
|                       malloc
```
and later the linker emits this error message:
```
[668/671] Linking C executable git2.exe
FAILED: git2.exe
/usr/x86_64-pc-cygwin/bin/ld: src/cli/CMakeFiles/git2_cli.dir/opt.c.o: in function `cli_opt_parse': …
```

cli: fix undefined alloca() on CYGWIN

---

src/libgit2/attr_file.c
tests/libgit2/filter/query.c

`.gitattributes` is case-insensitive when `core.ignorecase=true`.
Fixes #7017

attr: honor ignorecase in attribute matching

---

src/libgit2/odb.c
tests/libgit2/odb/alternates.c

Git does not limit relative paths in alternates to the first repository, so libgit2 shouldn't either.

alternates: allow relative paths in all repositories

---

tests/libgit2/checkout/conflict.c

Not all filesystems on Apple and Windows platforms are case‐insensitive; this test would previously fail on a case‐sensitive APFS volume.

conflict tests: check `core.ignorecase`

---

include/git2/common.h
src/CMakeLists.txt
src/cli/cmd_version.c
src/libgit2/settings.c
src/util/git2_features.h.in

Track some information about the compilation at compile time, and allow consumers to query it.

Introduce git_libgit2_buildinfo

---

tests/benchmarks/benchmark.sh

It can be useful to report the commit ID during benchmarks to track down regressions; leverage the addition of that in `git version` during benchmark runs.

benchmarks: report commit of build

---

src/libgit2/CMakeLists.txt

I've upgraded to using libgit2 v1.9, and I've been getting build errors that weren't there previously. This is caused by the custom ```<stdint.h>``` header file.
The build errors only occur when using a **installed** libgit2.
I am using Fedora Linux 41.
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.30)
project(using_libgit2)
add_executable(my_exe main.cpp)
find_package(libgit2)
target_link_libraries(my_exe PRIVATE libgit2::libgit2package)
```
main.cpp
```cpp
#include <cstdint>
int main() {
return 0;
}
```
Trying to build this leads to errors like this:
```
/usr/include/c++/14/cstdint:51:11: error: ‘int8_t’ has not been declared in ‘::’
51 |   using ::int8_t;
```
When using the installed libgit2 the include paths will now contain ```include/git2``` instead of ```include```. This …

Revert include path regression

---

tests/benchmarks/benchmark.sh

Don't fail the benchmark script if we can't identify the CLI commit.

cli: fix benchmark commit interrogation

---

cmake/DefaultCFlags.cmake

Currently, the DefaultCFlags.cmake overrides the
CMAKE_STATIC_LINKER_FLAGS to suppress linker warnings about files with no symbols defined.
This has the side effect of breaking MSVC cross compilation (where CMAKE_STATIC_LINKER_FLAGS is used to specify the /MACHINE:ARCH flag)
This commit make sure we append to CMAKE_STATIC_LINKER_FLAGS instead of replacing its values
The error when trying to cross compile with MSVC is the following:
```
[100%] Linking C static library ..\..\git2.lib
LINK : warning LNK4068: /MACHINE not specified; defaulting to X64
..\util\CMakeFiles\util.dir\alloc.c.obj : fatal error LNK1112: module machine type 'ARM64' conflicts with target machine type 'x64'
```

Fix MSVC cross compilation

---

include/git2/remote.h

The docstring for `git_remote_url` incorrectly states that this function will return the push URL if it was configured. This is wrong, as it does not (and should not, but `git_remote_pushurl` does - this is probably an oversight from copy/pasting the docstring from the latter function).

docs: correct wrong docstring info for git_remote_url

---

include/git2/oid.h

Fix the following warning reported by clang-tidy:
```
contrib/libs/libgit2/include/git2/oid.h:11:10: error: circular header file dependency detected while including 'types.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]
11 | #include "types.h"
|          ^
contrib/libs/libgit2/include/git2/types.h:70:10: note: 'oid.h' included from here
70 | #include "oid.h"
```

Fix circular includes between types.h and oid.h

---

fuzzers/CMakeLists.txt

I'm seeing the current fuzzer build fail (during `cmake`) like so:
```
-- Performing Test IS_FSANITIZE_FUZZER_NO_LINK_SUPPORTED
-- Performing Test IS_FSANITIZE_FUZZER_NO_LINK_SUPPORTED - Failed
CMake Error at cmake/AddCFlagIfSupported.cmake:17 (message):
Required flag -fsanitize=fuzzer-no-link is not supported
Call Stack (most recent call first):
fuzzers/CMakeLists.txt:6 (add_c_flag)
```
The cmake log output contains something like so:
```
/src/aflplusplus/libAFLDriver.a(aflpp_driver.o): in function `main':
aflpp_driver.c:(.text+0x11b): undefined reference to `LLVMFuzzerTestOneInput'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I haven't figured out exactly what's happening, but I believe that once line 5 has added `-fsanitize=fuzzer` to `CFLAGS`, …

fuzzers: Fix CFLAGS
